src/server/main_service.cc
src/server/multi_test.cc

Eval'ing `redis.call('FLUSHALL')` was enough to crash, fixes #2134

chore(eval): Don't crash on unsupported script commands

---

tests/dragonfly/replication_test.py

These timeouts were introduced by Roman to localize a deadlock issue. However, once Vlad fixed them, we did not revert the changes and it can happen that the machine that runs the CI is executing more tests at the same time causing this to fail/timeout. I reproduced locally, by running the same test case 3-4 times concurrently (the tests passed when I removed or increased the timeout). 
I did not remove the timeout, but rather chose to increase it -- which is not what we had before (we had no local timeouts) but I think it suffices for now to just increase it and it won't cause any problems.

fix(regTests): increase cancel replication test timeout

---

src/facade/command_id.h
src/facade/facade.cc
src/server/acl/acl_family.cc
src/server/bitops_family.cc
src/server/blocking_controller_test.cc
src/server/cluster/cluster_family.cc
src/server/command_registry.cc
src/server/command_registry.h
src/server/generic_family.cc
src/server/hll_family.cc
src/server/hset_family.cc
src/server/json_family.cc
src/server/list_family.cc
src/server/main_service.cc
src/server/search/search_family.cc
src/server/server_family.cc
src/server/set_family.cc
src/server/stream_family.cc
src/server/string_family.cc
src/server/test_utils.cc
src/server/transaction.cc
src/server/zset_family.cc

It will be represented via INTERLEAVED_KEYS option.

chore: remove Command step argument

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h

Fixes a bug in #2156 
Move block that is pipeline squashed out of the dispatch queue before applying it, see comment below

fix(connection): Clear dispatch queue before pipeline squashing

---

src/core/size_tracking_channel.h
src/facade/dragonfly_connection.h
src/server/memory_cmd.cc
src/server/memory_cmd.h
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/server_family.h
src/server/snapshot.cc
src/server/snapshot.h

Add `MEMORY STATS` command that prints some useful memory related information, including RSS, db memory size, connection count & buffer size, replication count & buffer size, serialization buffer size.

feat: Memory stats

---

tests/dragonfly/conftest.py
tests/dragonfly/tls_conf_test.py

Partially addresses #2081 by adding a test case to cover the use case
* add test for `ca_dir` 
I will update our docs as well.

chore(tls): add tls config test for ca_dir

---

src/server/memory_cmd.cc

The reason for the crash is that we can't use a mutex while iterating
connections. It uses a non-Fiber `Await()`, and it also has a fiber
atomic guard.
Instead use the common trick of allocating per-thread data and aggregate
afterward.

fix(stats): Do not crash upon issuing mem stats

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/dragonfly_listener.cc
src/facade/dragonfly_listener.h
src/server/cluster/cluster_family.cc
src/server/dflycmd.cc
src/server/server_family.cc
src/server/server_family.h

We have some places in our code base that first push a global change and then need to wait until there are no commands anymore running that have values of the old state cached / are amidst a breaking execution:
* When doing takeover, we first set the global state to taking-over and then wait for ongoing commands to finish. No new commands will be able to run because of the global state rejecting all commands
* When pushing cluster configs, before we delete moved slots, we want to make sure no command is accessing them, see #1480 
* Possibly when doing client pause (currently a PR)
The current implementation of `AwaitDispatches` waits until a point of time when _no dispatches at all_ are happening - which is too strong of a guarantee, we only want to wait for commands that were amidst …

chore(facade): Introduce AwaitCurrentDispatches

---

src/server/main_service.cc
src/server/server_state.cc
src/server/server_state.h
tests/dragonfly/replication_test.py

1. allow squashing commands on pause
2. move await on client pause inside InvokeCommand - this way all flows of command invoke will read pause state

fix(server): client pause fix on pipeline squash

---

src/core/search/search_test.cc
src/core/search/vector_utils.cc
src/server/search/doc_accessors.cc

fix(search): Fix vector search bugs :(

---

src/server/generic_family.cc

Fixes the case where a client library expect SCAN to return quicker (context: ruby's Rails.cache.delete_matched("prefix_*") times out)

fix: reduce the maxmimum running time of scan operation to ~100ms

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/facade.cc
src/facade/facade_types.h
src/server/main_service.cc
src/server/server_family.cc
tests/dragonfly/connection_test.py

* Add more connection state
* Fix dispatch of pipelined messages during connection closing state
* Skip same thread backpressure for publish producers
* Don't partially wait on borrow token
* Reduce size of Message by two 
* Small fixes
Now the pipelining logic does not throttle itself, only pubsub throttles if the subsriber thread is overflown.

chore: connection fixes

---

tests/dragonfly/connection_test.py

fix(pytest): Fix renamed flag

---

src/server/engine_shard_set.cc

* add missing doc for spill_file_prefix
I am curious if there was a reason why this flag description was empty. If it's experimental, then we should add this to the description as well.

chore: add missing doc for spill_file_prefix

---

src/server/replica.cc
src/server/replica.h

The bug: One connection calls replica start and second call replica stop. In this flow stop first reset state mask state_mask_.store(0), Start sets state mask state_mask_.store(R_ENABLED) continues to greet and create main replication fiber and then stop runs cntx_.Cancel(), which will at later be reset inside the main replication fiber. In this flow main replication fiber does not cancel and the connection calling to Stop is deadlocked waiting to join the main replication fiber.
The fix: run cntx_.Cancel() and state_mask_.store(0) in replica thread.
```mermaid
flowchart TD
A[Start] --> T[Time:T0]
T --> E["state |=Enabled"]
E -->  F[FiberDispatch]
B[Stop] --> R["state=0"] 
R --> T2[Time:T0] 
T2 --> T3[Time:T1]
T3 --> CC["Context.Cancel()"] 
CC --> D[JoinFiber/Deadlock]
T <--> T2 …
```

fix(replication): fix cancel replication race

---

src/facade/cmd_arg_parser.cc
src/facade/cmd_arg_parser.h
src/facade/cmd_arg_parser_test.cc
src/server/debugcmd.cc
src/server/detail/save_stages_controller.cc
src/server/detail/save_stages_controller.h
src/server/dflycmd.cc
src/server/main_service.cc
src/server/main_service.h
src/server/replica.cc
src/server/replica.h
src/server/search/search_family.cc
src/server/server_family.cc
src/server/server_family.h
src/server/set_family.cc
src/server/zset_family.cc
tests/dragonfly/replication_test.py
tests/dragonfly/snapshot_test.py

fix: forbid parallel save operations

---

contrib/charts/dragonfly/ci/priorityclassname-values.golden.yaml
contrib/charts/dragonfly/ci/priorityclassname-values.yaml
contrib/charts/dragonfly/templates/_pod.tpl
contrib/charts/dragonfly/values.yaml

We use scalers that can place pods according to [PriorityClass](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/).
We don’t want dragonfly to be removed as a result of high load on node. 
Not sure if it's right to do it here or using a post renderer.

feat(helm): add priority class name for pod

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h

* Pipelined command counter is increased even if SendAsync ignores it afterwards
* Add break after yield in connection close
* Add more debug info on check fail

fix(connection): Fix pipelined command counter

---

src/facade/acl_commands_def.h
src/facade/conn_context.h
src/facade/dragonfly_connection.cc
src/server/acl/acl_commands_def.h
src/server/conn_context.h

refactor(facade): Do not include / use server from facade

---

src/facade/reply_builder.cc
src/facade/reply_builder.h
src/facade/reply_builder_test.cc
src/facade/reply_capture.cc
src/facade/reply_capture.h
src/server/hset_family.cc
src/server/json_family.cc
src/server/main_service.cc
src/server/string_family.cc
src/server/string_family.h
src/server/transaction.h

Specifically, allocate only a single blob when returning multiple entries from a shard.

chore: improve performance of mget operation

---

src/server/main_service.cc
tests/dragonfly/connection_test.py

The multi command squasher takes it's base command id (EXEC or EVAL or EVALSHA) from the context. Then the context is modified to run different commands on it. Whenever collection is interrupted inside pipeline squashing due to a nested multi-transaction, we don't reset the base command when we continue using the context.

fix(squashing): Reset base command id

---

src/facade/dragonfly_connection.cc
src/server/command_registry.cc
src/server/command_registry.h
src/server/main_service.cc
src/server/server_family.cc
src/server/server_family.h
src/server/string_family.cc

Also,
1. rebase helio dependency
2. get rid of varz counters that are superseded by commands_total/commands_duration_seconds_total metrics
Resolves #2213

fix: fix cmd latency units in /metrics

---

src/server/main_service.cc
tests/dragonfly/pymemcached_test.py

The DF version is being unparseable by Memcached::getVersion() that expects n.n.n string. Change the version to emulate the old memcached server. The DF version can still be fetched via Memcached::getStats() function.

fix: memcached VERSION is now parseable by php-memcached client

---

src/facade/dragonfly_connection.h
src/server/test_utils.cc

Issue from #2227 
Currently the test context knows about the test connection, but the test connection doesn't know about the test context
so calling `cc_` inside the connection is a nullptr

fix(test): Fix connection context access

---

src/core/dense_set.cc
src/core/dense_set.h
src/core/string_set_test.cc
src/server/generic_family.cc
src/server/rdb_extensions.h
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/rdb_test.cc

fix(server): Save element expirations for hash sets & sets

---

src/facade/cmd_arg_parser.h
src/server/bitops_family.cc
src/server/bitops_family_test.cc

Resolves #213 
* implement bitfield command
* add tests
Note that there are certain optimizations that can be done. 
1. We read/write bit by bit (this is done in redis as well) even when we address the whole byte. Therefore, to update a single byte, we need 8 ops. To update 8 bytes, we need 64 ops. We can do that in one op, when these are aligned. Unless this becomes a proven bottleneck I would not spent time optimizing it further.
2. I do not like that we copy the whole string (target key value -- i.e, the bitfield) when we start processing/executing the command. This is wasteful, and for large large bitfields, this can quickly become a bottleneck. However, doing otherwise requires a little bit more involved work. In particular, we need a way to fetch and store individual bytes from the …

feat(bitops_family): implement bitfield command

---

src/server/dflycmd.h

fix(server): initialize replica acked lsn

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h

fix: assign threadlocal data structures during connection migration

---

src/core/search/indices.cc
src/core/search/indices.h
src/core/search/search.cc
src/core/search/search.h
src/server/search/search_family.cc
src/server/search/search_family_test.cc

* Return error for ft.create if index exists
* Add configurable M parameter to hnsw (we can't easily support eps / ef)
CC: @Niennienzz

fix(search): Small improvements

---

README.md
docs/faq.md

In addition addressed some questions raised during HN discussions.

chore: add benchmarks for a small cloud instance

---

src/facade/conn_context.h
src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/dragonfly_listener.cc
src/facade/dragonfly_listener.h
src/facade/facade.cc
src/facade/ok_main.cc
src/facade/service_interface.h
src/server/cluster/cluster_family.cc
src/server/dflycmd.cc
src/server/main_service.cc
src/server/main_service.h
src/server/server_family.cc
src/server/server_family.h
src/server/server_state.cc
src/server/server_state.h
tests/dragonfly/replication_test.py

In contrast to an AwaitDispatches() call, the tracker can be used to track connection dispatches _exactly when_ the state is changed, so we actually wait for the right commands to finish, not for anything that is running roughly at the same time
* Removes the dispatch pause as we don't need it anymore when we exclude paused commands from tracking
* Fixes the bug with multiple client pauses not being possible (because the old AwaitDispatches doesn't detect paused ones)
* Let's decide or put it off again 😅

feat: DispatchTracker to replace everything

---

src/server/main_service.cc

fixes https://github.com/dragonflydb/dragonfly/issues/2259

bug(server): remove `CO::READONLY` for `QUIT` command.

---

src/facade/reply_builder.cc
src/facade/reply_builder.h
src/facade/reply_builder_test.cc
src/server/server_family.cc

fixes https://github.com/dragonflydb/dragonfly/issues/2242 https://github.com/dragonflydb/dragonfly/issues/2253
Reference:
The definition of Redis verbatim strings: https://redis.io/docs/reference/protocol-spec/#verbatim-strings
"For example, the Redis command [INFO](https://redis.io/commands/info) outputs a report that includes newlines. When using RESP3, redis-cli displays it correctly because it is sent as a Verbatim String reply (with its three bytes being "txt"). When using RESP2, however, the redis-cli is hard-coded to look for the [INFO](https://redis.io/commands/info) command to ensure its correct display to the user."

feat(Server):support Verbatim strings resp type, using it for CLIENT LIST and INFO commands

---

.github/workflows/ci.yml
src/server/db_slice.cc
src/server/db_slice.h
src/server/table.cc
src/server/table.h
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc

Fixes: #2199 
The bug: On insert key is inserted to bin pending entries, if this key was deleted we would check fail on finding this item when trying to flush bin entries.
The fix: Call CancelIo when the entry is deleted

fix(tiering): fix crash when item was deleted before offloaded

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/reply_builder.cc
src/facade/reply_builder.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/main_service.cc
src/server/server_family.cc
src/server/server_family.h
src/server/transaction.cc
src/server/transaction.h

fixes https://github.com/dragonflydb/dragonfly/issues/2139
Implement CLIENT TRACKING subcommand.
Track the keys of a readonly command by maintaining mapping that maps keys to the sets of tracking clients.
Also include a transaction interface `Refurbish()`  that allows the reuse of a transaction, which is used for tracking the keys involved in a readonly command.

feat(server): Support CLIENT TRACKING subcommand (1/2)

---

src/server/db_slice.cc
src/server/tiered_storage.cc
src/server/tiered_storage_test.cc

fixes #2224
the bug: when updateing entry pre update will resets the PrimeValue if this is an external entries leading to crash if we insert entries with expire time.
the fix: reserve the expire mask in PrimeValue on pre update

fix(tiering): fix tiering crash on setting expire

---

src/server/main_service.cc
src/server/multi_test.cc

fix(server): handle no-key-transactional commands in multi/exec

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/string_family_test.cc
src/server/table.h
src/server/tiered_storage.cc
src/server/transaction.cc

fixes #2276 
The bug:
When running dragonfly in cache mode we bump up items on dash table when we find them. If we access few items on the callback that reside next to each other we will invalidate the first found iterator.
The fix:
After we bump up entry we insert the key to bump keys set. When checking if we can bump down a key we check the key is not in this set. Once we finish running the transaction callback we clear the set.

fix(bug): access invalid prime table iterator

---

src/server/CMakeLists.txt
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/cluster_shard_migration.cc
src/server/cluster/cluster_shard_migration.h
src/server/cluster/cluster_slot_migration.cc
src/server/cluster/cluster_slot_migration.h
tests/dragonfly/cluster_test.py

fixes #2295
DFLYMIGRATE FLOW command was added to establish connections for every shard replication process.
The slow serialization step is a separate issue so for now only eof_token is sent to reply for the DFLYMIGRATE FLOW command.
The expected state for START-SLOT-MIGRATION is FULL_SYNC now.

feat: add command flow for slot migration process

---

src/core/compact_object.cc
src/core/compact_object.h
src/core/sorted_map.cc
src/core/sorted_map.h
src/server/hset_family.cc
src/server/rdb_load.cc
src/server/set_family.cc
src/server/zset_family.cc

Now we allocate the inner objects (`StringSet`, `StringMap` and `SortedMap`) directly via mimalloc, which automatically accounts for them in the used memory metric. We also add this information for the type-specific metrics.

feat(server): Account for RObj concrete objects

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/server_family.cc
src/server/string_family_test.cc

Currently we expose hits/misses for read only commands only (compatible with redis). `keyspace_mutations` complement this providing number of key operations for write commands. It's interesting because now we can learn the number of key_ops vs API ops, where key_ops = misses + hits + mutations

feat: add keyspace_mutations metric

---

src/server/debugcmd.cc
src/server/memory_cmd.cc
src/server/server_family.cc
src/server/server_family.h

This metric shows how much the transaction queue of dragonfly is loaded.
Also remove the redunant `is_master` field from metrics.
Finally, removed unnecessary "role" metric from the prometheus metrics,  see #1754  for the context.

feat: expose tx_queue_len metric

---

src/core/intent_lock.h
src/server/db_slice.cc
src/server/debugcmd.cc
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/transaction.cc

This command shows the current state of transaction queues, specifically how many armed (ready to run) transactions there, how loaded these queue are and how many locks there are in each shard.
In addition, if a tx queue becomes too long, we will output warning logs about the state of the queue, in order to be able to identify the bottlenecks post-factum.

feat: introduce 'debug tx' command and periodic overload logs

---

src/server/server_family.cc
src/server/server_family.h
tests/dragonfly/replication_test.py

fix #2337 
The bug:
replicaof was not rejected while loading snapshot
The fix:
replicaof is allowed while server is in loading state to allow replicaof while replication in full sync mode
I now reject replicaof if the server is in loading state and it is master
Another bug fix:
allow cron snapshot if --replicaof flag was set

bug(server): reject replicaof while loading from snapshot

---

src/server/conn_context.h
src/server/engine_shard_set.cc
src/server/main_service.cc
src/server/transaction.cc

1. Fix AnalyzeTxQueue to stop crashing for various transaction types.
2. Pass exec command length to slowlog

chore: expose the multi length in slowlog

---

Makefile

Before this PR, using `make` for building releases used `-g1 -gz` to provide some level of debug symbols (mostly function names in stack traces).
We want to be able to have binaries with full debug symbols (for coredumps etc), but not in the public releases.
This PR builds with full debug symbols, but changes `make package` to strip most debug symbols, while keeping `.debug_line` (and keeping them compressed as if with `-gz`). This will allow a single build command for public releases as well as releases with full symbols.

feat(makefile): Build with full debug symbols and strip in `make package`

---

src/server/dfly_main.cc

We parse the container limits for heuristics that deduces memory/cpu capacities automatically. It's ok if we fail on some less common systems since there are manual overrides that allows specifying these limits explicitly.

fix: relax the requirement for parsing successfully container limits

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family_test.cc
src/server/db_slice.cc
src/server/table.cc
src/server/table.h

It's a good thing we waited with this feature until after the recent refactors. Now it's trivial and safer!
Fixes #1478

feat(getslotsinfo): Add memory usage per slot

---

src/server/debugcmd.cc
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/multi_command_squasher.cc
src/server/transaction.cc
src/server/transaction.h

It used mutex lock inside Await callback which is prohibited.
In addition, we improved loggings across the transaction code.

 fix "debug exec" command

---

src/server/common.cc
src/server/common.h
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/main_service.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h

feat(tiering): add max file size limit

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
tests/dragonfly/cluster_test.py

implements #2232
also adding the ability to use SLOT-MIGRATION-STATUS without args to print info about all migration processes for the current node

feat: add SLOT-MIGRATION-STATUS cmd for source node

---

src/server/blocking_controller.cc
src/server/blocking_controller.h
src/server/blocking_controller_test.cc
src/server/common.h
src/server/container_utils.cc
src/server/list_family.cc
src/server/stream_family.cc
src/server/stream_family_test.cc
src/server/transaction.cc
src/server/transaction.h
src/server/zset_family_test.cc

fixes #2294
bug: we unblocked XREADGROUP cmd even if we don't have new values
fix: added check with custom requirements for blocking commands

fix: unblock transactions only if requirements are correct

---

src/core/dash.h
src/core/dash_test.cc

bucket count is returned in Info command
This PR fixes the bucket count to be the number of buckets in dragonfly 
Before this fix the returned number was the slots number

fix(dash table): bucket count returns the number of buckets

---

src/facade/dragonfly_connection.cc
src/facade/facade.cc
src/facade/facade_types.h
src/facade/ok_main.cc
src/facade/reply_builder.cc
src/facade/reply_builder.h
src/facade/reply_builder_test.cc
src/facade/service_interface.h
src/server/blocking_controller_test.cc
src/server/main_service.cc
src/server/main_service.h
src/server/memory_cmd.cc
src/server/server_family.cc
src/server/server_family.h
src/server/server_state.h

Remove connection stats from server state and move them under FacadeStats.

chore: consolidate facade stats under a single struct

---

src/server/main_service.cc

Issue was that in `ServerFamilyTest.SlowLogLen` we set the threshold to be 0 microseconds and make sure that all commands are logged as slow. However, in opt, some commands sometimes take 0 microseconds, which fails the test.
Confirmed via:
```
./server_family_test --gtest_repeat=100 --gtest_filter=ServerFamilyTest.SlowLogLen
```

fix(test): Fix flaky test

---

src/server/generic_family.cc
src/server/rdb_save.cc
src/server/rdb_save.h

This utility class serializes `CompactObj`s as `RESTORE` commands, and has a similar interface (and a common base class) as `RdbSerializer`

feat(server): Add `RestoreSerializer`

---

src/server/rdb_save.cc
src/server/rdb_save.h

Specifically SendFullSyncCut and WriteJournalEntry. No functional change beyond cut-paste.

refactor(SerializerBase): Move some logic from RdbSerializer to SerializerBase

---

src/core/dash.h
src/core/dash_internal.h
src/core/dash_test.cc
src/server/db_slice.cc

Some naming changes + improving the interface of ForEachSlot command that now passes the bucket object instead of relying on the fact that we pass a reference to the bucket via capture. This makes the code more straightforward, imho.
no functional changes are made.

chore: improvements in dash code

---

src/server/server_family.cc
tests/dragonfly/replication_test.py

The issue came up when we introduced [here](https://github.com/dragonflydb/dragonfly/pull/2338/files#diff-04447876005188a028fe0e46ee54f437b03f9d2dfb8b456be2fa6fa539a56499R1945)  and it sometimes causes the CI to [fail](https://github.com/dragonflydb/dragonfly/actions/runs/7393992898/job/20114698331#step:6:3061). 
The problem is that we used `DispatchBrief` instead of `Await` in `SetMasterFlagOnAllThreads`. This triggered the condition introduced on the PR above because by the time the lock on `replicaof_mu` was released the flag change might not have been propagated to other proactor threads allowing an inconsistent state.

fix(regTests): assertion failure during load in cancel_replication_immediately 

---

src/server/transaction.cc
src/server/transaction.h

Extract part of #2376 
Also remove COORD_EXEC because it's never read (?). Could be useful in DCHECKS, but we already have per-shard armed flags 🤔

chore(transaction): Avoid COORD_SCHED_EXEC ambiguity with multi transactions

---

src/server/CMakeLists.txt
src/server/cluster/cluster_config.h
src/server/cluster/cluster_family.cc
src/server/cluster/unique_slot_checker.cc
src/server/cluster/unique_slot_checker.h
src/server/common.cc
src/server/db_slice.cc
src/server/dflycmd.cc
src/server/journal/journal.cc
src/server/journal/journal.h
src/server/journal/journal_slice.cc
src/server/journal/journal_test.cc
src/server/journal/serializer.cc
src/server/journal/streamer.cc
src/server/journal/streamer.h
src/server/journal/types.h
src/server/main_service.cc
src/server/multi_command_squasher.cc
src/server/multi_command_squasher.h
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/transaction.cc
src/server/transaction.h

`RestoreStreamer`, like `JournalStreamer`, streams journal changes to a sink. However, in addition, it traverses the DB like `RdbSerializer` and sends existing entries as `RESTORE` commands.
Adding it required a bit of plumbing to get all journal changes to be slot-aware.
In a follow-up PR I will remove the now unneeded `SerializerBase`.

feat(cluster): Add `RestoreStreamer`.

---

.github/workflows/release.yml
Makefile

Also, change its build directory to build-release. Simplify a bit its configuration steps as well. No change in functionality is expected.

chore: reduce Makefile for release procedures only

---

src/server/debugcmd.cc

fixes issue #2353 
The bug:
dcheck failed when running flushdb after debug populate 
The reason for this is that debug populate is not transactional and therefore did not call on callback finish to clear the bumped items in db slice
The fix:
call OnCbFinish after debug populate finishes

fix(server): call OnCbFinish after debug populate

---

src/server/dflycmd.cc
src/server/dflycmd.h
src/server/transaction.cc

This field is protected by ReplicaInfo::mu so non-protected access to it shows a design problem. Indeed, it was done for being able to access this field without a mutex inside ReplicationLags() function.
I moved the access to this field to GetReplicasRoleInfo where we need to lock ReplicaRoleInfo anyways. Also, done some cleanups in the file.
Finally, raised a threshold for "tx queue too long" warnings.

chore: remove atomic<> from ReplicaInfo::state

---

src/server/server_family.cc
tests/dragonfly/server_family_test.py

Currently, it supports the following syntax:
* `CLIENT KILL <addr>:<port>`
* `CLIENT KILL ID <id>`
* `CLIENT KILL ADDR <addr>:<port>`
* `CLIENT KILL LADDR <addr>:<port>`
It will not allow killing an admin-connection from a non-admin port.
There are a few parameters of `CLIENT KILL` that Redis supports but this PR does not yet add. Let's add them as needed.
Fixes #1614
Related to #1495

feat(server): Implement `CLIENT KILL`

---

src/server/hll_family.cc
src/server/hset_family.cc
src/server/json_family.cc
src/server/string_family.cc
tests/dragonfly/generic_test.py

There were executions paths that did not handle `std::bad_alloc` thrown in `AddOrFind`. Consequently, the commands affected did not reply to the client with error, triggering the `ReplyGuard`
Fixes #2380

fix: missing error reply to client after AddOrFind throw std::bad_alloc

---

src/server/common.cc
src/server/common.h
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/server_family.cc
src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc

The throttling is controlled by tiered_storage_throttle_us flag and can be disabled by passing `--tiered_storage_throttle_us=0`. This introduces a soft back-pressure during writes.
On my machine `debug POPULATE 10000000 key 1000 RAND` with tiered_storage_throttle_us=0 offloads 12% of all the entries, but with tiered_storage_throttle_us=1 it offloads almost 100% by prolonging the operation from 0.96s to 1.72s.

feat: allow throttling tiered writes

---

src/server/db_slice.cc

The (subtle) bug is that the previous code uses an `initializer_list` c'tor, which copies the `string_view` locally. Then it keeps that reference to the `string_view`, but it goes out of scope in the next line

fix: Invalid memory access

---

src/server/db_slice.cc
src/server/string_family.cc
src/server/transaction.cc
src/server/transaction.h
tests/dragonfly/replication_test.py

Before this change, OOM in shard callbacks could have led to data inconsistency between the master and the replica. For example, commands which mutated data on 1 shard but failed on another, like `LMOVE`.
After this change, callbacks that result in an OOM will correctly replicate their work (none, partial or complete) to replicas.
Note that `MSET` and `MSETNX` required special handling, in that they are the only commands that can _create_ multiple keys, and so some of them can fail.
Fixes #2381

fix(replication): Correctly replicate commands even when OOM

---

src/server/hll_family.cc

While at it, also fix `PFCOUNT` to say that it's a readonly cmd.
Fixed #2421

fix(server): Use custom journal for multi-key `PFMERGE` cmd

---

.github/workflows/release.yml
Makefile
tools/packaging/generate_debian_package.sh
tools/release.sh

We had a place in tools/packaging/generate_debian_package.sh that relied on the existence of build-opt, moreover, if it did not exist the script deadlocked.
1. Added more loggings
2. Removed the loop
3. Removed unnecessary dependency in the script on the build-dir name.

fix: release pipeline

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/facade.cc
src/facade/facade_types.h
src/server/server_family.cc

Unlike with regular latency measurement that measures the execution and the reply,
here we measure the overall latency from the point in time when a command was parsed.

feat: measure latency of pipelined commands

---

src/server/cluster/cluster_config.cc
src/server/cluster/cluster_config.h
src/server/common.cc
src/server/engine_shard_set.cc
src/server/main_service.cc

Motivation - after we submitted #2429 some smart-ass clients prevent users from accessing single-node commands like "SELECT". This PR fixes it by allowing consistent sharding based on hashtags even with cluster mode disabled.

fix: allow lock_on_hashtags with any cluster mode

---

src/server/conn_context.h
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/main_service.cc
src/server/multi_test.cc
src/server/server_family.cc
src/server/server_state.cc
src/server/server_state.h
src/server/transaction.cc
src/server/transaction.h

Previously, transactions would run out of order only when all shards determined that the keys locks were free. With this change, each shard might decide to run out of order independently if the locks are free. `COORD_OOO` is now deprecated and the `OUT_OF_ORDER` per-shard flag should is used to indicate it

feat(transaction): Independent out of order execution

---

src/server/CMakeLists.txt
src/server/cluster/cluster_config.h
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/cluster_shard_migration.cc
src/server/cluster/cluster_shard_migration.h
src/server/cluster/cluster_slot_migration.cc
src/server/cluster/cluster_slot_migration.h
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
src/server/journal/streamer.cc
src/server/journal/streamer.h
src/server/journal/tx_executor.cc
src/server/journal/tx_executor.h
src/server/replica.cc
src/server/replica.h
tests/dragonfly/cluster_test.py

feat(cluster): add data migrations from a source node to a target node and set state into STABLE_SYNC after full-sync-cut command
implements #2447
refactor(replication): move code that is common for cluster and replica into a separate file

feat(cluster): add tx execution in cluster_shard_migration

---

src/server/dfly_main.cc

feat(server): Add `backlog` flag for `listen()`

---

src/server/common.cc
src/server/common.h
src/server/io_mgr.cc
src/server/io_mgr.h
src/server/server_family.cc
src/server/server_family.h
src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h

This adds a development setting that allows reading from disk while bypassing the prefetching layer.
In addition, I added latency stats for disk reads.

feat: allow reading offloaded strings without loading to the store

---

src/facade/op_status.h
src/server/bitops_family.cc
src/server/db_slice.cc
src/server/db_slice.h
src/server/dragonfly_test.cc
src/server/error.h
src/server/generic_family.cc
src/server/hll_family.cc
src/server/hset_family.cc
src/server/json_family.cc
src/server/list_family.cc
src/server/rdb_load.cc
src/server/set_family.cc
src/server/stream_family.cc
src/server/string_family.cc
src/server/zset_family.cc

resolve comments in #2379
* return OpResult in AddOrFind instead of throwing bad_alloc

refactor: return OpResult in DbSlice::AddOrFind instead of throwing std::bad_alloc

---

src/server/transaction.cc
src/server/transaction.h

Fix for #2457 
1. Previously we set the ACTIVE flag on the wrong shard for non-atomic multi transactions, however we determined our activeness by the `shard_id == unique_shard_id` rule, so the code was working correctly. Added a DCHECK that asserts this (yes it failed tests)
2. I'm now explicitly clearing local_mask for atomic multi in `MultiSwitchCmd` and DHCECK that it's cleared during the initialization

fix(transaction): Improve ACTIVE flags management

---

src/server/journal/journal_slice.cc
src/server/top_keys.cc
src/server/transaction.cc
src/server/transaction.h

1. Stop writing to the replication ring_buffer
2. Stop allocating in TopKeys
3. Tighter CHECKs around tx execution.

fix: fixes for v1.14.0

---

tests/dragonfly/connection_test.py

fix: reduce test_pipeline_batching_while_migrating flakiness

---

src/core/compact_object_test.cc
src/core/json_object.cc
src/core/json_object.h
src/core/json_test.cc
src/core/sorted_map.cc
src/core/sorted_map.h
src/server/journal/tx_executor.h
src/server/json_family.cc
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/rdb_save.cc
src/server/search/doc_accessors.cc
src/server/search/search_family.cc
src/server/table.h

1. Move json object creation code to the shard-thread inside rdb_load
2. Now json_family never references "json" type, always dfly::JsonType
3. Switch JsonType to pmr::json.
4. Make sure we pass the correct memory_resource when creating json object from string.

chore: switch json object to pmr allocator

---

src/server/container_utils.cc
src/server/engine_shard_set.cc
src/server/transaction.cc
src/server/transaction.h

Motivation: We invented a separate seqlock mechanism to avoid calling `PollExecution` if we expired. Let's just make calling it safe and the seqlock mechanism becomes redundant.
Also, refactor PollExecution and update its comments to be easier to understand

chore(transaction): Simplify PollExecution()

---

src/core/interpreter.cc
src/core/search/compressed_sorted_set.h
src/facade/op_status.h
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_shard_migration.h
src/server/detail/snapshot_storage.cc
src/server/main_service.cc
src/server/stream_family.cc
src/server/zset_family.cc

chore: fix clang warnings

---

src/server/conn_context.cc
src/server/conn_context.h
src/server/engine_shard_set.cc
src/server/main_service.cc
src/server/transaction.cc
src/server/transaction.h

Introduce `CopyMultiKeys` to use copied key versions when locking, making way for #2463

chore(transaction): Launder copied keys in multi transactions

---

.github/workflows/ci.yml
src/server/transaction.cc

This is needed if we want to allow asynchronous transactional operations during the callback execution. Also update actions versions.

chore: lock keys when going through fast-path execution

---

src/core/dash_internal.h
src/core/dash_test.cc
src/server/db_slice.cc
src/server/db_slice.h
src/server/string_family.cc
src/server/string_family_test.cc

fix: #2465 
the bug: on cache mode mget bumps up items. When executing mget with the same key several times i.e mget key key we will invalidate the iterator when we bump up the item in dash table.
the fix: bump up/down items only once by using bumped_items set
This PR also reverts https://github.com/dragonflydb/dragonfly/pull/2474/commits/c2251138c6513836a1a1aa5fc39234fdb9085ce1
and updates the bumped stats and bumped_items set if the item was bumped

fix(server): mget crash on same key get

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/engine_shard_set.cc
src/server/table.cc
src/server/table.h
src/server/test_utils.cc
src/server/transaction.cc
src/server/transaction.h

This should reduce allocations in a common case (not multi). In addition, rename Transaction::args_ to kv_args_.

chore: Introduce LockKey for LockTable

---

src/core/interpreter.cc
src/core/interpreter_test.cc
tests/dragonfly/eval_test.py

fixes #2468
* add no-op lua function redis.replicate_commands()

feat(lua): add missing no-op redis.replicate_commands()

---

src/facade/facade.cc
src/facade/facade_types.h
src/facade/reply_builder.cc
src/server/server_family.cc

1. average batch latency will always be 0, because even in cases we have outliers they will be dominated by small CPU only copies that take dozens of ns.
2. Measuring an operation like kBatch, which is solely CPU-based, necessitated the use of a clock. According to the CPU profiler, this contributed to approximately 5% of the CPU usage.

chore: remove batch reply statistics

---

src/core/CMakeLists.txt
src/core/fibers.h
src/core/task_queue.cc
src/core/task_queue.h
src/server/detail/save_stages_controller.h
src/server/detail/snapshot_storage.cc
src/server/detail/snapshot_storage.h
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/server_family.cc
src/server/server_family.h

TaskQueue replaces fb2::FiberQueue and allows running multiple fibers on the consumer side.

chore: introduce TaskQueue for executing shard local tasks

---

src/server/generic_family.cc
src/server/generic_family_test.cc

Crash was a `CHECK()` failure when renaming to an existing key within the same shard.
Specifically, the problem was that we ran post updater after deletion, which is illegal as it could invalidate iterators.
Fixes #2502

fix(server): Fix crash in `RENAME`

---

src/server/transaction.cc
src/server/transaction.h

This PR introduces a PhasedBarrier primitive to replace the manual control of callback dispatches within transaction. A separate primitive makes way for simpler and easier code, as well as more clearly defined state semantics.
This PR has no functional changes.

chore(transaction): Use PhasedBarrier for easier synchronization

---

src/server/command_registry.h
src/server/common.h
src/server/script_mgr.cc
src/server/set_family.cc
src/server/stream_family.cc
src/server/transaction.cc
src/server/transaction.h
src/server/zset_family.cc

Also, simplify interfaces around REVERSE_MAPPING in the internal tx code.

fix: fix BLOCKING/REVERSE_MAPPING flags for some commands

---

src/server/conn_context.cc
src/server/multi_test.cc

fix: handle null length strings in stored commands

---

src/server/memory_cmd.cc

Given a hex address, it replies with whether or not this address is currently allocated by mimalloc's backing heap.

feat(server): Add `MEMORY TRACK ADDRESS` command

---

src/server/server_family.cc

Related Issue: https://github.com/dragonflydb/dragonfly/issues/857
The `CONFIG HELP` command is implemented in this PR.
The implementation of the `CONFIG HELP` command in Redis 7.2 was used as a reference.
The notation of the `CONFIG HELP` command in Redis 7.2 is as follows.
````
1) CONFIG <subcommand> [<arg> [value] [opt] ...] . Subcommands are: .
2) GET <pattern> .
3)     Return parameters matching the glob-like <pattern> and their values.
4) SET <directive> <value> 5) Set the configuration <directive> <value> .
5)     Set the configuration <directive> to <value>.
6) RESETSTAT
7)     Reset statistics reported by the INFO command.
8) REWRITE
9)     Rewrite the configuration file.
10) HELP
11)    Prints this help.
````
The `CONFIG REWRITE` command is not yet implemented in the current …

feat(server): Implement CONFIG HELP command

---

src/server/transaction.cc
src/server/transaction.h

Currently we assume waking a transaction is exlusive and we ensured exclusivity with
> if (wakeup_requested_.fetch_add(1, memory_order_relaxed) > 0) return
in `NotifySuspended()`
However we ensured no exclusivity with cancelling or timing out. I.e. it was totally possible for a transaction to time out and start preparing the cleanup hops, while another thread would call `NotifySuspended()`. What is more, we removed `COORD_BLOCKED` only after we called `Expire`, so we could be cancelled _while_ we are expiring. This results in a lot of unsafe data parallel accesses.
Another problem here is also that once we do 
> wakeup_requested_.fetch_add(1, memory_order_relaxed)
we technically allow blocking_ec_ in the coordinator to pass. If it wasn't suspended and just reached the check (fast path), …

fix(transaction): Add special barrier for blocking tx

---

src/server/zset_family.cc

Been seeing a few cases of `zset_family.cc:1344] Unexpected error 17`, which looks like its `CANCELLED`
This ignores `OpStatus::CANCELLED` in `BZPopMinMax`, which matches what `ListFamily::BPopGeneric` does (looks like it can be cancelled if the socket has an error)

fix(zset): ignore cancelled op status in BZPopMinMax

---

src/server/db_slice.cc
src/server/table.cc
src/server/table.h

This is a temporary fix for crash we have on check fail for db_slice size when post updater runs.
1. change check to dcheck
2. call find in post updater if needed

fix(server): auto updater find key again if needed

---

src/server/main_service.cc
src/server/replica.cc
src/server/transaction.cc
src/server/transaction.h
tests/dragonfly/replication_test.py

fix: fix replication v1.14

---

.github/actions/regression-tests/action.yml
tests/dragonfly/acl_family_test.py
tests/dragonfly/requirements.txt

* fix wrongly printing timedout emoji on non timedout test failures
* add pytest-timeout as dependency in tests/dragonfly/requirements

fix: wrongly printing timedout emoji on test failures

---

src/server/journal/journal_slice.cc
src/server/snapshot.cc
tests/dragonfly/replication_test.py

Addresses the second crash reported in #2500.

fix(server): Do not yield in journal if not allowed

---

src/core/interpreter.cc
src/core/interpreter.h
src/server/conn_context.cc
src/server/main_service.cc
src/server/server_family.cc
src/server/server_state.cc
src/server/server_state.h
tests/dragonfly/eval_test.py

Provides a fix for a critical problem where multi transactions holding locks and a place in the transaction queue would block on borrowing an interpreter, effectively causing a deadlock. This PR ensures that interpreter borrows happen only on unscheduled transactions, it also adds additional DCHECKs for more safety.

fix: fix interpreter acquisition with MULTI

---

src/server/list_family.cc
tests/dragonfly/eval_test.py

1. Increase load and lower limit for flaky test (release build was too fast)
2. Include 2553 by Romans request

fix(tests): increase interpreter test load, lower notice limit, include 2553

---

src/core/CMakeLists.txt
src/core/json/CMakeLists.txt
src/core/json/driver.cc
src/core/json/driver.h
src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_lexer.lex
src/core/json/jsonpath_test.cc
src/core/json/lexer_impl.cc
src/core/json/lexer_impl.h

Not finished yet, mostly a boilerplate plus minimal bindings for the test. Motivation: as long as we rely on jsoncons jsonpath implementation we won't be able to change json implementation as well. jsoncons path is quite qood but it will only work with jsoncons json library. By implementing this ourselves we will gain the freedom to change json implementation in the future.

feat: introduce a skeleton for jsonpath parser

---

src/server/replica.cc

fix(server): do not print warning on replica stop/ takeover

---

src/core/interpreter.cc
tests/dragonfly/instance.py
tests/dragonfly/requirements.txt
tests/dragonfly/seeder/README.md
tests/dragonfly/seeder/__init__.py
tests/dragonfly/seeder/script-generate.lua
tests/dragonfly/seeder/script-genlib.lua
tests/dragonfly/seeder/script-hash.lua
tests/dragonfly/seeder/script-hashlib.lua
tests/dragonfly/seeder/script-utillib.lua
tests/dragonfly/seeder_test.py

Adds new seeder based on lua scripts and a python wrapper for working with them
For now, doesn't support operations with types other than strings and only single-key operations
Intensity balance:
key target - 300
blue - add intensity
green - delete intensity
red - modification intensity
equilibrium point = ~0.956 * T

feat(pytest): Gen2 seeder, part 1

---

src/core/interpreter.cc
src/core/interpreter.h
src/server/main_service.cc
src/server/script_mgr.cc

InterpreterManager::Reset creates now a new storage for interpreters,
and waits for the old ones to be returned.

fix: make sure SCRIPT FLUSH concludes

---

src/server/server_family.cc
src/server/server_state.cc
src/server/server_state.h
src/server/test_utils.cc

chore: Remove manual memory management from stats

---

src/core/compact_object.cc
src/core/search/compressed_sorted_set.cc
src/server/dragonfly_test.cc
src/server/rdb_test.cc

depends on https://github.com/romange/helio/pull/213 (once it's merged I will pull the latest helio here)

fix: asan errors on unit tests

---

tests/dragonfly/instance.py

chore: Recognize exit status in regression tests

---

src/server/cluster/cluster_shard_migration.cc
src/server/journal/tx_executor.cc
src/server/journal/tx_executor.h
src/server/replica.cc

fixes #2544 
when enable_multi_shard_sync flag is false we do not sync execution of multi commands between shards in replication.
Now we will not accumulate the multi commands as well but will just execute them once we get the journal change in replica

chore(server): replica not accumulate multi commands untill exec

---

src/CMakeLists.txt
src/core/json/driver.cc
src/core/json/driver.h
src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_lexer.lex
src/core/json/jsonpath_test.cc
src/core/json/lexer_impl.cc
src/core/json/lexer_impl.h

Also update re/flex library to the latest version. Finally, introduce very basic parser test.

chore: provide plumbing for jsonpath error propagation

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/facade.cc
src/facade/facade_types.h
src/server/db_slice.cc
src/server/server_family.cc
tests/dragonfly/eval_test.py
tests/dragonfly/instance.py

Fixes #2569
Before the change we had a corner case where Dragonfly would call OnPreMigrateThread but would not call CancelOnErrorCb because OnBreakCb has already been called (it resets break_cb_engaged_)
On the other hand in OnPostMigrateThread we called RegisterOnErrorCb if breaker_cb_ which resulted in double registration. This change simplifies the logic by removing break_cb_engaged_ flag since CancelOnErrorCb is safe to call if nothing is registered. Moreover, we now skip Migrate flow if a socket is being closed.

fix: do not migrate during connection close

---

.github/workflows/ci.yml
src/server/test_utils.cc
src/server/test_utils.h
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc

fixes #2541 
Tiering unit tests might fail in github as we wait for fixed time 20 mili for writing to disc.
This PR introduces wait until condition function util for unit tests 
Tiering unit tests use this function to wait untill the tiered entries counter is updated or fail on timeout

fix(tiering tests): introduce wait until tiering entries num EQ/GT

---

src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_lexer.lex
src/core/json/jsonpath_test.cc
src/core/json/path.h

feat: add descent operator to jsonpath parser

---

src/core/compact_object.h
src/core/dash.h
src/core/dash_internal.h
src/core/dash_test.cc
src/server/db_slice.cc
src/server/db_slice.h
src/server/engine_shard_set.cc
src/server/server_family.cc
src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h

implement tiering background offloading based on https://junchengyang.com/publication/nsdi24-SIEVE.pdf
When fetching an item we set it as touched item (hot)
A background task running periodically traversing several buckets (continuing from the last place stopped) setting them as untouched items (cold) 
The background task checks if the item is cold (not touched from the last time the traverse set it as cold). If an item is cold and it can be offloaded schedule it for offload.

feat(tiering): add background offload step

---

src/server/generic_family_test.cc

The problem was that we checked both "sides" of the time, but the microseconds part will be 0 every one in, well, a million invocations.

fix(test): Unflake `GenericFamilyTest.Time*Keys`

---

src/core/json/CMakeLists.txt
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/core/json/path.h

chore: add jsonpath evaluate

---

src/server/transaction.cc
src/server/transaction.h

Copying poll flags prevents concurrent data access to `PerShardData::local_mask` when dispatching poll tasks

chore(transaction): Copy poll flags

---

src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/core/json/path.h

feat: support descent path operator

---

.gitignore
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/facade/facade_test.h
src/server/CMakeLists.txt
src/server/json_family.cc
src/server/json_family_test.cc

The feature is disabled under a flag and it covers read operations for now.

wire json::Path into json_family

---

src/core/compact_object.cc
src/core/compact_object_test.cc
src/redis/object.c
src/redis/object.h
src/redis/redis_aux.c
src/redis/redis_aux.h
src/redis/t_zset.c
src/server/container_utils.cc
src/server/rdb_load.cc
src/server/rdb_save.cc
src/server/set_family.cc
src/server/set_family.h
src/server/set_family_test.cc

chore: cleanup of redis implementation of sets/hashmaps

---

src/server/command_registry.cc
src/server/command_registry.h
src/server/debugcmd.cc
src/server/transaction.cc
src/server/transaction.h

Moves part out of #2376 
Idea: We decide whether we have to schedule not based on our multi status (atomic multi), but solely based on the fact if COORD_SCHED is set
Goal: Being able to use ScheduleSingleHop()/Schedule() for multi transactions, and thus later allow single hop multi transactions

chore(transaction): Untie scheduling from multi status

---

src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/core/json/path.h
src/server/json_family.cc

Add mutate method to jsonpath

---

src/server/CMakeLists.txt
src/server/dfly_bench.cc

Currently supports only ratio param, without command customization.
Added Normal/Uniform distributions.
Improved printings a bit to make it more useful as a cli.

add loadtest benchmarking program

---

src/core/json/driver.cc
src/core/json/driver.h
src/core/json/json_test.cc
src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_lexer.lex
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/core/json/path.h

Specifically, allows expressions in the form of
`max($.objs[*].score)`, i.e. where a function aggregates 0 or more values produced by the path expression. The final value is passed to a PathCallback. In case no matches are found, json null value is passed. In any case, the callback is called exactly once for such expressions. Currently only `max` function is supported.
In addition, fixed a parser bug that does not allow fields after the bracketing expression.
Finally, introduced an utility function for easier parsing of json::Path.

chore: allow aggregate functions for jsonpath

---

tests/dragonfly/cluster_test.py

The test didn't check anything because we pushed the config before actually generating the capture. Note that in my original #2496 this is not the case 🤨

fix: fix cluster test

---

src/server/common.cc
src/server/common.h
src/server/detail/save_stages_controller.cc
src/server/detail/save_stages_controller.h
src/server/rdb_test.cc
src/server/server_family.cc
src/server/server_family.h
src/server/snapshot.cc
src/server/snapshot.h
tests/dragonfly/replication_test.py
tests/dragonfly/snapshot_test.py

fixes #2597 
The bug:
server crashed because when replicaof no one was executed the replica was creating a snapshot and there for the server state was not active but saving.
check fail -server_family.cc:2142] Check failed: service_.SwitchState(GlobalState::LOADING, GlobalState::ACTIVE).first == GlobalState::ACTIVE Server is set to replica no one, yet state is not active!
The fix:
1. remove saving from server states
2. move save stage controller to be a member of server family

fix(server): saving is not a server state

---

src/server/server_family.cc
tests/dragonfly/replication_test.py

Closes #862
I've ran `INFO ALL` locally and the only section that showed IN CAPS was `cmdstat_COMMAND`.
So I 'lowercased' all commands on `GetMetrics()` and fixed the `replication_test.py` accordingly.
Also checked that Redis behaves the same.

fix(server_family): `GetMetrics` should show commands in lowercase

---

src/server/cluster/cluster_config.cc
src/server/cluster/cluster_config.h
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/cluster_shard_migration.cc
src/server/cluster/cluster_slot_migration.cc
src/server/cluster/cluster_slot_migration.h
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
tests/dragonfly/cluster_test.py

ACK cmd is the answer from a target node to  a source node' FINALIZE cmd

feat(cluster): #2448 add new DFLYMIGRATE ACK cmd

---

.github/workflows/regression-tests.yml

test: Run slow tests in regression runs (again^2)

---

src/core/interpreter.cc
src/core/interpreter.h
src/server/common.cc
tests/dragonfly/instance.py
tests/dragonfly/json_test.py
tests/dragonfly/replication_test.py
tests/dragonfly/seeder/__init__.py
tests/dragonfly/seeder/script-generate.lua
tests/dragonfly/seeder/script-genlib.lua
tests/dragonfly/seeder/script-hash.lua
tests/dragonfly/seeder/script-hashlib.lua
tests/dragonfly/seeder/script-utillib.lua
tests/dragonfly/seeder_test.py

This PR:
* adds more types to the seeder, finally all types are supported
* makes `dragonfly.ihash` use internal command dispatch to avoid excessive copies
* refactors replication test a little to show how to use markers

feat(pytest): More types for seeder

---

src/facade/error.h
src/facade/facade.cc
src/facade/reply_builder.cc
src/server/main_service.cc
src/server/server_family.cc
tests/dragonfly/replication_test.py
tests/dragonfly/utility.py

addresses #2617 
* add -LOADING prefix for loading errors
* replace -ERR with -LOADING for loading errors

fix: loading state error type to be compatible with redis

---

src/server/hset_family.cc

Partially addresses #2500 and avoid crashing the process.

fix: provide more context in case we have duplicate keys

---

CMakeLists.txt
src/CMakeLists.txt
src/server/json_family.cc
src/server/search/doc_accessors.cc

search_family_test passes witth `--jsonpathv2`

chore: doc_accessors now parse with json::Path as well

---

src/core/interpreter.cc
src/core/interpreter_test.cc

```
eval "local a = {}; setmetatable(a,{__index=function() foo() end}) return a" 1 0
```
This command can make dragonfly crash, I fix it.

fix: crash when using nonexistent global variable in lua

---

.github/actions/lint-test-chart/action.yml
.github/workflows/bullmq-tests.yml
.github/workflows/cov.yml
.github/workflows/daily-builds.yml
.github/workflows/docker-release.yml
.github/workflows/reusable-container-workflow.yaml
src/core/uring.h
src/facade/cmd_arg_parser.cc
src/facade/cmd_arg_parser_test.cc
src/facade/dragonfly_connection.cc
src/server/CMakeLists.txt
src/server/detail/save_stages_controller.cc
src/server/detail/snapshot_storage.cc
src/server/detail/snapshot_storage.h
src/server/list_family.cc
src/server/tiered_storage.h

Also update actions versions to Node 20.
This change allows dragonfly to be built on MacOs. However, we still have multiple failing tests.

chore: fix build for MacOs

---

src/server/detail/save_stages_controller.cc
src/server/detail/save_stages_controller.h
src/server/server_family.cc
src/server/server_family.h

fixes #2644
* Initialize resources atomically to avoid race condition
* Finalize/cleanup resources atomically to avoid race condition
* Refactor SaveStagesController::Save

fix: data race in save_stages_controller

---

.github/workflows/ci.yml
.github/workflows/daily-builds.yml
src/redis/zmalloc.h

Fixes `hset_family_test` tests on MacOS
Looks like `zmalloc_size` isn't defined properly on Mac, so `zmalloc` uses `src/redis/zmalloc_mi.c` definition but `zmalloc_size` uses `malloc_size`
```
void *zp = zmalloc(10);
cout << "zmalloc; zmalloc_size " << zmalloc_size(zp) << endl;  // 0
cout << "zmalloc; malloc_size " << malloc_size(zp) << endl;  // 0
cout << "zmalloc; zmalloc_usable_size " << zmalloc_usable_size(zp) << endl;  // 16
void *mp = malloc(10);
cout << "malloc; malloc_size " << malloc_size(mp) << endl;  // 16
cout << "malloc; zmalloc_size " << zmalloc_size(mp) << endl;  // 16
```
This just copies the `USE_ZMALLOC_MI` branch from `libc` into `macos` branch (I don't really understand this allocator stuff but with this the `hset_family_test` tests pass running locally on Mac - will …

fix: fix zmalloc_size on macos

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/memcache_parser.cc
src/server/main_service.cc
tests/dragonfly/conftest.py
tests/dragonfly/connection_test.py
tests/dragonfly/pymemcached_test.py

Add support for pipelining to memcached connection interface
Update pytests to cover noreply dynamics more extensively

feat(connection): Support pipelining with Memcached

---

.github/workflows/ci.yml
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/server/json_family.cc
src/server/json_family_test.cc

chore: JSON.GET now works with our own jsonpath

---

src/server/json_family.cc

chore: fully switch to dual parsing with json::Path

---

src/server/main_service.cc

With the new seeder, this shows up all the time in the logs - it slows execution down. The new seeder also uses squasing, so it might provide not much insight into what was executed last

chore: Move CallFromScript log to level 2

---

src/core/json/path.cc
src/core/json/path.h
src/server/json_family.cc
src/server/json_family_test.cc
tests/dragonfly/instance.py

Also, fix various protocol bug when we sent simple string instead of sending bulk strings.

chore: Del and NUMINCRBY use json::Path

---

tests/dragonfly/cluster_test.py
tests/dragonfly/utility.py

Redis-py has a bug where they don't find a cached connection once they normalize the host address (i.e. replace localhost with 127.0.0.1), this leads to `Unclosed ClusterNode object` error if a note has more than one slot range
Maybe it's fixed in the latest version 🤷🏻‍♂️

fix: replace localhost with 127.0.0.1 in cluster tests

---

src/core/dash.h
src/server/generic_family.cc
src/server/generic_family.h
src/server/generic_family_test.cc

Resolves #443.
Redis claims to have `O(1)` time complexity because:
1. it sets a threshold of 100 tries to get a key, each try it:
2. collects 15 entries from a random `dict` then:
3. gets a random entry from those 15
4. if the key is not expire, returns the key, else go back to step 2.
~So for this solution I set a threshold of 15 entries, and loop through all shards in parallel collecting 2 entries per child, then I take one random index of these collection.~
Sometimes the `RANDOMKEY` command throws the following error on the `std::vector<>::~vector()`:
```shell
*** SIGSEGV received at time=1708536096 on cpu 0 ***
PC: @     0x55a4ffdb89f9  (unknown)  mi_free
@     0x55a5007d8b38        192  absl::lts_20230802::WriteFailureInfo()
@     0x55a5007d910d        272 …
```

feat(generic_family): implement RANDOMKEY command

---

src/facade/dragonfly_listener.cc
src/facade/dragonfly_listener.h
src/server/command_registry.h
src/server/main_service.cc
src/server/server_family.cc
src/server/transaction.cc
tests/dragonfly/connection_test.py

fix(server): client pause work while blocking commands run

---

src/facade/facade.cc
src/server/dragonfly_test.cc
src/server/main_service.cc

Redis, due to its old lua enginer and bunch of historic reasons returns floats as integers from lua scripts. This means `eval "return 42.9" 0` would return 42 as long integer.
Dragonfly supports both integers and floats in its lua engine, returning a precise "42.9" in the same scenario. RESP2 does not support float types so "42.9" is returned as a bulk string for RESP2 connections. For RESP3, dragonfly returns 42.9 as a native RESP3 double primitive.
This PR introduces an optional legacy behavior for Dragonfly only for the RESP2 protocol. When the `--lua_resp2_legacy_float` flag is passed, Dragonfly will round down the double value to the nearest integer and return it as RESP2 native long integer.
Fixes #2664

fix: optionally return float as integer from lua script

---

src/server/main_service.cc
src/server/server_family.cc
src/server/server_state.cc
src/server/server_state.h

Expose oom/cmd errors when we reject executing a command if we reached OOM state (controlled by oom_deny_ratio flag).
Expose oom/insert errors when we do not insert a new key or do not grow a dashtable (controlled by table_growth_margin).

chore: add oom stats to /metrics

---

.github/workflows/daily-sanitizers.yml

I forgot to add a manual trigger to daily sanitizers.

fix: missing manual trigger for daily sanitizers

---

tools/docker/healthcheck.sh
tools/packaging/Dockerfile.alpine-dev
tools/packaging/Dockerfile.ubuntu-dev
tools/packaging/Dockerfile.ubuntu-prod

Chore: Fixed Docker Health Check

---

src/server/db_slice.cc

In the fiber we used to call `mi_heap_collect()` when we're done deleting items. But since that fiber captures a `vector` of intrusive pointers to `DbTable`s, it can't free all memory used by the tables themselves.
A local test shows that this fix helps almost entirely: when occupying a 5gb DB, `FLUSHALL` will reduce RSS by 4.7gb, leaving 300mb still used. A follow up `MEMORY DECOMMIT` *will* indeed remove these 300mb, but I'm still not sure why they are not released immediately. Still looking...
Addresses (1) of #2690

fix(flushall): Decommit memory after releasing tables.

---

src/server/db_slice.cc
src/server/memory_cmd.cc
src/server/server_state.cc
src/server/server_state.h

Provides more stats and control with glibc-malloc based allocator. For example,
with v1.15.0 (--proactor_threads=2), empty database, `info memory`returns
```
used_memory:614576
used_memory_human:600.2KiB
used_memory_peak:614576
used_memory_peak_human:600.2KiB
used_memory_rss:19922944
used_memory_rss_human:19.00MiB
```
then during `memtier_benchmark  -n 300000  --key-maximum 100000 --ratio 0:1 --threads=30 -c 100` (i.e GET-only with 3k connections):
```
used_memory:614576
used_memory_human:600.2KiB
used_memory_peak:614576
used_memory_peak_human:600.2KiB
used_memory_rss:59985920
used_memory_rss_human:57.21MiB
used_memory_peak_rss:59985920
```
connections overhead grows by ~39MB.
when the traffic stops, `used_memory_rss_human` becomes `30.35MiB` and we do not know where 11MB gets lost and …

chore: add malloc-based stats and decommit

---

src/server/cluster/cluster_config.h
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/cluster_slot_migration.cc
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
tests/dragonfly/cluster_test.py

feat(cluster): automatic slot migration finalization #2697

---

src/server/generic_family.cc
src/server/list_family.cc
src/server/transaction.cc
src/server/transaction.h

* renable_auto_journal was atomic for some reason, change to regular bool
~~* Move OOM check to where it belongs~~
* add DCHECKS in guard functions
* Simplify cancel shard cb (we never set KEYLOCK_ACQUIRED for global... maybe we want to change it somewhen in the future?)

chore: little transaction cleanup

---

src/server/channel_store.cc
src/server/channel_store.h

I assume this is why our ARM regtest `test_pubsub_numsub` had outdated info. This pointer is shared between threads and update immediately, but the memory behind it is not synced...

fix(channel store): add acquire/release pair in fast update path

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/dflycmd.cc
src/server/server_family.cc
src/server/server_family.h
tests/dragonfly/cluster_test.py
tests/dragonfly/utility.py

This flag sets the unique ID of a node in a cluster.
It is UB (and bad) to set the same ID to multiple nodes in a cluster.
If unset (default), the `master_replid` (previously known as `master_id`) is used.
Fixes #2643
Related to #2636

feat(cluster): Add `--cluster_id` flag

---

src/facade/dragonfly_listener.cc
src/facade/dragonfly_listener.h
src/server/memory_cmd.cc
tools/generate-tls-files.sh

Until now, OpenSSL used `malloc()` directly. This PR overrides it to use mimalloc.
Fixes #2709

feat(server): Use mimalloc in SSL calls

---

src/server/common.h
src/server/generic_family.cc
src/server/rdb_load.cc
src/server/string_family.cc
src/server/string_family_test.cc

Also, provide a module name if stumbled upon module data that can not be loaded by dragonfly.

chore: improve compatibility of EXPIRE functions with Redis

---

src/server/generic_family_test.cc
src/server/server_family.cc
src/server/server_family.h
tests/dragonfly/replication_test.py
tests/dragonfly/snapshot_test.py
tests/dragonfly/utility.py

resolves #2642
* make BgSave command async
Note that we extend the command by adding `BGSAVE [RDB_TYPE] [NAME] [SCHEDULE]` but in Redis it's `BGSAVE [SCHEDULE]`. Unfortunately, DF supports two rdb_types (df extension and plain redis rdb) and I would like to keep compatibility. 
Furthermore, the option [schedule] is missing. See: #2701

fix(BgSave): async from sync

---

src/server/blocking_controller.cc
src/server/engine_shard_set.cc
src/server/main_service.cc
src/server/transaction.cc
src/server/transaction.h

1. Replaces run_barrier as a synchronization point with is_armed + an embedded blocking counter for awaiting running jobs
2. Replaces `IsArmedInShard` + `GetLocalMask` + `is_armed.exchange` chain with a single `DisarmInShard()` / `DisarmInShardWhen`

fix(transaction): Replace with armed sync point

---

src/server/main_service.cc

Fix to one of #2580 
We do support not lua inside multi, so this optional is no longer relevant

chore: fix DeduceExecMode

---

.github/actions/lint-test-chart/action.yml
.github/workflows/ci.yml
.github/workflows/daily-builds.yml
.github/workflows/docker-release.yml
.github/workflows/regression-tests.yml
.github/workflows/release.yml
.github/workflows/reusable-container-workflow.yaml
contrib/charts/dragonfly/ci/priorityclassname-values.golden.yaml
src/core/mi_memory_resource.cc
src/core/mi_memory_resource.h
src/server/CMakeLists.txt
src/server/dfly_main.cc
src/server/memory_cmd.cc
src/server/replica.cc
src/server/server_family.cc
src/server/server_family.h

1. Use mi_malloc for allocating fiber stacks. Introduce FiberStackResource - a memory resource dedicated for handling stack allocations, and inject it into Fibers library as well as accept listeners.
2. Add "memory_fiberstack_vms_bytes" metric exposing fiber stack vm usage.

chore: Introduce fiber stack allocator

---

src/core/flatbuffers_test.cc
src/core/json/CMakeLists.txt
src/core/json/detail/flat_dfs.cc
src/core/json/detail/flat_dfs.h
src/core/json/jsonpath_test.cc
src/core/json/path.h

Also adjust jsonpath_test to be a typed test to allow run the same tests for both jsoncons and flatbuffers.

chore: add skeleton files for flat_dfs code

---

src/server/json_family.cc
src/server/json_family_test.cc

To my defense Redis does the same 😆 Closes #2722

chore: Support json paths without root selector

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/cluster_slot_migration.cc
src/server/cluster/cluster_slot_migration.h
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
tests/dragonfly/cluster_test.py

start-slot-migration command is removed
initiating process starts from the source node instead of the target node

refactor: remove start-slot-migration cmd #2727

---

src/core/json/detail/flat_dfs.cc
src/core/json/driver.cc
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/core/json/path.h

1. More test fixes to support both types
2. Adjust Aggregation functions to work with both types
3. jsonpath_test build from both types and passes for JsonType, the tests are skipped for flexbuffers

chore: preparations for adding flat json support

---

src/server/replica.cc
tests/dragonfly/proxy.py
tests/dragonfly/replication_test.py

Until now, replicas would re-connect and re-replicate a master after the master will restart. This is problematic in case the master loses its data, which will cause the replica to flush all and lose its data as well.
This is a breaking change though, in that whoever controls the replica now has to explicitly issue a `REPLICAOF X Y` in order to re-establish a connection to a new master. This is true even if the master loaded an up to date RDB file.
It's not necessary if the replica lost connection to the master and the master was always alive, and the connection is re-established.
Fixes #2636

feat(replication): Do not auto replicate different master

---

src/facade/dragonfly_connection.cc
src/facade/reply_capture.h
src/server/CMakeLists.txt
src/server/http_api.cc
src/server/http_api.h
src/server/main_service.cc
tests/dragonfly/connection_test.py
tests/dragonfly/instance.py

The goal is to provide very basic support for simple commands,
fancy stuff like pipelining, blocking commands won't work.
1. Added optional registration for /api handler.
2. Implemented parsing of post body.
3. Added basic formatting routine for the response. It does not cover all the commands but should suffice for
basic usage.
The API is a POST method and the body of the request should contain command arguments formatted as json array.
For example, `'["set", "foo", "bar", "ex", "100"]'`.
The response is a json object with either `result` field holding the response of the command or
`error` field containing the error message sent by the server.
See `test_http` test in tests/dragonfly/connection_test.py for more details.

chore: preparation for basic http api

---

src/core/json/detail/flat_dfs.cc
src/core/json/jsonpath_test.cc

This commit fixes the logic around read only traversals over flexbuffer json object.

chore: fix flat_dfs read tests.

---

tests/dragonfly/conftest.py

The problem is that each time we start an instance it overwrites the `last_log_file`. The problem with this is that it erases some of the logs that we should upload during failure. This patch addresses this by providing clean up semantics. Specifically, the file `last_log_file` gets erased each time we start a test case and instances now open the file in `append mode` instead of `overwrite`

fix(ci): do not overwrite last_log_file among tests

---

src/server/cluster/cluster_config.cc
src/server/cluster/cluster_config.h
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family_test.cc
src/server/cluster/slot_set.h
src/server/common.cc
src/server/common.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/debugcmd.cc
src/server/detail/save_stages_controller.h
src/server/journal/executor.cc
src/server/journal/executor.h
src/server/main_service.cc
src/server/main_service.h
src/server/replica.cc
src/server/replica.h
src/server/server_family.cc
src/server/server_family.h
src/server/test_utils.cc
src/server/zset_family.cc
tests/dragonfly/cluster_test.py

In this PR we introduce new command 
ADDREPLICAOF <host> <port> <slot start> <slot end>
and extend REPLICAOF command with optional params <slot start> <slot end>
The slot range data is used only to flush the relevant data if the replication to a node disconnected
To replicate a cluster we first issue command 
REPLICAOF <host> <port> <slot start> <slot end> 
with data for a single node from the cluster
than for each additinal cluster master node we run
ADDREPLICAOF <host> <port> <slot start> <slot end>
To promote the replica to master we will run 
REPLICAOF NO ONE
If we run REPLICAOF this will start replication from scratch removing all added replicas

feat(server): support cluster replication

---

src/core/dash_internal.h
src/server/db_slice.cc

addressed #2486 
* cache fetched_items_ before preemption such that `OnCbFinish` does not affect it

fix: fiber preempts on read path and OnCbFinish() clears fetched_items_

---

src/server/CMakeLists.txt
src/server/io_mgr.cc
src/server/io_mgr.h
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/disk_storage_test.cc

DiskStorage is a simple utility class for async operations. It internally combines ExternalAllocator and IoMgr. This is a very useful abstraction missing from the old design.

feat(tiering): DiskStorage

---

src/server/CMakeLists.txt
src/server/acl/acl_commands_def.h
src/server/acl/acl_family_test.cc
src/server/bloom_family.cc
src/server/bloom_family.h
src/server/bloom_family_test.cc
src/server/main_service.cc

Consists of 3 basic functions:
BF.RESERVE, BF.ADD, BF.EXISTS

chore: add a boilerplate for bloom filter family

---

src/core/flatbuffers.h
src/core/flatbuffers_test.cc
src/core/json/json_object.h
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/core/json/path.h

chore: introduce conversion routines between JsonType and FlatJson

---

src/core/dash.h
src/core/dash_internal.h
src/core/dash_test.cc
src/server/db_slice.cc

* rename all Policy members for consistency 
* remove duplicate code

chore: remove duplicate code from dash and simplify

---

src/core/CMakeLists.txt
src/core/bloom.cc
src/core/bloom.h
src/core/bloom_test.cc

Based on https://github.com/jvirkki/libbloom implementation.
Unlike the original, our implementation uses XXH3 hash function to seed bit index generation. In addition, it assumes mi_malloc interface for dynamic allocation.

chore: add bloom filter class

---

src/core/bloom.cc
src/core/bloom.h
src/core/bloom_test.cc

Based on https://gsd.di.uminho.pt/members/cbm/ps/dbloom.pdf
The data-structure itself is a growing list of bloom filters, where the next filter has exponentially larger capacity with exponentially tighter error bound.
The Exist() goes over all the filters and it's enough that at least one of them returns a positive result. For Add(), we make ensure that all the existing filters do not have the element, as well as making sure that the last filter that is being filled does not cross its maximum designated capacity.

chore: add SBF data structure

---

src/server/CMakeLists.txt
src/server/server_state.cc

Make great sanitizers great again.
`malloc_trim` segfaults on sanitizers workflow because sanitizers use their own malloc implementation and they are unaware of `malloc_trim`. Consequently, when called, some of it's contents are not properly initialized causing the tests to segfault.
* remove malloc_trim from sanitizers build
resolves #2751

fix(ci): malloc trim on sanitizers workflow

---

src/server/string_family.cc

chore: refactor StringFamily::Set to use CmdArgParser

---

src/server/dragonfly_test.cc
src/server/string_family.cc
src/server/test_utils.cc

fix: propagate memcached flags to replica

---

src/server/journal/journal.cc
src/server/journal/journal_slice.cc
src/server/journal/journal_slice.h
src/server/journal/serializer.cc
src/server/journal/streamer.cc
src/server/journal/streamer.h
src/server/journal/tx_executor.cc
src/server/journal/types.h
src/server/replica.cc
src/server/snapshot.cc

The bug:
When downgrading from main to 15.1 using replica takeover the takeover will fail as lags are different between master and replica. The reason for this is that we wrote the LSN opcode to journal but did not send this opcode to replica if the replica version is lower than DflyVersion::VER4 because the replica does not know this opcode.
The problem is that lsn would increase in master but not in replica leading to replica takover fail as lag increase.
The fix:
Sending the LSN opcode now from steamer and do not write it to journal this way we will not increase journal lsn counter

bug(server): do not write lsn opcode to journal

---

.github/actions/regression-tests/action.yml
src/server/journal/tx_executor.cc
src/server/replica.cc

The bug:
The execution fiber in replica with multi shard sync was not awaked therefore it did not execute some data recieved in replica side. 
The fix:
call notifyAll on waker to wake the ACK fiber and the executor fiber

fix(replication): replication with multi shard sync enabled lagging

---

src/server/cluster/cluster_config.cc
src/server/cluster/cluster_config.h
src/server/cluster/cluster_config_test.cc
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/cluster_family_test.cc
src/server/cluster/cluster_slot_migration.h
src/server/cluster/unique_slot_checker.cc
src/server/cluster/unique_slot_checker.h
src/server/common.cc
src/server/db_slice.cc
src/server/debugcmd.h
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/generic_family.cc
src/server/journal/streamer.cc
src/server/journal/types.cc
src/server/journal/types.h
src/server/main_service.cc
src/server/table.cc
src/server/table.h

have implemented part of the new config logic regarding migration
do refactoring and remove extra includes

fix: #2745 don't start migration process again after apply the same the same config is applied

---

src/core/compact_object.cc
src/core/compact_object.h
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/core/json/path.h
src/server/json_family.cc

This is done by converting the flat blob into mutable c++ json and then building a new flat blob.
Also, add JsonFlat encoding to CompactObject class.

chore: implement path mutation for JsonFlat

---

src/core/bloom.cc
src/core/bloom.h
src/core/compact_object.h

Needed to be able to (de)serialize SBF objects.

chore: expose direct API on Bloom objects

---

tests/dragonfly/connection_test.py

Fixes #2828 
The issue is actually quite simple, both SUBSCRIBE and UNSUBSCRIBE don't send any replies and instead issue RESP3 push notificaitons. The client, however, doesn't wait even for the push notifications
https://github.com/redis/redis-py/blob/master/redis/client.py#L807-L809
I added a manual `get_message` call

fix(tests): Fix numsub test

---

src/facade/dragonfly_connection.cc
src/server/http_api.cc
tests/dragonfly/connection_test.py
tests/dragonfly/http_conf_test.py

And thanks to @sunneydev for finding the bug and providing the tests.
The tests actually uncovered another bug where we may parse partial http requests.
This one is handled by https://github.com/romange/helio/pull/243

fix: authorize the http connection to call commands

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
tests/dragonfly/cluster_test.py
tools/cluster_mgr.py

The number of keys in an _incoming_ migration indicates how many keys were received, while for _outgoing_ it shows the total number. Combining the two can provide the control plane with percentage.
This slightly modified the format of the response.
Fixes #2756

feat(cluster): Send number of keys for incoming and outgoing migrations.

---

src/facade/conn_context.h
src/server/blocking_controller_test.cc
src/server/container_utils.cc
src/server/container_utils.h
src/server/list_family.cc
src/server/stream_family.cc
src/server/transaction.cc
src/server/transaction.h
src/server/zset_family.cc
tests/dragonfly/connection_test.py

fixes #2660 
The bug:
connection blocking and pause flags are not set on all blocking commands.
Therefor if client pause is running when running brpoplpush it will not be able to puase and return timeout, as
the DispatchTracker will not know that this connections are blocking connecitons
The fix:
Pass connection cntx to WaitOnWatch to set the blocking and pause flags

bug(server): set connection flags block/pause flag on all blocking commands

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/server/dflycmd.cc

resolves #2769
The problem is that we are shutting down master. During this flow, we iterate and shutdown all of the listeners and then we give a chance for the currently executing commands to finish with `DispatchTracker`. However, this is problematic, because internally it traverses all of the connections in all shards and sends `SendCheckPoint` messages. When this happens, it forces the connection that handles the replica to activate its `dispatch_fiber_`.  If this happens before we `Migrate` the connection in the replication flow (dflycmd) then we will trigger the CHECK that asserts that the dispatch_fiber is not actve (it was never launched). 
Unfortunately this is based on timing and therefore it requires two things:
1. Migrate might fail if `dispatch_fiber` is active. In that case …

fix: test_replicaof_reject_on_load crash on stop

---

src/server/json_family.cc
src/server/json_family_test.cc

resolves #2871
* make path optional in json.objkeys

fix(json): make path optional in json.objkeys

---

src/server/string_family.cc
src/server/string_family_test.cc

fix: return wrong type errors for SET...GET command

---

src/server/replica.cc
tests/dragonfly/redis_replication_test.py

currently partial sync flow is not implemented.
In this flow we encountered in https://github.com/dragonflydb/dragonfly/issues/2836 we can see that dragonfly tries to reconnect to valkey master after the first sync failed, because it already has the valkey master id, it kick-start a partial sync . currently partial sync flow is not implemented, so we just read the header - `absl::ConsumePrefix(&header, "CONTINUE")` 
and move to stable sync.
fixes #2836

fix(redis replication): remove partial sync flow ,not supported yet

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/debugcmd.cc
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/server_family.cc
src/server/table.cc
src/server/table.h
src/server/test_utils.cc
src/server/transaction.cc
src/server/transaction.h

It's a first step that will probably simplify dependencies in many places where we need to keep key strings for that. A second step will be to reduce the CPU load of multi-key operations like MSET and precompute Fingerprints once.

chore: LockTable tracks fingerprints of keys

---

src/facade/dragonfly_connection.cc
src/server/dflycmd.cc

chore: reject TLS handshake when our listener is plain TCP

---

src/facade/error.h
src/facade/facade.cc
src/facade/facade_types.h
src/server/main_service.cc
src/server/multi_test.cc
src/server/script_mgr.cc
src/server/script_mgr.h
src/server/server_family.cc

fixes #2870 
1. expose a metric with script errors
2. Add an error log of a script SHA and the reason for failure. The error log must be bounded with at most K log entries per script so we won't have logs overflow for high throughput traffic.
3. Additional feature (under a flag) upon receiving the undeclared variable error - transform the script to globally-atomic and retry the call.

feat server: bring visibility to script errors

---

src/server/main_service.cc
tests/dragonfly/connection_test.py

resolves #2891
* disable authentication on UDS socket
* add a test so the bug won't happen again

fix(acl): authentication with UDS socket

---

src/server/transaction.cc

RegisterBreakHook cancels the barrier ahead to not suspend in the blocking part under any case

chore(blocking): Remove faulty DCHECK

---

src/server/cluster/cluster_config.cc
src/server/cluster/cluster_config.h
src/server/cluster/cluster_config_test.cc
src/server/common.cc
src/server/common.h
src/server/main_service.cc
src/server/test_utils.cc
src/server/test_utils.h

Before this PR: Hashtags, if enabled, meant the text between `{` and `}` in the key (if exists and non-empty).
After this PR:
* Hashtags can _still_ be enabled / disabled
* Hashtag open / close char can be specified (and can be the same), like `:` popular with BullMQ
* Hashtag can include `N` closing tags to skip, like `{a}b}c}d` with `2` will return `a}b}c`.
* Hashtags can be limited to only be applied on keys with a specified prefix
This will allow some existing systems to migrate without code changes in client code.

feat(server): Allow configuration of hashtag extraction

---

src/server/replica.cc
tests/dragonfly/cluster_test.py
tests/dragonfly/utility.py

The bug:
When replicating redis cluster node we move the server to loading state in the full sync phase with the node,
when other cluster redis nodes are in stable sync and executing commands we rejected the commands execution due to loading state of server.
The fix:
setting conn_context.journal_emulated = true will make sure we dont reject the command on loading state
resolves: #2886

fix(cluster_replication): replicate redis cluster node bug fix

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/server/acl/acl_family.cc

Fixes a bug that was reported in Discord. 
When there is an update to an ACL user, the changes are propagated by traversing all the connections on each thread and calling SendAsync with an ACL update message pushed at the front of the queue. This internally activates the `dispatch_fb_`.
Unfortunately, traversals on HTTP connections are causing numerous issues:
1. SendAsync is problematic because for example it accesses `stats_` which uninitialized for that flow 
2. We don't Join the dispatch_fb_ fiber on HTTP flow
All in all, I skip Http connections all together since they are not really part of ACL's atm. Furthermore, I noticed that in some HTTP connections the `cc_` was nullptr (which I think it happens during shudown) and for that I added a sanity check that it's not nullpt (and …

fix(acl): skip http and add check on connection traversals

---

src/server/multi_test.cc

The recent patch that logs script failures introduced 2 false positives in the sanitizers build which I had to manually disable. 
Unfortunately, we can't deal with these failures because sanitizers only fully support boost `ucontext` which is `slow` and sends our build/execution time of tests to the moon.

fix(sanitizers): false positive fail on multi_test::Eval

---

src/core/heap_size.h
src/server/cluster/cluster_config.cc
src/server/cluster/cluster_config.h
src/server/cluster/cluster_config_test.cc
src/server/common.cc
src/server/common.h
src/server/conn_context.cc
src/server/conn_context.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/engine_shard_set.cc
src/server/main_service.cc
src/server/string_family_test.cc
src/server/table.cc
src/server/table.h
src/server/test_utils.cc
src/server/test_utils.h
src/server/transaction.cc

The main change here is introduction of the strong type LockTag that differentiates from a string_view key.
Also, some testing improvements to improve the footprint of the next PR.

chore: preparation step for lock fingerprints

---

src/server/string_family.cc
src/server/string_family.h
src/server/tiered_storage_test.cc

Because I'm editing the string family, I also want to clean it up a little to make changes easier. I'll remove more redundant code in successive tiering PRs
No functional changes except breaking old tiering

chore(string_family): Refactor SetCmd

---

src/facade/reply_builder.cc
src/facade/reply_builder.h
src/server/server_family.cc

For high connection rate cases it can be significant. In addition, refactor reply_builder so we could use SendStringArrInternal for more cases like SendScoredArray that also has high latency overhead for replies.

fix: Improve reply latency of HELLO

---

src/facade/reply_builder.cc
src/facade/reply_builder.h
src/server/main_service.cc

Use SendStringArrInternal that reduces dramatically number of socket calls for long arrays.

chore: improve reply latency of SendScoredArray

---

src/facade/dragonfly_connection.cc

Fixes the following crash: https://github.com/dragonflydb/dragonfly/actions/runs/8746231840/job/24002706099#step:6:1987
The problem is that when an instance is shutdown, it iterates over each of the connections on each shard and it shuts down the socket while the main listener dispatches a connection to the next proactor. When this happens, the socket is closed by the time `HandleRequests` is invoked, which triggers the `DCHECK(socket->IsOpen())` while it tries to register the error cb via `RegisterOnErrorCb`.

fix: socket closed when RegisterOnErrorCb is called in HandleRequests

---

src/server/common.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/engine_shard_set.cc
src/server/main_service.cc
src/server/server_family.cc
src/server/table.cc
src/server/table.h
src/server/test_utils.cc
src/server/test_utils.h
src/server/transaction.cc
src/server/transaction.h

1. Introduce LockTag a type representing the part of the key that is used for locking.
2. Hash keys once in each transaction.

chore: get rid of lock keys

---

src/server/server_family.cc

This fixes compatibility issues with frameworks like Lettuce Java that expect exact words when parsing INFO response.

fix: introduce info_replication_valkey_compatible flag

---

src/server/server_family.cc

As requested in #2912 
Add the metrics in the two places, run manual tests to confirm that custom and default values are reflected. No automatic tests were found for similar functionality so none were added.
Pre-commit hooks passed.
Test command:
> ./dragonfly --admin_nopass --logtostderr --bind localhost --maxclients 54321 --port 5000
Relevant output of `/metrics`:
```
dragonfly_max_clients 54321
```
Relevant output of redis-cli:
```
127.0.0.1:5000> info clients
connected_clients:1
max_clients:54321
client_read_buffer_bytes:256
blocked_clients:0
dispatch_queue_entries:0
```
Results of unit test (`python3 -m pytest -xv dragonfly`):
`30 passed, 3 skipped, 1 warning, 1 error`
Error was due to redis version mismatch (redis-server-6.2.11 required, 7.2.4 present)

feat(metrics): adding max_clients to metrics and info output (#2912)

---

src/core/json/detail/flat_dfs.cc
src/core/json/detail/flat_dfs.h
src/core/json/detail/jsoncons_dfs.cc
src/core/json/detail/jsoncons_dfs.h
src/core/json/json_test.cc
src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_lexer.lex
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/core/json/path.h

Before this change, we only allowed a single non-negative index or a wildcard inside brackets []. For example, "$.foo[1]".
This PR extends the indexing expression to negative indices. It also builds up the foundation to support [begin:end] slices, though this has not been implemented in this PR.

feat: extended bracket index in jsonpath

---

tests/dragonfly/instance.py

The problem is `proc.wait()` can deadlock according to https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait
I quote:
>>Note This will deadlock when using stdout=PIPE or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use [Popen.communicate()](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) when using pipes to avoid that.
Which we do: 
```
205         self.proc = subprocess.Popen(
206             run_cmd, cwd=self.params.cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
207         )
```

fix(pytests): replace proc.wait() with proc.communicate() to avoid deadlocks

---

src/server/common.cc
src/server/common.h
src/server/server_family.cc
src/server/server_family.h
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/disk_storage_test.cc
src/server/tiering/io_mgr.h
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc
src/server/tiering/small_bins.cc
src/server/tiering/small_bins.h
tests/dragonfly/tiering_test.py

chore(tiering): Lots of metrics

---

src/facade/dragonfly_connection.cc

resolves #2905 
The problem is that DF might be shutting down (which sets the connection_closing to true) and a call to `Migrate` will trigger the check that the connection is not closing. The fix is simple: just return false when Migrate is called and the connection is closing.
* Return false when Migrate is called on a closing connection

fix: crash during migration when connection is closing

---

src/server/dflycmd.h
src/server/main_service.cc
src/server/protocol_client.h
src/server/replica.cc
src/server/replica.h
src/server/server_family.cc
src/server/server_family.h

resolves #2907 
* remove acl-checker which is also the source of this bug
* add a fallback that cancels replication when REPLCONF ACK fail

fix: remove acl-check and cancel instead when REPLCONF ACK fails to validate

---

tests/dragonfly/instance.py

Fixes: https://github.com/dragonflydb/dragonfly/pull/2964#discussion_r1584260766
* check return code of process after terminate

fix: check return code of process after communicate

---

src/server/acl/helpers.cc
src/server/acl/helpers.h
tests/dragonfly/acl_family_test.py

resolves #2980
* allow non hashed passwords when loading from acl file

fix: allow non hashed passwords when loading users from acl file

---

tools/packaging/Dockerfile.ubuntu-dev
tools/packaging/Dockerfile.ubuntu-prod

1. Restrict build context in our dev/weekly builder to ease development iterations.
2. Switch weekly build to debian 12-slim because it's smaller than 24.04
3. Update our prod releases to use ubuntu 22.04

chore: update our container distributions versions

---

src/server/acl/acl_family.cc
src/server/dfly_main.cc

We add other listeners to `listeners`, but we seem to have forgotten to do that to the memcached listener.
Fixes #2986

fix(memcached): Register memcached listener to handle `--maxclients`

---

src/server/cluster/cluster_family.cc
src/server/db_slice.cc
src/server/journal/journal_test.cc
src/server/journal/serializer.cc
src/server/journal/serializer.h
src/server/journal/streamer.cc
src/server/journal/types.cc
src/server/journal/types.h
src/server/json_family.cc
src/server/transaction.cc
src/server/tx_base.cc
tests/dragonfly/replication_test.py

This PR changes `Entry::Payload` to struct instead of variant.

chore: another preparation commit to get rid of kv_args in transaction

---

src/core/compact_object.cc
src/core/segment_allocator.cc
src/core/segment_allocator.h
src/core/small_string.cc
src/core/small_string.h

When allocating small string if SegmentAllocator::address_table_ is bigger than 2^12 we will get wrong pointer when translating the address SegmentAllocator::Translate
This led to crash in dragonfly in DbSlice::AddExpire
CHECK(db_arr_[db_ind]->expire.Insert(main_it->first.AsRef(), ExpirePeriod(delta)).second);
As the key was not in the dash table but because the key string that was fetched from main_it->first.AsRef() was not the correct key that was in the insert flow as the address table was too big

fix(server): small string allocations only under 256 bytes str

---

src/server/cluster/cluster_family.cc
src/server/cluster/incoming_slot_migration.cc
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
tests/dragonfly/cluster_test.py

This fixes a few small places, but most importantly it does not allow a migration to start before both the outgoing and incoming side received the updated config. This solves a few edge cases.
Fixes #2968

fix(cluster-migration): Support cancelling migration right after starting it

---

src/server/server_family.cc

As reported on discord:
"text format parsing error in line 31: second TYPE line for metric name"
Also, improved consistency between other headers and their values.

chore: fix double header issue

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/string_family.cc
src/server/string_family.h
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc
src/server/tiering/small_bins.cc
src/server/tiering/small_bins.h
src/server/tiering/small_bins_test.cc

* Support multiple logical dbs in tiering
* Automatically cancel pending io with FindMutable
* Refactor some small parts

chore: small tiering fixes

---

.github/workflows/benchmark.yml

Benchmark fixes

---

src/server/command_registry.cc
src/server/command_registry.h
src/server/container_utils.cc
src/server/journal/types.h
src/server/json_family.cc
src/server/list_family.cc
src/server/stream_family.cc
src/server/string_family.cc
src/server/transaction.cc
src/server/transaction.h
src/server/tx_base.cc
src/server/tx_base.h
src/server/zset_family.cc

The main change is in tx_base.* where we introduce ShardArgs slice that
is only forward iterable. It allows us to go over sub-ranges of the full arguments
slice or read an index of any of its elements.
Since ShardArgs provide now indices into the original argument list we do not need to build the reverse index in transactions.

chore: get rid of kv_args and replace it with slices to full_args

---

src/server/transaction.cc

fixes #3015 
This PR does not allow preempting in the callback but it fixes the problem with back-pressure and memory usage for non auto journal commands that described in the issue.

fix(server): non auto journal write after callback finish

---

src/server/io_utils.cc
src/server/io_utils.h

In cases where we do not allow await in journaling steaming buffer size can increase
This PR shrinks the steaming buffer if its gets too big

fix(server): shrink replication steaming buf

---

src/core/dash.h
src/core/dash_internal.h
src/core/dash_test.cc

Goal: Introduce FindFirst(hash, predicate) so we can find an entry without a key - just by hash and predicate
Currently we always invoke the comparator with the same key we passed down, so it can be replaced by a predicate... Which also solves our first problem
Will be used in #3021

chore(dash): Replace comparator with predicate

---

src/core/json/json_test.cc
src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_lexer.lex
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/core/json/path.h

Support for expressions like `$.arr[1:-2]`.
The change applies to our own implementation of jsonpath, jsoncons already supports this format.

feat: support subrange expressions in jsonpathv2

---

src/server/rdb_load.h
src/server/replica.cc
src/server/replica.h

this should fix the problem: Running replicaof no one on replica in full sync state returns after more than 20 seconds
the problem was that after we shutdown the socket the buffer still contained data and we processed it.

fix: reduce delay when stop replica #3020

---

src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_test.cc
src/core/json/path.cc
src/server/json_family.cc

Add indices in form of [:end] or [start:]

chore: add half-range indices

---

src/server/dfly_main.cc

The leakage can be identified by checking /proc/net/sockstat
Fixes https://github.com/dragonflydb/dragonfly/issues/3045

chore: reset enable_direct_fd to avoid socket leakage in kernel

---

src/server/tiered_storage_test.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h

Fixes #3078 
The better way would be to wait for all SQE to be handled... but this works too

fix(tiering): wait for IO before test teardown

---

src/server/memory_cmd.cc
src/server/memory_cmd.h
src/server/script_mgr.cc
src/server/script_mgr.h

1. script errors are now logged continously but at most 5 per second.
2. "memory arena" is introduced - it prints the arena stats per thread. "memory malloc-stats" now only prints the global stats.

chore: minor fixes

---

src/server/db_slice.cc
src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc
src/server/transaction.h

Adds a `ReportDelete` to OpManager, so deletes from small bins happen asynchronously too. This was a problem before, one more step for #3021

fix(tiering): Async delete for small bins

---

src/facade/dragonfly_connection.cc

* add `DCHECK`
* add comments to describe flows and correctness

chore: improve Migration()

---

src/server/stream_family.cc
src/server/stream_family_test.cc

Single shard XREAD becomes single hop

feat(streams): Stream optimizations

---

src/server/common.cc
src/server/common.h
src/server/server_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage_test.cc
src/server/tiering/common.h
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/small_bins.cc
src/server/tiering/small_bins.h
src/server/tiering/small_bins_test.cc

feat(tiering): Defragmentation

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/tiered_storage_test.cc

Async tiering and async flushall don't mix well, pending operations will be confused by the atomic db_table pointer swaps, and fetching, stats and other stuff will break.
This PR moves the cleanup section to be executed before swapping table pointers if any tiered entries are detected
For #3073

fix(server): Sync FLUSH with tiering

---

src/server/server_family.cc

Note that this will break the history of renamed `pipeline_queue_bytes` - but that's ok because that metric was broken

feat(server): Pipeline and dispatch on `/metrics`

---

tools/cluster_mgr.py

* Make sure attached node is in right mode
* Enable detaching nodes

feat(cluster_mgr): Improvements to `cluster_mgr.py`

---

src/server/snapshot.cc
src/server/snapshot.h
tests/dragonfly/conftest.py
tests/dragonfly/instance.py
tests/dragonfly/redis_replication_test.py
tests/dragonfly/seeder/__init__.py
tests/dragonfly/seeder_test.py
tests/dragonfly/snapshot_test.py

The bug: writing full sync cut opcode to rdb snapshot format breaks compatibility with rdb format
PR changes:
Do not write dfly full sync cut opcode for disk snapshot (not for df and not for rdb)
Add pytest for loading rdb snapshot generated by dragonfly with Redis server

fix(server): fix compatibility with rdb snapshot

---

.github/workflows/reusable-container-workflow.yaml
src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h

chore: call breaker_cb_ on shutdown

---

src/server/search/doc_index.h
src/server/search/search_family.cc
src/server/search/search_family.h
src/server/search/search_family_test.cc

feat(search): basic FT.ALTER

---

.github/workflows/daily-builds.yml
src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/dragonfly_listener.cc
src/facade/facade.cc
src/facade/facade_types.h
src/server/replica.cc
src/server/server_family.cc
src/server/test_utils.cc
tests/dragonfly/connection_test.py

Also, improve synchronization primitives and replace them with thread-local variations.
Before the change, on my local machine with the dragonfly running with 8 threads, `memtier_benchmark  -c 10 --threads 8  --command="PING"  --key-maximum 100000000  --hide-histogram --distinct-client-seed --pipeline=20 --test-time=10`
reached 10M qps with 0.327ms p99.9.
After the change, the same command showed 13.8M qps with 0.2ms p99.9

chore: Introduce pipeline back-pressure

---

src/server/main_service.cc
src/server/server_family_test.cc
src/server/transaction.cc
src/server/transaction.h

The issue is that lua scripts don't follow normal flow and the `tracking_cb_` are not called when the transaction concludes. 
* add missing tracking_cb_ invkoe in RunSquashedMultiCb
* add test

fix: lua and client tracking

---

src/server/conn_context.cc
src/server/conn_context.h
src/server/server_family.cc
src/server/server_family_test.cc

* implement client tracking optout
* fix a bug of allowing client caching no without tracking optout
* fix error message compatibility with redis/valkey
Partially resolves #3157

feat: client tracking optout

---

.github/workflows/benchmark.yml
.github/workflows/bullmq-tests.yml
.github/workflows/ci.yml
.github/workflows/daily-builds.yml
.github/workflows/daily-sanitizers.yml
.github/workflows/release.yml

* add option to allow iouring within docker

fix(ci): docker not using iouring

---

src/server/search/search_family.cc
src/server/search/search_family_test.cc

metric name in vector parameters should be case insensitive

chore: improve ft.create for vector search

---

src/server/cluster/cluster_defs.h
src/server/cluster/cluster_family.cc
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h

Fixes some regression test failures

fix(cluster): Wait before all access to slot migrations

---

src/core/dash_internal.h
src/core/dash_test.cc
tests/dragonfly/replication_test.py

The bug:
CVCOnBump did not serialize all the relevant buckets
The fix:
if origin bucket is stash bucket always serialize it the original bucket and its probing

fix(server): fix bug in replication on cached mode

---

src/facade/acl_commands_def.h
src/facade/conn_context.h
src/server/acl/acl_family.cc
src/server/acl/acl_family_test.cc
src/server/acl/helpers.cc
src/server/acl/user_registry.cc
src/server/acl/user_registry.h
src/server/conn_context.cc
src/server/conn_context.h
src/server/main_service.cc
src/server/replica.cc
src/server/server_family.cc
src/server/test_utils.cc
tests/dragonfly/acl_family_test.py

Resolves #3151
* print categories and commands in lower case instead of capital case
* fix a bug of default user inheriting the wrong acl rules on new connections
* move keys position to be after password when printed from an acl command

chore: small acl compat changes

---

src/server/common.cc
src/server/common.h
src/server/protocol_client.cc

Fixes the issue when we are trying to Report the error from JournalStreamer::OnCompletion that is called from a proactor callback directly from the I/O fiber.
We can not use fiber mutexes in the I/O fiber so we switch to regular mutex and reduce its critical sections as much as possible.
Should fix the following failure:
https://github.com/dragonflydb/dragonfly/actions/runs/9536876957/job/26284317328#step:6:622

chore: allow calling Context::ReportError from I/O dispatch fiber

---

src/core/search/search.cc
src/server/search/search_family_test.cc

chore(search): Add __vector_score alias

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/detail/save_stages_controller.cc
src/server/journal/journal_slice.cc
src/server/journal/journal_slice.h
src/server/transaction.cc

We have a bug with the journal->RegisterOnChange functions:
1) Start 2 tasks with traversing through the whole DB
2) The first task is already work
3) Second task do db_slice_->RegisterOnChange(db_callback)
4) After that second task do journal->RegisterOnChange(..) and yield to another fiber on the mutex JournalSlice::cb_mu_
5) during the 4th step we do LPUSH for example and db_callback save the bucket
6) we still don't have a callback for the journal so we lost data for LPUSH
7) we finish journal->RegisterOnChange(..)
This issue was reproducible in test_cluster_fuzzymigration
Also, I have fixed the issue with db_slice_->UnregisterOnChange() if it was called during callbacks processing (if the fiber yields during callback)

fix: fix RegisterOnChange methods for journal and db_slice

---

src/facade/error.h
src/facade/facade.cc
src/facade/facade_types.h
src/server/generic_family.cc
src/server/generic_family.h
src/server/rdb_load.h
tests/dragonfly/replication_test.py

fixes dragonflydb#3107, fixes dragonflydb#3113, fixes dragonflydb#307
Implemented using the `DUMP` and `RESTORE` commands, as mentioned [here](https://github.com/dragonflydb/dragonfly/issues/604#issuecomment-1373055960)
Some functionality still is not working due to #837. So I can try to fix the issue with `RESTORE` command or implement `RENAME` command in another way

fix(generic_family): fix RenameGeneric command for non-string data types

---

src/server/replica.cc
tests/dragonfly/replication_test.py

That was a misleading name, as the logic was the exact opposite (oops :facepalm:)
This PR introduces a new name for the same flag: `break_replication_on_master_restart`
We're keeping the previous flag for now, to make transition easier. We'll remove it in a later Dragonfly version (>= 1.22)
Fixes #3192

fix(server): Rename confusing flag `replica_reconnect_on_master_restart`

---

src/core/sorted_map.cc
src/core/sorted_map.h

chore(core): Remove DfImpl inside ScoredMap

---

tests/dragonfly/cluster_test.py

It's supposed to be fixed with https://github.com/dragonflydb/dragonfly/pull/3180
If it'll fail again I'll of course take another look

chore: Re-enable previously flaky test

---

src/server/acl/acl_family.cc
src/server/acl/acl_family_test.cc
src/server/acl/helpers.cc
src/server/acl/helpers.h
src/server/acl/user.cc
src/server/acl/user.h
src/server/acl/user_registry.cc
tests/dragonfly/acl_family_test.py

resolves #2817
* add support for multiple passwords
* add support for deleting passwords
* add support for resetpass
* add tests
* always prefix passwords with hashtag when printed

feat(acl): add support of multiple passwords

---

src/server/replica.cc
src/server/server_family.cc
tests/dragonfly/sentinel_test.py

resolves #3202
Allows sentinel to do automatic failover based on the score of each replica on multi replica setup
* add replica-priority flag
* print it if node is replica as slave_priority

chore: add replica-priority flag

---

src/server/generic_family.cc

refers to the [comment](https://github.com/dragonflydb/dragonfly/pull/3200#issuecomment-2184763684)

feat(generic_family): Assemble RESTORE and STICK commands into one commmand during replication of the RENAME command

---

src/core/bloom.cc
src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/reply_builder.cc
src/server/CMakeLists.txt
src/server/channel_store.cc
src/server/channel_store.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/dragonfly_test.cc
src/server/main_service.cc
src/server/table.h
tests/dragonfly/connection_test.py

feat(server): expiry notifications

---

.github/actions/regression-tests/action.yml
tests/dragonfly/replication_test.py

The bug is that by the time we issue a `REPLICA OF` command `dragonfly` might finish loading the snapshot triggering a false positive assertion later on. I increased the snapshot size to provide a smaller window for this issue as I would not like to relax the contstrains.
Furthermore, the reason that some of the logs did not exist in the failed log files is that assertions in pytest kill the process bypassing the `SIGTERM` handlers we defined (and consequently loose some portion of the logs)

fix: replicaof_reject_on_load flake

---

src/server/tiering/disk_storage.cc
src/server/tiering/op_manager.cc

* Sneaky bug, found it during benchmarks - we don't clear pending_stash_ver_ with immediate errors
* Fix resize bug during multiples of min grow size, need to use >

fix(tiering): Fix pending leak during immediate stash error

---

src/facade/conn_context.cc
src/facade/conn_context.h
src/facade/ok_main.cc
src/server/cluster/cluster_family.cc
src/server/conn_context.cc
src/server/conn_context.h
src/server/debugcmd.cc
src/server/dflycmd.cc
src/server/hset_family.cc
src/server/json_family.cc
src/server/list_family.cc
src/server/main_service.cc
src/server/script_mgr.cc
src/server/server_family.cc
src/server/set_family.cc
src/server/stream_family.cc
src/server/string_family.cc
src/server/zset_family.cc

chore: provide basic logging to catch possible command errors

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/outgoing_slot_migration.cc

DispatchTracker hasn't ignored the paused connections which was the reason for deadlock.

fix: fix deadlock in DFLYCLUSTER CONFIG command and outgoing migration finaliztion

---

tests/dragonfly/connection_test.py
tests/dragonfly/replication_test.py
tests/dragonfly/tiering_test.py
tests/dragonfly/utility.py

A gift 🎁 to Roman 😆 
Async generator with automatic break when all asserts pass
```py
for object, breaker in tick_timer(lambda: obj()):
with breaker:
assert conditions on object
...
```
if the asserts don't pass, it throws a timeout error together with an assert error to see the cause

fix(pytest): timed ticker for simpler conditions

---

src/server/generic_family.cc
src/server/multi_test.cc

Fix #3232 in simplest possible way
We should consider making SCAN a nokey transactional command

fix(server): Fix SCAN deadlock

---

.github/workflows/ci.yml
.github/workflows/daily-builds.yml
src/server/common.h
src/server/server_family.cc
src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
tests/dragonfly/tiering_test.py

Also some changes to mac-os build (still disabled).

chore: introduce back-pressure to tiered storage

---

src/server/main_service.cc

Example:
```
127.0.0.1:6379> EVAL "return redis.call('SET', 'k', 'v')" 0
(error) ERR Error running script (call to 5c4d62f4e30c54fb15935b5892148e5ce7374077): @user_script:2: script tried accessing undeclared key, key: k
```
Fixes #3212

chore(lua): Return which undeclared key was accessed

---

src/server/cluster/cluster_config.cc
src/server/cluster/cluster_config.h
src/server/cluster/cluster_config_test.cc
src/server/cluster/cluster_defs.cc
src/server/cluster/cluster_defs.h
src/server/cluster/cluster_family.cc
src/server/cluster/incoming_slot_migration.cc
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/slot_set.h
tests/dragonfly/cluster_test.py

fix for #3227
We had an incorrect MOVE error. We updated only the current node slots config and used the whole cluster config to create the MOVE error. So as a result we redirected to the same node instead of the target node. After several failed attempts we get a TTL exhausted error on the client.
The fix is simple: if the slot that is checked in GetMasterNodeForSlot belongs to the current node, it means the slot was moved to another node, so we need to check migrations.

fix: fix move error during migration finalization

---

src/server/tiered_storage.cc
src/server/tiering/disk_storage.cc
src/server/tiering/op_manager.cc

chore: initiate grow preemptively

---

src/server/dfly_bench.cc

chore: dfly_bench can send traffic to memcached

---

src/facade/dragonfly_connection.cc
src/server/rdb_save.cc

Minor fixes to improve debug test coverage and logs.

chore: debugging fixes

---

LICENSE.md

The original BUSL-1.1 license has "fourth anniversary". The typo in the text says "forth", which is not sensible.
Also a newline was munched when the text was formatted for 72 character line width. This patch restores it.

chore(license): Fix typo in LICENSE.md text

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/dragonfly_test.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc
tests/dragonfly/conftest.py
tests/dragonfly/instance.py

The bug was around io pending entries that have not been properly cleaned during flush. This PR simplified the logic around tiered storage handling during flush, it always performs the cleaning in the synchronous part of the command.
In addition, this PR improves error logging in tests if dragonfly process exits with an error. Finally, a test is added that makes sure pending tiered items are flushed during the flash call.
Fixes #3252

fix: properly clean tiered state upon flash

---

src/server/server_family.cc
tests/dragonfly/instance.py
tests/dragonfly/replication_test.py

fixes #3280 
The bug:
info replication first checks if the server is master, if not takes replica mutex and calls
`dfly::Replica::GetInfo()`
When running replica takeover we take the mutex, finish the takeover, reset the replica object and set `is_master` to true.
With this flow when if we get the mutex after takeover is done but check is master before we will get a crash for accessing the replica object which was reset.
The fix:
take the mutex before checking is_master

fix(bug): crash on takeover and info replication

---

src/server/journal/journal_test.cc
src/server/journal/serializer.cc
src/server/main_service.cc
src/server/multi_command_squasher.cc
src/server/multi_command_squasher.h
src/server/snapshot.cc
src/server/transaction.cc
src/server/transaction.h
src/server/tx_base.cc
src/server/tx_base.h

Because replica does not execute multi transactions atomically and ignores the EXEC opcode we can stop sending it from master.
This PR does not removes the exec opcode read from replica as doing so will prevent version upgrade. If there is old master version that will send the EXEC opcode replica will read the entry increase the journal count lsn on its side and nothing more.

feat(server): master stop sending exec opcode to replica

---

src/core/bptree_set.h
src/core/sorted_map.cc
src/core/sorted_map.h
src/server/zset_family.cc
src/server/zset_family_test.cc

Before, we run FromRank operation count times. This operation computes subtree counts on the fly. Now, we iterate over a tree first, delete the keys from the map - no rank calls. And only after we filled the result, we delete the entries from the tree. For cases where we delete all the entries we avoid calling FromRank.
Moreover, we optimized FromRank operations to handle corner cases of most right and most left nodes by avoiding computing the subtree counts.

chore: optimize zpopminmax operations

---

src/server/CMakeLists.txt

* fix missing preprocessor macro when WITH_AWS is on

fix: define macro WITH_AWS in cmake when flag is ON

---

src/core/compact_object.cc
src/core/compact_object.h
src/core/compact_object_test.cc

Currently, compact object does decoding/encoding of its internal string blobs. For tiering usecase, it makes sense to introduce the direct access to the blobs and avoid this unnecessary translation.
This PR introduces such access.

chore: Add CompactObj Raw methods

---

src/server/rdb_load.cc

Before this change we first printed the value, which could be long resulting in the TTL not appearing in the log due to max line length
If the TTL is invalid, we should print it first to see what value it has

chore: On invalid TTL, print the TTL first

---

src/server/engine_shard_set.cc
src/server/tiered_storage.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc

There are no functional changes in this PR.
ReportXXX functions are renamed to NotifyXXX
Some functions were moved to private, and some pulled out from the class as being stateless.
This is preparational change before doing changes in the tiered storage code.

chore: moving functions + renaming in tiered storage

---

src/server/db_slice.cc
src/server/tiered_storage.cc
src/server/tiered_storage_test.cc

1. Renamed ReportXXX callbacks to NotifyXXX
2. Pulled RecordDelete/RecordAdded out of TieredStorage::ShardOpManager.
3. Moved TieredStorage::ShardOpManager functions to to private scope.
4. Streamlined code in TieredStorage::Delete

chore: refactoring around tiered storage

---

docs/namespaces.md
src/server/bitops_family.cc
src/server/bloom_family.cc
src/server/container_utils.cc
src/server/db_slice.cc
src/server/db_slice.h
src/server/detail/save_stages_controller.cc
src/server/dflycmd.cc
src/server/dragonfly_test.cc
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/generic_family.cc
src/server/hll_family.cc
src/server/hset_family.cc
src/server/json_family.cc
src/server/list_family.cc
src/server/main_service.cc
src/server/memory_cmd.cc
src/server/search/doc_index.cc
src/server/server_family.cc
src/server/set_family.cc
src/server/stream_family.cc
src/server/string_family.cc
src/server/transaction.cc
src/server/transaction.h
src/server/tx_base.cc
src/server/tx_base.h
src/server/zset_family.cc

This is a refactor that will put us closer to adding namespaces, see included `docs/namespaces.md`

refactor: Use `DbContext`, `OpArgs` and `Transaction` to access `DbSlice`

---

src/server/tiered_storage.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/disk_storage_test.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc
src/server/tiering/small_bins.cc
src/server/tiering/small_bins.h
src/server/tiering/small_bins_test.cc

Before that OpManager::Stash, DiskStorage::Stash and SmallBins::Stash received a single value argument as a serialized blob of an object value.
Now they accept an additional footer argument that allows appending arbitrary byte sequence when preparing a disk page. We could, of course serialize, into value before calling these interface but then we would need another copy.
With two arguments we allow an optional meta-format that has a footer after the value.
This PR does not use this feature yet, but we will need it in the next PR in order to store the encoding mask of the string object. In the future we will need storing other meta information in case we decide supporting multiple DF types.

chore: Separate tiered serialization format from object values

---

src/server/cluster/cluster_family.cc
src/server/cluster/incoming_slot_migration.cc
src/server/cluster/incoming_slot_migration.h
src/server/cluster/outgoing_slot_migration.cc
src/server/journal/streamer.cc
src/server/journal/streamer.h

**The Bug**
Before this fix, source nodes would send `FIN` entries to target nodes (in all thread flows), and would then send a `DFLYMIGRATE ACK` command to verify that all flows received the `FIN` in time.
If they didn't, the source node would retry this logic in a loop, until successful.
The problem is that, in some rear cases, one or more of the flows would indeed be in a `FIN` state, _but of a previous `FIN` that is already outdated_. If that's indeed the case, all data between that `FIN` and the next `FIN`(s) will be lost.
**The Fix**
We already have an attempt id that we send in the `DFLYMIGRATE ACK` command, and return it in the response. This fix utilizes the same attempt id to be sent to all flows, and then when joined, we make sure we join on the correct (latest) attempt id. …

fix(cluster): Join on specified attempt id

---

tests/dragonfly/acl_family_test.py

Ari asked about this functionality and even though we support it in data plane the control planes depends on it and therefore it's good to have a compatibility test. The test just checks that the `requirepass` is overwritten by the `aclfile`
* add a test that uses both requirepass and aclfile

chore(acl): add test with requirepass and aclfile

---

tests/dragonfly/cluster_test.py

chore: skip test_cluster_flushall_during_migration

---

tests/dragonfly/replication_test.py
tests/dragonfly/snapshot_test.py
tests/dragonfly/utility.py

fixes the regression failing https://github.com/dragonflydb/dragonfly/actions/runs/9926774277

fix (pytest): generate unique random dbfilename for tests

---

src/core/compact_object.cc
src/core/compact_object.h
src/core/compact_object_test.cc
src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc

It's more efficient to offload raw blobs kept in CompactObject than decoded strings. Unfortunately, it's also more complicated. The complexity arises around Read/Modify operations that must convert a raw blob into a processed string. Moreover, Modify decodes the raw string, therefore subsequent callbacks already see the decoded string.
Finally, this PR fixes the logic in NotifyFetched flow: before it could skip uploading the modified value back to memory, which breaks correctness.

chore: bypass decoding/encoding of the data when performing offloading

---

src/server/tiered_storage.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h

Don't run offloading and stashing if we know ahead that there won't be enough space left

chore(tiering): Fixes

---

src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/detail/save_stages_controller.cc
src/server/dflycmd.cc
src/server/journal/streamer.cc
src/server/journal/streamer.h
src/server/transaction.cc
src/server/transaction.h

Fixes #3229, but the bigger issue is that migrations didn't use transactions at all the whole time 🤯 
Now we have a global transaction cut to start a migration - registering both the journal and db_slice callbacks while the datastore is under a global lock and no commands are running

fix(migration): Use transactions!

---

src/core/search/indices.cc
src/core/search/search_test.cc

Fixes #3256 
We internally re-use ids, so we can keep replace_deleted disabled

chore: remove replace_deleted flag from hnswlib

---

.github/workflows/benchmark.yml
tools/benchmark/k8s-benchmark-job.yaml
tools/benchmark/post_run_checks.py

improvements added to the workflow:
1. add version upgrade from last version to last weekly docker build
2. run memtier benchmark while version is upgraded (if will fail due to takeover to a new pod)
3. run memtier benchmark again after version upgrade finished
4. send logs to channel if benchmark failed

feat(test): Improve benchmark workflow

---

src/server/blocking_controller_test.cc
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/main_service.cc

This removes a race between periodic fiber and namespaces during shutdown.
Fixes #3328

fix: Proper shutdown sequence with Namespaces

---

tests/dragonfly/conftest.py

Pytest has several phases: "setup", "call", and "teardown". Previously I have copied logs only for the "call" state (when the tests are running). During the "teardown" phase all resources are freed and if we have an error during this process we need to copy logs too

fix(test): copy logs for failed test during TEARDOWN phase

---

src/core/compact_object.h
src/server/acl/acl_family_test.cc
src/server/acl/acl_log.cc
src/server/acl/acl_log.h
src/server/acl/validator.h
src/server/cluster/incoming_slot_migration.cc
src/server/db_slice.cc
src/server/string_family.cc
src/server/test_utils.cc
src/server/tiered_storage.cc
src/server/tiered_storage_test.cc
src/server/transaction.cc

chore(tiering): add protection against overruning memory budget

---

src/server/cluster/cluster_defs.cc
src/server/cluster/cluster_defs.h
src/server/cluster/cluster_family.h
src/server/common.cc
src/server/list_family.cc
src/server/main_service.cc
src/server/zset_family.cc
tests/dragonfly/cluster_test.py

We had incorrect results for blocking commands for KEY_MOVED error.

Fix blocking commands moved error

---

src/facade/facade_types.h
src/server/acl/validator.cc
src/server/cluster/cluster_family_test.cc
src/server/main_service.cc
src/server/multi_command_squasher.cc
src/server/transaction.cc
src/server/tx_base.cc
src/server/tx_base.h

* Fixes a bug in cluster slot checks where we miss the bonus key
* Makes KeyIndex iterable, so we don't have to loop manually, avoiding bugs like this one

chore: Make KeyIndex iterable

---

src/facade/dragonfly_connection.cc
src/server/memory_cmd.cc
tests/dragonfly/connection_test.py

Leave only connection memory usage in memory stats. We should think how we can move it also to /metrics. In addition, added a test verifying that redis parser memory usage is tracked.

chore: remove redundant metrics from memory stats

---

src/server/journal/streamer.cc
src/server/journal/streamer.h

Before it was possible to issue several concurrent AsyncWrite requests. But these are not atomic, which leads to replication stream corruption. Now we wait for the previous request to finish before sending the next one.
ThrottleIfNeeded is now takes into account pending buffer size for throttling.
Fixes #3329

fix: corruption in replication stream

---

src/server/engine_shard_set.cc
src/server/tiered_storage_test.cc
tests/dragonfly/connection_test.py

chore: pull helio

---

src/server/common.cc
src/server/common.h
src/server/server_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage_test.cc
tests/dragonfly/cluster_test.py
tests/dragonfly/connection_test.py
tests/dragonfly/utility.py

1. Added a robust assert_eventually decorator for pytests
2. Improved the assertion condition in TieredStorageTest.BackgroundOffloading
3. Added total_uploaded stats for tiering that tells how many times offloaded values
were promoted back to RAM.

chore: fix test_parser_memory_stats flakiness

---

src/core/string_set.h
src/server/set_family.cc

Weekend cleanup after I closed my pending tasks 🛀🏻

chore(server): Introduce StringSetWrapper

---

src/server/db_slice.cc
src/server/tiered_storage.cc
src/server/tiered_storage_test.cc
src/server/tiering/op_manager.h

Before: we uploaded values from tiered storage on a first lookup.
Now: we wait for a second hit before uploading to RAM.

fix: do not upload offload values on a first hit

---

tests/dragonfly/cluster_test.py

fix: failure in test_cluster_fuzzymigration

---

src/server/string_family.cc

Without this change, issuing `redis-cli getex` crashes Dragonfly.
Fixes #3359

fix(server): Require >=1 args to `GETEX`

---

src/server/transaction.cc

Our area of attack during concurrent transaction access is the call to `DisarmInShard` and `DisarmInShardWhen`, which only access is_armed - an atomic varible. It is not safe to arbitrarily call GetNamespace() if we write to it in InitBase
Solution: Don't write to it post first initialization

fix(transaction): Fix namespace access

---

src/core/CMakeLists.txt
src/core/compact_object.cc
src/core/compact_object.h
src/core/cool_queue.cc
src/core/cool_queue.h
src/core/dfly_core_test.cc

Also, add the according API to compact object.
Now external objects can be in two states: Cool and Offloaded.

chore: Introduce CoolQueue

---

src/server/engine_shard_set.cc
src/server/engine_shard_set.h

Before - each thread updated its own variable and then, the global "used_mem_current" was updated by summing used memory from each thread.
Now, each thread updates used_mem_current directly. The code is simpler and also provides more precise results.

chore: simplify computation of used_mem_current

---

src/server/replica.h

While getting deeper into the implementation of replication, I just found some methods that we no longer use

chore(replica): remove unused methods in the Replica class

---

src/server/server_family.cc
src/server/transaction.cc
src/server/transaction.h

This code from `RegisterBreakHook` makes sure we can even cancel ahead, so that the transaction is guaranteed to not get stuck:
```c++
if (res->transaction)
res->transaction->CancelBlocking(nullptr);
```
however when we do this, we can do it as early as before running the more recent callback with Execute(), which in turn overwrites local_result_
at the end we get local_result_ being set to OK, but COORD_CANCELLED being set as well

fix(transaction): Properly store block cancel status

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/engine_shard_set.cc
src/server/table.h

We update table_memory upon each deletion and insertion of an element.

chore: Track db_slice table memory instantly

---

src/server/dfly_bench.cc

chore: dfly_bench - print ongoing error counts

---

src/server/engine_shard_set.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/op_manager.cc

This PR introduces a new state in which the offloaded value is not freed from memory but instead stays in the cool queue.
Upon Read we convert the cool value back to hot table and delete it from storage. When we low on memory we retire oldest cool values until we are above the threshold.
The PR does not fully finish the feature but it is workable enough to start (load)testing. Missing:
a) Handle Modify operations
b) Retire cool items in more cases where we are low on memory. Specifically, refrain from evictions as long as cool items exist.

chore: introduce a cool queue that gradually retires cool items

---

src/server/dflycmd.cc
src/server/journal/tx_executor.cc
tests/dragonfly/replication_test.py

There are a few issues with the test:
1. Not using the admin port, which could cause pause to deadlock
2. Not waiting for some of the `task`s (although that won't cause a failure)
But also in the product code:
1. We used to `std::move()` the same pointer multiple times
2. We assigned to the same status object from multiple threads
Hopefully this fixes the test. It used to fail every ~100 attempts on my machine, now it's been >1,000 and they all passed.

fix: Fix `test_take_over_seeder`

---

src/core/compact_object.h
src/server/acl/validator.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/engine_shard_set.cc
src/server/memory_cmd.cc
src/server/server_family.cc

Before: when running dragonfly with --cache_mode we could get OOM rejections even though the eviction policy allowed to evict items to free memory. Ideally, dragonfly in cache mode should not respond with the OOM error.
This PR reuses the same Eviction step we have in the Heartbeat and conditionally applies it during the insertion. In my test the OOM errors went from 500K to 0 and the server still respected memory limit.
Also, remove the old heuristics that has never been used.
Test:
./dfly_bench --key_prefix=bar: -d 1024 --ratio=1:0 --qps=200 -n 3000 ./dragonfly --dbfilename=  --proactor_threads=2 --maxmemory=600M --cache_mode

chore: reenable evictions upon insertion to avoid OOM rejections

---

src/server/common.h
src/server/db_slice.h
src/server/journal/journal.cc
src/server/journal/journal_slice.cc

We now might `preempt` when we serialize big values and the code in journal was marked as Atomic triggering an atomic section `CHECK`
* remove fiber guard from non atomic section
* move LocalBlockingCounter to common

fix: remove fiber guard from non atomic section

---

src/server/db_slice.h
src/server/transaction.cc

Inline transactions do not acquire any locks and therefore they should not preempt. This is no longer true when db_slice has registered callbacks.
* disable inline transactions when db_slice has registered callbacks

fix: disable inline transactions when db_slice has registered callbacks

---

tests/dragonfly/snapshot_test.py

The problem is that the test `test_big_value_serialization_memory_limit` will try to shutdown dragonfly at the end with a timeout of 15 seconds. Dragonfly during shutdown takes a snapshot which might take more than 15 seconds and the test fails.
* call flushall before we exit the test

fix: test_big_value_serialization_memory_limit shutdown timeout

---

tests/dragonfly/instance.py

Update the flag for extreme testing. We should remove this before the release.
* set serialization_max_chunk_size to 1 byte

chore: set serialization_max_chunk_size to 1 byte

---

src/server/acl/acl_family.h
src/server/acl/acl_family_test.cc

None does not exist in Valkey and its entry was missing from the indexes we use to map categories to commands leading to an out of bounds access and causing a segfault.
* remove none from acl categories

fix(acl): remove none from acl categories

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/dfly_bench.cc
src/server/engine_shard_set.cc
src/server/tiered_storage.cc
src/server/tiered_storage_test.cc

1. Fully support tiered_experimental_cooling for all operations
2. Offset cool storage usage when computing memory pressure situations in Hearbeat.
3. Introduce realtime entry counting per db_slice and provide DCHECK to verify it vs the old approach. Later we will switch to realtime entry and free memory computations when computing bytes per object, and remove the old approach in CacheStats().
4. Show hit rate during the run of dfly_bench loadtest.

chore: tiering - make Modify work with cool storage

---

tests/dragonfly/instance.py

This reverts commit 2867d54a055c49a5925c594d1f483de11d8cc566.

Revert "chore: set serialization_max_chunk_size to 1 byte (#3379)"

---

src/server/config_registry.cc
src/server/config_registry.h
src/server/server_family.cc
src/server/server_family_test.cc

This PR adds a small refactor to the way we set and get config names which have dashes (`-`) and underscores (`_`).
Until now, words were separated by underscores because this is how our flags library (absl) works. However, this is incompatible with Valkey, which uses dashes as a word separator.
Once merged, we will support both underscores and dashes in config names, but will only return the name with dashes. **This is a behavior change**.
We're doing this in order to be compatible with `replica-priority` and possibly other config names that Valkey uses.

 chore: Support setting the value of `replica-priority`

---

src/facade/CMakeLists.txt
src/server/CMakeLists.txt
src/server/dfly_bench.cc

1. Our latency/RPS computations were off because we started measuring before drivers started running. Now, Run/Start phases are separated, so the start time is measured more precisely (after the start phase)
2. Introduced progress per driver connection - one of my discoveries is that driver connections progress with differrent pace when running in coordinated omission. This can reach x5 speed differrences. Now we measure and output the fastest/slowest progress.
3. Coordinated omission is great when the Server Under Test is able to sustain the required RPS. But if the actual RPS is lower than the one is sent than the final latencies will be infinitely high. We fix it by introducing self-adjusting sleep interval, so if the actual RPS is lower we will increase the interval to be closer to …

feat: stabilize non-coordinated omission mode

---

src/server/cluster/cluster_config.cc
src/server/cluster/cluster_config.h
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/main_service.cc
tests/dragonfly/cluster_test.py

Add ClusterFamily::Shutdown to take out all migrations

chore: cancel slot migrations on shutdown

---

src/server/common.cc
src/server/common.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/debugcmd.cc
src/server/engine_shard_set.cc
src/server/generic_family.cc
src/server/journal/streamer.cc
src/server/journal/streamer.h
src/server/snapshot.cc
src/server/snapshot.h
tests/dragonfly/instance.py
tests/dragonfly/replication_test.py

`DastTable::Traverse` is error prone when the callback passed preempts because the segment might change. This is problematic and we need atomicity while traversing segments with preemption. The fix is to add Traverse in DbSlice and protect the traversal via `ConditionFlag`.
* add ConditionFlag to DbSlice
* add Traverse in DbSlice and protect it with the ConditionFlag
* remove condition flag from snapshot
* remove condition flag from streamer

chore: add db_slice lock to protect segments from preemptions

---

.github/actions/regression-tests/action.yml

The recent changes of the `serialization_max_chunk_size` set to 1 for extreme testing increased the running time of the tests causing them sometimes to timeout. 
Two examples are: 
https://github.com/dragonflydb/dragonfly/actions/runs/10169667062 and
https://github.com/dragonflydb/dragonfly/actions/runs/10171501123
which both timedout. The average runs takes roughly 39.5 seconds, which is almost 40.
* increase timeout on reg tests from 40 to 50

chore: increase timeout of regression tests

---

src/server/json_family.cc
src/server/json_family_test.cc

`json.merge` would throw an exception when the json object did not contain the element to replace because `RecursiveMerge` functions used `&dest->at(k_v.key())` which threw the exception. Remove `RecursiveMerge` completely and use the one implemented in jsoncons lib.
* add test
* replace RecursiveMerge with mergepatch::apply_merge_patch
* add exception handling for that flow

fix: json.merge exception crash

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
tests/dragonfly/pymemcached_test.py

fix(connection): Count memchached pipelined commands

---

tests/dragonfly/replication_test.py

Motivation: to avoid 80MB logs into stdout like this one: https://github.com/dragonflydb/dragonfly/actions/runs/10174852001/job/28141278813?pr=3401

chore: remove verbose printing of tests

---

src/server/json_family.cc
src/server/json_family_test.cc

Pass path argument and rewrite the JSON.MERGE code similar to OpToggle or other mutating functions. Currently works only with --experimental_flat_json=false.

feat: Support non-root paths for json.merge

---

src/core/CMakeLists.txt
src/core/task_queue.cc
src/core/task_queue.h
src/server/server_family.cc
src/server/server_family.h
src/server/tiered_storage_test.cc

This should help us in identifying deadlocks quickly.

chore: expose metric that shows how many task submitters are blocked

---

src/facade/dragonfly_connection.cc
src/facade/service_interface.h
src/server/blocking_controller_test.cc
src/server/container_utils.cc
src/server/debugcmd.cc
src/server/dfly_main.cc
src/server/dflycmd.cc
src/server/dflycmd.h
src/server/dragonfly_test.cc
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/main_service.cc
src/server/main_service.h
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/rdb_test.cc
src/server/search/search_family_test.cc
src/server/server_family.cc
src/server/server_family.h
src/server/test_utils.cc
src/server/tiered_storage.cc
src/server/tiered_storage_test.cc

Now unit tests will run the same Hearbeat fiber like in prod. The whole feature was redundant, with just few explicit settings of maxmemory_limit I succeeeded to make all unit tests pass.
In addition, this change allows passing a global handler that is called by heartbeat from a single thread. This is not used yet - preparation for the next PR to break hung up replication connections on a master.
Finally, this change has some non-functional clean-ups and warning fixes to improve code quality.

chore: retire TEST_EnableHeartBeat

---

README.ja-JP.md
README.ko-KR.md
README.md
README.zh-CN.md
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family_test.cc
src/server/conn_context.h
src/server/dflycmd.cc
src/server/main_service.cc
src/server/replica.cc
src/server/server_family.cc
tests/dragonfly/cluster_test.py
tests/dragonfly/replication_test.py

Before this PR, we only supported `cluster_announce_ip`.
It's basically the same feature, but used for cluster announcements instead of replication.
This PR adds support for `replica-announce-ip` and `replica-announce-port`, which can be set via new flags `--announce_ip` and `--announce_port`. These flags apply to both cluster and replica announcements.
Tested via running Sentinel, and making sure it is able to connect to announced ip+port, while it can't connect to announced false / unavailable ip+port.
Note: this PR deprecates `--cluster_announce_ip`, but continues to support it. We will remove it in a future version.
Fixes https://github.com/dragonflydb/dragonfly/issues/3380

feat(server): Support `replica-announce-ip`/`port`

---

src/server/cluster/cluster_family.cc
src/server/dflycmd.cc
src/server/dflycmd.h
src/server/main_service.cc
src/server/replica.cc
src/server/replica.h
src/server/server_family.cc
src/server/server_family.h
src/server/tiered_storage_test.cc
tests/dragonfly/replication_test.py

Allow non-exclusive, read-only access to Dfly::ReplicaInfo structure.
The most important change is in DflyCmd::CancelReplication, where before
it has locked ReplicaInfo mutex and then continued with locking the global mutex.
It is dangerous because most operations lock them in the opposite order.
Also rename ambigous GetReplicaInfo accessors to clearer names.

chore: improve replication locks

---

src/server/engine_shard_set.cc
src/server/engine_shard_set.h

1. Simplify CacheStats by using accessorts directly provided by DbSlice
2. Separate eviction for tiering as tiering can be done on replica.

chore: reorganize EngineShard::Heartbeat

---

src/server/dflycmd.cc
src/server/dflycmd.h
src/server/main_service.cc

Before that CancelReplication did too many things, moreover, we had StopReplication that did the same.
This PR moves CancelReplication under ReplicaInfo struct, and reduces code duplication around this change.

chore: simplify master replication cancelation interface

---

src/server/snapshot.cc

* reset serialization_max_chunk_size to `0`
* reword flag information

chore: reset serialization_max_chunk_size to 0

---

src/server/generic_family.cc
src/server/generic_family.h
src/server/main_service.cc
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/replica.cc
src/server/replica.h
src/server/server_family.cc
src/server/string_family.cc
src/server/string_family.h

Before that PAUSE paused the reconnection reconciler flow, now it also pauses the ongoing full sync replication if such exists.
In addition, this PR applies some clean-ups and removes redundant code

feat: DEBUG REPLICA PAUSE now pauses fullsync

---

src/server/replica.cc
tests/dragonfly/replication_test.py

test had 2 bugs:
1) deadlock in master (can't reproduce anymore after recent changes for replication)
2) incorrect checking (replica can't guarantee that got all data from the master if the connection is dropped)

test: fix test_disconnect_replica

---

tools/cluster_mgr.py

We recently changed `DFLYCLUSTER MYID` to `CLUSTER MYID`, but since our `cluster_mgr_test.py` is marked as XFAIL we missed updating it.

fix: cluster_mgr.py to use `CLUSTER MYID`

---

tests/dragonfly/instance.py

Intended to stabilize regression tests before releasing our next version.

chore: disable serialization_max_chunk_size in regtests

---

.github/actions/regression-tests/action.yml
.github/workflows/ci.yml
tests/dragonfly/acl_family_test.py
tests/dragonfly/conftest.py

Resolve #3424
The `env` variables exported when regression tests timeout are not working properly and the `if statement` on the action step `Print last log on timeout` would fail to read and upload the files set in `/tmp/last_log_file.txt`. Furthermore, another problem is the `job.timeout` argument that kills the whole job/matrix before the upload log step has a chance to run. For that, we need manual `timeouts` on the workflow similar to what we do in `regression tests action`. 
The fixes are simple:
* remove print last log on timeout action step
* copy the logs on timeout directly within the timeout step
* replace global timeout on CI workflow with timeout command per step
see also:
https://graphite.dev/guides/github-actions-timeouts#3-waiting-for-user-input-or-external-events

fix: missing logs on ci timeout

---

src/server/json_family.cc
tests/dragonfly/replication_test.py

The problem is that if one key in JSON.MSET is failed, the transaction status still is OK and we send the whole command in autojournaling. But JSON.MSET also sends only executed keys manual, so we had 2 times replication for success keys and 1 time for unsuccess, and as a result incorrect replica

fix: JSON.MSET command

---

src/redis/config.h
src/redis/quicklist.c
src/redis/quicklist.h
src/redis/redis_aux.c
src/redis/redis_aux.h
src/redis/ziplist.c
src/redis/zmalloc.h
src/redis/zmalloc_mi.c

It's impossible to review differential changes for `quicklist.*`, but it's easier to compare them with valkey versions - 
the only differences are the const modifiers that were added to our files.

chore: integrate quicklist changes from valkey

---

tests/dragonfly/conftest.py

os.remove(LAST_LOGS) might throw an exception if the file does not exist which we do not handle. Wrap it in try/catch block
see issue in: https://github.com/dragonflydb/dragonfly/actions/runs/10273843815/job/28429259846#step:6:373
```
INTERNALERROR>     os.remove(LAST_LOGS)
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/last_test_log_dir.txt'
```
* wrap in try/catch os.remove

fix: pytest teardown exception in os.remove(LAST_LOGS)

---

.github/workflows/ci.yml
src/server/db_slice.cc
src/server/db_slice.h
src/server/tiered_storage_test.cc

We compared memory_budget vs 0 before inserting a new item in DbSlice, and retired cool pages if we are low on memory.
The problem - when we decide whether we allow growing a table, we estimate the possible object size increase due to the future table growth. And the memory check described before was not consistent with the actual logic that rejected the insertion.
Moreover, the memory_budget tracking interaction with EvictionPolicy was over-complicated: we passed the memory_budget counter to the evp object and then read it back, even though evp did not track object deletions memory impact during objects evictions.
Now, we remove the responsibility from evp to update memory_budget_ so it's solely updated by DbSlice. We also update memory_budget_ during deletions, and when we pass it to …

chore: change how we track memory_budget during evictions

---

src/facade/reply_builder.cc
src/facade/reply_builder.h

The idea:
```c++
ReplyScope scope(); // tells underlying reply builder it's safe to snatch long strings as iovecs
StartArray(n)
for i = 1, n {
SendStr(arr[i])
}
```
and this way we can just write send code that internally turns into the same logic as in SendStrArr or SendMGetResponse (we also won't need custom methods)

chore: SinkReplyBuilder2 with vec batching

---

src/server/replica.cc
tests/dragonfly/instance.py
tests/dragonfly/replication_test.py

**Background**
In v1.21.0 we introduced support for `--announce_ip` for replicas to announce their public IP addresses.
Like Valkey, this uses `REPLCONF IP-ADDRESS` to announce their IP address.
**The issue**
Older Dragonfly releases (<1.21) did not support this feature. The master side simply returned an error for such `REPLCONF` attempts, however the replica code failed the replication, resulting in incompatible versions.
**The fix**
The fix is simple, just log an error if the master did not respect `REPLCONF IP-ADDRESS`. We can make this non-optional in the future again.
However, in addition, I added a regression test to make sure we are backwards compatible with v1.19.2. We'll bump this up every once in a while.
Fixes #3470

fix: Make replica's `REPLCONF IP-ADDRESS` optional

---

tests/dragonfly/replication_test.py

For commits marked with a git tag, the previous check did not hold.

chore: relax the version check in test_replicate_old_master

---

tests/dragonfly/generic_test.py
tests/dragonfly/instance.py

For reasons I do not exactly comprehend, `test_unknown_dfly_env` might fail when we try to `stop the instance`. The thing is, that dragonfly is already killed since we try to launch an instance with an invalid environment flag and `stop_all` should not actually have any effect. Since the error happens at teardown and when we call `stop_all` it makes sense to `skip it` since the instance is not alive in the first place. The fix is simple, allow skipping `stop_all` at instance teardown.
fixes #3314
* allow to skip stop_all on DflyInstanceFactory

fix: flake in teardown of test_unknown_dfly_env

---

tests/dragonfly/instance.py
tests/dragonfly/replication_test.py

The problem is that the test is using an older version of the master and the flag is not available.
* add a method in DflyInstance to remove this flag for this test

fix: test_replicate_old_master missing serialization_max_chunk_size

---

.github/workflows/daily-sanitizers.yml

The problem is that we do not properly post sanitizer failures on github and I always got notified via email instead.
* fix sanitizers failure post on google chat
* only report failures on main branch

fix: sanitizers post failure on google chat

---

src/facade/reply_builder.h

`ReplyBuilder2` family contain `public virtual functions` and therefore it was missing the `virtual destructors`. 
* add virtual destructors to ReplyBuilder2 family

fix: missing virtual destructors in ReplyBuilder2

---

src/core/task_queue.cc
src/core/task_queue.h
src/server/engine_shard.cc
src/server/engine_shard.h
src/server/engine_shard_set.cc
src/server/engine_shard_set.h

Also allow the TaskQueue to support multiple consumer fibers.

chore: introduce a secondary TaskQueue for shards

---

src/core/extent_tree.cc
src/core/extent_tree.h
src/core/extent_tree_test.cc
src/server/tiered_storage.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/external_alloc.cc

1. Before - when 15% margin of total size becomes larger than 256MB, we increased the file by 256MB even though we still had unused 256MB. Now it's fixed.
2. We attempted to grow a file even if it reached the limit and then returned the error. It is wrong handle "reach the limit" state as an error - it's just a logical constraint, so now we do not attempt to grow and handle this quietly.
3. There was a segfault bug in extent tree in case the existing segment and the new one needs to be united.

fix: bugs around the growth of a tiered file

---

src/server/multi_test.cc
src/server/script_mgr.cc
src/server/script_mgr.h
tests/dragonfly/replication_test.py
tests/dragonfly/seeder/script-generate.lua
tests/dragonfly/seeder/script-hash.lua

**Background**
We tried to be compatible with Valkey in their support of Lua flags, but we generally failed:
1. We are not really compatible with Valkey because our flags are different (we reject unknown flags, and Valkey flags are unknown to us)
2. The `#!lua` syntax doesn't work with Lua (`#` is not a comment), so scripts written for older versions of Redis can't be used with Dragonfly (i.e. they can't add Dragonfly flags and remain compatible with older Redis versions)
**Changes**
Instead of the previous syntax:
```
#!lua flags=allow-undeclared-keys,disable-atomicity
```
We now use this syntax:
```
--!df flags=allow-undeclared-keys,disable-atomicity
```
It is _not_ backwards compatible (with older versions of Dragonfly), but it should be very easy to adapt to, and doesn't suffer from …

chore: Change Lua embedded flags syntax

---

src/server/common.cc
src/server/common.h
src/server/main_service.cc
src/server/snapshot.cc

Disables ThreadLocalMutex altogether and add debug checks for big value set
* disable ThreadLocalMutex when big value ser is off
* add dcheck for debugging

fix: disable ThreadLocalMutex when big value ser is off

---

src/facade/reply_builder.cc
src/facade/reply_builder.h

Motivation: Repeated calls to ReservePiece where slowing down the code with lots of small strings. This is why I introduced WritePieces<> that will reserve all the space ahead and copy the strings in one pass.
With a long list of small strings, the current new io was about 10-15% slower than the old SendStringArrInternal
Result: +- same performance as SendStringArrInternal

chore(io): Optimize repeated ReservePiece calls

---

src/core/compact_object.cc
src/core/compact_object.h
src/server/container_utils.cc
src/server/db_slice.cc
src/server/db_slice.h
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/rdb_save.cc
tests/dragonfly/hash_family_test.py
tests/dragonfly/instance.py
tests/dragonfly/replication_test.py

fixes #3504
* skip empty objects in rdb save
* skip empty objects in rdb load
* delete empty keys in FindReadOnly

fix: skip empty objects on load and replication

---

src/server/engine_shard.cc

The problem is that we lock the same mutex `db_slice.GetSerializationMutex()` twice on the same fiber.
We first lock it in `RetireExpiredAndEvict()` and then eventually we write the expired items on the journal via (in the call path of `ExpireIfNeeded`) a call to `RecordExpired` which will apply the callbacks registered by the snapshot. These callbacks, acquire the same mutex:
```
384 void SliceSnapshot::OnJournalEntry(const journal::JournalItem& item, bool await) {                 
385   // To enable journal flushing to sync after non auto journal command is executed we call         
386   // TriggerJournalWriteToSink. This call uses the NOOP opcode with await=true. Since there is no  
387   // additional journal change to serialize, it simply invokes PushSerializedToChannel. …
```

fix: deadlock in Heartbeat()

---

src/facade/reply_builder.cc

The problem that `IOV_MAX` is not defined on all versions of macos. I found this one in librdkafka which I trust: https://github.com/confluentinc/librdkafka/blob/master/src/rd.h#L210C1-L212C21
* define IOV_MAX on macos if it's not defined

fix: macos build

---

src/server/engine_shard.cc
src/server/list_family_test.cc

Cause: `Check failed: continuation_trans_ == nullptr || continuation_trans_ == trans BLMOVE@4135983/2 {id=33648} when polling BLMOVE@4135965/1 {id=50088}cont_mask: 41 vs 41`
Preconditions: 
* Two BLMOVE commands waiting for different keys on _the same shard_, for both of them the source and destination key are located on different shards, so they need _two hops_ to get the job done
* _A single_ MULTI/EXEC unblocking both of them
Flow:
* Both suspended BLMOVEs wake up and continue running PollExecution
* Because they are 2-hop commands, they try to set continuation_trans_ 
* The first one does so successfully, the second doesn't expect it to be set, so it fails on the check above
Fix:
* Don't set continuation_trans_ for awoken blocking commands that want to proceed with another hop
* Is it …

fix(transaction): Don't set continuation for blocking

---

tools/docker/entrypoint.sh
tools/packaging/Dockerfile.alpine-dev
tools/packaging/Dockerfile.ubuntu-dev
tools/packaging/Dockerfile.ubuntu-prod

Fixes #2917
The problem is described in this "working as intended" issue https://github.com/moby/moby/issues/3124 So the advised approach of using "USER dfly" directive does not really work because it requires that the host will also define 'dfly' user with the same id. It's unrealistic expectation.
Therefore, we revert the fix done in #1775 and follow valkey approach: https://github.com/valkey-io/valkey-container/blob/mainline/docker-entrypoint.sh#L12
1. we run the entrypoint in the container as root which later spawns the dragonfly process
2. if we run as root:
a. we chmod files under /data to dfly.
b. use setpriv to run ourselves as dfly.
3. if we do not run as root we execute the docker command.
So even though the process starts as root, the server runs as dfly and only the bootstrap …

fix: named volume permissions in docker

---

src/server/list_family_test.cc

Somehow, the sanitizers build triggered `-werror=deprecated` https://github.com/dragonflydb/dragonfly/actions/runs/10505992538/job/29104705713#step:7:941 for  `error: implicit capture of 'this' via '[=]'`. This is solved by disabling the warning for that block (see comments)
* disable warning for the problematic block in list_family

fix: build errors in sanitizers daily workflow

---

src/server/search/doc_index.cc
src/server/search/doc_index.h
tests/dragonfly/replication_test.py

Fix search replication by ignoring updates while the index hasn't been built. This happens when we send traffic during journal full sync. 
Follow up: The indices exist during full sync only to store the index meta information. Ideally, we should just extract this information and create the indices immediately before ~~re~~building them, instead of separating this process into two stages

chore: fix search replication

---

src/server/zset_family.cc
src/server/zset_family_test.cc

1. Fix the bug of computing incorrectly the weight index in OpInter
2. Remove code duplication and factor out the parsing code from OpInter and OpUnion into PrepareWeightedSets
3. Implement TODO and support union of zsets and sets, which has already been implemented for ZINTER.
fixes #3553

fix: zinterstore correctly finds weights

---

src/server/main_service.cc
src/server/multi_test.cc
src/server/transaction.cc

Just a DCHECK failing because we didn't clean up properly, has no implications on optimized builds

chore(server): Fix watch

---

src/core/search/indices.cc
src/server/search/search_family_test.cc

Fixes #3500 
Invalid range query caused right tree iterator to be less than left, thus making the `for (left_it ++ != right_it)` loop endless

chore(search): fix numeric index query in rev order

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/server/main_service.cc

We already allow limiting the queue by memory usage but it also makes sense to limit by depth, so that in extreme cases we would provide backpressure back to client connections. Otherwise if we parse and read everything, clients do not have a sense of how loaded the connection is on the server side.

chore: allow limiting pipelining queue by length

---

tests/fakeredis/poetry.lock
tests/fakeredis/pyproject.toml

- Fix pytest settings: add `unsupported_server_types`.
- Update pytest to v8 and all plugins.

fix: add unsupported_server_types to fakeredis tests

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/string_family.cc
src/server/string_family_test.cc

1. strlen should return 0 for non existing types.
2. reject both EX and PX options in SET
3. prevent overflow of expiry time that is too large

fix: string compatibility issues

---

src/server/list_family.cc
src/server/list_family_test.cc
src/server/string_family.cc
src/server/string_family_test.cc
tests/fakeredis/test/test_mixins/test_string_commands.py

fix: compatibility around list and string commands

---

src/server/zset_family.cc
src/server/zset_family.h

Shadows #3562  and removes duplicate argparsing code completely.
Now all Z[REV]RANGE functions will call into ZRANGE directly with predefined params set. As a side effect the deprecated functions will now transparently support all options of ZRANGE 🤷🏻‍♂️

chore(server): Unify zset arg parsing

---

.gitignore
src/server/common.cc
src/server/common.h
src/server/generic_family.cc
src/server/generic_family_test.cc
src/server/list_family.cc
src/server/list_family_test.cc
src/server/string_family.cc
src/server/string_family_test.cc
tests/fakeredis/test/test_mixins/test_generic_commands.py
tests/fakeredis/test/test_mixins/test_string_commands.py

1. Fix corner cases around non existing keys
2. Fix matching logic for * glob, as well as '' glob.
3. Improve SORT option parsing.

fix: compatibility around list,string and sort commands

---

src/server/zset_family.cc
src/server/zset_family_test.cc

Quick fix, I'll shadow this again with proper code removal 💣

chore(server): Sort correctly in ZINTER

---

src/server/dragonfly_test.cc
src/server/generic_family.cc
src/server/main_service.cc
src/server/set_family.cc
src/server/set_family_test.cc
tests/fakeredis/test/test_mixins/test_pubsub_commands.py
tests/fakeredis/test/test_mixins/test_scripting.py

smismember should return an array of longs and not array of strings. ping in subscribe mode returns an array for resp2.

chore: improve compatibility of set and ping commands

---

tests/dragonfly/cluster_test.py

The test deadlocks on the CI.
https://github.com/dragonflydb/dragonfly/actions/runs/10556680020/job/29242720182?pr=3502
* disable test_cluster_flushall_during_migration

fix: disable test_cluster_flushall_during_migration

---

src/server/json_family.cc
src/server/json_family_test.cc

fixes dragonflydb#3558
relates to the #3580 . Another problem when we have multiple legacy mode paths in the `JSON.GET` command.

fix(json_family): Fix JSON.GET crash for the multiple legacy mode paths

---

src/core/interpreter.cc
src/core/interpreter_test.cc
tests/fakeredis/test/test_mixins/test_scripting.py

fix: return an error when invalid number of arguments is passed.

---

src/server/list_family_test.cc

fix: warning as error on sanitizers build

---

src/server/conn_context.h
src/server/dflycmd.h
src/server/replica.cc
src/server/replica.h
src/server/server_family.cc
src/server/server_family.h
src/server/version.h

Stop supporting DflyVersion::VER0 from more than a year ago. In addition, rename Metrics fields to make them more clear General improvements and fix the reconnect metric.

chore: remove DflyVersion::VER0

---

src/facade/cmd_arg_parser.cc
src/facade/cmd_arg_parser.h
src/facade/cmd_arg_parser_test.cc
src/server/bitops_family.cc
src/server/dflycmd.cc
src/server/hset_family.cc
src/server/json_family.cc
src/server/list_family.cc
src/server/search/doc_index.cc
src/server/search/doc_index.h
src/server/search/search_family.cc
src/server/server_family.cc
src/server/zset_family.cc

fix #3471 
fix also a couple of places where we forgot to compare case insensitive or call ToUpper.
Unfortunately, it's only part of the refactoring because there are some places where I want to spend more time and PR can become huge.

refactor: remove toUpper() from cmd_arg_parser

---

src/server/json_family.cc
src/server/json_family_test.cc
tests/fakeredis/test/test_json/test_json.py

JSON.STRAPPEND was completely broken.
First, it accepts exactly 3 arguments, i.e. a single value to append. Secondly, the value must be a json string, not the regular string. Meaning it must be in double quotes. So, before we parsed: `JSON.STRAPPEND key $.field bar` and now we parse: `JSON.STRAPPEND key $.field "bar"`
In addition fixed the behavior of JSON.STRLEN to return "no such key" error in case the json key does not exist and path is specified.

fix: JSON.STRAPPEND

---

src/server/stream_family.cc
src/server/stream_family_test.cc
tests/fakeredis/test/test_mixins/test_streams_commands.py

1. xreadgroup should return data for all the streams, irrespective whether they have results or not (unlike with XREAD)
2. xpending with 0 results should still return a 4-element array
3. reject ENTRIESREAD option as it's not implemented.

fix: xreadgroup replies as a map for RESP3

---

CMakeLists.txt
src/facade/reply_builder.h
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/incoming_slot_migration.cc
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
src/server/common.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/dflycmd.cc
src/server/dflycmd.h
src/server/engine_shard.cc
src/server/main_service.cc
src/server/main_service.h
src/server/namespaces.cc
src/server/server_family.cc
src/server/server_family.h

Part 2/2. 
resolves fully #3448
* add missing annotations
* small mutex fixes
* enable -Werror=thread-safety for clang builds

chore: enable -Werror=thread-safety and add missing annotations (part 2/2)

---

src/server/replica.cc
src/server/replica.h
src/server/server_family.cc
tests/dragonfly/redis_replication_test.py
tests/dragonfly/replication_test.py
tests/dragonfly/utility.py

In Valkey slave_repl_offset denotes the replication offset on replica site during stable sync phase. During fullsync phase it appears with 0 value.
In Dragonfly this field appears only after full sync has completed, thus it allows to check whether Dragonfly reached stable sync phase. The value of this field describes the cumulative progress of all the replication flows and it does not directly correspond to master side metrics.
In addition, this PR fixes the bug in wait_available_async() function in our replication tests. This function is intended to wait until a replica reaches stable state and it did by sending pings until they do not respond with LOADING error, hence the assumption is that the replica is in full sync state already.
However it can happen that master_link_status is "up" …

feat: add slave_repl_offset to the replication section.

---

README.ja-JP.md
README.ko-KR.md
README.md
README.zh-CN.md
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family_test.cc
src/server/main_service.cc
src/server/replica.cc
tests/dragonfly/cluster_test.py
tests/dragonfly/replication_test.py

This PR partially reverts #3421
Fixes #3541

chore: Split `--cluster_announce_ip` and `--replica_announce_ip`

---

tests/dragonfly/snapshot_test.py

see failed pytest https://github.com/dragonflydb/dragonfly/actions/runs/10653781303

fix pytest: use generic random dbfilename in tests

---

.devcontainer/alpine/post-create.sh
src/facade/reply_builder.h
src/server/detail/wrapped_json_path.h
src/server/json_family.cc
src/server/json_family_test.cc
tests/fakeredis/test/test_json/test_json.py

For legacy mode:
1. For mutate commands, an empty result should throw an error
2. For read commands, it returns nil if path was not found, but if it was matched but only with a wrong types, it will throw an error.
For non-legacy mode, objlen should throw an error for non existing key.
Simplified JsonCallbackResult a bit and made sure more fakeredis tests are passing.

fix: edge cases around mismatched path in json code

---

src/facade/cmd_arg_parser.cc
src/facade/cmd_arg_parser.h
src/facade/cmd_arg_parser_test.cc
src/server/json_family.cc
src/server/list_family.cc
src/server/search/search_family.cc
src/server/server_family.cc
src/server/stream_family.cc
src/server/string_family.cc
tests/dragonfly/search_test.py

There is no sense to do ExpectTail() because we do the same check in Next() or other operations

refactor: remove extra code from CmdArgParser

---

.github/workflows/test-fakeredis.yml
src/facade/facade_test.cc
src/server/zset_family.cc
src/server/zset_family_test.cc
tests/fakeredis/test/test_mixins/test_scripting.py

1. The offset value can be negative, in that case we should return an empty array.
2. Fix edge cases of inf*0 and -inf + inf, so they will result in 0 and non NaN (similarily to Valkey).

fix: limit parsing in zrange commands

---

.github/workflows/ci.yml
src/facade/cmd_arg_parser.h
src/server/list_family.cc
src/server/list_family_test.cc
tests/fakeredis/test/test_hypothesis.py

Fix the case where we pass an empty argument, which then is parsed as an empty string view with null pointer. The null pointer is not handled correctly by our low level c code, hence switch to using ""sv for that.

fix: crash when passing empty arguments

---

src/server/generic_family.cc
src/server/generic_family_test.cc

fixes #3636
The problem was that instead of implementing GT operator, we implemented !LT, which is GE operator. As a result the iterators inside the sort algorithm reached out of bounds.
---------

fix: crash during SORT DESC call

---

tools/docker/healthcheck.sh

https://github.com/dragonflydb/dragonfly/pull/3518 updated the process to run as `dfly` causing the `netstat` command to not have the process name being returned when ran normally:
```
su: warning: cannot change directory to /home/dfly: No such file or directory
(Not all processes could be identified, non-owned process info
will not be shown, you would have to be root to see it all.)
6379
```

fix(docker/healthcheck): run netstat port retreival command as dfly

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
tests/dragonfly/cluster_test.py

fixes: #3638 
The problem is a deadlock:
the first lock can be during shutdown or config for set_config_mu after that we try to remove outgoing migration and join it
the second lock happens if the migration process finishes and updates config, it tries to lock set_config_mu that is already locked
The solution: we can remove outgoing migration after unlocking the mutex, to do this under mutex lock we move the migrations from the common storage to a local variable and remove it after mutex unlocking.

fix: deadlock in the cluster migration process

---

src/core/allocation_tracker.cc
src/core/allocation_tracker.h
src/server/detail/save_stages_controller.cc
src/server/detail/save_stages_controller.h

Also, remove dependence of absl::TimeZone bloated monstrosity, which was required by absl::FormatTime api, even though we do not actually format a timezone.
When absl::LocalTimeZone is accessed it allocated hundreds of thousands of bytes for each shard thread (maybe due to lack thread safety during lazy initialization).
At the end, strftime does a great job without any shenanigans.

fix: recursive calls in the allocation tracker

---

src/server/dflycmd.cc
src/server/engine_shard.cc
src/server/engine_shard.h
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/snapshot.cc
src/server/snapshot.h

Some renames and added comments. Refactored StartIncremental into a separate function without any functional changes.

chore: cosmetic changes around Snapshot functions

---

src/server/search/aggregator.h
src/server/search/doc_accessors.cc
src/server/search/doc_accessors.h
src/server/search/doc_index.cc
src/server/search/doc_index.h
src/server/search/search_family.cc
src/server/search/search_family_test.cc

fixes dragonflydb#3492
The first pr that fixes the `FT.AGGREGATE` command:
1. Fixed a bug with loading index fields when the `LOAD` option is not specified
2. Added string to double conversion for `NUMERIC` fields
3. Fixed parsing for the fields with at sign `@`, e.g.:
```bash
FT.AGGREGATE index "*" SORTBY 1 @word REDUCE COUNT 0 AS count
```
5. Fixed reply output:
Before:
```shell
1) 1) 1) "some_field of the hset 1"
2) "value"
2) 1) "another_field of the hset 1"
2) "value"
2) 1) 1) "some_field of the hset 2"
2) "value"
2) 1) "another_field of the hset 2"
2) "value"
```
After:
```shell
1) (integer) 2
1) 1) "some_field of the hset 1"
2) "value"
3) "another_field of the hset 1"
4) "value"
2) 1) "some_field of the hset 2"
2) "value"
3) "another_field of the hset 2"
4) "value"
```

fix(search_family): Fix FT.AGGREGATE GROUPBY option

---

src/server/server_family.cc

We already adhere to all requirements, we just need to return the id when the command is issued :)
Fixes #3651

chore: Add `CLIENT ID` command

---

.github/workflows/test-fakeredis.yml
src/core/size_tracking_channel.h
src/server/rdb_save.cc
src/server/snapshot.cc
src/server/snapshot.h
tests/fakeredis/test/test_mixins/test_geo_commands.py

Records channel is redundant for DFS/replication because we have single producer/consumer
scenario and both running on the same thread. Unfortunately we need it for RDB snapshotting.
For non-rdb cases we could just pass a io sink to the snapshot producer,
so that it would use it directly instead of StringFile inside FlushChannelRecord.
This would reduce memory usage, eliminate yet another memory copy and generally would make everything simpler.
For that to work, we must serialize the order inside FlushChannelRecord and this PR allows this.

deprecate RecordsPopper and serialize channel records during push

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/server/server_family.cc
src/server/server_family.h
tests/dragonfly/connection_test.py

Add support for `CLIENT SETINFO <LIB-NAME | LIB-VER>` and also return
that as part of `CLIENT LIST`, like Valkey.
Fixes #3137

feat(server): Support `CLIENT SETINFO`

---

tests/dragonfly/cluster_test.py

We need to improve cluster reliability, so I've unskipped cluster tests and added a little debug info

test: unskip cluster tests and add debug info

---

src/server/debugcmd.cc
src/server/main_service.cc
src/server/server_family.cc

For some cases, this map can grow indefinitely.
This change makes it less detailed by making sure that number of possible keys is bounded. Still it can provide a good summary of nature of exec transactions.

chore: limit number of descriptors in the exec map

---

src/server/dflycmd.cc
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/snapshot.cc
src/server/snapshot.h

fix #3649 
The bug: while running debug populate and cancel replication ,rdb saver cancel is called with context cancel. Both flow calling StopChannel function which sets journal callback to 0 and unregister on journal change and closes channel.
When this flow was called from different fibers than the first call was locked on mutex to unregister the journal the second fiber whould skip the unregister as it was already set the call back id to 0 and it called the close channel leading to deadlock as callback could not push to channel as it was full.
The fiber which consumes from channel already exited because channel was marked as close
The fix:
Now we call close channel only after and if we call the unregister on change, we do this only once and in the cancel function

fix(server): fix replication master deadlock on cancelation flow

---

src/server/cluster/cluster_family.cc
src/server/cluster/incoming_slot_migration.cc
src/server/cluster/incoming_slot_migration.h

fixes: #3484
test_cluster_migration_cancel was broken because we haven't joined the migration process during canceling and can start flush slots before the last key update for every flow is executed. 
the fix: we join the migration process for cancel operation

fix: join for cancel incoming migration

---

src/server/json_family.cc
src/server/json_family_test.cc

fixes 3. bug in the #3671
```
127.0.0.1:6379> JSON.SET mykey . '{"name": "Alice", "age": 30}'
OK
127.0.0.1:6379> JSON.SET mykey .address '{"name": "Alice", "age": 30}'
(nil) // Result is wrong. Should return OK
```
Additionally, clean up a bit the code.

fix(json_family): Fix the JSON.SET bug if the path is in legacy mode and is not the root

---

tests/dragonfly/replication_test.py

I was able to reproduce it locally on debug build. As is it fails rather frequently. The test is flaky because by the time the client calls `REPLICAOF` command df might have finished loading the snapshot. The fix is increase load such that the client will get `busy loading` while calling `REPLICA OF COMMAND`. I rerun the test a couple of times without any failure locally. I will run it here a few times as well.
* increase snapshot size for the test
resolves #3689

fix: test_replicaof_reject_on_load assert failure

---

src/server/json_family.cc
src/server/json_family_test.cc

fixes 2. bug in the #3671.
[Regarding to the documentation](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/json-get.html), `NOESCAPE` option allowed to be present for legacy compatibility and has no other effect.
Additionally, the code for the `JSON.GET` command was cleaned up.

fix(json_family) Add NOESCAPE option to the JSON.GET command

---

src/server/acl/acl_family.cc
tests/dragonfly/acl_family_test.py

DF would fail to parse ACL file with multiple whitespaces. This PR fixes this.
* allow parsing extra whitespace characters in acl files
Resolves #3698

fix: allow parsing extra spaces on acl files

---

src/server/rdb_load.cc

we have an issue during the replication. 
```
W20240915 07:49:01.264786 159412 replica.cc:241] Error syncing with ... dragonfly.rdbload:8 Internal error when loading RDB file 8
E20240915 07:49:01.260331 159412 protocol_client.cc:291] Socket error system:103
E20240915 07:49:01.258461  2898 db_slice.cc:894] Internal error, inconsistent state, mcflag should be present but not found
```
The bug manifests on replica side and causes the data on replica be in inconsistent state, potentially triggering errors logs when it's being accessed. The server process will survive this state

fix: add default value has_mc_flag field

---

.github/workflows/ci.yml
.github/workflows/regression-tests.yml
tests/dragonfly/connection_test.py
tests/dragonfly/instance.py

We disable address space randomization when building the binary and use addr2line to symbolize the stacktrace if it exists.

chore: symbolize stack traces in tests upon crash

---

src/server/server_family.cc

Fixes loading S3 snapshots (see https://github.com/dragonflydb/dragonfly-operator/issues/243).
Before `fs::path path(load_path)` was loading an S3 URL like `s3://my-bucket/my-backup` as a local filepath which messed up the scheme (replaced `s3://` with `s3:/` I think).
So just replacing `fs::path` with `string` and setting `path = dir_path.generic_string()` which I think is equivalent?
As mentioned in 'Eng' chat there is an S3 test (https://github.com/dragonflydb/dragonfly/blob/main/tests/dragonfly/snapshot_test.py#L315) though that needs AWS credentials in CI to run the test. Happy to integrate (just needs setting an environment variable in the workflow) but I'll probably need some help setting up credentials

fix: fix s3 load snapshot

---

src/server/main_service.cc

Pre-this change, whenever Dragonfly was paused (either by a user or by internal processes like takeover or slot migration finalization), migrations and replications were also paused.
This could cause timing issues, which sometime result in migration failures. Specifically, when 2 nodes have migrations from one to the other **in parallel** (A->B and B->A), the `Pause()` that happens on A (which happens because it's a source node) will stop it from processing incoming traffic from B (incoming because it is also a target node).
If timed correctly, it will be locked until it times out, and so the migration will fail.
The fix is to prevent replications and migrations from adhering to `Pause()`s, which I think should not have happened in the first place because they should use the admin port …

fix(cluster): Do not `Pause()` replication / migrations

---

src/server/detail/wrapped_json_path.h
src/server/json_family.cc
src/server/json_family_test.cc

fixes 1. bug in the #3671 
1. Rename `UpdateEntry` to `JsonMutateOperation` by analogy with the `JsonEvaluateOperation` command
2. Add `empty_is_nil` option to the `JsonMutateOperation`

fix(json_family): Fix JSON.ARRPOP command in legacy mode should not return WRONGTYPE error 

---

src/server/json_family.cc
src/server/json_family_test.cc

fixes 5. bug in the #3671 
1. Separate double and int values during the comparison of the JSON objects
2. Remove the error for `JSON.ARRINDEX` command when the specified value is an object or array
3. Clean up code in the `JSON.ARRINDEX` command
4. Fix bug in the `JSON.NUMINCRBY` and `JSON.NUMMULTBY` commands when we should convert int value to the double in the json. For example:
```bash
127.0.0.1:6379> json.set json . '{"a":2}'
OK
127.0.0.1:6379> json.numincrby json $.a 1
"[3]"
127.0.0.1:6379> json.get json
"{\"a\":3}"
127.0.0.1:6379> json.numincrby json $.a 1.0
"[4]" // WRONG. We should return 4.0
127.0.0.1:6379> json.get json
"{\"a\":4}" // WRONG. "{\"a\":4.0}" is expected 
```

fix(json_family): Separate double and int values during the comparison of the JSON objects

---

tests/dragonfly/replication_test.py

There are 2 minor issues with this test:
1. It specified `cmdstat_replconf` as `cmd_stats` instead of `cmd`, that's clearly a typo as `cmd_stats` is a map with stats, while `replconf` is a Dragonfly command
2. Command `MULTI` is allowed to run even when the server is in paused state, see [here](https://github.com/dragonflydb/dragonfly/blob/main/src/server/main_service.cc#L1197):
``` // Don't interrupt running multi commands or admin connections. ```
Fixes #3675

fix: Fix test `test_client_pause_with_replica`

---

tests/dragonfly/cluster_mgr_test.py
tools/cluster_mgr.py

We updated the reply of `SLOT-MIGRATION-STATUS`, so `cluster_mgr.py` needs to be adjusted as well.

fix: Fix `cluster_mgr.py`

---

src/server/json_family.cc
src/server/json_family_test.cc

fixes 4. bug in the #3671 
The behavior for each `JSON.ARR*` command with out-of-range indexes varies. It is best described in the tests

fix(json_family): Fix out of bound ranges for the JSON.ARR* commands

---

tests/dragonfly/replication_test.py

fixes: #3713
update test_replicating_mc_flags: set keys for master via Redis port and read them from replica via Memcached port
add test_double_take_over: check circle replication when we do replication from first node to second, promote second node, and do replication again from second node to first.

test: add tests for replication

---

tests/dragonfly/replication_test.py

I've tried to reproduce the problem with test_replica_reconnections_after_network_disconnect locally but failed, so I decided to unskip it

test: unskip test for debugging purpose

---

src/server/replica.cc
tests/dragonfly/instance.py
tests/dragonfly/replication_test.py

test: add test for replication deadlock on replication timeout

---

tests/dragonfly/cluster_mgr_test.py

We saw failures due to port already in use

chore: Switch ports for `cluster_mgr_test.py`

---

src/core/compact_object.cc
src/server/rdb_load.cc

chore: change log level to warning for empty keys

---

tools/docker/healthcheck.sh

fix: allow the healthcheck run in non-privileged containers as well

---

src/facade/cmd_arg_parser.h
src/facade/cmd_arg_parser_test.cc
src/server/bitops_family.cc
src/server/bitops_family_test.cc

fixes: #3747
the problem was that we processed all incorrect values for the SETBIT command as 1
fix: return error if value for SETBIT is not 0 or 1
also added a helper type FInt for CmdArgParser that can validate a numerical range

fix: add value range check for SETBIT command

---

src/server/zset_family.cc

While working on https://github.com/dragonflydb/dragonfly/issues/3742, found other zset `STORE` commands don't conclude the transaction when they return an error.
Such as to reproduce:
```
127.0.0.1:6379> SET foo bar
OK
127.0.0.1:6379> ZINTERSTORE dest 1 foo
(error) WRONGTYPE Operation against a key holding the wrong kind of value
127.0.0.1:6379> ZINTERSTORE dest 1 foo
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
```
W20240921 13:27:23.480844 1039547 main_service.cc:1387]  ZINTERSTORE dest 1 foo failed with reason: -WRONGTYPE Operation against a key holding the wrong kind of value
*** SIGSEGV received at time=1726921644 on cpu 1 ***
[failure_signal_handler.cc : 345] RAW: Signal 11 raised at PC=0x620500431c6d while already in AbslFailureSignalHandler()
PC: @ …
```

fix: zset store conclude transaction on error

---

src/facade/command_id.h
src/server/command_registry.cc
src/server/command_registry.h
tests/dragonfly/generic_test.py

I suspect we have memory leak in eval when returning oom 
Using this flag set to evalsha,eval we can verify and if this is the case it stop the leak until we introduce a fix

feat(server): introduce oom_deny_commands flag

---

src/redis/rax.c
src/server/stream_family.cc

Add more logs around consumer variable because it seems suffers from data races, possibly read after free bug.

chore: add integrity checks to consumer->pel

---

src/server/dflycmd.cc
src/server/journal/streamer.cc
src/server/main_service.cc
src/server/rdb_load.cc
src/server/rdb_save.cc
src/server/server_family.cc

Before this change - we wrote in a single call whatever record chunks we pulled from the channel.
This can be problematic for 1GB chunks for example, which might take 10sec to write.
Lately we added a replication breaker on the master side that breaks the fully sync after
a predefined threshold has passed. By default it was 10sec. To improve the robustness of this
breaker, we now write chunks of upto 1MB and update last_write_time_ns_ more frequently.
Also, we added more logs to make replication delays on both sides more visible.
We also added logs of breaking the replication on the master sides.
Unfortunately, this did not help making BreakStalledFlowsInShard more robust because now the
problem moved to replica side which may take 20s+ seconds to parse huge values.
Therefore, I increased …

fix: make snapshotting process more responsive

---

tests/dragonfly/replication_test.py

Reduce the snapshot size by 20% and increase the timeout to avoid failures due to slow loads.
Fixes https://github.com/dragonflydb/dragonfly/actions/runs/10982136864/job/30490032552

fix: tune test_replicaof_reject_on_load parameters

---

tests/dragonfly/acl_family_test.py

I could not reproduce and this test failed once and it exists for over a year. I am quite skeptical if this is related with `ACL` because `MULTI/EXEC` command always returns an array as a reply. Even if it fails, we still get an array and if the commands return nothing then the array is simply empty. However, from the test failure, it's explicit that the returned object is a `string` so for example `EXEC` could have failed with `internal error` (some random thought). Furthermore, I don't see how else it would fail in `VerifyCommandExecution` so I would say it's unlikely we get a string error from there. Either way, if it ever fails again I would like to know what the error message is and hopefully this will shed some light on the actual issue.
* print result if assertion fails
helps with …

chore: logs on assert fail for test_acl_cat_commands_multi_exec_squash

---

src/server/string_family.cc
src/server/string_family_test.cc

fixes: #3752
The problem is that the invalid range was transformed into [0, 0] range, so the first symbol was returned.
fix: transformation is done after range is validated

fix: substr/getrange result for invalid range

---

src/server/zset_family.cc
src/server/zset_family.h
src/server/zset_family_test.cc

Adds support for `ZRANGESTORE`. Fixes https://github.com/dragonflydb/dragonfly/issues/3742.
Still checking the error handling is right (and trying to get my head around what errors can occur), though figured worth adding a draft PR to check the rough approach looks right. Unlike the other `Z...STORE` commands, `ZRANGESTORE` isn't varadic so I think just setting the command ID first/last key position is enough to get the transaction right?

feat(zset_family): add ZRANGESTORE

---

src/facade/reply_capture.cc
src/server/main_service.cc
src/server/multi_command_squasher.cc

bug 1: in multi command squasher error message was not set therefore it was not printed to log on the relevant command only on exec, fixed by setting the last error in CapturingReplyBuilder::SendError
bug 2: I sometimes see error logs which does not make sence f.e mset will print key does not exist, I added a dcheck for before command execution that there is no error set and it fails. reproduced with test_reply_guard_oom. @kostasrim will you be able to ivestigate this?

fix server: fix last error reply

---

src/server/detail/wrapped_json_path.h
src/server/json_family.cc

chore: give up on InlinedVector due to spurious warnings with optional

---

src/server/engine_shard.cc
src/server/engine_shard.h
src/server/error.h
src/server/server_family.cc
src/server/stream_family_test.cc
src/server/transaction.cc
src/server/transaction.h

Renames in transaction.h - no functional changes.
Fix a typo in error.h following  #3758

chore: some renames + fix a typo in RETURN_ON_BAD_STATUS

---

src/server/string_family.cc
src/server/string_family_test.cc
tests/fakeredis/test/test_hypothesis.py

fixes: #3769
the problem: set range modify stored value if the new value was empty
fix: if the new value is empty, the result is the size of the stored value without modification
also comment out the swapdb test, because we don't support this command

fix: setrange with empty value doesn't modify the DB

---

tests/dragonfly/acl_family_test.py

The reason it failed is that, in some rare cases, the subscriber did not
get the first few messages of the publisher. This is likely due to
timing of subscribe and publish, in different connections / threads.
Given Pub/Sub has very weak guarantees, it's probably ok as is, so I
just added a sleep to get the test to pass always.
Fixes #3678

fix: Fix flaky `test test_acl_revoke_pub_sub_while_subscribed`

---

src/server/string_family.cc
src/server/string_family_test.cc

fix: GETRANGE params validation according to fakeredis tests
set key 0
getrange key 0 -2 returns empty string
expected result  [0, -2]  is correct range and should be transformed into [0, 0] so the result should be 0

fix: GETRANGE params validation

---

src/server/bitops_family.cc
src/server/bitops_family_test.cc
tests/dragonfly/replication_test.py

There are two bugs:
Bug 1:
```
bitop not does_not_exist tmp2
get does_not_exist
```
Should return `nill` and not `""` 
Bug 2:
```
setup master and replica and then:
on master do: hset foo bar val -> bitop not foo bar -> get foo returns WRONGTYPE
on replica do GET foo returns ""
Now state_of(master) != state_of(replica)
```
Bug 3:
```
hset foo bar val -> bitop not foo bar -> get foo returns WRONGTYPE
```
when `get foo` should return `nill`, that is `bitop` acts as a `blind update` similar to `set` command
resolves #3528

fix: bitop do not add dst key if result is empty

---

src/server/acl/acl_family.cc
src/server/acl/acl_family_test.cc

Fixes #3458 
TESTED =  <img width="482" alt="1" src="https://github.com/user-attachments/assets/4529f3dd-5616-4d4a-a73e-f00643e8fdf7">
I did not add tests as there was no test earlier for the same but it can be added.

chore(acl_family): add allcomands and nocommands

---

src/server/db_slice.cc
src/server/server_family.cc

We have two `goto` statements in the codebase (we do have a bunch more in `redis/` folder but these should not be touched as we might want to `diff` them with the original files) and I replaced them with `lambdas` to simplify the control flows.
* replace goto statements with lambda calls

chore: remove goto statements

---

src/server/transaction.cc

A small refactoring to improve the flow of ScheduleInternal() as well as to prepare it for the next change that will reduce the CPU load from the shard queue.

chore: ScheduleInternal refactoring

---

src/facade/cmd_arg_parser.h
src/server/bitops_family.cc
src/server/bitops_family_test.cc

the problem: (bitcount foo 1 0) counts bit for invalid range because we exchange start and end and get range [0, 1]
fix: return 0 if the range is invalid

fix: bitcount invalid range

---

src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/op_manager_test.cc

Motivation: this failure (probably not a ssd):
https://github.com/dragonflydb/dragonfly/actions/runs/11051524561/job/30701596528?pr=3802#step:10:1555

chore: tune TieredStorageTest.MemoryPressure

---

src/server/dfly_bench.cc
src/server/dfly_main.cc

1. Issue ping upon connect, add a comment why.
2. log error if dfly_bench disconnects before all the requests were processed.
3. Refactor memcache parsing code into ParseMC function.

fix: make sure dfly_bench reliably connects

---

src/core/compact_object_test.cc
src/redis/listpack.c
src/redis/util.h

Also add benchmarks for lpCompare code when list contains integers.

chore: reformat listpack according to valkey 8

---

src/server/stream_family.cc
src/server/stream_family_test.cc

Fixes #3770 
Previously XREAD:
1. Fetched group consumer info (with a hop)
2. Looked up last stream ids (with a hop)
3. Determined if there are entries to read (on coordinator)
4. Dispatched a hop to read entries or retired to blocking mode
Instead we can merge steps (1), (2) and (3) into a single step, optionally with step (4) for single shard operations that can avoid concluding (we had this optimization before)

chore: refactor XRead

---

src/server/stream_family.cc
src/server/stream_family_test.cc

Refactoring broke single shard single hop xread, here it is again

chore: singlehop XREAD

---

src/core/compact_object_test.cc
src/redis/listpack.c
src/redis/listpack.h

Problem: when lists are long OpRem will spend lots of time comparing an element with records in the list. For integer-based lists, most of the time is spent in lpCompare. In addition, lpGet has lots of branches that penalize integers use-cases.
This PR:
1. Introduces lpGet2 - the improved version with less branches.
2. Benchmarks lpCompare vs an algorithm that compares records to an integer.
3. Benchmarks lpGet vs lpGet2
On c7g:
```
----------------------------------------------------------
Benchmark                Time             CPU   Iterations
----------------------------------------------------------
BM_LpCompare          3068 ns         3068 ns      1844176 …
```

chore: introduce an optimized integer compare algorithm for lists

---

src/core/compact_object_test.cc

Seems that lpStringToInt64 is fairly optimized.
On c7g:
```
BM_LpString2Int/1      27383 ns        27381 ns       204149
BM_LpString2Int/2      24535 ns        24534 ns       227981
```
so SimpleAtoi has only ~10% improvement.

chore: add a benchmark comparing lpStringToInt64 to SimpleAtoi

---

src/server/rdb_load.cc
src/server/rdb_load.h
src/server/rdb_test.cc

Adds support for loading huge sets (https://github.com/dragonflydb/dragonfly/issues/3760)

feat(rdb_load): add support for loading huge sets

---

src/redis/quicklist.c
src/redis/redis_aux.c
src/redis/redis_aux.h
src/server/list_family.cc

chore: now it's not needed to allocate quicklistIter on heap

---

src/server/rdb_load.cc

Fixes loading huge hmaps with TTL fields, where the TTL isn't parsed correctly:
```
Can't parse hashmap TTL for d6e8d4c162dd4b7252c55a5e348d017de976ac0b1ca5b3a262, ttl='cab59b6814524488e8ead622fc430e28f11b1fbd86e8f9f13b', val=52505369
```
This is caused by `kMaxBlobLen` not being a multiple of 3. As each `LoadTrace` segment contains elements key, value and TTL, when the segment is truncated, the next segment will be invalid. Such as it may start with 'value', 'ttl' instead of 'key', 'value', 'ttl', which leads to the above parsing error.
Therefore when the map includes a TTL, each segment must be a multiple of 3.
(I guess a simpler alternative is just to set `kMaxBlobLen` to be a multiple of both 2 and 3? I'm not sure how important being a power of 2 is?)

fix(rdb_load): fix loading huge hmaps with ttl

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/main_service.cc
tests/dragonfly/connection_test.py

We do not allow  `notify_keyspace_events` to be set at runtime via `config set` command. This PR addresses this.
* allow notify_keyspace_events in config set command
* add tests
Resolves #3708

chore: allow config set notify_keyspace_events

---

tests/dragonfly/acl_family_test.py
tests/dragonfly/cluster_mgr_test.py
tests/dragonfly/cluster_test.py
tests/dragonfly/conftest.py
tests/dragonfly/connection_test.py
tests/dragonfly/instance.py
tests/dragonfly/memory_test.py
tests/dragonfly/replication_test.py
tests/dragonfly/server_family_test.py
tests/dragonfly/snapshot_test.py
tests/dragonfly/utility.py

A common case is that we need to clean up a connection before we exit a test via `.close()` method. This is needed because otherwise the connection will raise a warning that it is left unclosed.  However, remembering to call `.close()` at each connection at the end of the test is cumbersome! Luckily, fixtures in python can be marked as `async` which allow us to:
* cache all clients created by `DflyInstance.client()`
* clean them all at the end of the fixture in one go
This PR adds this behaviour and cleans up the code in pytests. Bonus point is that no warnings are now generated.

chore: do not close connections at the end of pytest

---

src/server/rdb_load.cc

Fixes the logging an error when a key expires between being read and being loaded, meaning the start of the object is not loaded but we still attempt to append to the object
This will still append to an object if the start of the object was loaded, even if the item has now expired to avoid an inconsistent state
Also added `Expire key on load` vlog incase it happens again (should be rare so set to level `1`)

fix(rdb_load): fix appending to an expired key

---

tests/dragonfly/acl_family_test.py

Add logs to test such that we know why it failed.
* add logs
Helps with #3719

chore: add logs to test_acl_cat_commands_multi_exec_squash

---

src/redis/listpack.h
src/redis/quicklist.c
src/redis/quicklist.h
src/server/list_family.cc
src/server/list_family_test.cc

chore: optimize element removal for integer lists

---

src/facade/cmd_arg_parser.cc
src/facade/cmd_arg_parser.h
src/server/bitops_family.cc
src/server/memory_cmd.cc

fixes: #3471
the code was refactored to avoid using CmdArgParser::ToUpper()

refactor: remove CmdArgParser::ToUpper()

---

src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/op_manager_test.cc

chore: add pending_ops to disk stats

---

src/server/rdb_load.cc
src/server/rdb_test.cc

Follows https://github.com/dragonflydb/dragonfly/pull/3807 to add support for loading huge hmaps and zsets (https://github.com/dragonflydb/dragonfly/issues/3760)

feat(rdb_load): add support for loading huge hmaps and zsets

---

src/core/dense_set.cc
src/core/dense_set.h
src/core/score_map.cc
src/core/score_map.h
src/core/sds_utils.cc
src/core/sds_utils.h
src/core/string_map.cc
src/core/string_map.h
src/core/string_map_test.cc
src/core/string_set.cc
src/core/string_set.h
src/core/string_set_test.cc

Split up the previous PR https://github.com/dragonflydb/dragonfly/pull/3772 to only target the updates in core as a first pass. @romange 
I decided to split the `dense_set.SetExpiryTime` into two branching paths. One which updates the ttl directly, and one which replaces the given object, based on if we find a ttl or not.
This seems to be needed, since I can't seem to find the ttl-bits on the StringSet sds when receiving the DensePtr. (They get masked away?)
This code is the basis for adding hexpire and fieldexpire: https://github.com/dragonflydb/dragonfly/issues/3027
I left a few questions in the code, and am open to other comments as well.
Edit: I haven't really landed what return types make sense for all of the functions yet, but maybe void makes the most sense for all update methods, …

add dense_set.SetExpiryTime in preparation for fieldexpire

---

src/server/CMakeLists.txt
src/server/common.cc
src/server/common.h
src/server/engine_shard.cc
src/server/engine_shard.h
src/server/family_utils.cc
src/server/family_utils.h
src/server/list_family.cc
src/server/set_family.cc
src/server/stream_family.cc
src/server/zset_family.cc

Remove some of the c'stlye code

chore: WrapSds from family_utils.h

---

src/core/compact_object.cc
src/server/set_family_test.cc

This PR adds defragmentation logic for sets.
* add defrag logic for sets
* add small test
partially resolves #3822 [1/2]

chore: add defrag logic for sets

---

src/core/compact_object.h
src/redis/quicklist.c
src/redis/quicklist.h

Also remove unused quicklist function.
Relates to #3800

chore: extend RobjWrapper::sz_ to 2^56

---

src/server/rdb_load.cc
src/server/rdb_test.cc

Follows https://github.com/dragonflydb/dragonfly/pull/3807 and https://github.com/dragonflydb/dragonfly/pull/3823 to support loading huge lists (https://github.com/dragonflydb/dragonfly/issues/3760).
Note since lists pack 8Kb of entries per node by default, this uses a smaller segment length than the other types. Otherwise we'd only flush every 2GB (4092x8kbx64), whereas with a 512 length segment, we flush every 0.25GB.
Comparing a 5GB list with 1KB elements (`debug populate 1 test 1000 rand type list elements 5000000`):
* `main`: 3.29s / ~10GiB RSS
* `load-huge-lists` with kMaxBlobLen (4092) segment len: 2.77s / ~9GiB RSS
* `load-huge-lists` with 512 segment len: 2.21s / ~6.8GiB RSS

feat(rdb_load): add support for loading huge lists

---

src/core/dense_set.cc
src/core/dense_set.h
src/core/string_set_test.cc

Remove awkward fetch_tail case and streamline the code. Fix invalid prefetch adresses. Performance improved a little.
Before:
`BM_Fill/elements:32000     874677 ns       874647 ns         4774`
After:
`BM_Fill/elements:32000     831786 ns       831761 ns         5111`

chore: simplify CloneBatch code

---

src/core/dense_set.cc
src/core/dense_set.h

Before:
`BM_Clear/elements:32000     418763 ns       418749 ns         9965`
After:
`BM_Clear/elements:32000     323252 ns       323239 ns        12790`

chore: improve performance of ClearInternal

---

src/core/dense_set.cc
src/core/dense_set.h
src/core/string_set.cc
src/core/string_set.h
src/core/string_set_test.cc
src/server/rdb_load.cc

Clean up interface a bit. AddOrFindDense does not make much sense as a single function because it does not provide any performance benefits - we still must perform a lookup before inserting. AddSds should have been removed a long time ago.

chore: Remove DenseSet::AddOrFindDense and AddSds

---

src/core/dense_set.cc
src/core/dense_set.h
src/core/string_set.cc
src/core/string_set.h
src/core/string_set_test.cc
src/server/set_family.cc

1. Fix a performance bug in Find2 that made redundant comparisons
2. Provide a method to StringSet that adds several items in a batch
3. Use AddMany inside set_family
Before:
```
BM_Add        4253939 ns      4253713 ns          991
```
After:
```
BM_Add        3482177 ns      3482050 ns         1206
BM_AddMany    3101622 ns      3101507 ns         1360
```

chore: Implement AddMany method

---

src/core/dense_set.cc
src/core/dense_set.h
src/core/score_map.h
src/core/string_map.cc
src/core/string_map.h
src/core/string_set.h

Intended for future use - to deallocate large objects gradually. Currently nothing is changed in the functionality besides some cleanups.

chore: ClearInternal now can clear partially

---

src/server/debugcmd.cc
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/rdb_test.cc

Follows https://github.com/dragonflydb/dragonfly/pull/3850 to add support for loading huge streams (https://github.com/dragonflydb/dragonfly/issues/3760).
This loads the stream entries in partial reads, though loads the stream metadata and consumer groups in a single read (assuming consumer groups will be relatively small so don't need partial reads).
As with lists, loads streams in 512 segments as each stream node can contain 4kb of elements.
Also removes the outer `Ltrace::arr` as we now only use a single array. This means `YieldIfNeeded` is also redundant so removed.
Comparing a 5GB stream:
- `main`: 4.8s / ~13GB RSS
- `load-huge-streams`: 2.6s / ~7GB RSS

feat(rdb_load): add support for loading huge streams

---

src/server/memory_cmd.cc
src/server/rdb_load.cc
src/server/rdb_save.cc
src/server/rdb_test.cc
src/server/replica.cc
src/server/server_state.h

Sometimes for large values during snapshot loading/saving we allocate a lot of extra memory. For that, we might need to manually run `memory decommit` for `mimalloc` to release memory pages back to the OS. This PR addresses that by manually running `memory decommit` after each shard finishes loading or saving a snapshot.

chore: run memory decommit after snapshot load/save

---

src/server/acl/acl_family.cc
src/server/cluster/cluster_family.cc
src/server/memory_cmd.cc
src/server/stream_family.cc
src/server/zset_family.cc

We would like to stop passing MutableSlice as arguments and removing ToUpper is the first step to it.

chore: reduce usage of ToUpper

---

src/redis/rdb.h
src/server/rdb_load.cc

We currently support rdb files up to version `11`. This is a blocker for people who want to migrate to dragonfly with newer versions of the format. As of now, there is only `v12` and it only includes the addition of `RDB_OPCODE_SLOT_INFO`. For now this PR:
* adds support to load rdb files up to version 12
* reads and discards with a warning the contents of `RDB_OPCODE_SLOT_INFO` if found in the rdb file
addresses:  #3859

chore: allow rdb version 12

---

src/server/transaction.cc

We did not acquire any locks for transactions that are executing optimistically. However, this is problematic for callbacks that need to preempt (e.g. because a journal is active).
resolves #3841

chore: lock keys for optimistic transactions

---

src/server/channel_store.cc
tests/dragonfly/connection_test.py

This is a rare case where a closed connection is kept alive while the handling fiber yields, therefore leaving `cc_` (the connection context) pointing to null for other fibers to see.
As far as I can see, this can only happen during server shutdown, but there could be other cases that I have missed.
The test on its own does _not_ reproduce the crash, however with added `ThisFiber::SleepFor()`s I could reproduce the crash:
* Right before `DispatchBrief()` [here](https://github.com/dragonflydb/dragonfly/blob/e3214cb603fce42c8bb52a2c220c3115b7f8cecf/src/server/channel_store.cc#L154)
* Right after connection context `reset()` [here](https://github.com/dragonflydb/dragonfly/blob/2ab480e160dece516b908584f1933b25b760abfb/src/facade/dragonfly_connection.cc#L750)
In any case, calling …

fix: Do not publish to connections without context

---

src/server/server_family.cc
src/server/server_family.h

Today, some of the failures to load an RDB file passed via `--dbfilename` cause Dragonfly to terminate with an error code. This is ok and works as expected.
The problem is that the same code path is used for `DFLY LOAD`, which means that if there's an error loading the file (such as corrupted file), Dragonfly will exit instead of returning an error code to the client.
This change fixes that, by only exiting in the code path which loads on init.
Note: failure to load an RDB will have meant that the entire data store was flushed (like with `FLUSHALL`), so this is not an atomic operation.
Note to reviewer: apparently we can't call `Future::Get()` more than once, as the first call resets the state of the future and drops the previously saved value, so we use a Fiber here instead.

fix: Do not kill Dragonfly on failed `DFLY LOAD`

---

tests/dragonfly/seeder/__init__.py
tests/dragonfly/seeder/script-generate.lua
tests/dragonfly/seeder/script-genlib.lua
tests/dragonfly/seeder_test.py

Fixes #3840
Added element_size_ratio parameter to both static and dynamic seeder
data size ~ data volume, element size = data size ^ ratio, element count = data volume / element size

chore: collection size

---

tests/dragonfly/pymemcached_test.py

Disable the `test_noreply_pipeline` because it's really flaky. Will look on this once I wrap up with my pending tasks.
Issue link: https://github.com/dragonflydb/dragonfly/issues/3896

chore: skip flaky test_noreply_pipeline

---

src/server/cluster/cluster_family.cc

We're getting redundant errors logs of `outgoing_slot_migration.cc:184] ERR UNKNOWN_MIGRATION` (causing alerts)
Looks like this is expected to be ignored. `ClusterFamily::InitMigration` returns `SendError(OutgoingMigration::kUnknownMigration)`, and `OutgoingMigration::SyncFb` ignores `CheckRespIsSimpleReply(kUnknownMigration)`, which doesn't match
Therefore updating `ClusterFamily::InitMigration` to respond with a simple string `SendSimpleString(OutgoingMigration::kUnknownMigration)` instead so they match. Alternatively `ClusterFamily::InitMigration` could check for an error response (I'm not sure which side is right)?

fix(cluster): fix unknown migration error

---

src/server/dfly_main.cc

Currently, parsing `cgroups` only works for version 1. In this version, each controller has its own subfolder so for example when we want to fetch memory controller info we search for files in `/sys/fs/cgroup/memory`. However, in `cgroup version 2`, all of the controllers reside in the same folder `/sys/fs/cgroup/`. This PR add support to parse `version 2 cgroups` under the unified directory model. Furthermore, we also not parse `sys/fs/cgroup/user.slice/`
* add support for parsing cgroup version 2
* add `sys/fs/cgroup/user.slice/`
Probably resolves #3812

chrore: parse cgroup v2

---

src/core/search/indices.cc
src/core/search/indices.h
src/core/search/search.cc
src/core/search/search.h
src/core/search/search_test.cc
src/server/search/doc_index.cc
src/server/search/doc_index.h
src/server/search/search_family.cc
src/server/search/search_family_test.cc
tests/dragonfly/search_test.py

feat(search): STOPWORDS

---

src/server/engine_shard.cc
src/server/engine_shard.h
src/server/main_service.cc
src/server/server_family.cc
src/server/transaction.cc
src/server/transaction.h

Use intrusive queue that allows batching of scheduling calls instead of handling each call separately. This optimizations improves latency and throughput by 3-5%

chore: schedule chains

---

src/server/bitops_family.cc
src/server/bitops_family_test.cc

- BITPOS returns 0 for non-existent keys according to Redis's implementation.
- BITPOS allows only 0 and 1 as the bit mode argument.
NOTE: I've marked this commit as breaking change because it changes BITPOS's responses which might be used by users.
Addresses #3893

fix!: fix BITPOS command responses (#3893)

---

src/server/detail/save_stages_controller.cc
src/server/detail/snapshot_storage.cc
src/server/server_family.cc
tools/requirements.txt

The problem - we used file write in non-direct mode when writing snapshots in epoll mode. As a result - lots of data was cached into OS memory. But then during the rename operation, when we rename "xxx.dfs.tmp" into "xxx.dfs", the OS flushes the file caches and the thread is stuck in OS system call rename for a long time.
The fix - to use DIRECT mode and to avoid caching the data into OS caches at all.
Fixes #3895

fix: prevents Dragonfly from blocking in epoll during snapshotting

---

src/core/search/CMakeLists.txt
src/core/search/rax_tree.h
src/core/search/rax_tree_test.cc

Self contained RaxTreeMap that hides rax functions + allocations

chore(search): Rax TreeMap

---

src/core/allocation_tracker.cc
src/server/dfly_main.cc

Before, in order to use allocation tracker, one had to issue a `MEMORY TRACK` command. This flag is identical to that, but allows starting Dragonfly with certain ranges without issuing a command.
While here, fix a bug. Apparently, `absl::InlinedVector<>` has a bug in the implementation of `max_size()` and so in practice we did not limit the number of trackers. I switched to use `capacity()` instead, which I tested and it works well.
Notes:
1. Currently the flag always add 100% "sampling", we can extend that in the future if need be
2. I added the flag in `dfly_main.cc` with custom initialization, because it's low level, and I couldn't get it reasonably working with changes only to `allocation_tracker.cc`

chore: Add `--allocator_tracker` for default tracking

---

tests/dragonfly/pymemcached_test.py

This test is flaky because it depends on how fast the client will push the commands to dragonfly. Unfortunately, the problem here is that the CI can become slow (because we might run multiple regression tests on different branches) which will cause the assertion to fail. Since we don't really test here for regression (that would be the minimum amount of pipeline commands for X) but rather that we do actually pipeline I relaxed the constraints of the assertion to "at least have one pipelined command". This should make the test pass on cases where the CI becomes slow enough for the regression to show up.
Should resolve: #3896

chore: relax assertion in test_noreply_pipeline

---

src/server/replica.cc
tests/dragonfly/instance.py

Until now, we only tested Dragonfly against Redis 6.2.  It appears that something has changed in the way Redis sends stable sync commands, and now they also forward `MULTI` and `EXEC` as part of their replication.
Since we do not allow all commands to run under `MULTI`/`EXEC`, specifically `SELECT`, a Dragonfly replica of such servers failed these commands and became inconsistent with the data on the master.
The proposed fix is to simply ignore (i.e. not execute) `MULTI`/`EXEC` coming from a Redis/Valkey master, and run the commands within those transactions individually, like we do for other transactions.
To test this we randomly choose a redis/valkey server based on 3 available installed binaries and test against them.

fix: Support replicating Valkey and Redis 7.2

---

src/server/generic_family_test.cc
src/server/list_family_test.cc
src/server/rdb_load.cc
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/server_family.cc
tests/dragonfly/snapshot_test.py

Until now encoding of list was using ziplist encoding, which is supported by redis 6
This PR introduces encoding of list using listpack encoding by default (supported by redis 7), optionally change the encoding to ziplist encoding using flag.
This PR also fixes a bug: when serializing big entry of list it was serialized as plain node using lispack encoding therefore when loading the rdb we got error. By moving encoding all the list nodes to listpack encoding we fix this bug.

feat(server): use listpack node encoding for list

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h

ConnectionContext.reply_builder can be injected and replaced by the service logic.
before - dragonfly_connection accessed it via cc_->reply_builder in some places,
which led it to access the injected object. Moreover, EVAL commands can be offloaded
to another thread and that thread could inject the object, making the access to cc_->reply_builder_
non thread-safe.
Now dragonfly_connection copies aside the replier_builder_ pointer, and uses only this pointer for communicating with client.
Also, remove redundant arguments.

fix: dragonfly_connection should only access the original reply_builder

---

src/server/cluster/cluster_config.cc
src/server/cluster/cluster_config_test.cc
src/server/cluster/cluster_defs.cc
src/server/cluster/cluster_defs.h
src/server/cluster/cluster_family.cc

fixes: #3920
added comparison for cluster config and if the new config is equal to the previous one, we do nothing

chore: ignore applying the same cluster config twice

---

tests/dragonfly/cluster_test.py

this test is made to reproduce the problem from #3938

test: add test to reproduce a lot of memory consumtion during migration

---

src/server/command_registry.cc
src/server/command_registry.h
src/server/hset_family.cc
src/server/main_service.cc
src/server/main_service.h
src/server/server_state.cc
src/server/server_state.h

chore: remove ToUpper calls in main_service

---

src/facade/reply_builder.h
tests/dragonfly/connection_test.py

Fixes #3934 
I'll remove all of this horrbile glue in a follow up PR

chore(facade): Fix bad new IO glue

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/facade_types.h
src/facade/reply_builder.cc
src/facade/reply_builder.h
src/facade/reply_builder_test.cc
src/server/debugcmd.cc
src/server/debugcmd.h
src/server/server_family.cc

This PR introduces "DEBUG RECVSIZE ENABLE|DISABLE|tid" command that allows tracking of request sizes.

feat: track request sizes histograms

---

src/facade/reply_builder.cc
src/facade/reply_builder.h
src/server/command_registry.cc
src/server/command_registry.h
src/server/string_family.cc
src/server/string_family.h

For some of our commands we need to inject another transaction and another SinkReplyBuilder. This results into error-prone injections of temporary objects into ConnectionContext. Most commands just need Transaction and SinkReplyBuilder, so lets pass them explicitly. The final goal will be to remove Transaction and reply_builder fields from ConnectionContext.

chore: pass SinkReplyBuilder and Transaction explicitly. Part1

---

tests/dragonfly/cluster_test.py

Test takes more than 10 😱 minutes on the CI and it causes it to timeout. See https://github.com/dragonflydb/dragonfly/actions/runs/11400715614

chore: disable test_cluster_memory_consumption_migration

---

src/server/search/search_family.cc
src/server/search/search_family_test.cc

In previous versions of Dragonfly, field names in the FT.AGGREGATE command could be specified without the '@' sign. In the new version, a check was added. However, users are having issues with the new version, so we are temporarily disabling the check.

fix(search_family): Temporary remove the error when a field name does not have the '@' sign at the beginning in the FT.AGGREGATE command

---

tests/dragonfly/memory_test.py

It appears that newer versions of the gh runner require more memory. Some cases of the test `test_rss_used_mem_gap` allocate more than `6.5-7` gb of memory leaving barely `0.5gb` to the gh runner (7.5 in total available) which sometimes cause the instance to run out of memory. This produces the following two cases:
1. OOM-killer gets triggered and manages to iterate over all of the processes and kill df  (because it consumes the most memory and the process shall have the highest rank for the algorithm) `before` it runs out of memory.
2. OOM-killer gets triggered but does not manage to kill df because the system run out of memory.
Case 1. will cause the test to fail and case 2 will cause the instance to freeze. Rather unfortunate for both cases.
This PR addresses this by tuning the test, …

chore: tune test_rss_used_mem_gap

---

tests/dragonfly/replication_test.py

fixes: #3931
In this test, I simulate replication for quite big containers with different numbers of keys and different key numbers

test: add test to test big collections or collections with big values

---

tests/dragonfly/pymemcached_test.py

Test is flaky because it relies that the producer (the pytest) to send fast enough a bunch of commands before they get dispatched synchronously. I could not reproduce the failure by running the test in a loop on the same instance type as the gh runner but I increased the threshold and run it a couple of times manually without any failures.
Should resolve #3896

chore: increase load in test_noreply_pipeline

---

.github/workflows/test-fakeredis.yml
src/server/detail/wrapped_json_path.h
src/server/json_family.cc
src/server/json_family_test.cc
tests/fakeredis/test/test_json/test_json_arr_commands.py

fixes dragonflydb#3671
1. Fix the issue with the `JSON.ARRINDEX` command. It should return error for the empty result in the legacy mode
2. Temporary disable filter expression tests in the `test_json_arr_commands.py::test_arrindex`
3. Enable json fakeredis tests

chore(fakeredis): Enable JSON tests in the Fakeredis tests

---

src/server/common.h
src/server/db_slice.cc
src/server/generic_family.cc
src/server/generic_family.h

chore: pass SinkReplyBuilder and Transaction explicitly. Part2

---

src/server/generic_family.cc
tests/dragonfly/cluster_test.py

problem: crash if add keys during OOM
I've faced this situation when investigating memory consumption increasing for cluster slot migration
maxmemory default value was 8GB and the test used 9GB. The crash happened for the target node during the migration process.
fix: check the iterator before accessing the data
Also, I've updated the test to reproduce this situation easily

fix: crash if we OOM during migration process
