dragonflydb/dragonfly

src/server/journal/tx_executor.cc
src/server/main_service.cc
src/server/transaction.cc
src/server/transaction.h
tests/dragonfly/replication_test.py

fix: fix script replication

---

.github/actions/regression-tests/action.yml
src/server/replica.cc
src/server/replica.h

The bug:
exec opcode not sent to replica
The temporary fix:
execute multi commands on replica side once they are received without waiting for exec

Tmp fix replication

---

tests/dragonfly/eval_test.py

fix(pytest): Disable flaky interpreter test monitoring

---

.devcontainer/fedora/devcontainer.json
.devcontainer/ubuntu20/cmake-tools-kits.json
.devcontainer/ubuntu20/devcontainer.json
.devcontainer/ubuntu20/post-create.sh
src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_lexer.lex
src/core/json/jsonpath_test.cc

chore: parse a simple jsonpath

---

src/core/json/driver.cc
src/core/json/driver.h
src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_test.cc
src/core/json/path.h

feat: jsonpath supports index/wildcard expressions

---

.github/workflows/regression-tests.yml

fix(test): Apply pytest filter to regression tests as well

---

src/core/json/path.cc

No functional changes are made.

chore: refactor DfsItem to allow mutability semantics

---

src/core/compact_object.cc
src/core/compact_object.h
src/core/compact_object_test.cc
src/redis/object.h
src/server/list_family.cc
src/server/rdb_load.cc
src/server/set_family.cc
src/server/set_family.h
src/server/stream_family.cc

chore: remove ImportRObj routine and reduce reliance on object.c

---

src/server/transaction.cc
src/server/transaction.h

Add some stats aking to v1.14 debug branch
not sure where else to trigger detailed failure print

chore(transaction): Add debug stats for fail printing

---

.github/workflows/regression-tests.yml

test: Run slow tests in regression runs (again:)

---

tools/cluster_mgr.py

fix(cluster_mgr): Disable CPU affinity

---

src/server/replica.cc

* remove goto statements from replica.cc

refactor: remove goto statements from replica.cc

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h

fix: avoid crashing during the connection traversal

---

src/server/CMakeLists.txt
src/server/tiering/common.h
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc

feat(tiering): Introduce OpQueue and OpManager (isolated)

---

src/server/detail/save_stages_controller.cc
src/server/detail/save_stages_controller.h

fix(snapshot): Fix flag access

---

src/server/rdb_save.cc
src/server/rdb_save.h
src/server/snapshot.cc
src/server/snapshot.h

feat(server): Account for serializer's temporary buffer size

---

src/core/search/base.cc
src/core/search/base.h
src/core/search/search.cc
src/core/search/search.h
src/core/search/sort_indices.cc
src/core/search/sort_indices.h
src/server/search/aggregator.cc
src/server/search/aggregator.h
src/server/search/doc_index.cc
src/server/search/doc_index.h
src/server/search/search_family.cc
src/server/search/search_family.h
src/server/search/search_family_test.cc

Basic aggregate
* GROUPBY
* SORTBY
* LIMIT

Basic FT.AGGREGATE

---

.devcontainer/alpine/devcontainer.json
.devcontainer/fedora/devcontainer.json
.devcontainer/ubuntu22/devcontainer.json
.devcontainer/ubuntu22/post-create.sh

chore: add ubuntu22 devcontainer

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_listener.cc
src/facade/dragonfly_listener.h
src/server/engine_shard_set.h
src/server/journal/tx_executor.cc
src/server/rdb_load.cc
src/server/replica.cc

Contains suspiciously many changes from helio, but I'm on the latest main branch 🤷🏻

chore: Pull helio with new BlockingCounter

---

src/server/engine_shard_set.cc

Simplifies diff of #2708 
No functional changes, only refactoring

chore(transaction): Simplify PollExecution

---

tests/dragonfly/cluster_test.py

* disable flaky fuzzy migration test

chore: disable flaky fuzzy migration test

---

src/server/protocol_client.cc

We already have a Fiber-aware DNS resolver in Helio, so it's trivial to change and use.
I tested this end-to-end and it really resolves DNS addresses, not just localhost.
Fixes #947

chore: Use c-ares for resolving hosts in `ProtocolClient`

---

src/server/db_slice.cc
src/server/debugcmd.cc
src/server/debugcmd.h
src/server/dflycmd.cc
src/server/rdb_test.cc

Remove check-fail in ExpireIfNeeded and introduce DFLY LOAD

---

src/server/main_service.cc
src/server/server_family_test.cc

fix(transaction): nullptr access on non transactional commands

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family_test.cc

fix(cluster): Reply with correct `\n` / `\r\n` from `CLUSTER` sub cmd

---

src/server/cluster/cluster_family.cc
src/server/dflycmd.cc
src/server/dflycmd.h
src/server/server_family.cc
src/server/server_family.h
src/server/server_state.h
tests/dragonfly/cluster_test.py
tests/dragonfly/conftest.py

fix(cluster): Save replica ID per replica

---

src/facade/dragonfly_listener.cc

This will hopefully address #2737 and #2714

fix(ssl): Proper cleanup

---

src/facade/dragonfly_connection.cc
tests/dragonfly/connection_test.py
tests/dragonfly/tls_conf_test.py

chore: better error reporting when connecting to tls with plain socket

---

src/server/journal/journal.cc
src/server/journal/journal.h
src/server/journal/journal_slice.h
src/server/server_family.cc

chore: journal cleanup

---

src/server/server_family.cc
src/server/server_family.h

feat(server): Add TLS usage to /metrics and `INFO MEMORY`

---

tests/dragonfly/instance.py

* open last_log_file in append mode

chore(ci): open last_log_file in append mode

---

.github/workflows/benchmark.yml
tools/benchmark_checks.py

Create workflow to run benchmark on self hosted github runner

Benchmark runner

---

tests/dragonfly/cluster_test.py

* disable test_cluster_slot_migration because it needs refactoring -- design has changed

chore: disable test_cluster_slot_migration

---

src/server/tiering/disk_storage.cc

* replace delete with delete[]

fix: new[] delete[] missmatch in disk_storage

---

src/core/dash_internal.h
src/core/search/indices.cc
src/core/search/search.cc
src/facade/facade_types.h
src/server/bitops_family.cc
src/server/cluster/outgoing_slot_migration.h
src/server/search/doc_accessors.cc

* fix sanitizers build on clang
* clean up some warnings

fix: sanitizers clang build and clean up some warnings

---

src/server/CMakeLists.txt

also move source files to dfly_transaction target

chore(tiering): Disable compilation for MacOs

---

.github/workflows/daily-builds.yml

chore: fix daily build

---

src/core/bloom.cc
src/core/bloom.h
src/core/compact_object.cc
src/core/compact_object.h
src/core/compact_object_test.cc
src/redis/redis_aux.h
src/server/bloom_family.cc
src/server/bloom_family_test.cc
src/server/common.cc
src/server/db_slice.cc
src/server/table.cc

chore: expose SBF via compact_object

---

src/core/compact_object.cc
src/core/compact_object.h
src/server/bloom_family.cc
src/server/bloom_family.h
src/server/bloom_family_test.cc

Addresses https://github.com/dragonflydb/dragonfly/issues/1275
Still missing: persistence support.

feat: add bf.(m)add and bf.(m)exists commands

---

src/core/compact_object.cc
src/core/compact_object.h

fix: SBF memory leaks

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/cluster_shard_migration.cc
src/server/cluster/cluster_shard_migration.h
src/server/cluster/cluster_slot_migration.cc
src/server/cluster/cluster_slot_migration.h
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
src/server/journal/streamer.cc
src/server/journal/streamer.h

DFLYMIGRATE ACK is sent from a source node to a target node now

DFLYMIGRATE ACK refactoring

---

src/server/http_api.cc
tests/dragonfly/connection_test.py

fix: correct json response for errors

---

src/core/bloom.cc
src/core/bloom.h
src/core/bloom_test.cc

chore: bloom test - cover corner cases

---

.github/actions/regression-tests/action.yml
tests/dragonfly/replication_test.py

chore: Fix build by disabling the tests.

---

src/server/CMakeLists.txt
src/server/io_mgr.cc
src/server/tiering/common.h
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/disk_storage_test.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc
src/server/tiering/test_common.h

OpManager is a higher level abstraction over DiskStorage that provides:
* Tracking reads and comibing reads for the same offset
* Tracking stashes and cancelling them
* Enqueuing deletes after reads
* Running the resolve loop after reading an entry

feat(tiering): Simple OpManager

---

src/core/compact_object.cc
src/core/compact_object.h

chore: generalize CompactObject::AllocateMR

---

src/server/CMakeLists.txt
src/server/tiering/small_bins.cc
src/server/tiering/small_bins.h
src/server/tiering/small_bins_test.cc

Simplest design for small bins

feat(tiering): Simplest small bins

---

tools/docker/healthcheck.sh

fix: healthcheck for docker containers

---

src/facade/dragonfly_connection.h
src/server/dflycmd.cc

Print debug info on all connections when we get timeout on replica takeover

feat(server): add prints on takeover timeout

---

src/core/compact_object.cc
src/server/test_utils.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/op_manager.cc

feat(tiering): TieredStorageV2

---

src/core/compact_object.cc
src/core/compact_object_test.cc
src/server/rdb_extensions.h
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/rdb_test.cc

chore: serialize SBF

---

src/facade/dragonfly_connection.cc

chore: limit traffic logger only to the main interface

---

src/core/interpreter.cc
src/core/interpreter.h
src/core/interpreter_test.cc
src/server/dragonfly_test.cc
src/server/main_service.cc

chore(interpreter): Support object replies

---

src/server/cluster/cluster_family.cc
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
src/server/journal/streamer.cc
src/server/protocol_client.cc
src/server/protocol_client.h

first part of #2864. I decided to create 2 PRs to avoid conflicts with another PR

feat(cluster): add repeated ACK if an error is happened

---

README.md

chore: add a clear link on how to build dragonfly from source

---

src/core/sorted_map.cc

fix(zset): Better memory consumption calculation

---

src/server/server_family.cc

chore: add help string for memory_fiberstack_vms_bytes

---

.github/workflows/ci.yml
.github/workflows/regression-tests.yml
tests/dragonfly/instance.py
tests/dragonfly/replication_test.py

Test that ipv6 replication really works

chore: pull helio and add ipv6 replication test

---

.github/workflows/release.yml

chore: add ipv6 support for native linux release

---

src/server/common.cc
src/server/common.h
src/server/db_slice.cc
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/server_family.cc
src/server/server_family.h
src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/op_manager.h
tests/dragonfly/instance.py
tests/dragonfly/tiering_test.py

* Update GET, SET, DEL commands to use new tiering
* Add some stats

chore(tiering): Update Get, Set, Del

---

src/server/transaction.cc

Fixes use after free 😬 
Fixes #2910

fix(transaction): Use FinishHop in schedule

---

src/server/tiered_storage.h

Provide dummy implementation for MacOs

chore(tiering): Fix MacOs build

---

.github/actions/regression-tests/action.yml
tests/dragonfly/cluster_test.py

fix(test): Unflake fuzzy cluster migration test

---

src/server/bitops_family.cc
src/server/blocking_controller_test.cc
src/server/container_utils.cc
src/server/dflycmd.cc
src/server/generic_family.cc
src/server/hll_family.cc
src/server/list_family.cc
src/server/search/search_family.cc
src/server/server_family.cc
src/server/set_family.cc
src/server/stream_family.cc
src/server/string_family.cc
src/server/test_utils.cc
src/server/transaction.cc
src/server/transaction.h
src/server/zset_family.cc

chore: Remove Schedule() call

---

src/server/json_family.cc
src/server/json_family.h
src/server/json_family_test.cc
src/server/transaction.cc

chore: adjust transaction code to keystep/3 commands

---

src/server/string_family.cc
src/server/string_family.h
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/common.h
src/server/tiering/op_manager.cc
src/server/tiering/small_bins.cc
tests/dragonfly/tiering_test.py

* Introduces new tiering test
* Changes more of the string_family functions to support tiering

feat(tiering): Get, GetSet, Set test

---

src/server/blocking_controller_test.cc
src/server/channel_store.cc
src/server/cluster/cluster_family.cc
src/server/common.cc
src/server/conn_context.cc
src/server/debugcmd.cc
src/server/dflycmd.cc
src/server/main_service.cc
src/server/memory_cmd.cc
src/server/script_mgr.cc
src/server/server_family.cc
src/server/server_family.h
src/server/string_family.cc
src/server/test_utils.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc

chore: Pull helio with new future

---

src/facade/CMakeLists.txt
src/facade/dragonfly_connection.cc
src/facade/service_interface.cc
src/facade/service_interface.h
src/server/main_service.cc
src/server/main_service.h
tools/replay/main.go
tools/replay/parsing.go

Closes #2937 
Didn't yet add entry lengths

chore: Log db_index in traffic logger

---

src/server/db_slice.cc
src/server/dflycmd.cc
src/server/json_family.cc
tests/dragonfly/instance.py

1. change table_growth_margin to 0.4
2. fix info replication master side compatibility with valkey

fixes for v1.18.0

---

src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc

* Supports Modify operation for OpManager
* Exposes it to TieredStorageV2
* Adds support for tiering to APPEND
* Adds a small tests to cover cases

feat(tiering): Support append (and modifications in general)

---

src/server/tiered_storage.cc
src/server/tiered_storage_test.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/disk_storage_test.cc
src/server/tiering/io_mgr.cc
src/server/tiering/io_mgr.h
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc
src/server/tiering/test_common.h

* Use UringBuf to optionally issue prepared read/write
* Remove IoMgr functions no longer in use

feat(tiering): Registered buffers

---

src/core/overloaded.h
src/server/json_family.cc
src/server/json_family.h
src/server/json_family_test.cc

Spec https://datatracker.ietf.org/doc/html/rfc7386
Command: JSON.MERGE key path value

feat: implement json.merge

---

tests/dragonfly/instance.py

chore: remove version checks when running our regtests

---

src/server/generic_family.cc

Pass a temporary string object to extract key names more efficiently.

chore: improve performance of Scan operation

---

src/server/db_slice.cc
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/server_family.cc
src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/disk_storage_test.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc

* rename all V2 _v2 to regular
* add max_file_size limit

fix(tiering): rename v2 + max_file_size

---

src/server/tiered_storage.h

chore: fix tiering macos stub

---

src/facade/dragonfly_listener.cc
src/facade/dragonfly_listener.h
src/server/server_family.cc
src/server/server_family.h

Specifically export reached maxclient event.

chore: export listener stats

---

src/core/interpreter.cc
src/core/interpreter.h
src/server/server_family.cc
src/server/server_family.h

Stats include:
1. Interpreter count
2. Interpreter bytes
3. Time spent blocked waiting for an available interpreter

feat(lua): Add Lua stats to `INFO STATS` and `/metrics`

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/facade_test.cc
src/facade/facade_types.h
src/facade/reply_builder_test.cc
src/server/engine_shard_set.cc
src/server/server_family.cc
src/server/string_family.cc
src/server/tiered_storage_test.cc
src/server/top_keys_test.cc
src/server/version_monitor.cc
tests/dragonfly/tiering_test.py

chore: pull latest helio

---

src/server/dflycmd.cc

fix(server): lag is 0 when server not in stable state

---

.github/workflows/benchmark.yml
tools/benchmark/post_run_checks.py

Wait for 10 seconds for lag to be zero

Fix benchmark

---

src/core/compact_object.h
src/core/dash_internal.h
src/server/common.cc
src/server/common.h
src/server/engine_shard_set.cc
src/server/server_family.cc
src/server/table.cc
src/server/table.h
src/server/test_utils.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc

Simplest offloading loop, once memory budget was exceed it kicks in

feat(tiering): simple offload loop

---

src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc

feat(tiering): MGET support

---

.github/workflows/release.yml

chore: update versions and remove caching code

---

src/server/tiered_storage.h

chore: fix macos tiering

---

src/core/compact_object_test.cc
src/core/segment_allocator.cc
src/core/segment_allocator.h
src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/server/dfly_bench.cc
src/server/dfly_main.cc
src/server/dragonfly_test.cc
src/server/io_utils.cc
src/server/io_utils.h
src/server/journal/serializer.cc
src/server/journal/serializer.h
src/server/malloc_stats.cc
src/server/memory_cmd.cc
src/server/protocol_client.h
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/rdb_save.h
src/server/replica.h
src/server/tiering/disk_storage.cc

chore: update helio together with new mimalloc version

---

src/server/server_family.cc

fix: header for oom_errors_total

---

.github/workflows/ci.yml
.github/workflows/regression-tests.yml
.github/workflows/release.yml

chore: update deprecated actions

---

src/server/main_service.cc

chore: remove unneeded check-fails

---

src/server/wasm/wasm_family.cc
src/server/wasm/wasm_family.h
src/server/wasm/wasm_registry.cc
src/server/wasm/wasm_registry.h
src/wasm_sdk/README.md
src/wasm_sdk/cpp/README.md
src/wasm_sdk/cpp/examples/example.cc
src/wasm_sdk/cpp/include/dragonfly.h

* add sdk
* move loading at startup via flag

chore(wasm): add sdk and move loading wasm modules at startup via flag

---

src/facade/CMakeLists.txt
src/facade/reply_capture.h
src/facade/reply_formats.cc
src/facade/reply_formats.h
src/server/http_api.cc
src/server/main_service.cc
src/server/main_service.h
src/server/wasm/api.h
src/server/wasm/wasm_family.cc
src/server/wasm/wasm_family.h
src/server/wasm/wasm_registry.cc
src/server/wasm/wasm_registry.h
src/wasm_sdk/cpp/examples/example.cc
src/wasm_sdk/cpp/include/dragonfly.h

wasm: Calling commands

---

src/server/dflycmd.cc
src/server/server_family.cc
src/server/server_family.h
tools/local/monitoring/docker-compose.yml
tools/local/monitoring/grafana/provisioning/dashboards/dashboard.json

chore: Export replication memory stats

---

tools/local/monitoring/grafana/provisioning/dashboards/dashboard.json

Update grafana panel from deprecated "graph" to "timeseries"
fixes #3063

<chore>!: Update grafana panel 

---

tools/local/monitoring/grafana/provisioning/dashboards/dashboard.json

chore: add replication memory stats to the dashboard

---

src/wasm_sdk/go/README.md
src/wasm_sdk/go/example.go

* this is a small toy example, I didn't even create a module, but it works :)

chore(wasm): add Go SDK

---

src/server/container_utils.cc
src/server/container_utils.h
src/server/zset_family.cc

We should remove all this once we fix the bug

chore: bpop prints

---

tools/replay/main.go

chore: small replayer fixes

---

src/server/CMakeLists.txt
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_utility.cc
src/server/cluster/cluster_utility.h
src/server/cluster/incoming_slot_migration.cc
src/server/cluster/incoming_slot_migration.h
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
src/server/main_service.cc
src/server/multi_command_squasher.cc
src/server/transaction.h
tests/dragonfly/cluster_test.py

fix: fix cluster incorrect keys status

---

src/server/main_service.cc
tests/dragonfly/acl_family_test.py

fix(acl): return -NOPERM instead of response error

---

src/server/server_family.cc
src/server/server_family.h

feat(server): Expose serialization bytes via `INFO` and `/metrics`

---

src/server/stream_family.cc

Just refactoring to prepare code for optimizations
* Introudce separate function for determining if replies are relevant
* Remove some code focued on replies

chore(streams): Some refactoring

---

tools/cluster_mgr.py

feat(cluster_mgr): Allow attaching replicas

---

.github/workflows/ci.yml
src/facade/conn_context.h
src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/facade.cc
src/facade/facade_types.h
src/server/server_family.cc
tools/local/monitoring/docker-compose.yml
tools/local/monitoring/grafana/provisioning/dashboards/dashboard.json
tools/local/monitoring/prometheus/prometheus.yml

Export in /metrics
1. Total pipeline queue length
2. Total pipeline commands
3. Total pipelined duration

chore: export pipeline related metrics

---

src/server/container_utils.cc
src/server/transaction.h
src/server/zset_family.cc

chore: zset error log (from 1.18 branch)

---

src/server/cluster/outgoing_slot_migration.cc
tests/dragonfly/cluster_test.py
tests/dragonfly/utility.py

also I've done some refactoring for old tests

New test for cluster migration: connection issue

---

src/facade/dragonfly_connection.cc
src/server/common.cc
src/server/journal/journal.h
src/server/tiering/io_mgr.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h

chore: minor fixes + remove redundant DCHECK

---

src/server/cluster/cluster_family.cc
src/server/cluster/incoming_slot_migration.cc

fix: fix cluster_fuzzy_migration test

---

src/core/segment_allocator.cc
src/core/segment_allocator.h
tests/dragonfly/connection_test.py

* pull helio
* add test that covers tls deadlock

chore: pull helio add test for tls deadlock

---

tools/cluster_mgr.py

feat(cluster_mgr): Take over command

---

tools/cluster_mgr.py

feat(cluster_mgr): Fix migration action

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
tests/dragonfly/connection_test.py

chore: prevent Dispatch fiber to be launched during migration

---

src/server/CMakeLists.txt
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/server_family.cc
src/server/snapshot.cc
src/server/snapshot.h
src/server/tiered_storage.cc
src/server/tiering/external_alloc.cc
src/server/tiering/op_manager.cc
src/server/tiering/small_bins.cc
tests/dragonfly/snapshot_test.py

* Adds support for snapshotting for tiered entries

feat(tiering): Simple snapshotting

---

.github/workflows/release.yml

fix: upload action in version release

---

tests/dragonfly/cluster_mgr_test.py

test(cluster_mgr): Add tests for cluster_mgr.py

---

tests/dragonfly/connection_test.py

fix: Fix live-lock in connection test

---

src/server/cluster/cluster_defs.h
src/server/cluster/cluster_family.cc
src/server/cluster/incoming_slot_migration.cc
src/server/cluster/outgoing_slot_migration.cc

feat(cluster): Add important logs

---

src/server/cluster/cluster_config_test.cc
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/slot_set.h
tests/dragonfly/cluster_test.py

Added missed argument to the function call.
Fix flush slots functionality for migrations slots
Added tests

fix: fix bug in cluster/slot_set

---

src/core/search/indices.cc
src/core/search/indices.h
src/core/search/search.cc
src/core/search/search.h
src/core/search/search_test.cc
src/server/search/doc_index.cc
src/server/search/search_family.cc
src/server/search/search_family_test.cc
tests/dragonfly/search_test.py

feat(search): Tag field options (separator, case sensitivity)

---

src/server/conn_context.cc
src/server/conn_context.h
src/server/main_service.cc
src/server/multi_command_squasher.cc
src/server/server_family.cc

* add noloop subcommand
Partially resolves #3157

feat: add noloop subcommand in client tracking

---

.github/workflows/regression-tests.yml

* add missing option for iouring and docker

fix(ci): add missing docker option on reg tests workflow

---

src/server/command_registry.cc
src/server/json_family.cc
src/server/json_family_test.cc
src/server/string_family.cc
src/server/transaction.cc
src/server/tx_base.h
tests/dragonfly/utility.py

Fixes #2021 
* Adds JSON.MSET command
* Simplifies some code for MSET
* Fixes some bugs with JSON.MGET

feat(json): MSET

---

src/server/cluster/cluster_family.cc
src/server/cluster/incoming_slot_migration.cc
src/server/cluster/incoming_slot_migration.h
src/server/cluster/outgoing_slot_migration.h

feat: add incoming migration error processing

---

src/core/search/indices.cc
src/core/search/search.h
src/server/search/search_family.cc

chore: add parsing support for the rest of VECTOR parameters

---

src/core/search/search_parser_test.cc

chore: add a lexer test covering KNN query

---

src/core/string_set.h
src/facade/facade_types.h
src/facade/reply_builder.cc
src/facade/reply_builder.h
src/facade/reply_capture.cc
src/server/acl/acl_family.cc
src/server/acl/helpers.cc
src/server/acl/helpers.h
src/server/blocking_controller.cc
src/server/blocking_controller.h
src/server/conn_context.cc
src/server/journal/serializer.cc
src/server/journal/types.cc
src/server/json_family.cc
src/server/list_family.cc
src/server/main_service.cc
src/server/set_family.cc
src/server/transaction.cc
src/server/transaction.h
src/server/tx_base.cc
src/server/tx_base.h
src/server/zset_family.cc

Pulls iterator support from helio into the dragonfly repo. Also removes big chunk of #3154

chore: Refactor string span management

---

src/core/search/parser.y
src/core/search/query_driver.cc
src/core/search/query_driver.h

Also, warn explicitly about lack of scoring support for vector search.

chore(search): improve parser error reporting

---

src/facade/reply_builder.h
src/facade/reply_capture.cc
src/facade/reply_capture.h

fix(reply_builder): remove virtual modifier in SendError(ErrorReply) method

---

src/server/cluster/cluster_family.cc
tests/dragonfly/cluster_test.py

send config to finish migration immediately after it is DONE

test: improve cluster_fuzzy_migration test

---

tests/dragonfly/cluster_test.py

test(cluster): Make sure migration maintains TTL

---

src/server/generic_family.cc
src/server/journal/streamer.cc
src/server/journal/streamer.h
tests/dragonfly/cluster_test.py

feat(cluster): Support `STICK` bit in slot migration

---

tests/dragonfly/tiering_test.py

* Add memory usage test
* Add mixed APPEND call test

chore(tiering): More advanced tiering tests

---

tests/dragonfly/tiering_test.py

>  assert info["tiered_entries"] > 195_000  # some remain in unfilled small bins
E       assert 159610 > 195000
a bit slower than expected, give it more time

chore: fix tiering regtest test

---

src/core/search/ast_expr.cc
src/core/search/ast_expr.h
src/core/search/indices.cc
src/core/search/indices.h
src/core/search/lexer.lex
src/core/search/parser.y
src/core/search/search.cc
src/core/search/search_parser_test.cc

Adds EF_RUNTIME parameter to hnsw search

core(search): Add EF_RUNTIME parameter

---

tests/dragonfly/tiering_test.py

Let's silence it until I find the correct numbers

chore: disable tiering test

---

src/server/common.cc
src/server/common.h
src/server/debugcmd.h
src/server/server_family.cc
src/server/tiered_storage.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/small_bins.cc
src/server/tiering/small_bins_test.cc
tests/dragonfly/tiering_test.py

Also fixes small_bins deletion logic.
Fixes https://github.com/dragonflydb/dragonfly/issues/3240

chore(tiered): minor fixes + expose buffer allocation type stats

---

src/server/dfly_bench.cc

Add `-d` argument, plus output more info about the benchmark setup.

chore: improve dfly_bench

---

src/server/tiered_storage_test.cc
src/server/tiering/external_alloc.cc
src/server/tiering/external_alloc.h
src/server/tiering/external_alloc_test.cc

The intrusive free list I suggested, please review the design first.... I might have missed some detail from reading the current code that might break everything 😓

chore(tiering): External alloc free page chaining

---

.github/workflows/ci.yml
src/server/common.cc
src/server/engine_shard_set.cc

fix: total_stash_overflows statistic

---

.github/workflows/docker-release.yml
.github/workflows/reusable-container-workflow.yaml

chore: update action versions

---

tests/dragonfly/acl_family_test.py
tests/dragonfly/cluster_mgr_test.py
tests/dragonfly/cluster_test.py
tests/dragonfly/conftest.py
tests/dragonfly/connection_test.py
tests/dragonfly/generic_test.py
tests/dragonfly/memory_test.py
tests/dragonfly/redis_replication_test.py
tests/dragonfly/replication_test.py
tests/dragonfly/sentinel_test.py
tests/dragonfly/server_family_test.py
tests/dragonfly/shutdown_test.py
tests/dragonfly/snapshot_test.py

* replace all session wide df fixtures with scope

chore: replace session wide fixtures with scope

---

.github/workflows/ci.yml
src/server/cluster/cluster_defs.cc
src/server/tiered_storage.cc
src/server/tiering/small_bins.cc

chore: add more logs around the duplicate value case in small_bins

---

.github/workflows/regression-tests.yml
tests/dragonfly/conftest.py
tests/dragonfly/tiering_test.py

chore: upload all the logs from /tmp

---

src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/string_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
tests/dragonfly/snapshot_test.py

fix(tiering): Throttle snapshot load

---

src/server/dfly_bench.cc
tools/local/monitoring/docker-compose.yml

Also refactor ReceiveFB into multiple functions.
Finally, fix the memcached command in the local monitoring stack.

chore: print effective QPS of the server.

---

src/server/tiered_storage.cc
src/server/tiering/small_bins.h

chore: more debug checks around tiered storage

---

tests/dragonfly/cluster_mgr_test.py

Example failure: https://github.com/dragonflydb/dragonfly/actions/runs/9825683395/job/27126139458?pr=3277#step:12:520

chore: Disable cluster_mgr_test

---

src/server/memory_cmd.cc
src/server/transaction.cc

chore: Add 'memory arena show' command

---

src/core/compact_object.cc
src/core/compact_object.h

chore: refactor compact_object and introduce materialize method

---

src/server/acl/helpers.cc
src/server/acl/user.cc
src/server/acl/user.h
tests/dragonfly/acl_family_test.py

* fixed a bug of rehashing hashed passwords while loading plan/hashed passwords from acl file

fix(acl): loading interleaved plain and hashed passwords

---

tests/dragonfly/instance.py
tests/dragonfly/proxy.py

Also add some more logs to help debug teardown timeout issues

fix(tests): Add missing awaits

---

README.ja-JP.md
README.ko-KR.md
README.md
README.zh-CN.md

- Add more community links (Discourse forum, the new Dragonfly community page) to README.

chore: add more community links to README

---

src/server/dfly_bench.cc

chore: improve dfly_bench stats

---

src/server/dfly_bench.cc

With `--qps=0` dfly_bench will wait for the last request to be replied before sending the next one.
In addition, we add SEQUENTIAL mode that allows running requests sequentially through the keyspace.
It's not useful yet since each driver will send exactly the same sequence, but I will fix it in subsequent PRs.

chore: Add coordinated omission mode

---

src/server/cluster/outgoing_slot_migration.cc
tests/dragonfly/cluster_test.py

fix: Cancel outgoing migration when retrying / closing

---

src/core/allocation_tracker.cc
src/core/allocation_tracker.h

fix: AllocationTracker::Remove return value was reversed

---

src/server/command_registry.cc
src/server/command_registry.h
src/server/main_service.cc
src/server/server_family.cc

chore: Log connection context when issuing dangerous cmds

---

src/server/db_slice.h

* add suffix _ to members
* add dcheck in destructor

chore: small rename and add dcheck on LocalBlockingCounter

---

src/server/dfly_bench.cc

1. Moved CommandGenerator to thread scope - there is no need to maintain separate command generator per connection.
2. Added "done" metric - to know how much was done so far.

chore: fixes to dfly_bench

---

src/core/sorted_map.cc
src/core/sorted_map.h
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/snapshot.cc
src/server/snapshot.h
tests/dragonfly/replication_test.py

* disable compression when we chunk big values

chore: disable compression on big values

---

src/server/snapshot.cc

* add ConditionGuard on JournalEntry such that the stream state stays consistent

fix: protect OnJournalEntry with ConditionGuard

---

src/core/compact_object.cc
src/core/compact_object.h
src/core/cool_queue.h
src/server/common.cc
src/server/common.h
src/server/engine_shard_set.cc
src/server/engine_shard_set.h
src/server/server_family.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiering/op_manager.h

There are no changes in functionality here.

chore: small fixes around tiering

---

src/facade/redis_parser_test.cc

chore: add a test for HeapSize() function

---

tests/dragonfly/cluster_test.py

* mark cluster_fuzzymigration as skipped

chore: disable cluster_fuzzymigration

---

src/server/rdb_save.cc
src/server/rdb_save.h
src/server/snapshot.cc
src/server/snapshot.h
tests/dragonfly/instance.py
tests/dragonfly/snapshot_test.py

* default serialization_max_chunk_size to 10 mb
* add test for big values
* small rename of enum to conform style guide

chore: add mem test for big values and default the flag

---

src/server/replica.cc

* update replication_acks_interval flag to 1000

update: replication_acks_interval flag to 1000

---

src/core/compact_object.cc
src/core/compact_object.h
src/server/common.cc
src/server/common.h
src/server/debugcmd.cc
src/server/generic_family.cc
src/server/generic_family_test.cc
src/server/server_family.cc
tests/dragonfly/json_test.py

fix: Fix unsupported object type rejson-rl in RedisInsight

---

src/core/compact_object.h
src/server/db_slice.cc
src/server/snapshot.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h

Simplify tiering code by moving warmup duty to db slice

chore(tiering): Move cool entry warmup to DbSlice

---

.github/workflows/daily-builds.yml
src/server/db_slice.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
src/server/transaction.cc

Also, add debug function that prints local state if deadlocks occure.

fix: reenable macos builds

---

src/server/protocol_client.cc

chore: Don't print password to log on replica `AUTH` failure

---

src/facade/dragonfly_connection.cc
src/server/common.cc
src/server/common.h
src/server/db_slice.cc
src/server/dfly_main.cc
src/server/engine_shard_set.cc
src/server/server_family.cc
src/server/string_family.cc
src/server/string_family.h
src/server/tiered_storage.cc
src/server/tiered_storage.h
tests/dragonfly/instance.py

1. Add background offloading stats
2. remove direct_fd override - helio is already updated with default=false, so it's not needed anymore.
3. remove redundant tiered_storage_memory_margin flag

chore: Tiered fixes

---

src/core/interpreter.cc
src/core/interpreter.h
src/server/script_mgr.cc
src/server/script_mgr.h
src/server/server_state.cc
src/server/server_state.h
tests/dragonfly/eval_test.py

Adds SCRIPT GC command to invoke GC and a simple test

fix(server): Implement SCRIPT GC command

---

src/server/cluster/cluster_family.cc
tests/dragonfly/cluster_test.py
tests/dragonfly/instance.py

Basic test for #2831
quote:
> add tests for cluster with replicas, do slot migration and check data consistency

test(cluster): Migration replication test

---

.github/workflows/ci.yml
.github/workflows/regression-tests.yml
tests/dragonfly/pymemcached_test.py

chore: fix memcached pipeline test

---

src/facade/reply_builder.cc
src/facade/reply_builder_test.cc

Fixes #3449 that was introduced by #3425

fix: properly seriailize meta buffer in SendStringArrInternal

---

src/facade/cmd_arg_parser.h
src/facade/error.h
src/facade/facade.cc
src/facade/op_status.cc
src/facade/op_status.h
src/server/detail/wrapped_json_path.h
src/server/error.h
src/server/json_family.cc
src/server/json_family_test.cc

3/3 prs for the full support of the json legacy mode.
fixes #2959

feat(json_family): Add support of the JSON legacy mode

---

src/server/list_family.cc

chore(server): Remove old blocking debug

---

src/server/list_family.cc

chore(server): Use parser more in list_family

---

src/server/tiered_storage_test.cc

chore: make tiered_test more reliable

---

src/facade/reply_builder.cc
src/facade/reply_builder.h

My final result is this 300LOC file that replaces all of our current io
https://github.com/dranikpg/dragonfly/blob/new-sink-reply-builder-2/src/facade/reply_builder.cc
Enhanced almost complete SinkReplyBuilder ready for Redis/MC reply builder implementations
#3475 shows how this is used

chore(facade): Update SinkReplyBuilder2

---

tests/dragonfly/replication_test.py

chore: Download Dragonfly versions only when needed

---

src/server/dfly_bench.cc

fix: division by zero bug

---

tests/dragonfly/replication_test.py

test: fix test_scripts

---

src/facade/reply_builder.cc
src/facade/reply_builder.h

Full implementation of RESP2/RESP3 Redis Protocol on top of new sink reply builder, except small utils like verbatim which I left for another PR

chore(facade): RedisReplyBuilder2 base

---

src/facade/reply_builder.cc
src/facade/reply_builder.h

chore(facade): MCReplyBuilder2

---

src/facade/reply_builder.cc
src/facade/reply_builder.h
src/facade/reply_builder_test.cc

Extension interface with more detailed functions

chore(facade): RedisReplyBuilder2 (extensions)

---

src/server/dragonfly_test.cc
src/server/server_family.cc
src/server/server_family.h
tests/dragonfly/acl_family_test.py
tests/dragonfly/requirements.txt
tests/dragonfly/tls_conf_test.py

fixes #3476 
* fix HELLO AUTH with non default user
* add test_auth_resp3_bug
* add decode_responses=True to acl tests and refactor
* fix test_default_user_bug

fix: HELLO AUTH with non default user

---

src/server/db_slice.cc

chore: add logs to debug tiered memory failures

---

src/core/search/indices.cc
src/core/search/indices.h
src/facade/error.h
src/facade/facade.cc
src/server/search/doc_index.cc
src/server/search/doc_index.h
src/server/search/search_family.cc
src/server/search/search_family.h
src/server/search/search_family_test.cc

feat: implement FT.TAGVALS

---

.github/actions/regression-tests/action.yml
tests/dragonfly/acl_family_test.py

the test contains 2 bugs:
1) wasn't set the key pattern
2) incorrect error type for EXEC command

test: fix test_acl_deluser

---

src/server/replica.cc
src/server/replica.h
src/server/server_family.cc
src/server/server_family.h
tests/dragonfly/proxy.py
tests/dragonfly/replication_test.py

feat: Expose replica_reconnect_count for Prometheus metrics

---

src/server/cluster/cluster_family.cc
src/server/cluster/incoming_slot_migration.cc
src/server/journal/streamer.cc

fix: clang warnings

---

src/server/CMakeLists.txt
src/server/dragonfly_test.cc

* disable failing false positive

fix: disable sanitizers false positive

---

src/server/main_service.cc

chore(config): make pipeline_squash configurable

---

src/server/search/search_family.cc
src/server/search/search_family_test.cc

fix(search_family): Add error on creating indexes from non-zero databases

---

src/server/rdb_extensions.h
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/rdb_save.cc
src/server/rdb_save.h
src/server/snapshot.cc
src/server/snapshot.h
src/server/string_family.cc
src/server/string_family.h
tests/dragonfly/pymemcached_test.py
tests/dragonfly/replication_test.py
tests/dragonfly/snapshot_test.py

fix for #3134. MC_flags is uint32_t now and I added serialization and deserialization for it.

fix: MC flags size and serialization #3134

---

src/core/json/jsonpath_grammar.y
src/core/json/jsonpath_lexer.lex
src/core/json/jsonpath_test.cc
src/server/json_family_test.cc
src/server/search/search_family_test.cc

fix(jsonpath): Add JsonPath grammar for the child identifier in brackets

---

src/server/server_family.cc
src/server/server_family.h
tests/dragonfly/snapshot_test.py

feat(server_family): Add backup/restore Prometheus metrics

---

src/core/search/parser.y
src/core/search/search_parser_test.cc
src/server/search/search_family_test.cc

fix(search_family): Fix query parsing for the integer tags in OR expression

---

src/server/zset_family.cc
src/server/zset_family_test.cc

fix(server): Fix ZRANGEBYLEX limit params

---

src/server/zset_family.cc

Shadows #3566, removes duplicate code

chore(server): Unify zset boolean operations into single function

---

src/core/search/query_driver.cc

Now it needs to be enabled with vlog

chore(search): Silence query parser error

---

src/server/generic_family.cc
src/server/generic_family.h
src/server/generic_family_test.cc

feat(generic_family): Implement EXPIRETIME and PEXPIRETIME commands

---

tests/README.md
tests/dragonfly/conftest.py

chore: allow running dragonfly pytests in repeat

---

src/facade/error.h
src/facade/facade.cc
src/facade/op_status.cc
src/facade/op_status.h
src/server/json_family.cc
src/server/json_family_test.cc

fixes #3558
The problem was that the case, where the specified jsonpath does not exist, was not handled

fix(json_family): Fix json get crash due to an invalid json path

---

src/server/main_service.cc

Also order other configuration variables alphabetically.

feat: add oom_deny_ratio to mutable config

---

tests/dragonfly/replication_test.py

* skip the test because it's flaky

fix: skip test_replica_reconnections_after_network_disconnect

---

README.md

docs(readme): Fix data mistake

---

src/core/search/lexer.lex
src/core/search/parser.y
src/core/search/scanner.h
src/core/search/search_parser_test.cc

fixes https://github.com/dragonflydb/dragonfly/issues/3581

refactor: remove double conversion from str to number to str in search

---

.github/workflows/ci.yml
src/facade/conn_context.cc
src/facade/reply_builder.cc
src/facade/reply_builder.h
src/server/hset_family.cc
tests/dragonfly/instance.py

It has been running for weeks with the flag on, so enabled it also for community.

chore: enable experimental_new_io by default.

---

src/server/db_slice.cc
src/server/rdb_load.cc
src/server/rdb_load.h
src/server/replica.cc
src/server/search/doc_index.cc
src/server/search/doc_index.h
src/server/search/search_family_test.cc
src/server/server_family.cc
src/server/server_family_test.cc

fix(server_family): Remove search indexes during the FLUSHALL command

---

src/facade/acl_commands_def.h
src/facade/command_id.h
src/facade/conn_context.h
src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/facade.cc
src/server/acl/acl_family.cc
src/server/acl/acl_family.h
src/server/acl/acl_family_test.cc
src/server/acl/acl_log.h
src/server/acl/user.cc
src/server/acl/user.h
src/server/acl/user_registry.cc
src/server/acl/validator.cc
src/server/acl/validator.h
src/server/conn_context.cc
src/server/server_family.cc
tests/dragonfly/acl_family_test.py

This PR adds support for `pub/sub` ACL's. After it is merged the feature is feature complete :)
resolves #2930
* add support for pub/sub
* add tests

feat(acl): add pub/sub

---

src/server/json_family.cc

relates to [this comment](https://github.com/dragonflydb/dragonfly/pull/3597#discussion_r1735999443).
We should not use `CompactObj::memory_resource()` on the coordinator thread.

fix(json_family): Fix JsonFromString method

---

tools/local/monitoring/grafana/provisioning/dashboards/dragonfly.json

In this PR i fixed the 3 bottom panels of the dragonfly grafana dashboard which were hardcoded to a datasource that does only exist on someone elses developer machine.

fix(grafana): Fix grafana dragonfly dashboard datasource

---

.github/workflows/test-fakeredis.yml
src/facade/error.h
src/facade/facade.cc
src/facade/reply_builder.cc
tests/fakeredis/test/test_sortedset_commands.py

1. Fix html publishing code
2. Upload dragonfly logs
3. Run it on pull requests

chore: run fakeredis flow with the debug build

---

src/server/zset_family.cc

fix(bug): zinter command should run on replica

---

src/facade/dragonfly_connection.cc

chore: improve debug logs in dragonfly_connection

---

tests/dragonfly/search_test.py

test: fix search tests

---

tests/dragonfly/instance.py

* disable big value ser on reg tests

chore: disable big value ser on reg tests

---

src/server/generic_family.cc
src/server/generic_family_test.cc

fix: 'renamenx foo foo' should return 0 if foo exists

---

src/server/debugcmd.cc

* added a missing comma which fixes the printed layout

fix: debug help printed layout

---

src/server/tiering/disk_storage.cc

chore: allow disabling io_uring registered buffers

---

src/facade/cmd_arg_parser.cc
src/facade/cmd_arg_parser.h
src/facade/cmd_arg_parser_test.cc
src/server/bitops_family.cc
src/server/json_family.cc
src/server/list_family.cc
src/server/search/aggregator.cc
src/server/search/aggregator.h
src/server/search/aggregator_test.cc
src/server/search/search_family.cc
src/server/server_family.cc
src/server/string_family.cc

feat: add processing of tail args into CmdArgParser::Check
rename Switch to MapNext
add TryMapNext

CmdArgParser improvement

---

tests/dragonfly/pymemcached_test.py

fixes: #3654
The problem was that expiration has happened a little earlier than check

test: fix MC test_expiration

---

README.md
README.zh-CN.md

- Add some community suggestions to README, as advised by the team. Please let me know!

chore: add some community suggestions to README

---

src/server/script_mgr.cc

server logs: change script error to warning

---

src/server/search/search_family.cc
src/server/search/search_family_test.cc

fix(search_family): Fix LOAD option behavior in the FT.AGGREGATE command

---

src/server/rdb_save.cc
src/server/snapshot.cc

chore: adjust RdbChannel sizes

---

src/core/allocation_tracker.cc
tools/parse_allocator_tracking_logs.py

chore: add a script that parses allocator tracking logs

---

tests/dragonfly/acl_family_test.py

The failure is not related to ACL's. Python's event loop has no guarantees around the order of coroutines being rescheduled upon `await`. So it could be the case that a publisher gets stalled just enough for the subscriber to timeout and the test to fail. You can see this by observing the logs I added around the code (it won't round robin via publish and subscribe but rather the scheduler will pick different orderings each time). 
If for some reason my hypothesis here is wrong, we will have the logs I added to help us understand any other underline problem.
Hopefully should resolve: #3678

fix: test_acl_revoke_pub_sub_while_subscribed

---

src/server/cluster/cluster_defs.h
src/server/cluster/cluster_family.cc
src/server/cluster/incoming_slot_migration.h
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
tests/dragonfly/cluster_test.py

Update dflycluster slot-migration-status reply

---

src/core/string_set_test.cc

chore: add clone benchmark

---

src/facade/reply_builder.cc
src/facade/reply_builder.h

This PR https://github.com/dragonflydb/dragonfly/commit/1f36c9952dd5537fb004d408ffebc977bc4cce8b disabled the ReplyGuard.
* enable ReplyGuard
Resolves #3690

chore: enable ReplyGuard in ReplyBuilder2

---

.github/actions/regression-tests/action.yml
.github/workflows/regression-tests.yml
tests/dragonfly/snapshot_test.py

Fixes the S3 snapshot test and enables in regression tests.

tests: fix and enable s3 snapshot test

---

src/facade/reply_builder.cc
src/facade/reply_builder.h
src/server/protocol_client.cc
src/server/protocol_client.h
src/server/replica.h

chore: Remove ReqSerializer

---

src/server/stream_family.cc

small refactoring for XGROUP command code:
- Added CmdArgParser usage
- Help information was merged into one place

refactor: use CmdArgParser for XGROUP command

---

src/server/set_family.cc

Factor out reply function to smooth transtion to new io guards

chore: add SetReplies

---

tests/dragonfly/replication_test.py

chore: add missing await in test_take_over_seeder

---

src/server/stream_family.cc
src/server/transaction.h

Also did some cosmetic improvements. No functionality should be changed.

chore: refactor a lambda function into a named one

---

src/server/error.h

chore: fix return on bad status

---

src/redis/ziplist.c
src/server/rdb_load.cc

Also, reformat ziplist.c to valkey 8 formatting (no code changes besides this).

chore: add more error logs around ziplist parsing checks

---

src/server/cluster/cluster_family_test.cc
src/server/main_service.cc

fixes: #3761
fix: reject pub/sub commands as not supported

fix: mark pubusb commands as unsupported for cluster

---

tests/dragonfly/pymemcached_test.py

test: update test_noreply_pipeline to prevent false fail

---

src/server/generic_family.cc
src/server/search/search_family_test.cc

fix(generic_family): Update indexes in the RESTORE and RENAME commands

---

tests/dragonfly/snapshot_test.py

test: more stabe test_bgsave_and_save

---

src/core/string_set.cc
src/core/string_set.h
src/core/string_set_test.cc
src/server/set_family.cc

chore: Refactor AddMany

---

src/core/search/rax_tree.h

chore(search): Fix deprecated functions

---

src/server/conn_context.cc
src/server/generic_family.cc
src/server/generic_family.h
src/server/main_service.cc
src/server/server_family.cc
src/server/server_family.h
src/server/string_family.cc
src/server/string_family.h

Move privately used header code to cc files. Remove redunandant includes. No functional changes.

chore(refactoring): header clean ups

---

src/server/bitops_family.cc
src/server/debugcmd.cc
src/server/debugcmd.h
src/server/dflycmd.cc
src/server/generic_family.cc

Also remove std:: in bitops family to reduce noise. No functional changes.

chore: get rid of ToUpper call and use AsciiStrToUpper

---

src/server/common.cc
src/server/common.h
src/server/debugcmd.cc
src/server/main_service.cc
src/server/memory_cmd.cc
src/server/script_mgr.cc
src/server/server_family.cc

chore: get rid of ToUpper/ToLower mutations on arguments

---

src/server/hll_family.cc
src/server/set_family.cc
src/server/set_family.h

chore: pass SinkReplyBuilder and Transaction explicitly. Part3

---

src/server/stream_family.cc
src/server/stream_family.h

chore: pass SinkReplyBuilder and Transaction explicitly. Part8

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/main_service.cc
src/server/main_service.h

chore: pass SinkReplyBuilder and Transaction explicitly. Part9

---

tests/dragonfly/sentinel_test.py

Prevent from checking replica too early,
to avoid "Loading" exception.

fix: flaky test_failover test

---

src/facade/conn_context.cc
src/facade/conn_context.h
src/facade/dragonfly_connection.cc
src/facade/ok_main.cc
src/facade/service_interface.h
src/server/acl/acl_family.cc
src/server/cluster/cluster_family.cc
src/server/command_registry.cc
src/server/command_registry.h
src/server/conn_context.cc
src/server/conn_context.h
src/server/debugcmd.cc
src/server/generic_family.cc
src/server/http_api.cc
src/server/journal/executor.cc
src/server/main_service.cc
src/server/main_service.h
src/server/multi_command_squasher.cc
src/server/multi_command_squasher.h
src/server/rdb_load.cc
src/server/replica.cc
src/server/server_family.cc
src/server/string_family.cc
src/server/test_utils.cc
src/server/zset_family.cc

chore: pass RedisReplyBuilder explicitly from dragonfly connection

---

src/server/db_slice.cc

chore: decrease logs severity for OOM from error to warning

---

tests/dragonfly/replication_test.py

fixes: #3931
addresses comments from #3959

test: update test_big_containers

---

src/server/detail/snapshot_storage.cc
src/server/detail/snapshot_storage.h

Is done as preparation to share some of its code with GCS implementation.

chore: refactor part of s3 logic for loading a snapshot.

---

tests/dragonfly/pymemcached_test.py

chore: add retry to test_noreply_pipeline test

---

src/server/debugcmd.cc
src/server/dflycmd.cc
src/server/dflycmd.h
src/server/main_service.cc
src/server/server_family.cc
src/server/server_family.h

chore: eliminate redundant ConnectionContext arguments

---

src/server/detail/snapshot_storage.cc

feat: support GCS storage for saving/loading snapshots

---

src/facade/redis_parser.cc
src/facade/redis_parser.h

1. Eliminate redundant states
2. Eliminate redundant member variables
Added some comments. No functional changes. Preparation for #4076

chore: parser clean ups

---

src/core/qlist.cc
src/core/qlist.h
src/core/qlist_test.cc

chore: Add QList::Iterator

---

src/core/qlist.cc
src/core/qlist.h
src/core/qlist_test.cc

Also, copy the main flow for the Insert function.
It's not finished yet, hence no tests yet.

chore: implement QList::Iterate

---

src/server/search/search_family_test.cc

fix(sanitizers): disable false positive FtProfileInvalidQuery 

---

src/facade/dragonfly_connection.cc

chore: fix a potential crash during client list

---

src/server/main_service.cc

chore: fix a regression build break

---

src/server/dfly_main.cc
tests/dragonfly/instance.py

chore: log exit code of failing dragonfly in tests

---

tools/local/monitoring/grafana/provisioning/dashboards/dragonfly.json

feat(dashboard) Adjust dashboard according to #4164

adjusted grafana dashboard to be more user friendly

---

src/server/engine_shard.cc
src/server/rdb_save.cc

chore: stop periodic task earlier during the shutdown process

---

src/redis/redis_aux.c
src/redis/redis_aux.h
src/server/debugcmd.cc
src/server/dragonfly_test.cc
src/server/zset_family.cc

fix: debug object encoding names

---

.github/workflows/ci.yml
src/server/list_family.cc

chore: fully support qlist in all list_family commands

---

src/server/hset_family.cc
src/server/hset_family.h
src/server/set_family.cc
src/server/set_family.h

chore: update command interface for hset/set families

---

LICENSE.md
src/core/qlist.cc
src/core/qlist.h
src/core/qlist_test.cc

Also update license's change date.

chore: remove tail field from qlist

---

src/core/qlist.cc
src/core/qlist.h

chore: qlist code clean ups

---

src/server/generic_family.cc
src/server/generic_family.h
src/server/hll_family.cc
src/server/list_family.cc
src/server/list_family.h

chore: change the interface of hll, generic and list commands

---

src/server/main_service.cc
src/server/server_family_test.cc

fix: command docs

---

src/server/json_family.cc
src/server/json_family.h

fix: command interface for json_family

---

src/server/acl/acl_family.cc
src/server/acl/acl_family.h
src/server/hll_family.cc
src/server/stream_family.cc

chore: update command interface for acl, hll families

---

src/server/common.cc
src/server/common.h
src/server/journal/cmd_serializer.cc
src/server/journal/cmd_serializer.h
src/server/journal/streamer.cc
src/server/main_service.cc
src/server/rdb_save.cc
src/server/server_state.h
src/server/snapshot.cc

feat server: support config set serialization_max_chunk_size

---

src/core/compact_object_test.cc

fix: mismatch new-delete in unit test

---

src/CMakeLists.txt

chore: update reflex version and fix its build on alpine

---

src/server/cluster/incoming_slot_migration.cc
src/server/journal/streamer.cc
tests/dragonfly/cluster_test.py

added logs to investigate https://github.com/dragonflydb/dragonfly/issues/4289

test: update logs and test for debug purpose

---

src/server/CMakeLists.txt
src/server/detail/compressor.cc
src/server/detail/compressor.h
src/server/rdb_save.cc
src/server/rdb_save.h

chore: factor out CompressorImpl into separate files

---

tests/dragonfly/cluster_test.py

Open issue to follow up on this test - https://github.com/dragonflydb/dragonfly/issues/4180

fix (regression tests): skip flaky test

---

tests/dragonfly/cluster_test.py

chore: Disable failing test

---

tests/dragonfly/cluster_test.py

make ports dynamic for cluster tests
close task for Proxy

fix: cluster tests stability

---

src/CMakeLists.txt
src/server/detail/compressor.cc
src/server/rdb_save.cc
src/server/rdb_test.cc

fix: avoid on stack allocation of lz4 compression context

---

src/core/search/base.h
src/core/search/indices.cc
src/core/search/indices.h
src/core/search/search_test.cc
src/core/search/sort_indices.cc
src/core/search/sort_indices.h
src/server/search/doc_accessors.cc
src/server/search/doc_accessors.h
src/server/search/search_family_test.cc

fixes dragonflydb#4107, dragonflydb#4129

fix(search_family): Support boolean and nullable types in indexes

---

tests/dragonfly/replication_test.py

fix(pytest): fix failing test test_replication_timeout_on_full_sync

---

src/server/rdb_save.cc
tests/dragonfly/snapshot_test.py

feat(rdb_saver): Support big value serialization for stream

---

src/server/cluster/cluster_family.cc
src/server/cluster/outgoing_slot_migration.h

fixes: https://github.com/dragonflydb/dragonfly/issues/4364
problem: incorrect response value

fix: return value for DflyMigrateAck

---

src/server/cluster/slot_set.h

fixes: https://github.com/dragonflydb/dragonfly/issues/4358

refactor: slot_set don't use stack memory anymore

---

src/server/db_slice.cc
src/server/dfly_bench.cc
src/server/tiered_storage.cc
src/server/tiered_storage_test.cc

fix: properly clear tiered stashes upon expirations

---

src/facade/reply_builder.cc
src/facade/reply_builder.h
src/server/generic_family.cc
tests/dragonfly/memcache_meta.py

feat: support deletions with meta protocol

---

tests/dragonfly/replication_test.py
tests/dragonfly/seeder/__init__.py

This pr adds memory usage checks to pytest checking replication for big values

chore(pytest): add check for rss grow in replicaiton big values

---

tests/dragonfly/cluster_test.py

chore: Increase migration wait time in `test_cluster_migration_huge_container`

---

tests/dragonfly/cluster_test.py

test: add test migration in cache mode

---

docs/build-from-source.md
src/CMakeLists.txt
src/redis/debug.c

chore: fix build on FreeBSD

---

src/server/db_slice.cc
src/server/generic_family.cc
src/server/generic_family_test.cc

Also, provide better logs if AddOrNew function fails adding a new entry

fix: improve error propagation with RESTORE commands

---

src/server/CMakeLists.txt
src/server/rdb_test.cc
src/server/test_utils.cc

Passed successfully:
https://github.com/dragonflydb/dragonfly/actions/runs/12787491935/job/35646767241

fix(sanitizers): Set stack size to 64 KB during tests for Sanitizers

---

tools/local/monitoring/docker-compose.yml
tools/local/monitoring/grafana/provisioning/dashboards/redis.json
tools/local/monitoring/prometheus/prometheus.yml

feat(dev): allow monitoring a valkey server on localhost

---

src/server/dfly_bench.cc

chore: dfly_bench now accepts __data__ and __score__ template names

---

.github/workflows/ci.yml
src/server/detail/compressor.cc
tests/dragonfly/instance.py

`HELIO_STACK_CHECK` is deprecated. See: https://github.com/romange/helio/pull/353/files 
* remove HELIO_STACK_CHECK
* use FLAGS_fiber_safety_margin

chore: replace deprecated HELIO_STACK_CHECK

---

src/server/tiering/op_manager_test.cc

chore: OpManagerTest fixes

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/server/channel_store.cc

Make it generic and move pubsub related logic into channel_store.

chore: remove pubsub semantics from Connection::WeakRef

---

src/server/cluster/outgoing_slot_migration.cc

Fix typo in outgoing_slot_migration.cc

---

.dockerignore
.github/workflows/docker-dev-release.yml
tools/packaging/Dockerfile.alpine-dev
tools/packaging/Dockerfile.ubuntu-dev

Our previous weekly pipeline used qemu, was very slow and over-complicated.
This one uses matrix-build with proper parallelisation and the latest arm64 github runners.
now it takes less than 30 minutes to build everything.
lets make it daily.

chore: new docker build pipeline

---

src/server/rdb_test.cc
tools/packaging/debian/dragonfly.service
tools/packaging/rpm/dragonfly.spec

Also, fix the deadlock problem on shutdown on Oracle Linux 5.15 Fixes #4505

fix: rpm package setup

---

.github/workflows/epoll-regression-tests.yml

* split epoll from uring flows

chore: split epoll/uring reg test flows

---

src/core/dfly_core_test.cc
src/server/dragonfly_test.cc

Add a test covering stringmatchlen.

chore: add reflex matcher to the benchmarks

---

src/core/CMakeLists.txt
src/core/dfly_core_test.cc
src/core/glob_matcher.cc
src/core/glob_matcher.h
src/server/acl/validator.cc
src/server/channel_store.cc
src/server/common.cc
src/server/common.h
src/server/config_registry.cc
src/server/dragonfly_test.cc
src/server/generic_family.cc

Right now it's just a wrapper around stringmatchlen, so no functional changes are expected.

chore: introduce GlobMatcher

---

.github/workflows/ci.yml
src/server/tiering/common.h
src/server/tiering/op_manager.cc
src/server/tiering/op_manager_test.cc

chore: add more logs to the op_manager code

---

.github/workflows/release.yml

use arm64 platform to build arm64 instead of QEMU

chore: update release build for arm

---

src/core/qlist.cc
src/core/qlist.h
src/core/qlist_test.cc
src/server/rdb_save.cc

chore: move QList::Node definition into dragonfly codebase

---

tests/dragonfly/cluster_test.py

Fixes #4498
* pull helio
* readd epoll test_migration_one_after_another

chore: pull helio epoll fix and tests

---

tools/replay/main.go
tools/replay/workers.go

1. Provide clear usage instructions
2. Add "pace" option, which when false, sends traffic as quickly as possible (default true).
3. Add skip option that sometimes can be useful to remove unneeded noise

feat: introduce more options for traffic logger

---

docs/dashtable.md

docs: the broken link was fixed

docs: the broken link was fixed

---

src/server/dfly_main.cc

fix: ASCII logo was added #3796

fix: ascii logo was added

---

src/facade/error.h
src/facade/facade.cc
src/server/cluster/cluster_family_test.cc
src/server/cluster_support.cc
src/server/cluster_support.h
src/server/main_service.cc

fixes: #4452
problem: the CROSSSLOT error wasn't checked for MULTI/EXEC transactions
fix: added the check

fix: multi/exec CROSSSLOT error processing

---

src/core/CMakeLists.txt
src/core/zstd_test.cc

Add a zstd playground to test and play with compression techniques.

chore: add zstd_test

---

src/server/generic_family.cc
src/server/generic_family_test.cc

fix: invalid BUSYKEY response

---

src/server/generic_family.cc

chore: propagate reserve data upon restore

---

src/core/compact_object.cc
src/core/score_map.h
src/core/sorted_map.cc
src/core/sorted_map.h
src/core/sorted_map_test.cc
src/server/zset_family.cc

chore: get rid of sds in SortedMap::AddElem

---

src/facade/ok_main.cc
tests/dragonfly/connection_test.py

fix: improve test_send_delay_metric test

---

src/server/debugcmd.cc

Also, make the report a bit clearer.

chore: add listpack statistics to objhist

---

src/core/compact_object.h
src/server/tiered_storage.cc
src/server/tiering/disk_storage.cc
src/server/tiering/disk_storage.h
src/server/tiering/disk_storage_test.cc
src/server/tiering/op_manager.cc
src/server/tiering/op_manager.h
src/server/tiering/op_manager_test.cc
src/server/tiering/small_bins.cc
src/server/tiering/small_bins.h
src/server/tiering/small_bins_test.cc

Latest helio fixes the bug in DnsResolve - fixes #4244
Also, add some comments and perform minor clean ups in tiered codebase.

fix: pull latest helio

---

.github/workflows/docker-release2.yml

Also, add the missing notifications.
Fixes #4633

fix: bring back the helm step to docker release action

---

src/server/db_slice.cc

fix: do not crash upon inconsistent expire iterator

---

src/server/db_slice.cc
src/server/db_slice.h
src/server/journal/journal_slice.cc
src/server/journal/streamer.h
src/server/list_family.cc
src/server/snapshot.h
src/server/table.cc
src/server/table.h
src/server/transaction.h
src/server/tx_base.h
src/server/zset_family.cc

Adding comments plus some missing include headers. No functional changes.

chore: cluster related clean ups

---

src/server/server_family.cc

fix(metrics): add corresponding comments to command metrics

---

src/server/string_family.cc

chore: add debug printings to SetExisting

---

src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family.h
src/server/cluster/incoming_slot_migration.cc
src/server/cluster/incoming_slot_migration.h
src/server/cluster/outgoing_slot_migration.cc
src/server/cluster/outgoing_slot_migration.h
src/server/common.cc

just clean cluster code a little

refactor: clean cluster code

---

src/server/dfly_bench.cc

fix: buffer overrun in GetRandomHex

---

src/server/cluster/cluster_family.cc
tests/dragonfly/cluster_test.py

feat: allow cluster READONLY command

---

src/server/dfly_bench.cc

binary strings are supported by RESP protocol so we now generate commands using this protocol, so that we could pass binary strings.
In addition, fixed "done" metric which did not account for number of shards cluster mode.

feat: allow non-ascii values in dfly_bench

---

src/server/cluster/cluster_defs.h

problem: config is ignored if only health status is changed

Fix extended node info comparison

---

tests/dragonfly/cluster_mgr_test.py
tests/dragonfly/cluster_test.py
tests/dragonfly/replication_test.py

fix: python tests were excluded for epoll case. https://github.com/dragonflydb/dragonfly/issues/4812

fix: python tests were excluded for epoll case.

---

src/server/dfly_bench.cc

This mode is compatible with memtier_benchmark, as well as "debug populate ... SLOTS ..." We can not use it for custom commands since Dragonfly/Redis require a common hash slot for multiple keys.

feat(dfly_bench): allow generation of keys without hashslots for set/get

---

tests/dragonfly/snapshot_test.py

fix(pytest): Save into S3 temp directory

---

src/core/search/search.cc

fix: Added query to log on error

fix: Added query to log on error

---

tools/local/monitoring/grafana/provisioning/dashboards/dragonfly.json

fix: local dashboard show rapid changes in QPS

---

tests/dragonfly/connection_test.py

fixes: https://github.com/dragonflydb/dragonfly/issues/4893

fix: update timeout for connection test

---

src/server/cluster/outgoing_slot_migration.cc
src/server/journal/serializer.cc
src/server/journal/tx_executor.cc
src/server/journal/types.h
tests/dragonfly/cluster_test.py

fixes: #4834
also remove deprecated code

fix: make pause all for migration finalization

---

tests/dragonfly/cluster_mgr_test.py

test: add logs for cluster_mgr_test.py

---

src/server/cluster/cluster_defs.cc

related to: https://github.com/dragonflydb/dragonfly/issues/4541

chore: improve SlotRanges::Merge algorithm

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/facade/reply_builder.cc
src/facade/reply_builder.h
src/server/server_state.cc

The original issue is here: https://github.com/dragonflydb/dragonfly/issues/4893
- Additional logging was added.
- Dropping stale connections updated.

fix: Dropping stale connections updated

---

src/core/search/indices.cc
src/server/search/search_family_test.cc

fixed: https://github.com/dragonflydb/dragonfly/issues/4923

fix: prefix search with added synonyms fixed

---

src/server/container_utils.cc
src/server/zset_family_test.cc

fixes: https://github.com/dragonflydb/dragonfly/issues/4943

fix: ZRANGE with LIMIT parameters crash fixed

---

.github/workflows/ci.yml
.github/workflows/daily-builds.yml
src/server/db_slice.cc
src/server/dfly_main.cc
src/server/multi_command_squasher.cc

Also fix some clang and CI warnings.

fix: broken gha cache

---

src/core/search/ast_expr.h
src/core/search/base.h
src/core/search/indices.h
src/core/search/parser.y
src/core/search/search.cc
src/core/search/search_test.cc
src/core/search/sort_indices.h
src/server/search/search_family_test.cc

fixes: https://github.com/dragonflydb/dragonfly/issues/4937

feat: wildcard pattern added for fields to find all non-null values

---

src/server/main_service.cc
src/server/multi_command_squasher.cc
src/server/multi_command_squasher.h
src/server/snapshot.cc

No functionality was changed. Also fix a build error on macos.

chore: pass max_squash_size for MultiCommandSquasher via option

---

tests/dragonfly/cluster_test.py

Updated test test_readonly_replication:
1) use admin port for replication
2) added check for MOVED error when readonly replica is removed

test: add check for removing readonly replica

---

src/server/main_service.cc
src/server/multi_command_squasher.cc
src/server/server_family.cc
src/server/server_state.h

This PR make squashed commands num configurable using config set

feat (server): add flag max_squashed_cmd_num

---

src/redis/lua/struct/lua_struct.c

**Description**
This PR fixes a potential vulnerability that was cloned from Redis but did not receive the security patch. The original issue was reported and fixed under https://github.com/antirez/redis/commit/1eb08bcd4634ae42ec45e8284923ac048beaa4c3.
This PR applies the same patch to eliminate the vulnerability.
References
https://nvd.nist.gov/vuln/detail/cve-2018-11219
https://github.com/antirez/redis/commit/1eb08bcd4634ae42ec45e8284923ac048beaa4c3

fix: potential vulnerable cloned functions

---

src/server/hll_family.cc
src/server/hll_family_test.cc

fix: potential crash with multi-sharded pfmerge

---

.clang-tidy
src/facade/facade_types.h
src/server/list_family.cc
src/server/main_service.cc

chore: fix some clang-tidy warnings

---

CONTRIBUTING.md

pipx is preferable for global commands

refactor: update contributing doc

---

src/server/cluster/outgoing_slot_migration.cc

chore: add DCHECK to easier tests debugging

---

src/server/json_family.cc
src/server/json_family_test.cc

fixes: https://github.com/dragonflydb/dragonfly/issues/5025

fix: JSON.ARRPOP command crash fixed

---

src/server/dfly_bench.cc

As opposted to the cumulatative one that is shown at the end. The reason for this: if P99 went up temporarily - it does not go back easily and stays up.

chore: show moving P99 latency in dfly_bench

---

src/facade/reply_builder.cc
src/facade/reply_builder_test.cc

fixes: https://github.com/dragonflydb/dragonfly/issues/5047

fix: send response error for long sequence instead of command crash

---

src/server/dfly_bench.cc

In this flow dfly_bench only connects to the server, reproducing high connection rate scenario.

feat(dfly_bench): introduce connect only flow

---

src/core/CMakeLists.txt
src/core/dfly_core_test.cc
src/core/huff_coder.cc
src/core/huff_coder.h
src/server/debugcmd.cc

One of the building blocks for #4883

chore: introduce huffman encoder class

---

src/server/detail/save_stages_controller.cc
src/server/detail/save_stages_controller.h
src/server/server_family.cc
src/server/server_family.h

Add missing metrics: 
* rdb_bgsave_in_progress
* rdb_last_bgsave_status
resolves #5060

chore(metrics): add rdb_bgsave_in_progress and rdb_last_bgsave_status

---

src/core/dash.h
src/core/dash_bench.cc
src/core/dash_internal.h
src/core/dash_test.cc
src/server/db_slice.cc

Added types PhysicalBid and LogicalBid to help showing the meaning/context behind a bucket id.

chore: futher dash table clean ups

---

src/core/compact_object.cc

fix: remove code duplicate in GetSlice

---

src/server/dfly_bench.cc

chore: allow skipping cluster probing

---

src/core/compact_object.cc
src/core/compact_object.h
src/core/dfly_core_test.cc
src/core/huff_coder.cc
src/core/huff_coder.h

Read path and tests will follow in the next PR.
Partially addresses #4880

feat: add huffman coding to compact object

---

tests/dragonfly/cluster_test.py

test: tune test_cluster_migration_while_seeding

---

src/core/compact_object.cc
src/core/compact_object.h
src/core/compact_object_test.cc
src/redis/CMakeLists.txt
src/redis/dict.c
src/redis/redis_aux.h
src/redis/td_malloc.h
src/redis/tdigest.c
src/redis/zmalloc.c
src/redis/zmalloc.h
src/redis/zmalloc_mi.c
src/server/CMakeLists.txt
src/server/acl/acl_commands_def.h
src/server/tdigest_family.cc
src/server/tdigest_family.h

* add tdigest hist to compact object
* add sample test
* add tdigest family prototype
* fix zcalloc function prototype

chore: add tdigest to compact object

---

src/core/intrusive_string_list.h
src/core/intrusive_string_set.h
src/core/intrusive_string_set_test.cc

feat: add hash to ISLEntry

---

src/core/intrusive_string_list.h
src/core/intrusive_string_set.h

feat: add SSO for intrusive_string_set

---

src/core/intrusive_string_list.h
src/core/intrusive_string_set.h
src/core/intrusive_string_set_test.cc

Expiry fields during find

---

src/core/intrusive_string_set.h
src/core/intrusive_string_set_test.cc

Fill for IntrusiveStringSet

---

src/server/server_family.cc

chore: update module versions

---

src/core/compact_object.cc
src/core/compact_object.h
src/server/db_slice.cc
src/server/db_slice.h
src/server/debugcmd.cc
src/server/server_family.cc
src/server/server_family.h

Also add an optimization for ascii strings of sizes 17, 18

chore: provide metrics for huffman encoding

---

src/server/replica.cc
src/server/replica.h
src/server/server_family.cc

state_mask_ should not be atomic.

chore: replica clean ups

---

src/core/compact_object.cc
src/core/compact_object.h
src/core/intrusive_string_set.h
src/server/container_utils.cc
src/server/db_slice.cc
src/server/debugcmd.cc
src/server/rdb_load.cc
src/server/set_family.cc
src/server/set_family.h

RDB save code is still absent, needs to check RDB load code too

feat: Integrate IntrusiveStringSet

---

src/core/compact_object.cc
src/core/top_keys.cc
src/core/top_keys.h
src/server/CMakeLists.txt
src/server/topk_family.cc
src/server/topk_family.h
src/server/topk_family_test.cc

Implements the last topk commands (query, info, incrby) and adds tests.
* add topk.query
* add topk.info
* add topk.incrby
* add tests

chore: add topk commands and tests

---

src/core/intrusive_string_list.h
src/core/intrusive_string_set.h
src/core/intrusive_string_set_test.cc

feat: add current bucket id into hash

---

src/core/intrusive_string_list.h
src/core/intrusive_string_set.h
src/core/intrusive_string_set_test.cc

feat(intrusive_string_set): Fixed set TTL tests

---

src/core/intrusive_string_list.h
src/core/intrusive_string_set.h
src/core/intrusive_string_set_test.cc

Improve rehash

---

src/facade/redis_parser.cc

I saw `redis_parser.cc:292] Failed to parse len 69*` logs but it's hard to say whether it's a bug in dragonfly or something else.
This pr adds more logs around this case and increases the error level for this message.

chore: improve logs around the parser error

---

src/facade/CMakeLists.txt
src/facade/resp_validator.cc
tests/dragonfly/replication_test.py

feat: introduce resp validator

---

src/facade/command_id.h
src/server/geo_family.cc
src/server/geo_family.h

chore: minor fixes in geo_family

---

src/facade/cmd_arg_parser.cc
src/facade/cmd_arg_parser.h
src/server/geo_family.cc

refactor: geosearch cmd with CmdArgParser

---

src/server/geo_family.cc
src/server/geo_family_test.cc
src/server/transaction.cc

feat: add Georadius command

---

src/core/dash.h
src/core/dash_test.cc
src/server/db_slice.cc

chore: more tests around dash table

---

src/server/CMakeLists.txt
src/server/detail/snapshot_storage.cc
src/server/detail/snapshot_storage.h

chore: introduce azure snapshot storage skeleton

---

src/core/dash.h
src/core/dash_internal.h
src/core/dash_test.cc

C++ improvements around Segment class plus
small refactorings that do not change functionality.

chore: minor dash fixes

---

src/server/acl/acl_family.cc
src/server/acl/acl_family_test.cc

fix: typo in AclFamily

---

tests/dragonfly/connection_test.py

The timeout has been increased.
The potential fix for https://github.com/dragonflydb/dragonfly/issues/5251

fix: test_pubsub_unsubscribe test timeout increased

---

src/redis/listpack.c

We observed a corruption in stream code that looks like use-after-free pattern. This change introduces code that should pinpoint the place where the corruption happens by reading the first 4 bytes in the allocated listpack block. The first 4 bytes are used for storing the size argument of listpack. we check if the values there are correct and crash otherwise.
Adresses https://github.com/dragonflydb/dragonfly/issues/5255

chore: add corruption check for lpSetTotalBytes

---

src/server/dfly_bench.cc

In certain situations dfly_bench is used as a load generation function, for example testing performance while new replica is added in dftest. In this case it is useful to run dfly_bench for a long period of time while another operation is running, and then stop it once the other operation ends.
Stopping the process using sigkill etc loses information about the stats collected so far. In this change a signal handler is added such that on sigterm the driver processes stop gracefully and report stats similar to a normal run ending.

dfly_bench: Support terminating early

---

src/server/protocol_client.cc

fix(protocol_client): Check if sock_ is not null before calling class method

---

src/server/family_utils.cc
src/server/family_utils.h
src/server/stream_family.cc

This reverts commit 74524415c3f5076ac82ae182f76c3af57b6cafa1.
This is done because of the possible regression that causes #5255

Revert "fix(stream_family): Fix stream memory tracking issues (#5024)"

---

src/core/compact_object.cc
src/server/stream_family.cc
src/server/stream_family.h

This reverts commit 39a00806c96d54fd6768f3e65837600335671aff.
It's done to fix regression described in #5255

Revert "fix(stream_family): Fix memory tracking for the STREAMS (#4781)"

---

src/core/dfly_core_test.cc

chore: add another benchmark test for the GlobMatcher

---

src/server/server_family.cc

fix: fix db_capacity metrics description

---

src/server/family_utils.h
src/server/generic_family.cc
src/server/json_family.cc
src/server/search/doc_index.cc
src/server/search/doc_index.h
src/server/string_family.cc

related to [this comment ](https://github.com/dragonflydb/dragonfly/pull/5306#discussion_r2149618144)

chore(search_family): Add AddGenericDoc/RemoveGenericDoc methods

---

src/server/server_family.cc
tests/dragonfly/cluster_test.py

Add flag pause_wait_timeout to get stable migration finalization in the tests, and unskip cluster flaky tests to understand whether we have more issues or not

feat: add flag pause_wait_timeout

---

tests/dragonfly/tiering_test.py

chore(tiering_test): tune memory settings to be below 6GB

---

src/core/search/search_test.cc

Relevant to this issue: https://github.com/dragonflydb/dragonfly/issues/5347
This PR adds the benchmark for testing vector operations.

test: Vector operations benchmark was added

---

src/server/replica.cc
src/server/replica.h
src/server/server_family.cc
tests/dragonfly/replication_test.py

* rename `lsn_buffer_*` metrics to `psync_*`
* add psync attempts/successes for replica

chore: add psync metrics for replica

---

tests/dragonfly/search_benchmark_utils.py

fix: search_benchmark_utils on python 3.12

---

.github/workflows/ci.yml
src/core/search/indices.cc
src/core/search/indices.h
src/core/search/range_tree.cc
src/core/search/range_tree.h
src/core/search/search_test.cc

second PR to improve perfomance of the NumericIndex::Range method. First PR is here #5414
- numeric benchmarks added in search_test

feat(search_family): Add RangeTree to NumericIndex

---

src/server/search/doc_index.cc
src/server/search/doc_index.h
src/server/search/search_family.cc
src/server/search/search_family_test.cc
tests/dragonfly/replication_test.py

1. Add fast path for LIMIT=0
2. Remove LOAD parameter from FT.SEARCH and remove tests for it (Another PR will add proper json tests)

chore(search): LIMIT=0 Fast path and remove LOAD parameter from FT.SEARCH

---

tests/dragonfly/instance.py
tests/dragonfly/search_benchmark_test.py
tests/dragonfly/server_family_test.py

- The benchmark was moved to the class
- Init state executes once for all test cases
- One simple test was added as an example

test: search benchmark updated to use class fixture for multiple tests

---

src/facade/facade.cc
src/facade/facade_types.h
src/facade/tls_helpers.cc
src/server/server_family.cc

* add handshake statistics
* expose that in metrics

chore: add tls handshake statistics

---

src/facade/dragonfly_connection.cc
src/facade/facade.cc
src/facade/facade_types.h
src/server/cluster/cluster_family.cc
src/server/cluster/cluster_family_test.cc
src/server/db_slice.cc
src/server/debugcmd.cc
src/server/dflycmd.cc
src/server/journal/streamer.cc
src/server/main_service.cc
src/server/multi_command_squasher.cc
src/server/server_family.cc
src/server/server_state.cc
src/server/server_state.h

1. pipeline metrics regarding its depth before squashing.
2. various metrics around table memory and shard threads.

chore: add more metrics

---

src/server/script_mgr.cc

Fixes: https://github.com/dragonflydb/dragonfly/issues/5495

fix: lua_undeclared_keys_shas updated for additional sha

---

src/core/bptree_set.h
src/core/dash.h
src/core/dash_internal.h
src/core/interpreter.cc
src/core/search/block_list.cc
src/core/search/block_list.h
src/core/search/block_list_test.cc
src/core/search/compressed_sorted_set.cc
src/core/search/compressed_sorted_set.h
src/core/search/range_tree.cc
src/core/sorted_map.cc
src/facade/dragonfly_connection.cc
src/facade/redis_parser.cc
src/server/channel_store.cc
src/server/conn_context.cc
src/server/debugcmd.cc
src/server/detail/save_stages_controller.cc
src/server/engine_shard.cc
src/server/journal/journal_test.cc
src/server/json_family.cc
src/server/replica.cc
src/server/server_family.cc
src/server/snapshot.cc
src/server/stream_family.cc

* replace occurrences of size() > 0 with empty()

chore: replace size() > 0 with !empty()

---

src/server/multi_command_squasher.cc
src/server/protocol_client.cc
src/server/server_family.cc
src/server/server_state.cc
src/server/server_state.h

fix: enable keep alive on replica side of replication connections

---

src/core/search/indices.cc
src/core/search/indices.h
src/core/search/range_tree.cc
src/core/search/range_tree.h
src/core/search/search.cc

Small changes before merging second pr that should simplify logic

chore(search_family): Simplify logic for numeric indexes. FIRST PR

---

src/server/server_family.cc

Problem:
INFO commands were blocked for extended periods when SAVE operations to S3 encountered network issues. This happened because `InitResourcesAndStart()` was called while holding `save_mu_`, causing all INFO commands to wait for S3 operations to complete.
How to reproduce:
```
$ sudo tc qdisc add dev eth0 root netem delay 30000ms
$ redis-cli SAVE DF s3://some-name-used-on-aws/backup backup
```
Another terminal:
```
$ redis-cli ping
$ redis-cli info
```
Ping responds with `PONG`. The Info command hangs.
NOTE:
To reset the slowing down setting:
```
$ sudo tc qdisc del dev eth0 root
```
Solution: Move `SaveStagesController` creation and `InitResourcesAndStart()` outside of `save_mu_` scope.
This fix unblocks the INFO command, but it can't fix the long blocking behavior of saving. It …

fix: Prevent INFO command deadlock during S3 save operations

---

tools/replay/main.go

chore: measure p99.9 in the replayer

---

tools/replay/main.go

chore: add p999 metric for realtime tables as well

---

src/facade/dragonfly_connection.cc
src/facade/dragonfly_connection.h
src/server/channel_store.cc
src/server/db_slice.cc
src/server/main_service.cc
src/server/server_family.cc
tests/dragonfly/connection_test.py

feat: allow migrating client connections via CLIENT MIGRATE

---

src/core/dash_internal.h
src/core/page_usage_stats.cc
src/core/search/block_list_test.cc
src/facade/dragonfly_connection.cc
src/redis/zmalloc.h
src/redis/zmalloc_mi.c
src/server/command_registry.cc
src/server/db_slice.cc
src/server/multi_command_squasher.cc

Also, add more logs around possibly long running DragonflyConnection fiber. Finally, pulling helio fixes #5529

chore: pull helio

---

src/server/db_slice.cc

Decommit memory only under flag

chore(cluster): Decommit memory only under flag

---

.github/workflows/daily-builds.yml

Added chat notification steps for daily builds.

chore: update daily builds notifications

---

src/server/main_service.cc

Implementing the 'command info' command https://github.com/dragonflydb/dragonfly/issues/5466

feat(server): support command help command

---

src/core/linear_search_map.h

add keys method, that returns vector of keys in the map

feat(linear_search_map): Add keys method

---

src/server/geo_family.cc

Fix daily build for macOS:
https://github.com/dragonflydb/dragonfly/actions/runs/16823323839

fix: macos build geo_family.cc

---

src/facade/dragonfly_listener.cc
src/server/dflycmd.cc
src/server/server_family.cc

* do not shutdown after takeover only in full cluster mode
* print ssl version for main listener

chore: do not shutdown after takeover only in full cluster mode

---

src/server/engine_shard.cc
src/server/main_service.cc
src/server/tiered_storage.cc
src/server/tiered_storage.h
src/server/tiered_storage_test.cc
tests/dragonfly/snapshot_test.py
tests/dragonfly/tiering_test.py

* Move all memory calculations to tiered_storage
* Rename flags to tiered_offload_threshold and tiered_upload_threshold, update descriptions
* Make the settings mutable via config set

chore(tiered_storage): Rename flags, make them updatable

---

src/server/cluster/outgoing_slot_migration.cc

fixes: #5154
problem: timeout overflow, because of incorrect subtraction
fix: reorder variables

fix: timeout overflow during migration finalization

---

src/server/server_family.cc
src/server/server_family.h

Groups memory usage under `metrics dragonfly_memory_by_class_bytes`
resolves #5455

chore: group memory prometheous metrics

---

src/server/journal/streamer.cc

fixes: #5675
problem: previous fix wasn't complete, because `CVCUponInsert` can call lambda several times and we could get snapshot_version_  = 0 after ` if (snapshot_version_ == 0)` check
fix: move check into lambda

fix: check snapshot_version in correct place

---

src/server/list_family.cc
tests/dragonfly/replication_test.py

related to: #5413 
problem: LMPOP, RPOPLPUSH, LMOVE can create an undeterministic result on the replica, so they should be transformed into deterministic operations.
fix: LMPOP should be LPOP/RPOP, LMOVE and RPOPLPUSH should be a sequence of POP and PUSH operations

fix: list ops transformation during replication

---

src/external_libs.cmake

Needed to be able to pass compile/define flags.
Specifically, pass MI_STAT=1 to enable mimalloc stats aggregation.

chore: rewrite mimalloc2 external lib dependency

---

src/server/bitops_family.cc
src/server/bitops_family_test.cc

fix: bitfield no operations command

---

tests/dragonfly/cluster_test.py
tests/dragonfly/replication_test.py

This reverts commit 5b496fc5c58cb68c3cabab93cb61b9ca9f513a53.

Revert "test: unskip epoll cluster and replication tests (#5757)"

---

src/server/db_slice.cc

chore: unlink deletes hashes asynchronously

---

src/server/journal/journal_slice.cc
src/server/journal/streamer.cc

chore: tune replication/migration settings

---

src/core/allocation_tracker.cc

Fixes #4438
It was calling VLOG which internally allocated while holding a lot of resources (like a mutex), so it makes sense that it doesn't expect at all that VLOG will be called in-between.
I suggest simply to not log anything if LogMessage::Flush is in-between, not sure if that's strict enough. Should be for the mutex, but who knows that else could break with updates. (The test works now)

fix(server): Fix AllocatingTracker crash due to VLOG

---

src/server/server_family.cc

Filesystem issue is resolved, but the state is not reset. Will add a test later when I finish my io lib
Fixes #3816

fix(server): Resest global state on loading error

---

tests/dragonfly/acl_family_test.py

In test_acl_cat_commands_multi_exec_squash we set an ACL to deny set commands, and then check if subsequent set command fails. However this can fail because of time taken for the ACL setuser to propagate changes to shards, during this time a set command may succeed.
The test is changed to retry the command a fixed number of times until eventually it is denied.
fixes https://github.com/dragonflydb/dragonfly/issues/3719

pytest: Retry set until failure after ACL update

---

Makefile
src/CMakeLists.txt
src/core/search/CMakeLists.txt
src/core/search/search_test.cc
src/core/search/vector_utils.cc
src/external_libs.cmake

- Added inner product (IP) SimSIMD integration.
- Updated benchmarks.
How to reproduce test results:
```
make release-simd
cd build-release-simd
./search_test --bench
```
Tested on AWS EC2.
`c8g` gravitron4
```
...
BM_Scalar_Intensive/distance_type:0                                   344 us          344 us         2034 ops=2.034M ops_per_sec=2.90691M/s Scalar_L2_Intensive
BM_Scalar_Intensive/distance_type:1                                   365 us          365 us         1915 ops=1.915M ops_per_sec=2.73777M/s Scalar_Cosine_Intensive
BM_Scalar_Intensive/distance_type:2                                   346 us          346 us         2022 ops=2.022M ops_per_sec=2.888M/s Scalar_IP_Intensive
...
BM_SimSIMD_Intensive/distance_type:0                                 99.9 us         99.9 us …
```

feat: SimSIMD update and integration

---

src/server/dfly_main.cc

revert changes for stack size in DEBUG mode

refactor: restore stack size for debug builds

---

src/server/config_registry.cc
src/server/config_registry.h
src/server/main_service.cc
src/server/search/search_family.cc
src/server/search/search_family.h
src/server/search/search_family_test.cc

feat: add FT.CONFIG command

---

src/core/search/parser.y
src/server/search/search_family_test.cc

feat: add field prefix/suffix search
