dragonflydb/dragonfly

src/server/cluster/outgoing_slot_migration.cc
Fixes adding a delay before retrying after receiving an 'unknown migration' response. Since 'unknown migration' isn't considered an error, `last_error_` won't be set (broke in https://github.com/dragonflydb/dragonfly/pull/3899)
=> fix(cluster): fix backoff on unknown migration

src/server/bitops_family.cc, src/server/hset_family.cc, src/server/hset_family.h
=> chore: pass SinkReplyBuilder and Transaction explicitly. Part4

src/server/debugcmd.cc, src/server/debugcmd.h, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/main_service.cc, src/server/memory_cmd.cc, src/server/memory_cmd.h, src/server/server_family.cc
Specifically, remove `cntx->reply_builder` references where possible.
=> chore: reduce dependency of debug/memory commands on ConnectionContext

src/core/dense_set.cc, src/core/dense_set.h, src/core/string_map_test.cc
The interface around DenseLinkKey is confusing but SetObject works only for unwrapped objects.
Added assert to catch these issues in the future.
Fixes #3973
=> fix: properly set object with DenseLinkKey

src/core/search/rax_tree.h
The destructor of RaxTreeMap was missing causing memory leak.
Sanitizers caught it :)
=> fix(memory-leak): add missing destructor to RaxTreeMap

src/server/list_family.cc, src/server/list_family.h, src/server/zset_family.cc, src/server/zset_family.h
This PR changes list_family.
zset_family has not been changed yet - the code is just moved to the anonymous namespace.
=> chore: pass SinkReplyBuilder and Transaction explicitly. Part5

src/server/acl/acl_family.cc, src/server/acl/acl_family.h, src/server/script_mgr.cc, src/server/script_mgr.h, src/server/server_family.cc, src/server/zset_family.cc, src/server/zset_family.h
=> chore: pass SinkReplyBuilder and Transaction explicitly. Part6

src/core/dense_set.cc, src/core/string_map_test.cc
=> fix: properly set ttl bit during object replacement

src/core/search/rax_tree.h
The main problem is that `find(std::string_view key)` returns a `FindIterator` which contains the `key` that was passed as argument in the call to `find` and not the actual `key contained and allocated within rax` and is easy dangle: 
```
FindIterator res = find(std::string("some_key")); 
```
res now contains a dangling pointer because the internal string_view now points to the temporary (std::string("some_key")) which got deallocated at the end of the expression above.
The simplest solution is to make `FindIterator` own the key. (yes it does copy which is not great but it avoids dangling pointers). 
We can always optimize the copy later.
Also fixes a memory leak in the destructor: we need to iterate over all the available children in the rax tree and delete the data we allocated before …
=> fix: replace string_view with string in RaxTreeMap::FindIterator

src/server/cluster/cluster_config.cc
fixes #3964:
problem: outgoing migrations start for replica because there wasn't a check for source node ID
=> fix: prevent starting migrations from replica

src/core/search/ast_expr.cc, src/core/search/ast_expr.h, src/core/search/parser.y, src/core/search/search.cc, src/core/search/search_test.cc
Last piece: allow prefix searching with tag value
=> feat(search): Prefix search for tags

src/server/bloom_family.cc, src/server/bloom_family.h, src/server/error.h, src/server/json_family.cc, src/server/json_family.h
=> chore: pass SinkReplyBuilder and Transaction explicitly. Part7

src/core/dense_set.cc, src/core/dense_set.h, src/core/string_set_test.cc
=> fix: keep the ttl bit when dense_set grows with expiring items

src/core/search/search.cc, src/core/search/search.h, src/server/search/doc_accessors.cc, src/server/search/doc_accessors.h, src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
fixes dragonflydb#3782, dragonflydb#3659
=> fix(search_family): Fix indexes loading in the FT.SEARCH and Ft.AGGREGATE commands

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/facade.cc, src/facade/facade_types.h, src/facade/reply_builder.cc, src/server/acl/acl_family.cc, src/server/acl/acl_log.cc, src/server/config_registry.h, src/server/main_service.cc, src/server/server_family.cc, src/server/test_utils.cc
Fixes #3999 following up on discussion at #3997.
=> feat: introduce metrics/logs of when pipelining is being throttled

src/server/detail/snapshot_storage.cc, src/server/detail/snapshot_storage.h, src/server/server_family.cc
S3 and file expansion logic had some duplicate code. this PR refactors it before adding GCS support.
=> chore: refactor snapshot expanding logic

src/server/CMakeLists.txt, src/server/detail/snapshot_storage.cc, src/server/detail/snapshot_storage.h
It's not been used yet so no functional changes.
=> chore: introduce GcsSnapshotStorage

src/server/dflycmd.cc, src/server/main_service.cc, src/server/replica.cc, src/server/replica.h, src/server/search/search_family.cc, src/server/search/search_family.h, src/server/server_family.cc, src/server/server_family.h
=> chore: pass SinkReplyBuilder and Transaction explicitly. Part10

src/server/debugcmd.cc, src/server/debugcmd.h, src/server/memory_cmd.cc, src/server/memory_cmd.h, src/server/search/search_family.cc, src/server/server_family.cc, src/server/set_family.cc
Also perform additional clean-up of cntx->reply_builder() - Part11
=> fix: build break in search_family

src/core/bptree_set.h, src/core/sorted_map.cc, src/core/sorted_map.h, src/server/zset_family.cc, src/server/zset_family_test.cc
Hey, it adds WITHSCORE support to zrank/zrevrank.
I actually wrote another one version with templated RankResult and constexpr'ed ifs, but i couldn't see performance differences with a simple 'boolean and if' solution. Since the other commands implemented with the last approach I've decided to go this way.
Another change it a new method in SortedMap. It could be implemented without this invention but it helps to avoid double lookup in the 'score_map'. The method returns std::pair which doesn't have self-explanatory fields with its 'first' and 'second'  but I've hesitated to add a new struct for this purpose.
=> feat(zset_family): support WITHSCORE in zrevrank/zrank commands (#3921)

src/server/engine_shard.cc, src/server/main_service.cc
Increase verbosity levels of uring_proactor if deadlock was detected in debug mode. Also allow optionally to disable periodic fiber, which sometimes helps during the debugging.
=> chore: improve verbosity logging during shutdown

src/server/search/search_family_test.cc
The test fails because of false positive so I disabled it.
=> chore: skip AggregateWithLoadOptionHard on sanitizers (false positive)

tests/dragonfly/pymemcached_test.py
=> chore: print info stats if test_noreply_pipeline fails

src/facade/reply_builder.cc, src/server/detail/save_stages_controller.cc, src/server/detail/save_stages_controller.h, src/server/detail/snapshot_storage.cc, src/server/detail/snapshot_storage.h, src/server/server_family.cc
Not everything is supported but manual load save is supported.
1. Run dragonfly with `--dir gs://bucket/path`
2. In redis-cli: a. SET foo bar b. SAVE DF gsdump c. DFLY LOAD gs://bucket/path/gsdump-summary.dfs
=> chore: support load/save from GCS

src/server/journal/streamer.cc, src/server/journal/streamer.h, tests/dragonfly/cluster_test.py
fixes: #3938
the problem was that we did throttling after bucker serialization, now the throttling is done after every entry if needed
=> fix: reduce memory consumption during migration

src/server/engine_shard.cc, src/server/engine_shard.h, src/server/transaction.cc
=> chore: add tx queue head debug info in AnalyzeTxQueue

src/core/dense_set.cc, src/core/dense_set.h, src/core/score_map.cc, src/core/string_map.cc
We did not properly defrag all links in a chain. This PR adds this.
* add defrag for all nodes in a link chain
=> chore(DenseSet): defrag all links in a chain

src/core/bptree_set.h, src/core/bptree_set_test.cc, src/core/score_map.cc, src/core/sorted_map.cc
`ReallocIfNeeded` deleted and reinserted the same key in the `BPTree` stored in `SortedMap`. This is not really needed since the key is actually the same and we can just update the pointer within `BPTree` instead of doing the deletion + insertion chore.
Resolves #3963
=> chore: add ForceUpdate to BPTree

src/facade/conn_context.h, src/facade/dragonfly_connection.cc, src/server/conn_context.cc, src/server/conn_context.h, src/server/debugcmd.cc, src/server/journal/executor.cc, src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/rdb_load.cc, src/server/test_utils.cc
Also, deprecate `reply_builder()` access method.
Finally, remove reply builder injection as its not needed anymore - we always pass this object via stack.
=> chore: pass reply_builder explicitly to pubsub module

src/server/detail/save_stages_controller.cc, src/server/detail/save_stages_controller.h, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/snapshot.cc, src/server/snapshot.h, tests/dragonfly/snapshot_test.py
=> feat(server): dont use channel for replication / save df

src/core/CMakeLists.txt, src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc, src/core/sorted_map_test.cc, src/redis/quicklist.h
This class will consolidate list functionality across multiple layers, and eventually replace the original quicklist code. Right now we added the skeleton files and defined most of the interface. The implementation is not done yet.
=> chore: add QList class

src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc
The code is copied from quicklist.c
=> chore: add push functionality to QList class

src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc
=> Add index based iterator to QList interface

src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc
Also add a basic test for this
=> chore: implement QList::Insert function

src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc
Also add a parametrized test covering fill/compress options.
Fix a compression bug introduced when copying the code.
Introduce move c'tor/operator.
=> chore: implement QList::Erase functionality

src/core/compact_object.cc, src/core/compact_object.h, src/server/list_family.cc, src/server/rdb_save.cc, src/server/set_family.cc
The feature is guarded by list_experimental_v2 flag, which is disabled.
=> chore: Add initial bindings for QList in list_family

src/server/common.cc, src/server/common.h, src/server/conn_context.cc, src/server/conn_context.h, src/server/main_service.cc, src/server/multi_test.cc, src/server/script_mgr.cc, src/server/script_mgr.h, src/server/server_family.cc, src/server/transaction.cc
fix #4071 
2 bugs found in the flow:
1. we did not use the interperter borrowed in the script load command before running the multi transaction
2. we call InitByArgs for each command in multi transaction. in this flow Transaction::shard_data_ must not be resized to 1. (see comment here - https://github.com/dragonflydb/dragonfly/blob/f8b3fa0d7bf1d95674f80eef826ffd66f5a57659/src/server/transaction.cc#L343) When calling script load we resized it to 1 leading to the crash.
=> fix(server): handle running script load inside multi

src/facade/conn_context.cc, src/facade/dragonfly_connection.cc, src/facade/facade.cc, src/facade/facade_types.h, src/facade/reply_builder.cc, src/facade/reply_builder.h, src/facade/reply_builder_test.cc, src/facade/reply_capture.cc, src/facade/reply_capture.h, src/server/debugcmd.cc, src/server/generic_family.cc, src/server/hset_family.cc, src/server/http_api.cc, src/server/json_family.cc, src/server/list_family.cc, src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/protocol_client.cc, src/server/search/search_family.cc, src/server/server_family.cc, src/server/set_family.cc, src/server/string_family.cc
Remove old IO
* Remove SinkReplyBuilder, RedisReplyBuilder, MCReplyBuilder, replace them with new __2 version
* Remove MGetResponse and SendScoredArray 
* Simplify to use new small interface
* CaptruingReplyBuilder
* HttpReplyBuilder
* InterpreterReplier
=> chore: remove old io

src/core/qlist.cc, src/core/qlist.h, src/server/list_family.cc
=> chore: Implement list Pop/Erase functionality with QList

src/server/blocking_controller_test.cc, src/server/cluster/cluster_family.cc, src/server/cluster/cluster_utility.cc, src/server/cluster/outgoing_slot_migration.cc, src/server/common.cc, src/server/common.h, src/server/detail/save_stages_controller.cc, src/server/dflycmd.cc, src/server/dragonfly_test.cc, src/server/engine_shard.cc, src/server/engine_shard_set.cc, src/server/journal/executor.cc, src/server/list_family_test.cc, src/server/main_service.cc, src/server/namespaces.cc, src/server/namespaces.h, src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/replica.cc, src/server/server_family.cc, src/server/test_utils.cc, src/server/test_utils.h
Before the namespaces object was defined globally. However it has non-trivial d'tor that is being called after main exits. It's quite dangerous to have global non-POD objects being defined globally. For example, if we used LOG(INFO) inside the Clear function , that would crash dragonfly on exit.
Ths PR changes it to be a global pointer.
=> chore: change Namespaces to be a global pointer

docs/build-from-source.md
added zlib1g-dev into "build from source" instruction
=> fix: update instruction how to build from the source for ubuntu

tests/dragonfly/pymemcached_test.py
Fixes #3896. Now we retry several times.
In my checks this should significantly reduce the failure probability.
=> fix: test_noreply_pipeline flakiness

src/server/list_family.cc, src/server/list_family_test.cc
All tests in list_family_test besides LTrim pass.
=> chore: Implement LMOVE over QList

src/core/search/base.cc, src/core/search/base.h, src/core/search/indices.cc, src/core/search/indices.h, src/core/search/search.cc, src/core/search/search.h, src/core/search/search_test.cc, src/core/search/sort_indices.cc, src/core/search/sort_indices.h, src/core/search/vector_utils.cc, src/core/search/vector_utils.h, src/server/search/doc_accessors.cc, src/server/search/doc_accessors.h, src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family_test.cc
=> fix(search_family): Process wrong field types in indexes for the FT.SEARCH and FT.AGGREGATE commands

src/facade/conn_context.cc, src/facade/conn_context.h, src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/dragonfly_listener.h, src/facade/facade.cc, src/facade/facade_types.h, src/facade/ok_main.cc, src/facade/reply_builder.h, src/facade/service_interface.h, src/server/acl/acl_family.cc, src/server/acl/acl_family.h, src/server/conn_context.cc, src/server/conn_context.h, src/server/main_service.cc, src/server/main_service.h, src/server/replica.cc, src/server/string_family.cc, src/server/test_utils.cc
=> chore: decouple reply_builder from ConnectionContext

src/core/qlist.cc, src/server/container_utils.cc, src/server/rdb_load.cc
generic_family_test and rdb_test pass with qlist enabled.
=> chore: support rdb loading and container utils with QList.

src/core/dash.h, src/core/dash_test.cc, src/server/snapshot.cc, src/server/snapshot.h
This PR introduces new api to dash table TraversingBuckets which traveses table by physical buckets
when creating a snapshot we now call this api. The snapshot correctness stays and there are less calls to Serialize bucket callback as it is called only once per bucket and not on every slot
=> feat(server) : snapshot traverse physical buckets

src/facade/reply_builder.cc, src/server/string_family.cc
#3953 removed `SendMGetResponse` and we ended up calling Send() when `sink_` is `nullptr` which had no effect because the vec was empty.
=> fix: skip Send() in SinkReplyBuilder::Flush() when vec is empty

src/server/main_service.cc, tests/dragonfly/connection_test.py
The regression was caused by #3947 and it causes crashes in bullmq. It has not been found till now because python client sends commands in uppercase. Fixes #4113
=> fix: regression in squashing code when determining eval commands

tests/dragonfly/replication_test.py, tests/dragonfly/snapshot_test.py
We have a few *very* slow tests on the CI. Specifically: 
```
241.30s call     dragonfly/replication_test.py::test_replication_all[df_factory0-mode0-8-t_replicas8-seeder_config8-50000-True]
240.80s call     dragonfly/replication_test.py::test_replication_all[df_factory0-mode0-8-t_replicas7-seeder_config7-50000-False]
239.92s call     dragonfly/replication_test.py::test_replication_all[df_factory0-mode1-8-t_replicas7-seeder_config7-50000-False]
236.87s call     dragonfly/replication_test.py::test_replication_all[df_factory0-mode1-8-t_replicas8-seeder_config8-50000-True]
178.18s call     dragonfly/snapshot_test.py::test_big_value_serialization_memory_limit[HSET-df_factory0]
175.97s call     dragonfly/snapshot_test.py::test_big_value_serialization_memory_limit[SADD-df_factory0]
175.79s call …
```
=> fix: slow CI tests

tests/dragonfly/cluster_test.py
=> test: add test for snapshoting during migration

src/facade/dragonfly_connection.cc
This is a rare condition, which we know can happen during shutdown (see [here](https://github.com/dragonflydb/dragonfly/pull/3873#issue-2568503374))
Hopefully fixes #3776 but we couldn't reproduce it to make sure.
=> fix: Do not use `cc_` in connection if it's null

src/server/cluster/cluster_defs.cc, src/server/cluster/cluster_defs.h, src/server/list_family.cc, src/server/main_service.cc, src/server/zset_family.cc
**The problem:**
When in cluster mode, `MOVED` replies (which are arguably not even errors) are aggregated per slot-id + remote host, and displayed in `# Errorstats` as such. For example, in a server that does _not_ own 8k slots, we will aggregate 8k different errors, and their counts (in memory).
This slows down all `INFO` replies, takes a lot of memory, and also makes `INFO` replies very long.
**The fix:**
Use `type` `MOVED` for moved replies, making them all the same under `# Errorstats`
Fixes #4118
=> fix: Use `MOVED` error type for moved replies

src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h
When running multi command squasher not all commands are actually getting squashed due to some constrains in the squasher. Therefor to correctly count the number of squashed commnads now we return the actuall number of squashed
=> fix server: fix stats of pipeline squashed commands

src/core/qlist.cc, src/core/qlist_test.cc
The blob allocation had invalid size and the value has never been copied.
=> chore: fix plain node insertion

src/facade/dragonfly_connection.cc, src/facade/facade.cc, src/facade/facade_types.h, src/server/common.h, src/server/server_family.cc, src/server/server_family.h
Info command may have a large latency when returning all the sections.
But often a single section is required. Specifically,
SERVER and REPLICATION sections are often fetched by clients
or management components.
This PR:
1. Removes any hops for "INFO SERVER" command.
2. Removes some redundant stats.
3. Prints latency stats around GetMetrics command if it took to much.
=> chore: optimize info command

src/server/main_service.cc
The bug:
slow invocations where not written to slowlog 
The fix:
extract the relevant connection pointer from context on squashing
=> fix server: fix write to slowlog on squashing flow

src/server/cluster/outgoing_slot_migration.cc
problem: the migration process can get stuck because of the pause between migration finalization attempts for  https://github.com/dragonflydb/dragonfly/pull/4081
fix: try reading the correct ACK response several times until timeout happens
=> fix: migration ACK response processing

src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, src/server/server_family.cc
part of the #4002
added INFO memory field "commnads_squashing_replies_bytes" to show the current consumption for replies of squashing commands
=> feat: add INFO memory section for squashing replies memory consuming

src/server/db_slice.cc, src/server/generic_family.cc, src/server/journal/executor.cc, src/server/main_service.cc, tests/dragonfly/replication_test.py
=> fix: allow SELECT in multi/exec if it's a noop

src/facade/error.h, src/facade/facade.cc, src/server/main_service.cc, src/server/rdb_load.cc
1. Now error stats show "restrict_denied" instead of "Cannot execute restricted command ..." error.
2. Increased verbosity level when loading a key with expired timestamp.
3. pulled helio with better logs coverage of tls_socket.cc code.
=> chore: tune logs and improve restrict denied error

src/server/multi_command_squasher.cc, src/server/server_family.cc
address comments from https://github.com/dragonflydb/dragonfly/pull/4147
=> fix: UB during cmd squashing reply size calculation

src/redis/rdb.h, src/server/detail/snapshot_storage.cc, src/server/detail/snapshot_storage.h, src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/rdb_test.cc, src/server/server_family.cc, tests/dragonfly/replication_test.py, tests/dragonfly/utility.py
Prevent loading snapshots with used memory higher than max memory limit.
1. Store the used memory metadata only inside the summary file
2. Load the summary file before loading anything else, and if the used-memory is higher, abort the load.
=> fix: enforce load limits when loading snapshot

src/server/journal/executor.cc
Fixes #4150. The failure can be reproduced with high probability on ARM via `pytest dragonfly/replication_test.py -k test_replication_all[df_factory0-mode0-8-t_replicas3-seeder_config3-2000-False]`
Not sure why this barrier is needed but #4146 removes the barrier which breaks a gentle balance in the code in unexpected way.
=> fix: test_replication_all failure

src/server/debugcmd.cc, src/server/generic_family.cc, src/server/rdb_load.cc, src/server/rdb_load.h, tests/dragonfly/cluster_test.py, tests/dragonfly/generic_test.py
We have an internal utility tool that we use to deserialize values in some use cases:
* `RESTORE`
* Cluster slot migration
* `RENAME`, if the source and target shards are different
We [recently](https://github.com/dragonflydb/dragonfly/issues/3760) changed this area of the code, which caused this regression as it only handled RDB / replication streams.
Fixes #4143
=> fix: Huge entries fail to load outside RDB / replication

src/core/compact_object.cc, src/core/compact_object.h, src/core/qlist.cc, src/core/qlist.h, src/server/dfly_main.cc, src/server/dragonfly_test.cc, src/server/memory_cmd.cc
Specifically fixes "MEMORY USAGE" for lists.
The  `mi_collect` call may actually fix #3776  At least in my tests it stopped crashing.
=> chore: allow slow and precise memory measurement of an object

src/core/dense_set.cc, src/core/dense_set.h, src/core/score_map.cc, src/core/string_map.cc
reverts #4019 because:
1. `DefragStrMap2` calls `ReallocIfNeeded()` on each `StringMap::iterator` and the traversal also includes all of the elements of a all `links`.  This TraverseApply just adds extra iterations, if the `iterator` passed is `link`.
2. Suspect to cause the crash/regrssion in #4167
I am still not sure if `TraverseApply` actually causes the crash described in (2)
=> fix: remove DenseSet::IteratorBase::TraverseApply

src/server/dfly_main.cc, src/server/main_service.cc, tests/dragonfly/conftest.py, tests/dragonfly/instance.py
1. Better logging in regtests
2. Release resources in dfly_main in more controlled manner.
3. Switch to ignoring signals when unregister signal handlers during the shutdown.
Fixes #3776, hopefully the last time.
=> chore: fix shutdown sequence in Dragonfly server

src/server/command_registry.cc, src/server/command_registry.h, src/server/conn_context.h, src/server/main_service.cc, src/server/main_service.h, src/server/multi_test.cc, src/server/test_utils.cc, src/server/transaction.cc
Fixes https://github.com/dragonflydb/dragonfly/issues/3880 and https://github.com/dragonflydb/dragonfly/issues/3879
=> feat(server): add eval_ro and evalsha_ro

src/server/cluster/cluster_family.cc, tests/dragonfly/cluster_test.py
Part of #4173 (see for context)
This fixes:
* `CLUSTER NODES`
* `CLUSTER SHARDS`
* `CLUSTER SLOTS`
But only for emulated cluster mode. @romange - should we also handle real cluster (in a future PR)?
=> chore: Hide replicas from `CLUSTER` subcmds in managed mode

tools/packaging/debian/dragonfly.logrotate
If multiple logs are being rotated and one of them fails (due to exit 1), the other logs that follow won't be rotated either, unless logrotate is run again.
If you want to prevent the rotation of a specific log file and not affect the rest of the logs, you'll want to handle the condition properly to ensure that logrotate doesn't abort due to the failure of the prerotate script.
To prevent the rotation of a specific log file without causing issues for other logs, you can use exit 0 to prevent rotation cleanly or design your prerotate script to handle conditions carefully.
=> fix(tools): Prevent dragonfly.logrotate from stopping logrotate service

src/facade/dragonfly_connection.cc, src/facade/redis_parser.cc, src/facade/redis_parser_test.cc
The long-term goal is to make the parser to consume the whole input when
it returns INPUT_PENDING. It requires several baby step PRs.
This PR:
1. Adds more invariant checks
2. Avoids calling RedisParser::Parse with an empty buffer.
3. In bulk string parsing - remove redundant "optimization" of rejecting partial strings of less than 32 bytes,
in other words consume small parts as well. The unit test adjusted accordingly.
=> chore: more parser improvements

src/core/search/search.cc, src/core/search/search.h, src/core/string_or_view.h, src/server/search/doc_accessors.cc, src/server/search/doc_accessors.h, src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
=> fix(search_family): Fix LOAD fields parsing in the FT.AGGREGATE and FT.SEARCH commands

src/server/CMakeLists.txt, src/server/container_utils.cc, src/server/container_utils.h, src/server/journal/cmd_serializer.cc, src/server/journal/cmd_serializer.h, src/server/journal/streamer.cc, src/server/journal/streamer.h, tests/dragonfly/cluster_test.py
Before this PR we used `RESTORE` commands for transferring data between source and target nodes in cluster slots migration.
While this _works_, it has a side effect of consuming 2x memory for huge values (i.e. if a single key's value takes 10gb, serializing it will take 20gb or even 30gb).
With this PR we break down huge keys into multiple commands (`RPUSH`, `HSET`, etc), respecting the existing `--serialization_max_chunk_size` flag.
Note that we still use `RESTORE` serialization for small values and for some data types which are not (yet?) supported.
Part of #4100
=> feat: Huge values breakdown in cluster migration

src/server/cluster/cluster_family.cc, src/server/cluster/cluster_family.h, src/server/cluster/incoming_slot_migration.cc, src/server/cluster/incoming_slot_migration.h, src/server/cluster/outgoing_slot_migration.cc, src/server/cluster/outgoing_slot_migration.h, src/server/debugcmd.cc, src/server/debugcmd.h, src/server/journal/streamer.cc, src/server/journal/streamer.h, src/server/main_service.cc, src/server/main_service.h, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/cluster_test.py, tests/dragonfly/instance.py
fixes: #4080
added test for #3247 but it is flaky so it is skipped for now
=> feat: cluster migrations restarts if timeout happens

src/server/string_family.cc
In case of duplicate mget keys, skips fetching the same key twice. The optimization is straighforward - we just copy the response for the original key, since the response is a shallow object, we potentially save lots of memory with this deduplication.
=> fix: deduplicate mget response

.github/workflows/regression-tests.yml, tests/dragonfly/requirements.txt
Should work only for self-hosted runners.
The core files will be kept in /var/crash/
We also copy automatically dragonfly binary into /var/crash to be able to debug later.
=> chore: produce core files in regtests

src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc, src/server/debugcmd.cc, src/server/list_family_test.cc
1. Reduce code duplication.
2. Expose qlist node count via "debug object"
3. Add more tests to qlist_test
4. Fix a bug in QList::Erase
=> chore: qlist improvements

src/server/search/search_family.cc, src/server/search/search_family_test.cc
=> fix(search_family): Fix crash when no SEPARATOR is specified in the FT.CREATE command

tests/dragonfly/cluster_mgr_test.py, tools/cluster_mgr.py
problem: unclosed connection prevents correct cluster node close for cluster_mgr_test.py
fix: I've found a couple of places where we didn't close clients correctly, and @chakaz  told me that we should use 127.0.0.1 instead of localhost
=> fix: cluster_mgr script

src/server/dflycmd.cc, src/server/dflycmd.h, src/server/snapshot.cc
The bug:
In case of socket error inside StopFullSyncInThread we would overide the cleanup function in StartStableSyncInThread as we will call it even if the StopFullSyncInThread failed, causing the reset of saver not in his shard thread
The fix:
return error status from StopFullSyncInThread and incase of error dont call StartStableSyncInThread
=> bug(replication): snapshot cleanup fix in transition to stable sync

src/server/journal/streamer.cc, tests/dragonfly/cluster_test.py
=> test: fix and unskip test_migration_timeout_on_sync

src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc
Also fix a typo bug in NodeAllowMerge.
=> chore: Add more qlist tests

src/server/common.h, src/server/dflycmd.cc, src/server/server_family.cc, src/server/server_family.h, src/server/stream_family.cc, src/server/stream_family.h, src/server/string_family.h
=> chore: change the interface of stream and server commands

src/server/main_service.cc
=> chore: add noop docs subcmd

src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc, src/server/list_family.cc
After running `debug POPULATE 100 list 100 rand type list elements 10000` with `--list_experimental_v2=false`:
```
type_used_memory_list:16512800
used_memory:105573120
```
When running with `--list_experimental_v2=true`:
```
used_memory:105573120
type_used_memory_list:103601700
```
TODO: does not yet handle compressed entries correctly but we do not enable compression by default.
Fixes #3800
=> chore: Track QList memory

src/core/qlist.cc, src/server/debugcmd.cc
=> chore: support qlist compression when accounting for memory

src/server/bitops_family.cc, src/server/bloom_family.cc, src/server/bloom_family.h, src/server/generic_family.h, src/server/zset_family.cc, src/server/zset_family.h
=> chore: update command interface for bitops, bloom, zset families

src/facade/facade_test.h, src/redis/t_stream.c, src/server/stream_family.cc, src/server/stream_family_test.cc
1. Memory leak in streamGetEdgeID 
2. Addresses CVE-2022-31144   (fixes https://github.com/dragonflydb/dragonfly/issues/3830)
3. Fixes XAUTOCLAIM bugs and adds tests.
4. Limits the count argument in XAUTOCLAIM command to 2^18 (CVE-2022-35951)
=> fix: bugs in stream code

src/server/cluster/outgoing_slot_migration.cc, src/server/container_utils.cc, src/server/journal/streamer.cc, src/server/multi_command_squasher.cc, tests/dragonfly/cluster_test.py
There are actually a few failures fixed in this PR, only one of which is a test bug:
* `db_slice_->Traverse()` can yield, causing `fiber_cancelled_`'s value to change
* When a migration is cancelled, it may never finish `WaitForInflightToComplete()` because it has `in_flight_bytes_` that will never reach destination due to the cancellation
* `IterateMap()` with numeric key/values overrode the key's buffer with the value's buffer
Fixes #4207
=> fix: Fix `test_network_disconnect_during_migration` test

src/server/rdb_test.cc
problem: RdbTest.LoadStream3 used incorrect file
fix: change file name to correct
Also, I've moved RdbTest.SnapshotTooBig to the end of the file to check the reproducibility of #4215, because it tests OOM error and I don't have other ideas for now
=> fix: RdbTest.LoadStream3 incorrect file usage

src/server/cluster/cluster_family.cc, src/server/main_service.cc, tests/dragonfly/cluster_test.py
So far we only handled emulated cluster. This PR adds real cluster support.
Related to #4173
=> chore: Hide replica info in real cluster if `--managed_service_info`

src/server/cluster/cluster_family.cc, src/server/server_family.cc
Specifically:
* `INFO REPLICATION` does not list the replicas, but does still show `connected_slaves`
* `INFO SERVER` does not show `thread_count` and `os`
Fixes #4173
=> chore: Hide managed service info in `INFO`

src/core/interpreter.cc, src/core/interpreter.h, tests/dragonfly/memory_test.py
The bug:
calling lua_error does not return, instead it unwinds the Lua call stack until an error handler is found or the
script exits. This lead to memory leak on object that should release memory in destructor.
Specific example is the absl::FixedArray<string_view, 4> args(argc); which allocates on heap if argc > 4. The free was not called leading to memory leak.
The fix:
Add scoping to RedisGenericCommand and call RaiseError which calls lua_error after goto after destructors are called
=> fix(server): fix memory leak on lua error

src/server/db_slice.cc, src/server/db_slice.h, src/server/generic_family.cc, src/server/tx_base.cc, src/server/tx_base.h, tests/dragonfly/cluster_test.py
* add FiberGuard to RecordExpiry for non-preemptive flows
=> chore: split RecordExpiry preemptive and non-preemptive flows

src/server/cluster/outgoing_slot_migration.cc, src/server/common.h, src/server/dflycmd.cc, src/server/journal/journal_test.cc, src/server/journal/pending_buf.h, src/server/journal/streamer.cc, src/server/journal/streamer.h, tests/dragonfly/cluster_test.py
=> refactor: remove redundant allocations for streamer

src/server/detail/save_stages_controller.cc
Fixes creating local directories when `--dir` is a cloud path (eg S3)
Before, if the path was `s3://my-bucket/my-snapshots/`, we'd create directories `s3:/my-bucket/my-snapshots` locally (which were unused). Which was both messy and led to permissions issues if Dragonfly didn't have permission to create those directories
=> fix(save): don't create dirs for cloud dir

src/server/zset_family.cc
Most `GEO` commands don't seem to support case insensitive units, so seemed simplest to move `AsciiStrToUpper` into `ExtractUnit`
Such as `GEOSEARCH Sicily FROMLONLAT 15 37 BYRADIUS 200 km ASC` (copied from redis docs) would return an error `(error) ERR unsupported unit provided. please use M, KM, FT, MI`
=> fix(geo): support case insensitive units

tests/dragonfly/cluster_test.py
We have cascading failures in cluster tests because on assertion failures the nodes are not properly cleaned up and subsequent test cases that use the same ports fail. I added a monotonically increasing port generator to mitigate this effect.
P.s. we `should` also take care how we clean up cluster nodes but I will leave that for a future PR.
=> chore: monotonically increasing ports for cluster tests

tests/dragonfly/memory_test.py
The test fails when it checks the gap between `used_memory` and `object_used_memory`, by assuming that all used memory is consumed by the `type` it `DEBUG POPULATE`s with.
This assumption is wrong, because there are other overheads, for example the dash table and string keys.
The test failed for types `STRING` and `LIST` because they used a larger number of keys as part of the test parameters, which added a larger overhead.
I fixed the parameters such that all types use the same number of keys, and also the same number of elements, modifying only the element sizes (except for `STRING` which doesn't have sub-elements) so that the overall `min_rss` requirement of 3.5gb still passes.
Fixes #3723
=> chore: Fix `test_rss_used_mem_gap` for all types

src/server/main_service.cc
=> fix: prohibit read commands during takeover

src/server/journal/streamer.cc
The bug:
Dash table traverse function assumes that the cb does not preempts
the traverse applies the cb on each slot of the logical bucket.
In our flow the registered cb WriteBucket can preempt and therefore after preempting the assertion for iterating each slot of the bucket is triggered
F20241208 21:35:59.052592 21717 init.cc:25] [../src/core/dash_internal.h:1587]: assert(BucketIndex(hfun(bucket->key[slot])) == bid) failed!
the bug was discovered in the following regression run
https://github.com/dragonflydb/dragonfly/actions/runs/12225241118/job/34098992760
The fix:
We lately introduced an new dash table function TraveseBucket that iterate on physical bucket and it applies the cb on the bucket only once. It is used in snapshoting now to support big value serialization wich can preempt …
=> fix cluster: migration traverse bug

src/server/engine_shard.cc, tests/dragonfly/memory_test.py
This PR disables the eviction due to rss over limit
The problem with current eviction logic when rss is above the rss threshold is that we evict to many keys to reduce the rss usage.
In the test that I changed now we just debug populate a little bit higher than rss max memory threshold
If you run the test you can see that the eviction kicks in but continues for long time as we evict items but rss does not decrease
in this test we create 754974 keys and eventually get to evict 307100 keys to just drop 200MB of rss memory, while the the total rss memory is 4G.
So we are evicting so many items to get below the rss threshold (decrease 200MB), and this is because deleting items does not immediately decrease rss but only when defrag logic kicks in and starts to defragment the memory and calls …
=> fix(server) : dont apply eviction on rss over limit

src/server/command_registry.cc, src/server/command_registry.h, src/server/main_service.cc, src/server/main_service.h
Clean up command_registry interface as well.
=> chore: update command interface for main_service commands

src/facade/facade_test.h, src/server/rdb_extensions.h, src/server/rdb_load.cc, src/server/rdb_load.h, src/server/rdb_save.cc, src/server/rdb_test.cc
Now rdb_load supports RDB_TYPE_STREAM_LISTPACKS, RDB_TYPE_STREAM_LISTPACKS_2 and RDB_TYPE_STREAM_LISTPACKS_3 formats.
rdb_save still saves with RDB_TYPE_STREAM_LISTPACKS format - we want to release the DF version that can load everything first, and
then update the replicaion format in the next versions.
Also, update rdb_test.cc
`active-time` is not supported yet, will be added in the next PR.
=> fix: support loading of 7.x streams correctly

src/server/stream_family.cc, src/server/stream_family_test.cc, src/server/transaction.cc
Partiall addresses https://github.com/dragonflydb/dragonfly/issues/4193
=> chore: fixes the parse error for xread/xreadgroup with unbalanced ids

src/core/compact_object.cc, src/core/compact_object_test.cc
That'd be a total waste of time and energy, not to mention you'll crash.
Fixes #4167
=> fix: Do not attempt to defrag `StringSet` as a `StringMap`

src/redis/stream.h, src/redis/t_stream.c, src/server/family_utils.cc, src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/stream_family.cc, src/server/stream_family_test.cc
Adjust XINFO command to output active-time property. Store active-time and switch to RDB_TYPE_STREAM_LISTPACKS_3 if FLAGS_stream_rdb_encode_v2 is enabled.
=> chore: add active time to stream consumers

src/server/search/aggregator.cc, src/server/search/aggregator.h, src/server/search/aggregator_test.cc, src/server/search/search_family.cc, src/server/search/search_family_test.cc
fixes dragonflydb#4230
First PR for complete support of the SORTBY option (#3631)
To see examples please check the issue.
Add code that checks, during aggregate steps, what fields should be printed.
=> fix(search_family): Remove the output of extra fields in the FT.AGGREGATE command

src/server/cluster/incoming_slot_migration.cc, src/server/cluster/outgoing_slot_migration.cc, tests/dragonfly/cluster_test.py
fixes: #4289
It looks like 2 seconds isn't enough to finalize the migration process. I've also improved the logs.
=> fix: increase cluster migration default timeout

src/core/qlist.cc, src/core/qlist_test.cc, tests/dragonfly/seeder/script-genlib.lua
=> fix: circular dependency in qlist

src/server/cluster/incoming_slot_migration.cc, src/server/cluster/outgoing_slot_migration.cc, src/server/main_service.cc
fixes: #4299
we decided to distinguish connection and finalization timeouts and introduced the new flag
=> feat: add migration_finalization_timeout_ms flag

src/server/db_slice.cc
=> fix: Protect `BumpUp()` from running in parallel to serialization

src/server/search/search_family.cc, src/server/search/search_family_test.cc
Fixes FT.AGGREGATE output for fields that are not present in the document
=> fix(search_family): Fix FT.AGGREGATE output

src/facade/redis_parser.cc, src/facade/redis_parser.h, src/facade/redis_parser_test.cc
1. Separate argument type parsing from argument parsing itself.
2. Handle strings of length 1.
This is done in preparation of improving the parser contract - so that when it returns INPUT_PENDING, it consumes the entire input.
=> chore: improve parser state machine

src/server/dragonfly_test.cc, src/server/server_family.cc, tests/dragonfly/acl_family_test.py
=> server: report redis version 7.2.0 to support Sidekiq

src/server/CMakeLists.txt, src/server/detail/decompress.cc, src/server/detail/decompress.h, src/server/error.cc, src/server/error.h, src/server/rdb_load.cc, src/server/rdb_load.h
rdb_load.cc is huge and contains many auxillary classes. This PR moves DecompressImpl and ErrorRdb code into detail/
It also fixes minor bugs around error conditions with de-compression: a. Do not check-fail on invalid opcode and return error_code instead. b. Print correctly LZ4 errors.
=> chore: factor out rdb_load utilities into separate files

tests/dragonfly/utility.py
This was a subtle and minor bug. Nice catch Borys!
=> fix: Remove hardcoded `@assert_eventually` 100 times retry

tests/dragonfly/cluster_test.py
remove serialization_max_chunk_size for cluster tests 
discussed in #4278
=> refactor: remove serialization_max_chunk_size for cluster tests

src/server/dflycmd.cc, src/server/server_family.cc
`ListenerInterface::TraverseConnectionsOnThread` sometimes calls `ThisFiber::SleepFor(1us)`, so we can't call it under `shard_set->pool()->AwaitBrief()`
=> fix: Do not preempt on dispatcher fiber

tests/dragonfly/seeder_test.py
Seeder in contrary to StaticSeeder does not guarantee the final size of a container because it uses modification actions which can add or remove items from the container once we enter more than half of key target keys
Therefore we can not use the check_list to see that the list size is 1 when we run seeder with collection_size=1
=> fix(test): seeder test remove check

src/facade/dragonfly_connection.cc, tests/dragonfly/connection_test.py
Before: if socket data arrived in small bits, then CheckForHttpProto would grow io_buf_ capacity exponentially with each iteration. For example, test_match_http test easily causes OOM.
This PR ensures that there is always a buffer available - but it grows linearly with the input size. Currently, the total input in CheckForHttpProto is limited to 1024.
=> fix: potential OOM when first request sent in small bits

src/server/rdb_save.cc
problem: we try to get the memory info during replication start, but the snapshot object doesn't exist yet
=> fix: crash during getting info about replication

src/facade/reply_builder.cc, src/facade/reply_builder.h, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/connection_test.py
Add send_delay_seconds/send_delay_ms metrics.
=> chore: add ability to track connections stuck at send

src/server/db_slice.h, src/server/generic_family.cc
In some rare cases we reach inconsistent state inside OpRestore where a key already exists, though it should not. In that case log the error instead of crashing the server. In addition, we update the existing entry to the latest restored value.
=> fix: do not check-fail in OpRestore

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h
Replace dispatch with async because we already have dispatch fiber in proactor code.
=> chore: fix wording around the dispatch fiber in dragonfly_connection

tests/dragonfly/instance.py
The problem:
if calling stop for one of the instances raise and exception we did not call stop for the rest
=> fix(pytest): call stop for all instances even if stop raise exception

src/server/main_service.cc, src/server/server_family.cc, tools/local/monitoring/docker-compose.yml
Also, update the local stack to use prometheus 3.0
Finally, hex-escape arguments when logging an error for a command.
Fixes #4277
=> fix: add content-type for metrics response

src/core/interpreter.cc, src/server/rdb_save.cc, src/server/rdb_test.cc, src/server/server_family.cc, src/server/server_state.cc, src/server/server_state.h, src/server/snapshot.cc, tests/dragonfly/instance.py, tests/dragonfly/replication_test.py, tests/dragonfly/seeder/__init__.py, tests/dragonfly/seeder/script-generate.lua, tests/dragonfly/seeder/script-genlib.lua, tests/dragonfly/seeder_test.py
Changes in this PR:
1. Fix bug in snapshot serialization that caused us not to do compression at all
2. Enable compression if big value serialization is enabled (flag max_serialization_chunk_size !=0)
3. Change dragonfly rand string lua call to generate more compressible string.
4. Add statistics to compression and check stats in tests
5. Simplify the seeder for generating big values. Instead of defining keys as keys of big value, define the total number of entries of big values when running seeder.
=> fix(server): use compression for non big values

src/server/cluster/cluster_config.cc
It's fine to use the heap in such cases, latency doesn't matter.
=> fix: Stack overflow in `DFLYCLUSTER CONFIG`

src/server/search/search_family.cc
We should print the warning every 30 seconds to avoid flooding the server logs
=> fix(search_family): Fix logging in ParseFieldWithAtSign

tests/dragonfly/cluster_test.py
fixes: https://github.com/dragonflydb/dragonfly/issues/4344
small changes that close resources correctly and help debug the test if it fails again
=> fix: test_network_disconnect_during_migration

src/server/detail/save_stages_controller.cc, src/server/dflycmd.cc, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/snapshot.cc, src/server/snapshot.h
fixes #4218
1. Move the two lambdas in `SliceSnapshot` to the `SnapshotDataConsumerInterface`.
2. Apply minor syntax fixes in the `RdbSaver` class.
Also, it makes sense to store the `Context*` pointer directly within the `RdbSaver` class instead of passing it to methods like `StartSnapshotInShard`, `StartIncrementalSnapshotInShard`, and `SaveBody`
=> refactor(rdb_saver): Add SnapshotDataConsumer to SliceSnapshot

src/core/search/rax_tree.h, src/redis/rax.c, src/redis/rax.h
related to [this comment](https://github.com/dragonflydb/dragonfly/pull/4228#issuecomment-2514645979)
=> chore(rax_tree): Introduce raxFreeWithCallback call in RaxTreeMap destructor

src/server/search/aggregator.cc, src/server/search/aggregator.h, src/server/search/aggregator_test.cc, src/server/search/doc_index.h, src/server/search/search_family.cc
related to this [comment](https://github.com/dragonflydb/dragonfly/pull/4231#discussion_r1864173422)
1. Add `Aggregator` class.
2. Remove redundant `std::string` copies entirely during the aggregation steps.
TODO:
1. Add logs
2. Remove the usage of `std::function`
=> refactor(search_family): Add Aggregator class

.github/workflows/ci.yml, .github/workflows/regression-tests.yml, src/facade/dragonfly_connection.cc, src/server/dfly_main.cc, src/server/snapshot.cc, src/server/transaction.cc, tools/local/gen-test-certs.sh
1. Run CI/Regression tests with HELIO_STACK_CHECK=4096.
This will crash if a fiber stack usage goes below this limit.
2. <s> Increase shard queue stack size to 64KB </s>
3. Increase fiber stack size to 40KB on Debug builds.
4. Updated helio has some changes around the TLS socket code.
In addition we add a helper script to generate self-signed certificates helpful for local development work.
=> chore: update helio and improve our stack overflow resiliency

src/core/compact_object.cc, src/core/compact_object_test.cc, src/core/json/json_object.h, src/server/cluster/cluster_config.cc, src/server/json_family.cc, src/server/json_family_test.cc, src/server/search/doc_accessors.cc, src/server/test_utils.cc
The problem: apparently, jsoncons uses strtod by default when parsing doubles. On some platforms (alpine/musl) this function uses lots of stack, which potentially can lead to stack corruption. This PR configures jsoncons to use std::from_chars that is more efficient and less stack hungry. The single include point to consume jsoncons/json.hpp should be "core/json_object.h"
=> fix: configure jsonconst double parser to use std::from_chars

src/server/search/aggregator.cc, src/server/search/aggregator.h, src/server/search/aggregator_test.cc, src/server/search/search_family.cc, src/server/search/search_family_test.cc
fixes #3631
Second PR for complete support of the SORTBY option. Please review first #4231
=> fix(search_family): Support multiple fields in SORTBY option in the FT.AGGREGATE command. SECOND PR

src/facade/dragonfly_connection.cc, src/facade/memcache_parser.cc, src/facade/memcache_parser.h, src/facade/memcache_parser_test.cc, tests/dragonfly/memcache_meta.py, tests/dragonfly/pymemcached_test.py, tests/dragonfly/requirements.txt
This is a stripped down version of supporting the memcache meta requests.
a. Not all meta flags are supported, but TTL, flags, arithmetics are supported. b. does not include reply support.
c. does not include new semantics that are not part of the older, ascii protocol.
The parser interface has not changed significantly, and the meta commands are emulated using the old, high level commands like ADD,REPLACE, INCR etc.
See https://raw.githubusercontent.com/memcached/memcached/refs/heads/master/doc/protocol.txt for more details regarding the meta commands spec.
=> feat: add support for meta memcache commands

src/facade/dragonfly_connection.cc, src/facade/memcache_parser.cc, src/facade/memcache_parser.h, src/facade/reply_builder.cc, src/facade/reply_builder.h, src/server/main_service.cc, src/server/string_family.cc, tests/dragonfly/memcache_meta.py, tests/dragonfly/pymemcached_test.py
=> feat: support memcache meta responses

src/server/dragonfly_test.cc, src/server/rdb_load.cc, src/server/stream_family.cc, src/server/stream_family.h, tests/dragonfly/memory_test.py
fixes: https://github.com/dragonflydb/dragonfly/issues/4321
problem: we didn't calculate stream memory usage during snapshot loading
=> fix: stream memory counting durin snapshot loading

src/server/cluster/incoming_slot_migration.cc, src/server/journal/tx_executor.cc, src/server/journal/tx_executor.h, src/server/journal/types.h, src/server/replica.cc, src/server/string_family.cc, src/server/transaction.cc, src/server/transaction.h
As we no longer use shard sync execution in replica, we dont need to the shard_cnt in journal.
In this PR:
1. ignore the value of shard_count from journal record in replica
2. stop journal NOOP from master side if the cb failed 
3. Unrelated to shard sync execution cleanup we no need to call TriggerJournalWriteToSink for NO_AUTOJOURNAL commands as we already do allow flush to sync from callback (changed here https://github.com/dragonflydb/dragonfly/pull/3945)
=> chore(server): cleanup replication shard sync execution

tests/dragonfly/cluster_test.py
fixes: https://github.com/dragonflydb/dragonfly/issues/4344
problem: we waited up to 10 seconds for the migration to be restarted but the default timeout for migration restart was 30 seconds
=> test: fix test_network_disconnect_during_migration

tests/dragonfly/snapshot_test.py
The issue was that the `upper_limit` value was set too low. Additionally, a sleep was added after the `DEBUG POPULATE` command to ensure that the RSS memory accurately reflects the entire dataset.
=> fix(snapshot_test): Fix test_big_value_serialization_memory_limit after adding streams support

src/core/extent_tree.cc, src/core/extent_tree_test.cc, src/server/tiering/external_alloc.cc, src/server/tiering/external_alloc_test.cc
ExternalAllocator allocates large sizes directly from the extent tree bypassing segment data structure. Unfortunately, we forgot to align Free() the same way. This PR:
1. Make sure that we add back the allocated range to the extent tree in Free.
2. Rewrite and simplify ExtentTree::Add implementation.
=> fix: ExternalAllocator::Free with large sizes

src/server/debugcmd.cc, tests/dragonfly/memory_test.py, tests/dragonfly/snapshot_test.py
fixes: #4124 
The reason for memory increase in debug populate relies in the fact that the batch on number of keys and not number of elements
The fix:
batch on max elements with max 5 elements at a time
=> fix(server): debug populate consume less memory

src/server/transaction.cc, src/server/transaction.h
When replicating we should not log journal change if the command execution failed.
This bug was introduced in a cleanup for replication code https://github.com/dragonflydb/dragonfly/commit/22994cf3b7b9134adcd384a44c6dd712d67f1b73
also fixes #4179
=> fix(replication): do not log to journal on callback fail

src/core/compact_object.cc, src/core/compact_object_test.cc, src/core/dense_set.cc, src/core/dense_set.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/engine_shard.cc, src/server/generic_family.cc, src/server/generic_family.h, src/server/hset_family.cc, src/server/json_family.cc, src/server/list_family.cc, src/server/set_family.cc, src/server/zset_family.cc
Done as a preparation to introduce asynchronous deletions for sets/zsets/hmaps.
1. Restrict the interface around DbSlice::Del. Now it requires for the iterator to be valid and the checks should
be explicit before the call. Most callers already provides a valid iterator.
2. Some minor refactoring in compact_object_test.
3. Expose DenseSet::ClearStep to allow iterative deletions of elements.
=> chore: minor refactorings around dense_set deletions

src/server/cluster/cluster_family.cc, src/server/db_slice.cc, src/server/db_slice.h, src/server/dflycmd.cc, src/server/engine_shard.cc, src/server/generic_family.cc, src/server/journal/journal.cc, src/server/journal/journal.h, src/server/journal/journal_slice.cc, src/server/journal/journal_slice.h, src/server/journal/streamer.cc, src/server/transaction.cc, src/server/transaction.h, src/server/tx_base.cc, src/server/tx_base.h
In this refactor we remove allow_await param from Journal::RecordEntry funciton
Instead the logic to allow await is configured with new function SetFlushToSink.
In every flow that does not allow preemtion instead for calling RecordEntry with allow_await = false
we call SetFlushToSink(false) and at the end SetFlushToSink(true)
=> feat(server): refactor allow preempt on journal record

src/server/rdb_load.cc, tests/dragonfly/cluster_test.py
fixes: https://github.com/dragonflydb/dragonfly/issues/4357
=> fix: allow cluster node load snapshot bigger than maxmemory

.github/actions/regression-tests/action.yml
This change introduces timeout of 5 minutes per test case.
The idea is to make sure that we do not enter by mistake very slow test cases.
In the flow of test timeout the logs are also copied and uploaded so if we have a deadlock bug in specific test we will have the logs
=> chore(pytest): add timeout per test

src/facade/reply_builder.cc, src/facade/reply_builder.h, src/facade/reply_builder_test.cc, src/facade/reply_capture.h, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, src/server/server_family.cc
fixes: https://github.com/dragonflydb/dragonfly/issues/4389
problem: we didn't provide the resp version into CapturingReplyBuilder
=> fix: provide resp3 option to CapturingReplyBuilder

.github/workflows/ci.yml, src/server/main_service.cc, src/server/multi_test.cc, src/server/server_family.cc
Deprecate multi_exec_mode and track_exec_frequencies.
Remove duplicated call to EnterLameDuck (done also in Service::Shutdown()).
=> chore: deprecate unneeded runtime flags

src/server/json_family.cc, src/server/json_family_test.cc
=> feat: allow querying of json objects stored as strings

src/server/dragonfly_test.cc
added test to check that replicaof can't run during the LOADING state
=> test: move ReplicaofRejectOnLoad test from pytest into unit tests

src/facade/redis_parser.cc, src/facade/redis_parser.h, src/facade/redis_parser_test.cc
This change is needed in order to eliminate cases where we return INPUT_PENDING but do not consume the whole string by rejecting several bytes.
This will simplify buffer management on the caller's size, so that if they pass a string that
does not result in complete parsed request, the whole string is consumed by the parser and the passed string can be 
discarded.
=> chore: Introduce small buffer in redis parser

src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc
The problem was with reverse iterator that was not set properly when the last node is deleted.
Also, move PushSentinel code into Push.
=> fix: invalid iterator case in Qlist::Erase

src/core/extent_tree.cc
The changes introduced in https://github.com/dragonflydb/dragonfly/blob/main/src/core/extent_tree.cc#L41 do not considerate that the cached iterator might be invalidated by the erase() above. As such, it causes an illegal access and it was caught by the sanitizers: https://github.com/dragonflydb/dragonfly/actions/runs/12644997917/job/35233466191#step:8:8607
=> fix: ExtentTree use of invalidated iterator

src/server/journal/streamer.cc, tests/dragonfly/cluster_test.py
problem: we have timeout for fuzzy_migration_test https://github.com/dragonflydb/dragonfly/actions/runs/12648427037/job/35242743189 because of the number of the logs
fix: reduce number of logs in cluster tests
=> chore: reduce number of logs in cluster tests

src/server/zset_family.cc, src/server/zset_family_test.cc
`geosearch` and `georadius` return an array of arrays even when WITHCOORD, WITHDIST, WITHHASH statements are omitted. 
* return array of arrays only when WITHCOORD, WITHDIST, WITHHASH statements are used
resolves #4382
=> fix: geosearch and georadius response format

src/server/CMakeLists.txt, src/server/geo_family.cc, src/server/geo_family.h, src/server/main_service.cc, src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
I was longing for this change for some time now and I grabbed the opportunity since I already worked on  #4420 
* Split geo family from zset family
I am not sure how I could reduce the size of the PR.
**There are no functional changes** only a refactor.
TODO for separate PR
* Split zset family test to reflect the changes here
* Maybe move the common functions from `ZSetFamily::` to a separate file
=> chore: split geo and zset families

src/server/main_service.cc, src/server/main_service.h, src/server/replica.cc, src/server/server_family.cc, tests/dragonfly/replication_test.py
During the shutdown sequence always switch to SHUTTING_DOWN. Make sure that the rest of the code does not break if it can not switch to the desired global state + some clean ups around state transitions.
=> fix: switch to SHUTTING_DOWN state unconditionally

src/server/CMakeLists.txt, src/server/cluster/cluster_config.cc, src/server/cluster/cluster_defs.cc, src/server/cluster/cluster_defs.h, src/server/cluster/cluster_family.cc, src/server/cluster/cluster_utility.cc, src/server/cluster/cluster_utility.h, src/server/cluster_support.cc, src/server/cluster_support.h, src/server/common.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/debugcmd.cc, src/server/engine_shard.cc, src/server/generic_family.cc, src/server/journal/journal.cc, src/server/journal/journal.h, src/server/journal/streamer.cc, src/server/journal/streamer.h, src/server/journal/types.cc, src/server/journal/types.h, src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, src/server/rdb_load.cc, src/server/server_family.cc, src/server/table.cc, src/server/transaction.cc, src/server/transaction.h, src/server/tx_base.cc
fixes: #3839
- no logic was changed
- remove transaction lib dependency on cluster
- remove extra headers
=> refactor: remove transaction lib on cluster code dependency

src/CMakeLists.txt, src/core/compact_object.cc, src/server/json_family.cc, tests/dragonfly/memory_test.py
jsoncons 0.178 has some pmr related fixes that should contribute to better stability in our codebase.
=> chore: update jsoncons version to 0.178

src/server/server_family.cc
=> fix: show managed stuff on privileged port

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/facade_types.h, src/server/dfly_main.cc
1. Move socket read code into a dedicated function. Remove std:: prefix in the code.
2. Add an optional iouring bufring registration. Currently not being used and is disabled by default.
=> chore: dragonfly connection refactorings

src/facade/reply_builder.cc, src/facade/reply_builder.h, src/facade/reply_builder_test.cc
Due to a corner-case bug, reply builder could add \0\0 to the end of bulk strings, instead of \r\n. The bug slipped our tests because redis-py parser most probably does not validate the ending as long as everything else is consistent.
This PR:
1. Adds a test that catches the bug
2. Adds a debug check that verifies the destination pointer is consistent with the iovec being used.
3. Fixes the bug.
Fixes #4424
=> fix: reply_builder should properly serialize bulk strings endings.

src/facade/redis_parser.cc, src/facade/redis_parser_test.cc
With empty inline string, the parser failed to continue parsing correctly the non-inline input.
=> fix: resp inline parsing correctly resets itself

.github/workflows/daily-sanitizers.yml, CMakeLists.txt, src/server/zset_family.h
Older versions of GCC fail to compile the new version `absl`.
* compile with clang
* update container to version 24
* move to x86 github runner ubuntu 24
* use compiler-rt instead of libgcc
* add cmake glue
Resolves #4453 and #4442
=> fix(ci): sanitizers build

src/server/journal/cmd_serializer.cc, src/server/journal/cmd_serializer.h, src/server/journal/streamer.cc, src/server/journal/streamer.h, tests/dragonfly/cluster_test.py, tests/dragonfly/instance.py
=> chore: Add stats print for slot migrations

src/server/cluster_support.cc, src/server/cluster_support.h, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, src/server/transaction.cc
problem: we reuse transactions during squashing without slot resetting 
fix: reset UniqueSlotChecker every time when we reuse a transaction
=> fix: slot calculation during transaction squashing

src/core/dash.h, src/core/dash_internal.h
It's not being used at this time.
=> chore: add Dash::Prefetch function

.github/workflows/ci.yml, src/core/dash_internal.h, src/core/json/jsonpath_grammar.y, src/core/json/jsonpath_test.cc, src/core/search/parser.y, src/core/search/vector_utils.cc, src/core/task_queue.cc, src/core/task_queue.h, src/server/acl/validator.cc, src/server/bitops_family.cc, src/server/detail/snapshot_storage.cc, src/server/dfly_bench.cc, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/dragonfly_test.cc, src/server/json_family.cc, src/server/list_family.cc, src/server/search/search_family_test.cc, src/server/stream_family.cc, src/server/string_family.cc
Also add `-Werror` to clang build in CI.
Fixes #4449
=> chore: Fix all clang build warnings

src/server/dragonfly_test.cc, src/server/server_family.cc, tests/dragonfly/acl_family_test.py, tests/dragonfly/cluster_mgr_test.py, tests/dragonfly/cluster_test.py, tests/dragonfly/connection_test.py, tests/dragonfly/replication_test.py, tests/dragonfly/requirements.txt, tests/dragonfly/snapshot_test.py, tests/dragonfly/utility.py, tests/integration/async.py
hiredis checks for redis version and requires to be greater than 7.4. Dragonfly reports 7.2 and the library throws an error. 
* bump up redis version in info command
* add compatibility test
* bump up py dependencies
* fix warnings and deprecated functions
Resolves #4473
=> fix: hiredis requires df to report version >7.4

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/server/main_service.cc
Before this PR, QueueBackpressure objects are in fact referenced from other threads in an awkward way via Connection::WeakRef::EnsureMemoryBudget().
This PR removes the complexities of accessing these objects from foreigh threads.
=> chore: make per-thread QueueBackpressure objects global

src/server/cluster/cluster_family.cc, tests/dragonfly/cluster_test.py
problem: we can not finish/start migration for the same pair of nodes in one config because slots weren't a part of the migration characteristic
fix: compare slots to distinguish migrations
=> feat: allow finish and start migration in the same config

src/server/dfly_bench.cc
noreply option is applicable for memcached.
great option ensure the tcp connection is indeed established before proceeding with loadtest.
=> feat: add support for noreply and great options

src/core/json/json_object.cc, src/facade/error.h, src/facade/facade.cc, src/facade/op_status.cc, src/facade/op_status.h, src/server/json_family.cc, src/server/json_family_test.cc
This will slightly reduce processing time and memory allocation on the heap. Redis has its own limit set to [128](https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/json-document-overview.html#json-nesting-depth-limit).
[Inspired by this discussion](https://github.com/danielaparker/jsoncons/issues/531#issuecomment-2293758437)
=> feat(json_family): Add json_nesting_depth_limit flag

src/facade/conn_context.h, src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/server/blocking_controller_test.cc, src/server/main_service.cc, src/server/server_state.cc, src/server/server_state.h, tests/dragonfly/connection_test.py
`timeout` argument shuts down idle connections after the specified time.
Fixes #1677
=> feat: implement connection timeout functionality

src/server/dfly_bench.cc
=> feat: add 'testing_time' limit option to dfly_bench

tests/dragonfly/acl_family_test.py
=> fix: test_acl_cat_commands_multi_exec_squash

src/core/dash.h, src/server/journal/streamer.cc, src/server/snapshot.cc, tests/dragonfly/cluster_test.py
Fixes #4455 
The bug:
When running the RestoreStreamer::WriteBucket the iterator was not valid, pointing to a location in dash table that is not occupied.
The reason for this was that the call to FlushChangeToEarlierCallbacks when traversing the buckets can delete entires in the dash table. This can happen when we remove finalized migration which results in flush slots operation. This operation also registers a callback which was invoked in FlushChangeToEarlierCallbacks.
The fix:
When traversing the bucket in WriteBucket/SerializeBucket we first update the iterator if needed.
=> fix(cluster): crash in cluster migration

tests/dragonfly/cluster_test.py
test_migration_one_after_another failed with epoll
I opened #4498 to follow up on this
=> skip test_migration_one_after_another on epoll

src/core/dash.h, src/server/generic_family_test.cc, src/server/script_mgr.cc
1. Fixes #4466 (we did not check validity of the scan cursor) We fix it by quietly returning "end of scan" result, i.e. no error are returned.
2. Add 34b1048274c8e50a0cc587a3ed9c383a82bb78c5 sha to the lua_undeclared_keys_shas list.
3. Pull helio that fixes bugs with WaitQueue and IdleTasks: https://github.com/romange/helio/commit/2ab4412b78afbf7d3102b472fb0e6f70b194a535
=> fix: several bugs

src/server/db_slice.cc, src/server/db_slice.h, src/server/rdb_load.cc, src/server/rdb_test.cc
**The Issue**
Before this PR, when loading an RDB, we modified `fetched_items_` as part of the loading process. This has little effect, unless the next issued command calls `FLUSHALL` / `FLUSHDB` (could happen in `DFLY LOAD`, `REPLICAOF` or just calling `FLUSHALL` directly). In such a case, a `CHECK()` fails.
**The Fix**
While load is not run as a command (in a transaction), it still uses APIs that assume that they are called in the context of a command. As such, it indirectly used `DbSlice::FindInternal()`, which bumps elements when called.
This PR adds another sub-mode to `DbSlice`, named `load_in_progress_`. When `true`, we treat `DbSlice` as if it is not in cache mode, ignoring `cache_mode_`.
BTW this PR also renames `caching_mode_` to `cache_mode_` as we generally use the term `cache …
=> fix: Do not bump elements during RDB load

src/facade/reply_capture.cc, src/server/db_slice.cc, src/server/journal/streamer.cc, src/server/snapshot.cc, tests/dragonfly/cluster_test.py, tests/dragonfly/utility.py
fix #4455 
This PR:
1. fix crash in in registered callbacks:
The bug - calling bucket iterator get version will fail if bucket iterator is not valid. This case can happen when we have few callbacks executed on flush changes on earlier buckets. If the first one will remove all data from the bucket, the next call to the next registered callback will call Seek2Occupied and if the bucket is empty the iterator will be invalid.
2. add more test for cluster migration, running traffic while operating several migrations
=> fix cluster: migration crash fix

src/server/rdb_test.cc
The priodic call to CacheStats updates the shard data memory budget
Setting max_memory_limit before InitWithDbFilename ensures that this callback will be called with the correct max_memory_limit value at its first execution
=> fix(test): fix rdb random fail on OOM

src/server/dragonfly_test.cc
Also, improve robustness of StickyEviction that was failing for me.
=> chore: add benchmarking of ScanOpts::Matches

src/server/stream_family.cc, src/server/stream_family_test.cc
fixes: https://github.com/dragonflydb/dataplane-private/issues/27
=> fix: crash for delconsumer during stream reading

src/server/cluster/cluster_family.cc, src/server/multi_test.cc, src/server/script_mgr.cc
We accidentally instructed Sidekiq to add `disable-atomicity` to their script, despite them needing to run atomically.
This hack-ish PR adds a `--lua_force_atomicity_shas` flag to allow specifying which SHAs are forced to run in an atomic fashion, even if they are marked as non-atomic.
Fixes #4522
=> chore: Add Lua force atomicity flag

src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
related to the #4204
After adding the tests, several bugs were identified:
1. Bug with the `NOCONTENT` option.
2. An infinite loop occurring during the parsing of `RETURN` and `LOAD` options if the specified number of fields is big
=> fix(search_family): Add options test for the FT.SEARCH command

src/core/CMakeLists.txt, src/core/dfly_core_test.cc, src/core/glob_matcher.h, src/server/common.cc, src/server/common.h, src/server/dragonfly_test.cc, src/server/generic_family.cc, src/server/hset_family.cc, src/server/set_family.cc, src/server/zset_family.cc
1. Make GlobMatcher non-copyable. It's something I will need in the next PR.
2. Move low-level benchmarking testing code into dfly_core_test.
=> chore: refactoring around glob matching

src/core/sorted_map.cc, src/server/container_utils.cc, src/server/generic_family_test.cc, src/server/rdb_save.cc, src/server/replica.cc, src/server/server_family.cc, tests/dragonfly/instance.py, tests/dragonfly/sentinel_test.py, tests/dragonfly/snapshot_test.py, tests/pytest.ini
Also fix sentinel test by using a precise redis-server version.
Finally, add pytest warnings filter to reduce noise
=> chore: clean up of deprecated flags

tests/dragonfly/cluster_test.py
fixes: #4532
problem: because of the same name of the snapshot, we load it on the second test iteration.
fix: create a random snapshot name for every iteration
=> fix: test_snapshoting_during_migration

src/core/bptree_set.h, src/core/bptree_set_test.cc, src/core/sorted_map_test.cc
The bug was caused by incorrect handling of corner cases, when a path that should lead to an item was wrongfully cleared, which lead to empty results for SortedMap::GetRange query.
This PR:
1. fixes the wrong code in bptree_set.h.
2. Adds unit tests for both bptree_set_test and sorted_map_test.
Related to https://github.com/mastodon/mastodon/issues/33805
=> fix: Bug GEQ range query bug

src/server/dflycmd.cc
`DFLY LOAD` triggers the parser's destructor `DCHECK` which checks if the parsed error was consumed. 
Furthermore, fixes `dfly load path append nonsense` succeeding with `ok` .
* fix dcheck crash on dfly load
* fix dfly load with more than required arguments
IMO do we really need that `DCHECK` in the destructor ? Sometimes, there is no really reason to even consume it (see this PR as an example).
=> fix: consume parser error on dfly load

.github/workflows/bullmq-tests.yml
Unfortunately we have to use a custom fork with some timeout increases and commented out checks in order to pass, but still 650 tests are better than nothing.
Fork is at https://github.com/dragonflydb/bullmq
Fixes https://github.com/dragonflydb/dragonfly/issues/4126
=> Fix BullMQ tests workflow in GitHub actions

src/server/cluster/incoming_slot_migration.cc, src/server/cluster/incoming_slot_migration.h, src/server/common.cc, src/server/common.h, src/server/detail/save_stages_controller.h, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/journal/streamer.cc, src/server/journal/streamer.h, src/server/journal/tx_executor.cc, src/server/journal/tx_executor.h, src/server/protocol_client.cc, src/server/protocol_client.h, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/replica.cc, src/server/replica.h, src/server/snapshot.cc, src/server/snapshot.h
I decided to split Context refactoring into several parts to reduce the size of the code. This one is renaming the Context, so it's safe to merge it now.
=> refactor: rename Context into ExecutionState

src/server/engine_shard.cc, src/server/list_family.cc, src/server/transaction.cc
The bug:
incases where blmove runs on 2 shards and the first hop to run the lmove command will return error f.e wrong type the transaction does not conclude before return. 
Fixes:
1. add conclude on blmove runnning on 2 shards on error flow
2. add more prints to analyze tx
=> fix server: fix deadlock  blmove does not conclude on error

src/server/engine_shard.cc, src/server/list_family_test.cc, tests/dragonfly/generic_test.py
The bug requires lots of conditions in order to reproduce:
1. blocking operations on multiple databases
2. use of lua scripts that wake blocking transactions
The bug was discovered due to a deadlock in BLMOVE but could also manifest with other commands that would
"disappear" causing local starvation effects on the connections sending them.
With BLMOVE it causes a global deadlock in the transaction queue in dragonfly.
The fix is actually deleting a few lines of code introduced by https://github.com/dragonflydb/dragonfly/pull/3260 from 6 months ago,
so it is actually a long lived regression.
=> fix: a rare deadlock with blmove and multi-db

src/server/list_family_test.cc, src/server/main_service.cc
Before this PR, EVAL transactions would always use db_index=0 leading to inconsistent interactions with other commands on non-zero databases. Specifically the test in the PR would deadlock.
This PR fixes the issue. Also fixes #4583
=> fix: incorrect passing of db_index in EVAL transactions

src/server/generic_family.cc, src/server/string_family_test.cc
`redis-cli -x RESTORE x 5430186761345 < foo.dump` returns errors with index out of range
problem: max value for TTL is kMaxExpireDeadlineMs
fix: if TTL > kMaxExpireDeadlineMs; TTL = kMaxExpireDeadlineMs
=> fix: huge TTL in RESTORE cmd is rounded to kMaxExpireDeadlineMs

src/facade/cmd_arg_parser.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
related to the #4204
1. Fix some small issues during parsing of the several SEARCH methods
2. Remove using builder in Parse* methods.
It was a bad decision to use it because, in some cases, we were returning an error with `builder->SendError(...)`. However, in those cases, we were not handling parser errors with `parser->Error()`. As a result, debug builds were crashing because of this check:
```cpp
CmdArgParser::~CmdArgParser() {
DCHECK(!error_.has_value()) << "Parsing error occured but not checked";
}
```
Now, we ensure that parsing errors are processed in all cases.
3. Add options test for the `FT.AGGREGATE` command
=> fix(search_family): Add options test for the FT.AGGREGATE command

src/core/interpreter.cc, src/redis/stream.h, src/redis/t_stream.c, src/server/stream_family.cc, tests/dragonfly/replication_test.py, tests/dragonfly/seeder/script-hashlib.lua
Following [this comment](https://github.com/dragonflydb/dragonfly/pull/4574#discussion_r1949631279), this PR reverts the changes to the Redis code made in the PR #4448.
Some of the logic is copied from the Seeder's PR:
> ...
> 3. Fix bug when the whole stream was removed after trimming
> 4. Add full removal to the Python test
> 5. Add logs to the XADD command
Also, I added hash calculation for the streams in the seeder here, so `StaticSeeder.capture` works correctly. The `test_stream_approximate_trimming` test passes, confirming that the replication logic works properly.
=> fix(stream_family): Fix replication for the XADD and XTRIM commands

src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
ZDIFFSTORE command implementation. Use diff calculation function for both ZDIFF and ZDIFFSTORE commands. Using keys which are not ZSET should report back WRONG_TYPE error.
Closes #3887
=> feat(zset family): Implement ZDIFFSTORE

src/server/rdb_save.cc, tests/dragonfly/seeder/__init__.py, tests/dragonfly/seeder/script-genlib.lua, tests/dragonfly/seeder_test.py
fixes dragonflydb#4573
I can confirm that the seeder detects a difference if there is a bug in the replication of STREAMs
=> fix(seeder): Support stream types in the Seeder

src/server/list_family.cc, src/server/list_family_test.cc, src/server/zset_family.cc
fixes #4569 
The bug:
When calling list move (rpoplpush/ lmove/ lpoprpush) in a single shard flow we did not awake blocking transaction.
The fix:
call AwakeWatched from this flow
=> fix(server): list move on single shard wake blocking transaction

src/server/db_slice.cc, src/server/db_slice.h, src/server/main_service.cc, src/server/rdb_load.cc, src/server/rdb_test.cc, src/server/replica.cc, src/server/server_family.cc
The original issue was submitted in #4497 and we supplied a fix in #4507. However, the fix ignored that the `RdbLoader::Load()` function is run per flow/shard thread and the "poison pill" of updating the loading state at the end of `RdbLoader::Load()` introduced a race condition:
```
shard_set->Add(i, [bc]() mutable {
namespaces->GetDefaultNamespace().GetCurrentDbSlice().SetLoadInProgress(false);
bc->Dec();
}); 
```
Any flow `F` that finished loading its own snapshot first (relatively to the rest of the flows) will call `SetLoadInProgress(false)` on *ALL* shard threads. The consequence of that is that other flows are not yet done (their respective RdbLoader::Load()` is still processing) and next time the use the db slice API will start Bumping up items because now load in progress is …
=> fix: race when bumping items while loading a snapshot

tests/dragonfly/cluster_test.py, tests/dragonfly/utility.py
added test_keys_expiration_during_migration
=> test: added test_keys_expiration_during_migration

tests/dragonfly/snapshot_test.py
The issue is the `STREAM` data type consumes way less memory after the snapshot load and triggers the assertion `assert memory_after[counter] >= 0.5 * value`. The solution is to assert that the counter is non zero (that is that after loading the snapshot, df properly incremented the counters).
Resolves #4606
=> chore: fix test_snapshot

src/core/dfly_core_test.cc, src/core/glob_matcher.cc, tests/fakeredis/test/test_mixins/test_generic_commands.py
=> chore: fix glob translation with \ at the end

.clang-tidy, src/core/CMakeLists.txt, src/core/qlist.cc, src/core/qlist.h, src/core/qlist_test.cc
The feature is enabled via set_method call but since no code calls it the lz4 compression is still disabled in dragonfly.
=> feat: support lz4 compression method

tests/dragonfly/cluster_test.py
fixes: #4611
problem: too long migration process
=> fix: test_keys_expiration_during_migration

src/server/blocking_controller.cc, src/server/engine_shard.cc, src/server/engine_shard.h, src/server/transaction.cc, src/server/transaction.h
=> chore: simplify transaction code

.github/actions/regression-tests/action.yml, .github/workflows/epoll-regression-tests.yml
I accidentally introduced this bug which switched to iouring instead of epoll on the epoll regression tests.
* properly run epoll instead of iouring
* fix print message on failure
=> fix: epoll reg tests running on iouring

src/core/compact_object.h, src/server/db_slice.cc, src/server/generic_family.cc, src/server/generic_family.h, src/server/generic_family_test.cc, src/server/string_family.cc
We currently implement them only for sets but the same approach can work for zset, hashes, lists as well.
=> chore: introduce background deletions of DenseSet objects

src/core/dash.h, src/server/generic_family.cc
Scan command would not yield while traversing which means that it could potentially scan the whole dash table without any preemption until it finds at least one key that it matches. This is not good for some cases.
* allow yield in Scan
=> chore: allow yielding in Scan command

src/server/cluster/incoming_slot_migration.cc, src/server/cluster/outgoing_slot_migration.cc, src/server/common.cc, src/server/common.h, src/server/dflycmd.cc, src/server/journal/streamer.cc, src/server/journal/streamer.h, src/server/protocol_client.cc, src/server/rdb_save.cc, src/server/replica.cc, src/server/snapshot.cc
fixes: https://github.com/dragonflydb/dragonfly/issues/4284
refactor ExecutionState: now we can have 3 independent states RUN, CANCELLED, ERROR
=> refactor: simplify journal and restore streamer cancellation

src/core/compact_object.cc, src/core/compact_object.h, src/server/rdb_load.cc, src/server/rdb_load.h, src/server/rdb_save.cc, src/server/rdb_save.h, tests/dragonfly/replication_test.py
In this PR we introduce rdb loading of string alliteratively in chunks to prevent memory spikes on big string loading.
In this PR 
1. Add 2 apis to compact object to reserve memory and append to string
2. Reading of string data from rdb is done in chunks in case of big string
3. The rdb save compression logic is disabled in case of big buffer to prevent additional spike in snapshot while saving due to compression buffer and in the loader to decompress the buffer.
=> server: rdb loader big string loading in chunks

src/server/db_slice.cc, src/server/generic_family.cc
=> chore: remove redundant calls to GetSlice

src/core/sorted_map.cc, src/core/sorted_map.h, src/core/sorted_map_test.cc, src/core/task_queue.h, src/server/rdb_load.cc, src/server/rdb_load.h, src/server/rdb_save.cc
1. Reduce number of allocations when creating new members
2. Reverse the saving order because with bptree it's better to add elements from the smallest to largest.
3. Add a runtime flag rdb_load_dry_run that allows us to load the dataset without actually adding entries.
For zset rich dataset, the difference was 415s before vs 220s afterwards.
=> chore: Improve loading of sorted sets

src/server/replica.cc, src/server/replica.h, src/server/server_family.cc, tests/dragonfly/replication_test.py
We `unconditionally` flushed the replica even if `replicaof` failed to connect. We now flush *only* if replicaof succeeded to connect and therefore replication can properly start.
resolves #4501
=> fix: do not flush replicaof if failed to connect

src/core/CMakeLists.txt, src/core/dfly_core_test.cc, src/core/glob_matcher.cc, src/core/glob_matcher.h
1. cherry-pick valkey security fixes with stringmatchlen with exponential complexity of stars See https://nvd.nist.gov/vuln/detail/cve-2022-36021
2. Fallback to stringmatchlen for short lengths.
3. Add another backend to GlobMatcher - PCRE2, though do not enable at the moment. While this backend is the fastest one - it requires an additional shared lib dependency.
=> fix: performance degradation with Reflex matching

src/core/string_set.cc, src/core/string_set.h, src/core/string_set_test.cc, src/server/db_slice.cc, src/server/hset_family.cc, src/server/rdb_load.cc, src/server/server_family.cc, src/server/table.cc, src/server/table.h, src/server/zset_family.cc
They were wrong, we usually do not need them,
and they complicated code. The right way to do it - to add them to OBJHIST statistics.
In addition, did some other code improvements without functional changes.
=> chore: get rid of lispack stats

src/redis/hyperloglog.c, src/redis/hyperloglog.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/debugcmd.cc, src/server/debugcmd.h, src/server/table.cc, src/server/table.h
HyperLogLog is an efficient data structure for approximate counting of unique elements. We use it to sample the traffic via "DEBUG KEYS ON/OFF" command.
=> feat: implement unique keys counting using hll

.github/workflows/ci.yml, src/server/test_utils.cc, src/server/transaction.cc
Helps with #4648
1. This PR removes single shard optimization in transaction scheduling.
2. add tx debug info on test deadlock
=> server: disable single shard tx optimization on scheduling

src/server/CMakeLists.txt, src/server/dfly_bench.cc
The load tester client opens a connection to each shard, in total `num_shards * FLAGS_c * FLAGS_proactor_threads` connections.
There is no support for MOVED responses at the moment so only static clusters are supported.
=> Support Cluster configuration for dfly_bench

src/server/generic_family.cc, src/server/replica.cc
I accidentally changed the error message in https://github.com/dragonflydb/dragonfly/commit/8512f726f4b98e936672281d963048c8fea9ab89#diff-8174e8eae32841a10b583a676b1b8ec068e7b3f2aa3cf61d2e952553ab343875R96
Furthermore, I never pushed the commit with the early return from the suggestion in https://github.com/dragonflydb/dragonfly/pull/4624/files#diff-f8f9387edb04c03ce7333ad3b69778d7b379fcf8c8765543f62b34d883e187c5R629
=> fix: replication error message and scan command yield

src/server/cluster/cluster_family.cc, src/server/cluster/cluster_family.h, src/server/cluster/incoming_slot_migration.h, src/server/cluster/outgoing_slot_migration.cc, src/server/cluster/outgoing_slot_migration.h, src/server/common.cc, src/server/common.h, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/cluster_test.py
fixes: #4572
added migration_errors_total statistic
fixed data race
=> feat: add migration error statistic

src/server/search/search_family.cc, src/server/search/search_family_test.cc
fixes #4677 and partially fixes #4204
=> fix(search_family): Add option tests for the FT.CREATE command

.pre-commit-config.yaml, docs/build-from-source.md, src/core/CMakeLists.txt, src/huff/LICENSE, src/huff/README.md, src/huff/hist.h, src/huff/huf.h, src/huff/mem.h, src/server/CMakeLists.txt, src/server/debugcmd.cc, src/server/debugcmd.h
This function analyzes the compressability of the keys using a single huffman tree. For example,
```
>debug POPULATE 1000000 keyabcdef 10
OK
> debug compression
1) max_symbol
2) (integer) 121
3) max_bits
4) (integer) 5
5) raw_size
6) (integer) 7861817
7) compressed_size
8) (integer) 4372270
9) ratio
10) "0.5561398847111297"
```
=> chore: introduce DEBUG COMPRESSION

src/facade/dragonfly_connection.cc, src/server/db_slice.cc, src/server/db_slice.h, src/server/server_family_test.cc, tests/dragonfly/cluster_test.py
We call PerformDeletion in an atomic block, which in turn calls SendInvalidationTrackingMessage that could block. We fix it by separating the blocking logic by moving the invalidation messages into a designated send queue and flush it later.
In addition rename the function to make it explicit that they are atomic (i.e. not blocking).
=> fix: SendInvalidationTrackingMessage should not block.

.devcontainer/fedora41/devcontainer.json, src/server/server_family.cc
FormatInfoMetrics used 18KB of stack size in debug mode.
Each call to append increased the stack even though the calls were done
from the scope blocks. This PR overcomes this by move the calls to lambda functions.
=> fix: reduce stack usage on Fedora

src/server/main_service.cc, tests/dragonfly/replication_test.py
fixes #4663 
The bug:
when `replicaof` is running in multi command the tx scheduling done when we start executing the multi tx while the 
`replicaof` command takes a mutex to prevent concurrent replicaof commands at the same time.
This may lead to deadlock if `tx1` is scheduled first but `tx2` takes the replication mutex first.
Notes:
`replicaof` command should not run in multi tx, we do support this because sentinel uses it but actually the other commands runinig in this multi tx are not transactional (config, client), therefore running the tx in non atomic mode has the same affect in this flow.
The fix:
if we have an admin command running inside multi tx, use none atomic mode for this tx.
=> fix(server): deadlock with replicaof inside multi

.pre-commit-config.yaml, src/server/db_slice.cc, src/server/debugcmd.cc, src/server/engine_shard.cc, src/server/engine_shard.h, src/server/protocol_client.cc, src/server/replica.cc, src/server/server_family.cc, src/server/transaction.cc
Add various debug logs to help tracking the deadlock.
Add more assertions in helio and provide state time for fibers during stacktrace printings.
=> chore: Add debug logs to help tracking transactional deadlocks

src/server/common.h, src/server/rdb_load.cc, src/server/rdb_load.h, src/server/snapshot.cc, src/server/snapshot.h, src/server/tiering/disk_storage.cc
Mainly comments and refactorings.
There are two functional differrences:
1. flush serialized entries in case we gathered at least K delayed
entries coming from tiered entities.
2. allow loading snapshots larger than memory for tiered enabled datastores.
Also pull latest helio with some bug fixes in gcs code.
=> chore: snapshot/tiering improvements

src/server/debugcmd.cc, src/server/main_service.cc, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/connection_test.py
Implement `client unpause` and `client help`.
* add client unpause
* add client help
* add test
Resolves #4628 and #3799
=> feat: client unpause and client help

src/server/zset_family.cc, src/server/zset_family_test.cc
fix: ZMSCORE return value if key does not exist #4670
=> fix: ZMSCORE return value if key does not exist

src/server/cluster/incoming_slot_migration.cc, src/server/journal/tx_executor.cc, src/server/replica.cc
fixes: https://github.com/dragonflydb/dragonfly/issues/4689
problem: we read from the socket after it was shutdown
=> fix: prevent tx_executor reading from sock if operation is canceled

.vscode/c_cpp_properties.json, src/facade/dragonfly_connection.cc, src/facade/facade_test.cc, src/facade/redis_parser.cc, src/facade/resp_expr.h
Making RedisParser::Buffer const, some minor changes in dragonfly_connection code.
No functionality is changed.
=> chore: minor clean ups before introducing ProvidedBuffers

src/server/dfly_main.cc, tests/dragonfly/instance.py, tests/dragonfly/replication_test.py
fix: Remove the dfly logo print from pytest run #4682
=> fix: Remove the dfly logo print from pytest run #4682

src/core/json/jsonpath_lexer.lex, src/server/detail/wrapped_json_path.h, src/server/json_family.cc, src/server/json_family_test.cc
fixes dragonflydb#4381
The main bug was in the `ConvertExpressionToJsonPointer` method. I don’t like the idea of parsing a JSON path directly. Instead, I decided to use our JSON path lexer to parse it first and then convert it into JsonPointer. For now, this approach should work fine.
I also spent a significant amount of time ensuring support for both our parsing method, `json::ParsePath`, and the jsoncons parsing method, depending on the `jsonpathv2` flag. However, I found some bugs in the jsoncons parsing method, and it also needs modifications to allow us to extract path tokens and traverse them to convert them into a JsonPointer. And jsoncons does not provide any built-in methods to convert `json_expression` into `json_pointer`. So, I think this is the best solution for now.
Also, in …
=> fix(json_family): Fix JSON.SET handling for nested fields

src/server/dfly_bench.cc
also support multiple slot ranges per node.
Initial parsing of MOVED response is done but slot migration is not supported yet.
=> fix(dfly_bench): support dns resolution for cluster hosts

src/core/string_set.cc, src/core/string_set.h, src/core/string_set_test.cc, src/server/set_family.cc, src/server/set_family_test.cc
Support is added for KEEPTTL to the SAddEx command as described in https://github.com/dragonflydb/dragonfly/issues/4701
=> feat(set_family): Add support for KEEPTTL to SAddEx

src/server/snapshot.cc, tests/dragonfly/replication_test.py
The bug is that the Expirations should not preempt while writing to the journal within Hearbeat. The atomicity guarantee was violated because the journal callaback would try to acquire a lock on a mutex that is already locked which forced the Heartbeat to preempt -- violating the atomicity gurantees of the operation.
=>  fix: preemption in atomic section of heartbeat

src/server/cluster/cluster_config.cc, src/server/cluster/cluster_config.h, src/server/cluster/cluster_defs.cc, src/server/cluster/cluster_family.cc, src/server/cluster/cluster_family.h, src/server/main_service.cc, src/server/rdb_load.cc
if you need cluster_config you don't need cluster_family now
=> refactor: move tl_cluster_config into cluster_config.cc

src/server/detail/save_stages_controller.cc, src/server/detail/snapshot_storage.cc, src/server/server_family.cc
our S3 code relies on aws sdk client, which is extremely stack hungry.
this PR moves some of s3 calls to one-off fibers with increased stacks,
which reduces stack usage for connection fibers executing snapshot save/load operations.
=> fix: improve stack margin for s3 related operations.

.gitignore
`cmake-build-debug` is managed by clion. added to gitignore
=> chore: Add clion build path to gitignore

src/server/journal/streamer.cc, tests/dragonfly/cluster_test.py
fix #4578
The problem:
When creating test with not a lot of data migration is fast and we are not able to test the flows of On db change and journal changes.
The fix:
Instead of increasing the data in tests which makes the test slower, I intorduce a flag which controls the speed of migration. By setting low value the migration process gives more time for commands to run at the time of cluster migration.
=> server: control cluster migration speed with flag

src/server/debugcmd.cc
Now the debug compression command runs over all the keys to count the histogram. Based on the histogram it estimates potential savings for huffman compression of the keyspace.
=> chore: improve debug compression

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/facade.cc, src/facade/facade_test.cc, src/facade/facade_types.h, src/facade/redis_parser.cc, src/facade/resp_expr.h, src/server/server_family.cc
iouring allows to register a pool of predefined buffers used by kernel. then during the recv operation the kernel will choose a buffer from the pool, copy data into it and return it to the application. This is in contrast to prealocate buffers that need to be passed to a regular Recv. So, for example, if we have 10000 connections, today we preallocate 10000 buffers, even though we may have only 100 in-flight requests.
This PR does not retire the old approach, but extends with the new once with the flag `--uring_recv_buffer_cnt=N` that specifies how many receive buffers per thread to preallocate.
=> feat: add an option to start using iouring provided buffers

src/server/channel_store.cc, tests/dragonfly/cluster_test.py
Channel store uses a `read-copy-update` to distribute the changes of the channel store to all proactors. The problem is that we use `memory_order_relaxed` to load the new pointer to the channel store for each proactor which `*does not guarantee*` that we fetch the latest value of the channel store. Hence, the fix is to use sequencial consistency such to force fetch the latest value of the channel store. Should fix #4724
Fixes #4659 and #4724
=> fix: enforce strong consistency in channel_store

src/server/stream_family.cc, src/server/transaction.cc, tests/dragonfly/replication_test.py
1. The first bug is that we were not resetting `re_enabled_auto_journal_` in the transaction. For example, if we are in multi-mode and one of the commands calls `ReviveAutoJournal`, the next commands with `CO::NO_AUTOJOURNAL` will still be auto-journaled because we didn't set `re_enabled_auto_journal_` to false
2. The second bug is specific to the STREAM logic. The `streamId` is generated using Unix time, which can differ between the master and the replica, potentially causing replication issues. To fix this, we need to pass `time_now_ms` from the master to the replica. To achieve this, the `TIMENOW` option was added to the `XADD` command.
=> fix(transaction): Fix auto journaling in transaction

src/core/dense_set.cc, src/core/dense_set.h, src/core/string_map.cc, src/core/string_map.h, src/server/hset_family.cc, src/server/hset_family_test.cc
The `KEEPTTL` option is added to `HSetEx` command. 
This option if specified makes sure that TTL is preserved for existing members. It coexists along with the `NX` option and should be specified at the start of the command:
```
HSETEX key [NX] [KEEPTTL] seconds field value [field value ...]
```
fixes https://github.com/dragonflydb/dragonfly/issues/4701
=> feat(hset_family): Add KEEPTTL support to HSetEx

src/facade/dragonfly_connection.cc
Use absl Time instead of Chrono in PipelineCacheSizeTracker
=> chore: replace chrono with absl in PipelineCacheSizeTracker

src/server/debugcmd.cc, src/server/debugcmd.h
feat(server): extend populate command with expire
fix issue https://github.com/dragonflydb/dragonfly/issues/4742
=> feat(server): extend populate command with expire

src/server/hset_family.cc, src/server/hset_family_test.cc
NX and KEEPTTL can be specified in any order, but only one of each or both must be specified.
=> chore: Handle hsetex options in any order

tests/dragonfly/replication_test.py
fix #4534 
The problem:
the test failed on check 
assert compressed_blobs > 0
Because the number of keys is not very big and having lots of big values that disable compression on specific bucket, the chances that no bucket will be compressed increase
The fix:
increase number of keys in test
=> fix test: test_replication_all increase key num

src/server/hset_family.cc, src/server/hset_family_test.cc
=> fix(server): hmget non uniqe keys response

src/server/debugcmd.cc, src/server/debugcmd.h
feat(server): extend populate command with expire, fix bug that expire the same key for multiple time
In pr https://github.com/dragonflydb/dragonfly/pull/4752 there is a bug that it will expire the same key for multiple time
=> feat(server): extend populate command with expire, fix bug that expire the same key for multiple time

src/server/cluster/cluster_config.cc, src/server/cluster/cluster_config_test.cc, src/server/cluster/cluster_defs.h, src/server/cluster/cluster_family.cc
=> feat: add node health status into config

src/server/protocol_client.cc
fix: optional brackets were removed for IPv6 host
fix: ipv6 support fix in the helio framework: https://github.com/romange/helio/pull/391
=> fix: optional brackets were removed for ipv6 host

src/server/bitops_family.cc, src/server/db_slice.cc, src/server/db_slice.h, src/server/generic_family.cc, src/server/json_family.cc, src/server/list_family.cc, src/server/stream_family.cc
* merge AddOrFindResult with ItAndUpdater
* remove unused functions
* add missing FiberAtomicGuards on atomic member functions
=> chore: clean up dbslice

src/server/db_slice.cc, src/server/rdb_load.cc, src/server/rdb_test.cc
The bug: during the loading when appending to the existing object, ItAndUpdater scope did not account for the appended data, and as a result `object_used_memory` and its variation did not account for streamed objects.
The fix: to extend the scope of the ItAndUpdater object to cover appends. Added a sanity DCHECK that ensures that object_used_memory is at least as the memory used by a single object. This dcheck fails pre-fix.
Fixes #4773
=> fix: proper memory accounting for objects loaded via streaming

src/server/cluster/cluster_config.cc, tests/dragonfly/cluster_test.py
=> fix bug : moved error port number on migration finish

src/server/cluster/cluster_config.cc, src/server/cluster/cluster_defs.cc, src/server/cluster/cluster_defs.h, src/server/cluster/cluster_family.cc, src/server/cluster/cluster_family_test.cc, tests/dragonfly/cluster_test.py
=> feat: add node health status for CLUSTER SLOTS and SHARDS

src/core/compact_object.cc, src/core/compact_object.h, src/server/string_family.cc, src/server/tiered_storage.cc, src/server/tiered_storage_test.cc
The bug: during the override of the existing external string, we called `TieredStorage::Delete` to delete the external reference. This function called CompactObj::Reset that cleared all the attributes on the value, including expiry.
The fix: preserve the mask but clear the external state from the object. Fixes #4672
=> fix: removal of Expiry bit when overriding external strings

src/server/server_family.cc
Get number of MOVED reported errors and send as Prometheus metric.
Closes #4749
=> feat(server): Cluster MOVED response Prometheus metric

src/facade/dragonfly_connection.cc
thread_queue_backpressure is a global array of per thread QueueBackpressure objects. We referenced these objects incorrectly in 1.27.0-2.
Fixes #4770
=> fix: invalid reference inside GetQueueBackpressure

src/server/generic_family.cc, src/server/rdb_save.cc, src/server/snapshot.cc, src/server/tiered_storage_test.cc
Before: the code crashed on check-fail if a dump of the external string was requested.
This PR fixes it.
We call SerializerBase::DumpObject also in CmdSerializer::SerializeRestore,
and there we also do not handle the external strings, which will be fixed
in the future.
=> fix: support dump for external objects

tests/dragonfly/connection_test.py
=> feat test: add test for pipeline queue overlimit

src/core/compact_object.cc, src/server/json_family.cc, tests/dragonfly/replication_test.py
fixes dragonflydb#4725
Bugs that were found:
1. The first bug was related to conversions between `size_t` and `int64_t`. We performed `size_t` += `int64_t` for negative values of `int64_t`. In this case, `int64_t` is first converted to a large `size_t` value before being added to `bytes_used`.
Additionally, this check doesn't make sense:
```cpp
if (size < 0) {
DCHECK(static_cast<int64_t>(u_.json_obj.cons.bytes_used) >= size);
}
```
- Because `size_t` is always ≥ 0, while `size` here is < 0.
- I suggest avoiding operations that can potentially cause an overflow and adding utility functions to handle such cases safely.
2. The second bug was that `db_slice.AddOrFind` could deallocate some memory, at least due to `owner_->tiered_storage()->ReclaimMemory`. And `JsonMemTracker` was created …
=> fix(json_family): Fix memory tracking for JSON

src/core/string_map.cc, src/core/string_map.h, src/server/hset_family.cc, src/server/hset_family_test.cc
When expiry is set on an hset its members are migrated to a string map.
When creating a new entry in string map with TTL, we also set a bit on the stored pointer as metadata, this is set as 1 << 63. As a consequence when reading back the pointer, if expiry is set, we need to unset the same bit to get the correct address, this is done already in string map internals.
This change adds a similar AND operation in the scan code to unset the TTL bit before dereferencing the pointer.
fixes https://github.com/dragonflydb/dragonfly/issues/4799
=> fix(hset_family): Fix crash on scan after expiry set

src/server/cluster/cluster_family.cc, src/server/cluster/cluster_family_test.cc, tests/dragonfly/cluster_test.py
managed_service_info is ignored for the cluster because we have "hidden" health status for the replica
=> feat: ignore managed_service_info flag for cluster

src/redis/hyperloglog.c, src/server/hll_family_test.cc
Fixed bug in hllMergeDense that writes to wrong register.
Fixes #4750
=> fix(hll_family): Fixed PFMERGE wrong merge operation

src/core/bptree_set.h, src/core/detail/bptree_internal.h, src/core/sorted_map.h
Not yet used by sorted_map code, so no function changes. This will allow to clean up a hackish comparator code in sorted_map.cc
=> chore(bptree): introduce ability comparing keys to non-key types

tools/cluster_mgr.py
Before: slot merging/splitting logic was mixed with business logic. Also, slots were represented as dictionary, which made the code less readable. Now, SlotRange handles the low-level logic, which makes the high-level code simpler to understand.
=> chore(cluster_mgr): introduce SlotRange class

src/server/command_registry.cc, src/server/command_registry.h, src/server/dragonfly_test.cc
Support for aliasing a command is added with the command line flag `command_alias`. Multiple aliases of the same command are allowed.
Example run:
server
```
./dragonfly --command_alias __set=set,doset=set
```
client
```
127.0.0.1:6379> __set foo bar
OK
127.0.0.1:6379> get foo
"bar"
127.0.0.1:6379> doset a b
OK
127.0.0.1:6379> get a
"b"
127.0.0.1:6379>
```
commands which have been renamed using `rename_command` should be aliased with the renamed command name instead of original.
TODO: update docs
=> feat(server): Add support for aliasing commands

src/core/sorted_map.cc, src/core/sorted_map.h
Now we can support custom Query class when working with bptree, so we get rid of pointer taggings.
=> chore: remove pointer tagging for ScoreSdsPolicy

src/server/debugcmd.cc, src/server/debugcmd.h
Move DoPopulateBatch under class and reduce the number of its argument.
=> chore: refactor debug populate

tests/dragonfly/cluster_test.py
fix: python test was excluded for epoll case. fixed: https://github.com/dragonflydb/dragonfly/issues/4822
=> fix: python test was excluded for epoll case.

tools/cluster_mgr.py
We further simplify the code around cluster config Also - add a command that populates all the cluster ranges in the cluster using the "populate" command. `--size` and `--valsize` arguments are also added.
=> feat(cluster_mgr): add populate command

src/server/dfly_bench.cc
There could be multiple errors in io buffer which fails to parse correctly. Fixed with 
getting error string form after parsing.
=> fix(dfly_bench): Get MOVED error from parsed response

src/server/search/search_family.cc, src/server/search/search_family_test.cc
fix: Backward compatibility for fields without the "@" sign in the FT.AGGREGATE command #4698
=> fix: Backward compatibility for fields without the "@" sign in the FT.AGGREGATE command

src/server/main_service.cc, src/server/server_family_test.cc
redis-cli uses COMMAND DOCS response to set up tab and hints completion. If we return OK no completion is set up. If we return an error the cli sets up fallback completion.
Here we change the response from OK to error so that the completion can be enabled as fallback.
fixes https://github.com/dragonflydb/dragonfly/issues/4841
=> feat(command docs): Enable fallback tab completion in cli

src/core/compact_object.cc, src/core/compact_object.h, src/core/sorted_map.cc, src/core/sorted_map.h, src/server/zset_family.cc, src/server/zset_family_test.cc
The usages of WrapSds are removed from zset_family calls.
In most cases it is a straightforward change to use string_view or string_view.data(), string_view.size(). 
In one case a wrapper had to be introduced.
fixes https://github.com/dragonflydb/dragonfly/issues/4639
=> chore(zset_family/score_map): Replace sds arguments with string_view

src/server/command_registry.cc, src/server/command_registry.h, src/server/dragonfly_test.cc, src/server/main_service.cc, src/server/main_service.h, src/server/server_family.cc
When a call is made to server, its call count and call time is counted against the string it was called with, if the command was found to be an alias.
Fixes https://github.com/dragonflydb/dragonfly/issues/4068
Follow up PR to https://github.com/dragonflydb/dragonfly/pull/4782
=> feat(metrics): Update metrics for aliased commands

src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/snapshot.cc, tests/dragonfly/replication_test.py
these changes helps to debug https://github.com/dragonflydb/dragonfly/issues/4795
=> chore: turn on more logs for test_replication_timeout_on_full_sync

src/core/compact_object.cc, src/server/rdb_load.cc
Small fix for the case if we cannot parse json string during loading.
=> fix(rdb_load): Handle JSON loading failure when parsing fails

src/server/detail/snapshot_storage.cc
When GCP storage is used we need to have trailing slash for matching sub directories so append if needed.
Fixes #4833
=> fix(snapshot): Append trailing slash for GCP

src/core/interpreter_test.cc, src/redis/lua/bit/bit.c
- Add code to prevent stack buffer overflow.
- Closes #4853
- interpreter_test result.
```
~/Desktop/dragonfly/build$ ./interpreter_test 
[==========] Running 16 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 16 tests from InterpreterTest
[ RUN      ] InterpreterTest.Basic
[       OK ] InterpreterTest.Basic (0 ms)
[ RUN      ] InterpreterTest.UnknownFunc
[       OK ] InterpreterTest.UnknownFunc (0 ms)
[ RUN      ] InterpreterTest.Stack
[       OK ] InterpreterTest.Stack (0 ms)
[ RUN      ] InterpreterTest.Add
[       OK ] InterpreterTest.Add (0 ms)
[ RUN      ] InterpreterTest.Execute
[       OK ] InterpreterTest.Execute (0 ms)
[ RUN      ] InterpreterTest.Call
[       OK ] InterpreterTest.Call (0 ms)
[ RUN      ] InterpreterTest.CallArray
[       OK ] …
```
=> fix(lua) : Prevent Lua stack buffer overflow crash (#4853)

tests/dragonfly/replication_test.py
fixes: https://github.com/dragonflydb/dragonfly/issues/4795
problem: in debug build, the replication process is quite slow, so 30s wasn't enough
=> fix: increase timeout for test_replication_timeout_on_full_sync

src/server/server_family.cc
This error triggers alerts in production.
It is redundant because we also printing a warning in main_service:
```
main_service.cc:1355]  CLIENT INFO > redis.log failed with reason: Unknown subcommand or wrong number of arguments for 'INFO'. Try CLIENT HELP.
```
=> fix(server_family): Remove redundant logging in the CLIENT command

contrib/docker/docker-compose.yml
- Removes the warning the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
This just follows the advice from docker of remove the version attribute from the compose file. No more warnings when following the guide 👍🏼
=> chore: Remove version attribute from compose file

src/core/search/lexer.lex, src/core/search/parser.y, src/core/search/search_test.cc
Syntax like this should be supported:
FT.SEARCH idx:positions @draw_end:[**1742916180,1742916180**] LIMIT 0 10000
Now, Dragonfly supports the following:
FT.SEARCH idx:positions "@draw_end:[1742916180 1742916180]" LIMIT 0 10000
FT.SEARCH idx:positions "@draw_end:[1742916180,1742916180]" LIMIT 0 10000
Original issue: https://github.com/dragonflydb/dragonfly/issues/4832
=> fix: FT.SEARCH commas support for ranges

tests/dragonfly/cluster_test.py
to debug #4834 I need more logs
=> chore: turn on more logs for test_migration_timeout_on_sync

src/server/common.cc, src/server/common.h, src/server/generic_family.cc, src/server/generic_family_test.cc
feat(server): SCAN command add ATTR options
fix https://github.com/dragonflydb/dragonfly/issues/4537
=> feat(server): SCAN command add ATTR options

src/core/search/CMakeLists.txt, src/core/search/indices.cc, src/core/search/indices.h, src/core/search/search.cc, src/core/search/search.h, src/core/search/search_test.cc, src/core/search/sort_indices.h, src/core/search/synonyms.cc, src/core/search/synonyms.h, src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/search/search_family.h, src/server/search/search_family_test.cc
feat: Added FT.SYNUPDATE: https://redis.io/docs/latest/commands/ft.synupdate/
feat: Added FT.SYNDUMP: https://redis.io/docs/latest/commands/ft.syndump/
=> feat: Support synonyms in queries. Add FT.SYNUPDATE, FT.SYNDUMP

src/server/main_service.cc, src/server/server_state.cc, tests/dragonfly/connection_test.py
=> feat(server): add connections send timeout

tools/packaging/Dockerfile.alpine-dev, tools/packaging/Dockerfile.ubuntu-dev
now it looks like this:
```
> docker run --rm ghcr.io/dragonflydb/dragonfly-dev:ubuntu-f767d82 --version
dragonfly f767d82-f767d82ce78ccbc90ddfb525f4ad4bd9aafcfbed
```
fixes #4830
=> fix: add version id for dev container builds

src/core/search/lexer.lex, src/core/search/search_parser_test.cc, src/server/search/search_family_test.cc
fix: Pattern matching error when query includes escaped special characters #4691
=> fix: '@text:prefix*' matching for fields.

tests/dragonfly/cluster_test.py
Problem: during seeding, we can add ttl up to 50ms, so to get the same data on fake_redis and DF we need to sleep a little before capture the resulted data
fixes: #4861
=> fix: test_migration_rebalance_node

src/server/debugcmd.cc, src/server/debugcmd.h
Extend `debug compression` to support value types. if no type is given, falls back to testing keys compressability.
=> feat: debug compression <type>

src/server/debugcmd.cc, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, src/server/server_family.h, src/server/transaction.cc, tests/dragonfly/cluster_test.py, tests/dragonfly/generic_test.py, tests/dragonfly/replication_test.py, tests/dragonfly/seeder/README.md, tests/dragonfly/seeder/__init__.py, tests/dragonfly/seeder_test.py, tests/dragonfly/snapshot_test.py, tests/dragonfly/tiering_test.py
Test `test_bug_in_json_memory_tracking` failed because it used `StaticSeeder` which uses `debug populate` which is non transactional. 
* rename StaticSeeder to DebugPopulateSeeder to show intent
* add a DCHECK in debug populate that triggers if there is a registered replica that hasn't reached stable sync
* small cleanup
fixes #4048
Also `test_disconnect_replica` was failing months ago but I run this for more than 5 hours without any success.
=> fix: lsn check failure

src/server/engine_shard.cc
We allowed running `heartbeat` during `global transactions`. That's not good. For example, during replication and while transitioning from full to stable sync we unregister and register journal callbacks with a preemption inbetween. If under preemption  heartbeat runs, then we loose those journal entries triggering an lsn check failure.
* early return from HeartBeat if shard is under global lock
Fixes another corner case in  #4048
=> fix: skip heartbeat if shard is under global lock

src/server/db_slice.cc, src/server/db_slice.h, src/server/debugcmd.cc, src/server/string_family_test.cc, src/server/transaction.cc, tests/dragonfly/generic_test.py
Bumpup logic is moved to OnCbFinish. Previously keys which are going to
be delete were also bumped up but with this change if key doesn't exists
on callback we will skip it.
Closes #4775
=> feat(server): Move bumpup logic out of FindInternal

tests/dragonfly/replication_test.py
`test_replica_snapshot_with_big_values_while_seeding` is skipped while failures are investigated
https://github.com/dragonflydb/dragonfly/issues/4899
=> pytest: temporarily skip test while its failures are investigated

tests/dragonfly/replication_test.py
The issue: client fails to connect and redis lib converts `OsError` to `ConnectionError` and rethrows. This happens rarely and the symptom can be treated by catching the exception.
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dragonfly/replication_test.py:1249: in block_during_takeover
assert await c_blocking.execute_command("BLPOP BLOCKING_KEY1 BLOCKING_KEY2 100") is None
/usr/local/lib/python3.8/dist-packages/redis/asyncio/client.py:611: in execute_command
conn = self.connection or await pool.get_connection(command_name, **options)
/usr/local/lib/python3.8/dist-packages/redis/asyncio/connection.py:1064: in get_connection
await self.ensure_connection(connection)
/usr/local/lib/python3.8/dist-packages/redis/asyncio/connection.py:1097: in …
```
=> fix: take_over_counters

src/server/hset_family.cc, src/server/hset_family_test.cc
When a search operation is performed on a hash set, expired fields are removed as a side effect.
If at the end of such an operation the hash set becomes empty, its key is removed from the database.
fixes #4856
=> fix(hset_family): Ensure empty hash sets are removed

.github/actions/regression-tests/action.yml, tests/dragonfly/replication_test.py
Locally, the test consumes roughly 8gb of memory. Our gh runner has 7.5GB. 
Solution: lower number of seeded keys
Also increase timeout for reg tests. It seems that we timeout now :)
Resolves #4899
=> fix: test_replica_snapshot_with_big_values_while_seeding

src/server/rdb_save.cc
When we fail to save empty pv, its tag should be printed as int rather than the default behavior of trying to print `uint8_t` as a char.
fixes #4856
=> fix(rdb): Print tag as int in error

src/server/server_family.cc, tests/dragonfly/snapshot_test.py
Exit process if error is reported when we try to load snapshot for both cloud storage and local directory.
Fixes #4840
=> feat(server): Exit process if error is report during load snapshot

tests/dragonfly/snapshot_test.py
Remove invalid argument from test_exit_on_s3_snapshot_load_err test
=> fix(pytest): Remove invalid argument from pytest

src/core/dense_set.cc, src/core/string_map_test.cc
When setting TTL, the object is cloned. An extra 4 bytes is requested during allocation. This can result in the object being allocated from a larger page, eg moving from 16 byte page to 32 byte page. The page block size is used to report object allocation size. Currently this change in size is not reflected in the total memory usage of the dense set, so it remains 16 bytes while the object allocated size is now 32 bytes.
If such an object is later replaced, we deduct the size of the object from total memory usage of the set. Here we can run into an overflow, because the size of the object is deducted from the tracked size of the set, and the former is greater than the latter.
To avoid this, if during setting expiry time the new size is different from old size, we update the set size. …
=> fix(hset): Fix size account discrepancy when setting TTL

src/server/cluster/cluster_family.cc, src/server/cluster/cluster_family.h, src/server/cluster/incoming_slot_migration.cc, src/server/cluster/incoming_slot_migration.h, src/server/cluster/outgoing_slot_migration.h
Made outgoing and incoming migration objects' lifetimes more similar
=> refactor: add ability to reinit incoming migration object

src/server/cluster/cluster_family.cc, tests/dragonfly/cluster_test.py
=> fix: cancel blocking command during migration finalization

tests/dragonfly/snapshot_test.py
Pytest test_exit_on_s3_snapshot_load_err can raise exception on start in some test environments. Now wait for exception in instance start and stop.
=> fix(pytest): Wait exception on instance start and stop

src/server/db_slice.cc, src/server/db_slice.h
Remove key argument in DbSlice::CallChangeCallbacks which is used only for DVLOG(2) logging. DbSlice::OnCbFinishBlocking needs to call this funciton but it doesn't have key name so it has to retrieve one from it.
=> chore: Cleanup DbSlice::CallChangeCallbacks

tests/dragonfly/replication_test.py
Temporarily disable test while failures are investigated
=> fix: Skip test_take_over_counters for epoll

src/core/compact_object.cc, src/server/stream_family.cc, src/server/stream_family.h
The problem is described in the first PR: #4777
fixes #4898
=> fix(stream_family): Fix memory tracking for the STREAMs. SECOND PR

src/server/generic_family_test.cc, src/server/set_family.cc
StringSet object doesn't update time when FIELDEXPIRE is called. It will use base time when object is created. Update object time when we want to expire field in SET object.
Fixes #4894
=> fix(set_family): Update object time during SET FIELDEXPIRE

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h
Close MONITOR connection if we overflow pipeline limits. It can happen
that MONITOR connection dispatches messages slower than they are received
causing memory to go out of bounds (and can result in process crash).
=> fix(connection): Close MONITOR connection if pipeline overflows

src/server/journal/journal.cc, src/server/journal/journal_slice.cc, src/server/rdb_save.cc, src/server/snapshot.cc, src/server/snapshot.h, src/server/tx_base.h, tests/dragonfly/replication_test.py
This should improve situation around #4787 -
maybe not solve it completely but improve it significantly.
On my tests when doing snapshotting under read traffic with master (memtier_benchmark --ratio 0:1 -d 256  --test-time=400  --distinct-client-seed --key-maximum=2000000 -c 5 -t 2 --pipeline=3) I got drop from 250K qps to 8K qps during the full sync phase.
With this PR, the throughput went up to 45K qps - 5x more but still much lower than 250K qps.
=> chore: Make snapshotting more responsive

README.ko-KR.md
First, thank you for creating such an interesting and amazing data store.
While reading the Korean version of the README file, I found a small typo where 'dashtable' was written as 'dastable,' so I have fixed it.
Although it's just a small typo, I hope this change contributes to the project.
I would appreciate it if you could review it.
Thank you!
=> docs(readme): fix typo in README.ko-KR.md

src/core/dense_set.cc, src/core/string_set_test.cc, src/server/set_family_test.cc
When extracting DensePtr from LinkObject we need to transfer TTL flag before this DensePtr is assigned.
Fixes #3915
=> fix(set_family): Transfer TTL flag from DenseLink object in delete

src/server/engine_shard.cc, src/server/engine_shard.h, src/server/server_family.cc
* evict in heartbeat if expire table is not empty
* add metrics around heartbeat evictions (total evictions and total evicted bytes) 
Resolves  #4950
=> chore: add metrics for heartbeat evictions

src/core/search/ast_expr.h, src/core/search/base.h, src/core/search/search.cc, src/core/search/search.h, src/server/search/aggregator.cc, src/server/search/aggregator.h, src/server/search/aggregator_test.cc, src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
fixes dragonflydb#4939, dragonflydb#4934
Fixes two issues. They are good described in the tickets above.
=> fix(search_family): Fix SORTBY option in FT.SEARCH for non-sortable fields and KNN search

src/core/dash.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/main_service.cc, src/server/server_family.cc, tests/dragonfly/replication_test.py, tools/local/monitoring/grafana/provisioning/dashboards/dragonfly.json
Also, add a local dashboard demonstrating prime table load per db.
=> feat: expose table capacities instead of number of buckets

src/server/dfly_bench.cc, tools/local/monitoring/grafana/provisioning/dashboards/dragonfly.json
Two commits:
1. Coordinated omission - with --qps=0, each request is sent and then we wait for the response and so on. For pipeline mode, k requests are sent and then we wait for some of them to return to send more
2. qps > 0: we schedule sending requests at frequency "qps" per connection but if pending requests count crosses a limit we throttle down requests. This mode enables gentle uncoordinated omission, where the schedule converges to the real throughput capacity of the backend (if it's slower than the target throughput).
3. qps < 0, similar as (2) but does not adjust its scheduling and may overload the server if target QPS is too high.
Before this change non-coordinated omission ( i.e. when qps != 0) worked only without pipelining.
Now, with pipelining mode with send a burst of P …
=> feat(dfly_bench): allow regulated throughput in 3 modes

src/server/acl/acl_family.cc, src/server/acl/acl_family_test.cc, src/server/acl/validator.cc, src/server/command_registry.cc, src/server/command_registry.h, src/server/dragonfly_test.cc, src/server/main_service.cc, src/server/main_service.h, src/server/server_family.cc, tests/dragonfly/replication_test.py
This is an effort to simplify previous PRs which introduced commits
https://github.com/dragonflydb/dragonfly/commit/91c27f1f18cb4378ca5daacbbe616855cce437fd
https://github.com/dragonflydb/dragonfly/commit/4539e3d024dd2348ebd60eeb73ef4fb04e110e8b
In this change the previous commits are reverted, and commands are cloned for each alias. An additional hidden opt is added for the cloned command. A new c-tor is added to clone commands cleanly.
FIXES https://github.com/dragonflydb/dragonfly/issues/4857
=> feat(server): Add support for command aliasing

src/core/search/parser.y, src/core/search/search_test.cc
The example to reproduce the crash:
```
FT.CREATE idx SCHEMA s TEXT t TAG SORTABLE v VECTOR HNSW 12 TYPE FLOAT32 DIM 2 DISTANCE_METRIC L2 INITIAL_CAP 10 M 16 EF_CONSTRUCTION 200
```
```
FT.SEARCH idx "*=>[KNN 2 @v $b]" PARAMS 2 b abcdefg
```
=> fix: FT.SEARCH KNN crash fixed

.github/workflows/mastodon-ruby-tests.yml
A workflow is added to run (on demand) the mastodon ruby test suite. Mastodon is a ruby on rails app, this test suite uses dragonfly latest image which is used in the test suite.
The suite is a simplified version of the full ruby tests run in mastodon. Coverage is skipped and some of the tests in `self_destruct_scheduler_spec` are excluded which rely on info fields which we do not currently expose. 
fixes https://github.com/dragonflydb/dragonfly/issues/4596
new workflow: https://github.com/dragonflydb/dragonfly/actions/workflows/mastodon-ruby-tests.yml
=> Add workflow to run mastodon ruby test suite

src/server/acl/acl_family.cc
A couple of variables are moved outside of a loop and reused within it.
=> chore(acl_family): Move some variables outside loop

src/server/generic_family.cc
The issue is that `Scan` has high latency (in seconds) when keys are large and there are no matches. Iterating 10k buckets and string matching each of the keys is potentially an expensive operation that depends on the keyspace and the number of actual matches. 
* replace heuristic in scan command to throttle based on time
=> chore: time sensitive throttle for scan command

tools/replay/go.mod, tools/replay/go.sum, tools/replay/main.go, tools/replay/workers.go
- **feat(replay): add latency distributions**
- **wrap exec instead**
- **also add avg latency**
- **also include pipeline range**
- **display both at the end**
=> feat(tools/replay): Add pipeline latency distribution data

src/server/debugcmd.cc
This PR refactors the `ParsePopulateArgs` function in `debugcmd.cc` to use the project's standard `CmdArgParser` class rather than manual argument parsing. The change:
- Replaces manual index-based argument access with structured parsing
- Uses `CmdArgParser` methods to track argument position and validate input
- Maintains identical validation rules and error messages
- Makes the code more consistent with other command implementations
The implementation has been tested using:
- `cmd_arg_parser_test`
- `server_family_test`
- `dragonfly_test`
All tests pass with no changes to behavior.
related: #4820
=> refactor(debug-cmd): migrate ParsePopulateArgs to CmdArgParser

.github/workflows/ci.yml
It will be easier to figure out which step failed. 
* split unit tests in different steps
=> chore: split unit test steps in ci workflow

src/server/cluster_support.cc, src/server/cluster_support.h, src/server/engine_shard.cc, src/server/hll_family_test.cc
This is relevant only for cluster-enabled configurations. Also, inline the cluster config getter functions, as they are on critical path for 100% of requests.
Finally, skip a test that triggers a check-fail bug filed in #5004
Fixes #5005
=> feat: allow sharding by cluster slot id

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/server/main_service.cc, src/server/server_family.cc, tests/dragonfly/connection_test.py, tools/local/monitoring/grafana/provisioning/dashboards/dragonfly.json
Fixes https://github.com/dragonflydb/dragonfly/issues/4998.
1. Reduces agressive yielding when reading multiple requests since it humpers pipeline efficiency.
Now we yield consistently based on cpu time spend since the last resume point (via flag with sane defaults).
2. Increases socket read buffer size effectively allowing processing more requests in bulk.
`./dragonfly  --cluster_mode=emulated`
latencies (usec) for pipeline sizes 80-199:
p50:  1887, p75: 2367, p90: 2897, p99: 6266
`./dragonfly  --cluster_mode=emulated --experimental_cluster_shard_by_slot`
latencies (usec) for pipeline sizes 80-199:
p50: 813, p75: 976, p90: 1216, p99: 3528
=> chore: Pipelining fixes

src/server/bitops_family.cc, src/server/bitops_family_test.cc
fixes: https://github.com/dragonflydb/dragonfly/issues/4988
=> fix: bitops_family crash fixed

src/server/conn_context.cc, src/server/conn_context.h, src/server/debugcmd.cc, src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h
1. Eliminate replies reverse call - will allow to unite replies and cmd vectors into one.
2. Introduce SwitchTxCmd function to avoid code duplication.
=> chore: clean ups around command squasher

.github/workflows/regression-tests.yml, src/server/server_family.cc, tests/dragonfly/connection_test.py
1. Fix a crash bug in RESETSTAT when number of shards is less than number of threads.
2. Tune regtests parameters for pipelining tests to pass.
=> fix: regtest failures

src/core/dfly_core_test.cc, src/core/glob_matcher.cc, src/server/dragonfly_test.cc
If string is longer than 16 chars we are using reflex library for matching. When used pattern is '*' or '**' we are 
removing trailing and leading star and have empty pattern as result. We should, in this edge case, set manually star regex.
Fixes #4948
=> fix(glob): Correctly match longer strings with '*' or '**' pattern

tests/dragonfly/seeder_test.py, tests/dragonfly/utility.py
Generate long string while generating commands. We will create number of
random samples when to use huge value. When key count matches sampled
number we will generate command with huge string value.
Closes #4430
=> feat(pytest): Generate huge val string in seeder

src/facade/dragonfly_connection.cc, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, src/server/string_family.cc, src/server/tiered_storage_test.cc
1. Remove one vector (affects allocation and data locality) in squashing.
2. stop deduplicating MGET keys by default, but keep it as a run-time flag.
Also, finally fix TieredStorageTest.FlushAll test.
=> chore: more performance improvements around MGET and pipelining

src/facade/reply_capture.cc, src/facade/reply_capture.h
=> chore: get rid of possible recursion when unwinding structured reply

src/server/generic_family.cc, src/server/generic_family_test.cc
=> fix: Support for additional flags in expireat, pexpire and pexpireat commands

src/core/dfly_core_test.cc, src/core/search/CMakeLists.txt, tests/dragonfly/connection_test.py
cycle clock like most clocks is affected by thread context switching, and maybe this is what causes test failures. Try to increase the parameter to even further.
Also, add benchmarks for the clock as well as fix some compiler warnings around parser.cc
=> chore: bump up max_busy_read_usec in tests

src/server/db_slice.cc, src/server/db_slice.h, src/server/engine_shard.cc, src/server/journal/journal.cc, src/server/journal/journal.h
FreeMemWithEvictionStep was not atomic yet was used by a flow -- RetireExpireAndEvict() -- which should be atomic. Therefore, we make this function atomic (since it's only used by that flow).
Resolves #4875
=> fix: make FreeMemWithEvictionStep atomic

src/server/family_utils.cc, src/server/family_utils.h, src/server/stream_family.cc
fixes #4961
Three bugs were found:
1. `WrapSds` can allocate memory and not free it after usage (due to the static variable). Because of this, we can account this allocation in the stream memory statistics. To fix it, I introduced `SdsWrapper`, an RAII wrapper for sds.
2. `OpRange` can allocate memory on the stream, which means it is a mutable command. And also we need to update memory statistics there
3. In `OpRange`, we didn't properly stop the `raxIterator` in all cases.
I suggest to completely remove `WrapSds` and use `SdsWrapper` instead.
The next steps would be to create wrappers for the redis stream code. And safely assert that:
1. Clean up the code
2. If the operation only reads -> const for the Wrapper (we can call only const methods) + assert that no allocation occurs
3. If the …
=> fix(stream_family): Fix stream memory tracking issues

src/server/cluster/cluster_family.cc
=> refactor: reduce number of cluster logs

src/server/debugcmd.cc, src/server/debugcmd.h, src/server/dragonfly_test.cc
The command shows verious io stats per thread
=> feat: introduce 'debug iostats' command

src/core/json/detail/jsoncons_dfs.cc, src/core/json/detail/jsoncons_dfs.h, src/core/json/jsonpath_test.cc, src/core/json/path.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5038
1. What's not working:
Using JSON.SET with recursive descent paths ($..) on nested JSON objects could lead to hangs or crashes. This occurred because the mutation logic could process the same node multiple times if it was discovered via different paths during the traversal.
2. How this PR fixes the issue:
This PR adjusts the iteration logic. When processing elements of an object or array targeted by a path segment, the code now correctly handles iterator advancement, especially after an element might have been modified or erased by the mutation callback. This ensures that each element within the target object/array is considered for mutation exactly once during that step, preventing infinite loops or incorrect processing that …
=> fix: json.set recursive processing crash

tests/dragonfly/replication_test.py
Test fails regularly and is a blocker when we try to merge a PR. Skip it for now. 
https://github.com/dragonflydb/dragonfly/issues/5059
=> chore: skip test_bug_in_json_memory_tracking

src/server/memory_cmd.cc, src/server/memory_cmd.h
This is the second PR to fix JSON memory tracking issues.
It adds the `WITHOUTKEY` option to the `MEMORY USAGE` command to exclude the memory usage of the key from the result. This will be useful for checking JSON memory usage in memory tests.
=> feat(memory_cmd): Add WITHOUTKEY option for the MEMORY USAGE command. SECOND PR

src/core/dash.h, src/core/dash_internal.h, src/core/dash_test.cc, src/server/detail/table.h
Remove stash template parameter because we only use dashtable with a single configuration of STASH_CNT=4.
=> chore: dash table clean ups

src/core/compact_object.cc, src/core/compact_object.h, src/server/common.cc, src/server/debugcmd.cc
Allow export/import of huffman tables via
`DEBUG COMPRESSION EXPORT` or `DEBUG COMPRESSION IMPORT <bintable>`
=> chore: further extend the compression analysis

src/server/CMakeLists.txt, src/server/json_family.cc, src/server/json_family_memory_test.cc, src/server/search/search_family_test.cc
fixes memory tracking issues for the JSON.SET command and #5054.
Also, partially fixes #4926
Bugs that were found and fixed:
1. We didn't reset the result of `ShardJsonFromString`, which parses the json_str into the jsoncons's json and returns optional of this. The bug was that `std::optional` still holds the value even after `std::move`. So we overestimate the memory usage.
2. Bug in memory tracker when we overestimate the memory usage because of this:
```cpp
if (is_op_set) {
diff += static_cast<int64_t>(mi_usable_size(pv.GetJson()));
}
```
3. Bug in partial `JSON.SET` when we called `ShardJsonFromString` before starting the memory tracking
4. Bug in indexes for the `JSON.SET` command: #5054
To fix this, I introduced `json_family_memory_test` and `JsonAutoUpdater`.
It ensures that …
=> fix(json_family): Fix memory tracking for the JSON.SET command. THIRD PR

src/server/dfly_bench.cc
Some datastores are password protected and we would like to connect to those via dfly_bench.
* add password flag 
resolves  #5071
=> chore: add password flag to dfly_bench

src/core/compact_object.cc, src/core/compact_object.h, src/core/compact_object_test.cc
Specifically get rit of MaskEnum and replace it with explicit bits aliasing the mask. Reorganize the encoding bits to be able to store 4 states that include huffman encoding.
Solves the first part of #4880
=> chore: reorganize compact object mask bits

src/server/engine_shard.cc, src/server/engine_shard.h, src/server/journal/streamer.cc, src/server/server_family.cc, tests/dragonfly/cluster_test.py
=> feat: add migrated keys statistic

.devcontainer/ubuntu24/devcontainer.json, .devcontainer/ubuntu24/post-create.sh, CMakeLists.txt, src/core/compact_object.cc, src/core/compact_object_test.cc, src/core/detail/bitpacking.cc, src/core/sse_port.h, src/server/debugcmd.cc
Also, revert the performance bomb from #2564
=> chore: allow setting huffman tables via DEBUG COMPRESSION SET

src/facade/reply_builder.cc, src/facade/reply_builder.h, src/server/dragonfly_test.cc, src/server/main_service.cc, src/server/string_family.cc, tests/dragonfly/memcache_meta.py, tests/dragonfly/pymemcached_test.py
Support is added for the GETS command. A placeholder CAS token of 0 is always returned.
FIXES https://github.com/dragonflydb/dragonfly/issues/5033
=> feat(memcache): Add support for GETS

src/core/compact_object.cc, src/core/compact_object.h, src/core/compact_object_test.cc, src/core/huff_coder.cc, src/core/small_string.h
This requires implementing HashCode, operator== methods as well.
Fixes https://github.com/dragonflydb/dragonfly/issues/4880
=> chore: support fetching a huffman encoded string from CompactObj

src/server/rdb_load.cc, tests/dragonfly/replication_test.py
When hset is loaded from rdb, if a ttl is specified by the user, we recreate a `string_view` on top of the same memory location, `tset_blob_`, that was used for `val` earlier. This causes the `val` string view to point to the same memory location now as TTL has. For example if the `val` string view was 'x' earlier (points to `tset_blob_`, size 1), and `ttl` is `7777777`, `val` now becomes '7'.
To fix this val is now given it's own string. TTL is kept as string view as the pointer is not reused anywhere in the following loop.
FIXES #4992
=> fix(hset_family): Fix val being overwritten by TTL

src/facade/dragonfly_connection.h, src/server/main_service.cc, src/server/server_family.cc, tests/dragonfly/pymemcached_test.py
This PR fixes authentication handling for the Memcached protocol. The previous fix in PR [#5085](https://github.com/dragonflydb/dragonfly/pull/5085) was wrong, because it turned password off for TLS connection regardless of whether it was Redis or Memcached.
Changes:
- Updated test_memcached_tls_no_requirepass to run with password configured but use the Memcached client without authentication.
- Reverted changes for ValidateServerTlsFlags().
- Skip password for Memcached protocol regardless of whether TLS is enabled or not.
Now Dragonfly correctly handles authentication settings for both protocols simultaneously.
=> fix: memcached authentication handling

src/server/dfly_main.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5096
This PR fixes a crash when starting Dragonfly if the Memcached port is the same as the Redis port.
=> fix: memcached port has been already used crash

src/core/search/ast_expr.cc, src/core/search/ast_expr.h, src/core/search/lexer.lex, src/core/search/parser.y, src/core/search/search.cc, src/core/search/search_parser_test.cc, src/core/search/search_test.cc, src/core/search/tag_types.h
This PR adds syntax parsing support for suffix (*term) and infix (\*term\*) search patterns. While the actual search implementation remains placeholder, this PR establishes the full parsing pipeline from lexer/parser through to AST nodes and query execution.
The foundation is now in place for future implementation of the actual search algorithms.
Related issues: 
- https://github.com/dragonflydb/dragonfly/issues/4982
- https://github.com/dragonflydb/dragonfly/issues/4983
=> chore: Add suffix and infix search syntax support in query parser

src/redis/CMakeLists.txt, src/redis/t-digest.LICENSE.md, src/redis/td_malloc.h, src/redis/tdigest.c, src/redis/tdigest.h
=> chore: import t-digest-c lib

src/core/search/compressed_sorted_set.cc, src/server/common.cc, src/server/common.h, src/server/generic_family.cc, src/server/generic_family_test.cc
`MINMSZ <len>` - keeps keys with values, whose allocated size is greater or equal to the specified length.
=> feat: add HELP SCAN and MINMSZ filter

src/server/debugcmd.cc, src/server/main_service.cc, src/server/main_service.h, src/server/multi_command_squasher.cc
refactor code a little. Command context can store some additional intermediate information, so using it we can avoid double calculations. 
For example, instead of a  transaction, we can store the Slot Id in the command context.
=> refactor: provide CommandContext into InvokeCmd

src/server/dfly_bench.cc
If dfly_bench runs against a cluster where auth is enabled, we have to send the password before fetching cluster info. This sets up each shard's endpoint correctly. Not doing so causes errors when handling `move` response, where hostnames are treated as ip addresses.
=> dfly_bench: Send auth if required before cluster setup

src/core/intrusive_string_list.h, src/core/intrusive_string_set.h, src/core/intrusive_string_set_test.cc
=> Adding object memory tracking

src/core/compact_object.cc, src/core/compact_object.h, src/server/main_service.cc, src/server/rdb_save.cc, src/server/tdigest_family.cc, src/server/tdigest_family.h
The following commands are implemented:
* create
* add
* rank
* revrank
* byrank
* byrevrank
* reset
* info
* min
* max
* cdf
=> chore: add tdigest commands

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/dragonfly_listener.cc, src/facade/tls_helpers.cc
1. Move no_tls_on_admin_port to listener, stop creating SSL_CTX objects on listeners that do not need it.
2. Make suites selection for tls1.2 and tls1.3 configurable at runtime.
=> chore: tls improvements

src/facade/resp_expr.h, src/server/CMakeLists.txt, src/server/tdigest_family.cc, src/server/tdigest_family_test.cc
* fix ByRank replies
* add basic test
=>  chore: fix ByRank replies and add basic tests

src/server/stream_family.cc, src/server/stream_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5120
Additional checks for the following argument were added after the key for the XTRIM command.
=> fix: XTRIM command crash

src/core/search/lexer.lex, src/core/search/parser.y, src/core/search/search_parser_test.cc, src/core/search/search_test.cc
Also fix the order of alias and the runtime arguments in KNN query.
Making sure that this query:
`"FT.SEARCH" "user-idx" "*=>[knn 3 @embedding $vector EF_RUNTIME 5 as vector_distance]" "RETURN" "1" "vector_distance"  DIALECT 2   "params" "2" "vector" "\n\xd7#>{\x14\xae\xbeH\xe1z?\x1f\x85k>"`  is parsed correctly.
=> fix: make search keywords case insensitive

src/server/tdigest_family.cc, src/server/tdigest_family_test.cc
Fixes a bunch of bugs around command replies for tdigest functions and adds tests.
* fix bugs around command replies
* add tests
=> chore: add tests

src/facade/reply_builder_test.cc, src/facade/reply_capture.cc, src/server/debugcmd.cc
The bug - we have not unwinded collections correctly. Apparently, we did not have testing coverage for CapturingReplyBuilder because the test was disabled due to historic reasons.
The fix: enable the test, make sure it reproduced the problem and fix the bug by correctly updating the pending collection length.
Fixes #5132
=> fix: collapsing logic in CapturingReplyBuilder

src/core/compact_object.cc, src/core/compact_object.h, src/redis/redis_aux.h, src/server/CMakeLists.txt, src/server/acl/acl_commands_def.h, src/server/main_service.cc, src/server/rdb_save.cc, src/server/topk_family.cc, src/server/topk_family.h
Add basic support for topk data structure in compact object and also implement prototypes for topk.reserve, topk.add and topk.list.
* add support for topk ds in compact object
* add topk.reserve prototype
* add topk.add prototype
* add topk.list prototype
=> chore: add basic TOPK commands

src/facade/CMakeLists.txt, src/facade/dragonfly_connection.cc, src/facade/socket_utils.cc, src/facade/socket_utils.h, src/server/cluster/incoming_slot_migration.cc, src/server/cluster/outgoing_slot_migration.cc, src/server/common.cc, src/server/protocol_client.cc, src/server/replica.cc, src/server/replica.h, src/server/server_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5041
This implementation enhances error diagnostics when replica connections fail by implementing a utility function that extracts and formats detailed TCP socket information from /proc/net/tcp and /proc/net/tcp6 on Linux systems.
The function converts raw socket data into a human-readable format with proper TCP state names and formatted IP addresses. It's integrated with Replica, Connection, and Migration components to provide better context during connection failures.
=> fix: improved socket error logging for connection diagnostics

src/core/detail/bitpacking.cc, src/core/sse_port.h
Fixes the regression introduced by #5083
The bug: accessing 2 bytes out of bounds when reading the source string. While the algorithm discards those bytes when doing decoding, it still can cause segfaults because these two bytes could belong to a new memory page that is not part of the process space.
=> fix: out of bounds SIMD access

tests/dragonfly/replication_test.py
The test changed in this PR `test_replica_reconnect` is failing often where the replica does not see updated master link status, after master is terminated. The replica code path may take some time to set the flags in its state mask. Adding a sleep may help with avoiding this test failure.
=> pytest: Add sleep to let master stop propagate to replica

src/core/compact_object_test.cc, src/core/detail/bitpacking.cc
for ascii pack and unpack,
Also optimize scalar unpack for both x86 and aarch64.
We had to fix the bug in https://github.com/dragonflydb/dragonfly/pull/5140 and now we load chunks of 7 bytes
during unpacking. This greatly degraded the performance of
scalar unpack, so we now use the "naive" byte by byte implementation
which actually faster then using 7-byte loads on both x86 and aarch64.
On c4a (aarch64):
Benchmarks before:
```
------------------------------------------------------------
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
BM_PackNaive             222 ns          222 ns     18936335
BM_Pack                  222 ns          222 ns     18956309
BM_Pack2                 222 ns          222 ns     18951694 …
```
=> chore: enable simd optimizations for aarch64

src/server/hll_family.cc, src/server/hll_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5159
PFCOUNT command crashes when arguments include keys of different types (regular strings and HyperLogLog) due to improper WRONG_TYPE error handling in the transaction flow.
Fixed PFCountMulti to properly propagate WRONG_TYPE errors. Modified callback to always return OpStatus::OK while tracking errors separately.
=> fix: Prevent crash in PFCOUNT when using keys of different types

src/server/search/doc_accessors.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5125
This PR addresses the issue of excessive "Invalid Json path" warnings in the logs when using computed fields (e.g., vector_distance from KNN search) in FT.SEARCH RETURN clauses.
Although the search functionality itself worked correctly and returned the computed values, these warnings cluttered the logs unnecessarily.
This change modifies `JsonAccessor::GetPath` to use `VLOG(1)` instead of `LOG(WARNING)` when a JSON path cannot be parsed or an expression cannot be created. This silences these specific warnings under normal log levels, as they are not indicative of an actual error when dealing with fields that are computed and not expected to be found within the JSON document structure.
This approach simplifies the solution by …
=> chore: lower log level for harmless "Invalid Json path" warnings

src/core/dash.h, src/core/dash_internal.h, src/core/dash_test.cc, src/server/db_slice.cc
1. Removed unused Segment::MoveFrom function.
2. Reduce reliance on kTotalBuckets constant
=> chore: refactorings in dash code.

src/core/dash.h, src/core/dash_internal.h, src/core/dash_test.cc, src/server/db_slice.cc
1. Currently, memory resource is not used - only passed if needed.
This is needed for https://github.com/dragonflydb/dragonfly/issues/5073
2. HotspotBuckets are renamed to HotBuckets.
3. Move TryInsertToBucket function to bucket level
=> chore(dash_table): pass memory resource to segment

src/facade/redis_parser.cc, src/facade/redis_parser.h, src/facade/redis_parser_test.cc
If simple response or error message is split we should still able to parse it correctly. If eol is not found in first message we are switching to bulk state where we consume messages until we read bulk correctly. Each split message will append data to bulk string until '\r\n' is found.
Fixes #5113
=> fix(parser): Parse correctly split simple response or error msg in client mode

src/server/json_family.cc, src/server/json_family_memory_test.cc, src/server/search/search_family_test.cc
fixes #5055
This PR fixes several issues in JSON.DEL command - we didn't update the indexes and track the memory usage at all. One of the bugs is good described in #5055.
=> fix(json_family): Fix memory tracking for the JSON.DEL command. FIFTH PR

src/server/cluster/cluster_defs.h, src/server/cluster/cluster_family.cc, src/server/cluster/incoming_slot_migration.cc, src/server/cluster/incoming_slot_migration.h, src/server/cluster/outgoing_slot_migration.cc, src/server/cluster/outgoing_slot_migration.h, src/server/conn_context.h, src/server/journal/executor.cc, src/server/journal/serializer.cc, src/server/journal/types.h, src/server/main_service.cc, src/server/protocol_client.cc, src/server/protocol_client.h, tests/dragonfly/cluster_test.py, tools/cluster_mgr.py
If applying command on incoming node will result in OOM (we overflow
max_memory_limit) we are closing migration and switch state to FATAL.
=> fix(cluster_family): Cancel slot migration from incoming node on OOM

tests/dragonfly/seeder_test.py
=> fix: timeout for test_seeder_key_target

src/server/zset_family.cc, src/server/zset_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5204
The issue:
ZCOUNT command crashed with assertion failure when min > max (e.g., `ZCOUNT key 945 261`). The assertion `range.min <= range.max` in `SortedMap::Count()` was triggered, causing the server to crash.
The solution:
Added early validation in `OpCount()` function to return 0 immediately when `range.min > range.max`, before calling `SortedMap::Count()`.
=> fix: ZCOUNT crash when min > max

tests/dragonfly/cluster_test.py
Add additional sleep between waiting for cluster status and SLOT-MIGRATION-STATUS request. There is rare timing issue when we set status to FATAL but error message is still not available.
Closes #5208
=> fix(pytest): Sleep in sporadically failing test_slot_migration_oom pytest

src/facade/memcache_parser_test.cc, src/server/conn_context.h, src/server/main_service.cc
When the GAT command is supplied, store the expiry within the memcache flag, also add and set an enum value for setting expiry within the same flag.
We still call MGETS for now, and the expiry value is unused. A future PR will implement the changes for applying the expiry.
a continuation of https://github.com/dragonflydb/dragonfly/pull/5199
=> (string_family): Add priliminary support for GAT

src/core/dash.h, src/core/dash_internal.h, src/core/dash_test.cc
Does not change functionality.
bucket_count is currently constant for a segment so the additional arithmetics do not affect bucket_count_.
=> chore: minor changes in dash code

src/server/engine_shard.cc, src/server/engine_shard.h, src/server/transaction.cc, src/server/transaction.h
The motivation: to narrow down a rare crash issue happenning around stale continuation_trans_ pointer.
The goal is to inspect these variables when a similar crash happens again.
=> chore: maintain meta information around continous transactions

src/server/search/search_family.cc, src/server/search/search_family_test.cc
Adds `self_time` to the profile and switches to resp3 instead of arrays of strings
=> chore(search): Add self time and resp3 format to ft.profile

src/server/bitops_family.cc, src/server/bitops_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5237
- Fixed BITFIELD SET overflow saturation: Now correctly returns old values.
- Fixed BITFIELD INCRBY calculations: Corrected increment logic to return proper values.
- Fixed type validation: Now properly rejects uppercase type specifiers (e.g., "I8" instead of "i8").
- Fixed UIntOverflow wrap logic: Changed from modulo to bitwise AND for proper wrap-around behavior.
=> fix: BITFIELD: overflow handling, type validation, and return values

src/facade/cmd_arg_parser.h, src/server/conn_context.cc, src/server/conn_context.h, src/server/debugcmd.cc, src/server/list_family.cc, src/server/list_family_test.cc, src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/multi_test.cc, src/server/set_family_test.cc, src/server/transaction.cc, src/server/zset_family_test.cc
Fixes #5247 
Issue:
1. Even when EVAL was non-transational (zero keys and no flags), it still initialized the transaction partially
2. MultiSwitchCmd was still called for non-transational commands, which was ok is the transaction was initialized fully or not at all
3. Combining (1) and (2), EVAL was wrongfully setting up a transation, which was then DCHECKed in (2)
Fix:
1. Correctly filter out zero keys commands
2. Call MultiSwitchCmd only for transactional (CO::Transactional) commands (includes empty eval)
3. Guard better against potential zero keys commands: lmpop, zmpop
4. Small list family cleanup
=> fix(transaction): Fix non-transactional multi/exec transaction access

src/server/search/doc_index.cc, src/server/search/search_family_test.cc
Fix crash for empty keys in `ShardDocIndex::DocKeyIndex`
=> fix(search_family): Fix empty key bug

src/core/dash_internal.h, src/core/dash_test.cc, src/server/search/search_family_test.cc
Also, relax SearchNonNullFields some checks that break if we change dashtable internals due to change of items ordering in the table.
=> chore: minor fixes in dash table

src/core/json/detail/jsoncons_dfs.cc, src/core/json/detail/jsoncons_dfs.h, src/core/json/jsonpath_test.cc, src/core/json/path.cc, src/core/json/path.h, src/server/json_family.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5259
This PR resolves an issue where JSON.DEL failed to remove all targeted elements when a JSONPath expression (e.g., $..a) matched multiple nodes within a JSON object.
The bug was caused by using forward iteration while deleting from a collection, which resulted in skipping elements as indices shifted during the mutation.
The solution implements a context-aware traversal strategy:
- Reverse traversal is now explicitly used for delete operations, guaranteeing that all matched nodes are processed and removed correctly.
- Forward traversal is preserved for non-destructive mutations (e.g., updates), for which it is safe and efficient.
This approach ensures JSON.DEL is robust and predictable without impacting other mutation commands.
=> fix(json): Ensure full deletion for multi-match JSONPaths

src/facade/dragonfly_connection.cc, src/server/conn_context.cc
When connection is subscribed to channel we are receiving async messages and sending them back to client. When UNSUBSCRIBE is received on same connection it can happen that we are starting to send back data in batch mode. In batch mode we will be aggregating responses until flush. Last message in queue should flush during reply but if it didn't (i.e. PubSub message was discarded) we are going to flush manually.
Fixes #5139 #5251
=> fix(reply_builder): Flush if last message didn't reply and flush but supose to

src/facade/dragonfly_connection.cc, src/facade/facade.cc, src/facade/facade_types.h, src/server/common.cc, src/server/common.h, src/server/engine_shard_set.cc, src/server/main_service.cc
Use it for memory related flags
Also change pipeline_squash to 1 by default.
=> chore: move MemoryBytesFlag to facade

tools/replay/main.go, tools/replay/workers.go
Introduces CLI flag -skip-time-min (int) to skip the first N minutes of recorded traffic.
=> chore: add -skip-time-min flag to skip initial N minutes during replay traffic

src/server/generic_family.cc, src/server/generic_family_test.cc
Added Store option in Sort command as mentioned [in this comment](https://github.com/dragonflydb/dragonfly/issues/3886#issuecomment-2395547969) which is in issue #3886. Please review this PR in the meanwhile I will start with SORT_RO command implementation.
=> feat: Added store option for sort command.

src/server/generic_family.cc
fixes: #5295
problem: we could return an error status for the deserialization operation during the transaction
=> fix: prevent rename cmd crash

src/server/search/search_family_test.cc, src/server/string_family.cc
fixes dragonflydb#5215
The problem was that the `StringFamily::Set` command could change the key's type. If the previous type was `HSET` or `JSON`, the key was indexed. When `StringFamily::Set` is called on such a key, it changes the type from HSET/JSON to STRING, but we forgot to remove the key from the indexes.
This PR adds a call to `RemoveDoc` inside `StringFamily::Set` to properly clean up the old index entry.
A snippet that reproduces the issue has been added to the tests, along with explanatory comments:
```
127.0.0.1:6379> ft.create index on hash schema field TEXT
OK
127.0.0.1:6379> hset k1 field value
(integer) 1
127.0.0.1:6379> set k1 anothervalue
OK
127.0.0.1:6379> rename k1 anotherkey
OK
127.0.0.1:6379> hset k1 field value
Error: Server closed the connection
(1.29s)
```
=> fix(string_family): Add RemoveDoc for the SET command

src/server/db_slice.cc, src/server/db_slice.h
This is done in preparation to fix bugs around memory accounding in the rename command"
=> chore: minor refactoring around AutoUpdater

src/server/string_family.cc
A couple of functions are extracted from the MGet command. In a follow up PR, the GAT command will be added which
will reuse some of the functions:
- A function to collect keys is extracted. This takes a function as input which will return an iterator for one key. The iterator can be mutable or immutable, for MGet it is immutable. For GAT it will be mutable.
- A check is added such that a read-only command does not use a function returning a mutable iterator.
- Another function is created to reorder collected results based on the shards of the keys and the original order of the keys in the command.
For context, the original PR is https://github.com/dragonflydb/dragonfly/pull/5257
=> chore(string_family): Refactor to prep for adding the GAT command

src/server/bitops_family.cc, src/server/bloom_family.cc, src/server/db_slice.cc, src/server/db_slice.h, src/server/dragonfly_test.cc, src/server/hll_family.cc, src/server/hset_family.cc, src/server/json_family.cc, src/server/list_family.cc, src/server/set_family.cc, src/server/stream_family.cc, src/server/string_family.cc, src/server/zset_family.cc
fixes dragonflydb#5271
This PR introduces an `unsigned req_obj_type` parameter to the `AddOrFind` method (with the main changes located in the db_slice files). It also verifies that all usages of AddOrFind across the codebase behave as expected.
=> chore(db_slice): Add object type to AddOrFind

src/facade/memcache_parser_test.cc, src/server/acl/acl_family_test.cc, src/server/conn_context.h, src/server/dragonfly_test.cc, src/server/main_service.cc, src/server/string_family.cc, src/server/string_family.h, src/server/test_utils.cc, tests/dragonfly/replication_test.py
A new command is added to the string family called `GAT` which implements the memcache get and touch semantics. The command syntax is `GAT <expiry-seconds> key [keys...]`.
Most of the changes in the PR are related to extracting common code from the `MGET` path to be reused for `GAT`. 
A collection function is extracted which takes a search function to search for an individual key and collect results across many keys. Search has a dbslice iterator template parameter which can be mutable or immutable, depending on the command invoking it.
A runtime check is made such that a read only command does not invoke the helper with a mutable iterator.
Follow up of https://github.com/dragonflydb/dragonfly/pull/5199
The `GATS` command is also implemented, it returns a placeholder CAS version of 0 for …
=> Implementation of memcache GAT and GATS commands

src/core/json/detail/jsoncons_dfs.cc, src/core/json/detail/jsoncons_dfs.h, src/core/json/jsonpath_test.cc, src/core/json/path.cc, src/core/json/path.h, src/server/json_family.cc, src/server/json_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5259
Issue:
`JSON.DEL doc "$..a"` was returning 2 instead of 1 when deleting nested objects with the same key name, because both parent and child deletions were counted separately.
Solution:
Added filtering logic to avoid counting child nodes that are automatically deleted when their parent is removed. Only applies to recursive descent deletion operations where one object directly contains another with the same target key.
Testing:
- A unit test was added
- Fakeredis test was checked `poetry run pytest -s test/test_json/test_json.py  -k test_json_delete_with_dollar`
=> fix(json): JSON.DEL recursive descent duplicate counting for nested same-key elements

src/core/dfly_core_test.cc, src/core/glob_matcher.cc
Also add more edge-case tests taken from Valkey.
=> chore: integrate Valkey fixes into stringmatchlen_impl

src/server/multi_command_squasher.cc, src/server/multi_test.cc, src/server/transaction.cc
Fixes #5272 
We have a fast path for single key commands - fast, because we know ahead it's single shard. I didn't implement bonus key handling there, because they always have at least two commands. Except when squashing, we choose this fast path as we know again ahead of time that it will be only a single shard.
=> fix: Handle bonus key + init error in squashing

.github/workflows/ci.yml, src/core/compact_object.cc, src/core/qlist.h, src/redis/redis_aux.c, src/redis/redis_aux.h, src/server/container_utils.cc, src/server/container_utils.h, src/server/debugcmd.cc, src/server/list_family.cc, src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/rdb_save.h, tests/dragonfly/instance.py
c-based quicklist code was being sunset since 01/25. This PR removes all the references to the quicklist encoding, greatly simplifying list related logic.
=> chore: get rid of quicklist encoding

src/server/snapshot.cc, src/server/snapshot.h, tests/dragonfly/replication_test.py, tests/dragonfly/tiering_test.py, tests/dragonfly/utility.py
The issue - during the snapshotting
we tried to fetch the same delayed entry which lead to data-races and deadlocks.
The fix - to pull the entry into a stack before preempting,
ensuring each fiber handles its own entry.
Fixes https://github.com/dragonflydb/dragonfly/issues/4965
=> fix: data race when doing a snapshot in cache mode

src/core/search/base.h, src/core/search/indices.cc, src/core/search/indices.h, src/core/search/search.cc, src/core/search/sort_indices.cc, src/core/search/sort_indices.h
Fixes non-sortable results from GetAllResults methods and improves performance of these methods.
Changes in this PR:
1. Fix null_values in SortIndex. It didn't use polymorphic allocator before
2. Small performance improvement for `NumericIndex`: in the `GetAllResults` method we’re calling the `Range` method, which performs two `lower_bound` operations on the `entries_` tree. But this overhead is unnecessary — we just need to traverse the entire tree.
3. Small performance improvement for `SimpleValueSortIndex`: in the `GetAllResults` method we checked `!null_values.contains(id)`, but that doesn’t make sense — we don’t add null values to `values_`, and such entries also wouldn’t pass the check for an empty value
FIRST PR of perfomance improvements
=> chore(search_family): Minor performance improvements to GetAllResults methods. FIRST PR

src/core/search/indices.cc, src/core/search/indices.h, src/core/search/search_test.cc
When index consists of only singular values per document, we do not have to deduplicate doc ids during query time.
Benchmarks:
Before the PR:
```
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
BM_SearchDocIds/0       7238 ns         7238 ns       388043
BM_SearchDocIds/1      30202 ns        30200 ns        89480
BM_SearchDocIds/2      20986 ns        20984 ns       133450
```
After:
```
Benchmark                  Time             CPU   Iterations
------------------------------------------------------------
BM_SearchDocIds/0       7071 ns         7070 ns       406632
BM_SearchDocIds/1      13149 ns        13142 ns       218935
BM_SearchDocIds/2      11870 ns        11868 ns       236922
```
=> chore: avoid deduplicating docs ids when not needed

src/CMakeLists.txt, src/server/CMakeLists.txt, src/server/acl/acl_family.cc, src/server/command_registry.cc, src/server/command_registry.h, src/server/conn_context.h, src/server/main_service.cc, src/server/main_service.h
Mostly a boilerplate PR, should not change functionality.
1. reduce number of absl::GetCurrentTimeNanos() calls by one during the command execution.
2. add hdr_histogram object to CommandId but do not yet record anything into it.
First part to address #5092
=> chore: add hdr_histogram to the project

src/core/dash.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/rdb_load.cc, src/server/replica.cc, src/server/server_family.cc, src/server/snapshot.cc, src/server/snapshot.h, tests/dragonfly/replication_test.py
This PR introduces new logic for replication - no point in time , enabled/disable by flag use_snapshot_version
The new logic improves server throughput during full sync replication.
The new logic:
Replica needs to be eventually equal to master data (after full sync state) therefore we do not need to create a point in time snapshot to replicate the master data.
In this PR when traversing master data to replicate and send to replica we dont care about bucket snapshot version. The main fiber serializes the data, OnDbChange - a hook to serialize the data before a write op is done is empty, OnMove - a hook to serialize the data when items are moved in dash table, this is relevant as when inserting new items to dash some items can be moved to other buckets, OnJournalChange - continues …
=> feat (server) : introduce no point in time replication

tests/dragonfly/replication_test.py
Increase allowed diff to be `1` instead of `0`. Reason for this is that extra PING is going to be sent during TAKEOVER so replica_1 and replica_2 are not going to be in sync. And no partial sync is done on second TAKEOVER.
Fixes #5359
=> fix(pytest): Increase allowed diff in test_partial_replication_on_same_source_master

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/dragonfly_listener.cc
We override globally c++ new/delete in dfly_main.
Therefore it is not needed anymore to use custom mimalloc specific allocators.
=> chore: remove unneeded mimalloc-specific code

patches/mimalloc-v2.2.4.patch, src/external_libs.cmake
This only adds it to the buld files.
We currently use helio dependency. This PR adds mimalloc of a newer version directly to dragonfly as mimalloc2. The goal is to switch to mimalloc2 in the future.
=> chore: add mimalloc2 third_party library

src/server/replica.cc
Root cause:
During sync phases (`R_SYNCING` and `R_SYNC_OK`), connection disconnects are common and expected
Solution:
Modified `LOG_REPL_ERROR` to use state-based logging
=> fix(replication): reduce ERROR to WARNING for connection issues during sync

src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
Fix clang-tidy warnings in zset_family code as well.
Fixes #5374
=> fix(zset): expand parsing of rank arguments beyond int32

tests/dragonfly/replication_test.py
=> test: replication_test.py::test_bug_in_json_memory_tracking enabled

tests/dragonfly/replication_test.py
Disable cache mode in pytest test_replication_all until #5371 is fixed.
=> chore: Disable test_replication_all cache mode

src/server/snapshot.cc, tests/dragonfly/replication_test.py
The bug:
big_value_mu_ was missing in SliceSnapshot::OnMoved therefor rdb on big value could get corrupted.
added the big_value_mu_ and a test
=> fix(server): fix serialization on move with big values

contrib/charts/dragonfly/README.md, contrib/charts/dragonfly/values.yaml
This PR fixes minor typos in the Helm chart documentation:
- Corrected a typo in the `values.yaml`
- Fixed a matching typo in the `README.md` file
These changes improve clarity and consistency for users deploying Dragonfly with Helm. 
No functional code changes were introduced.
=> fix(values): fix typos in Helm README and values file

src/server/error.h, src/server/rdb_load.cc, src/server/rdb_load.h, src/server/rdb_save.cc, src/server/rdb_test.cc
fixes: https://github.com/dragonflydb/dragonfly/issues/5299
problem: we do expiration during serialization and save 0-size hmap or set that is incorrect
fix: avoid expiration during serialization and filter out expired hmap and set during loading
=> fix: no set/hmap expiration during serialization

src/server/detail/save_stages_controller.cc, src/server/detail/save_stages_controller.h, src/server/dflycmd.cc, src/server/error.cc, src/server/error.h, src/server/rdb_load.cc, src/server/rdb_load.h, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/rdb_test.cc, src/server/server_family.cc, src/server/server_family.h
fixes: https://github.com/dragonflydb/dragonfly/issues/5284
Problem: Currently, different dfs snapshot files can be loaded as part of the same logical snapshot if they have the same name pattern.
Fix: Added SnapshotId AUX field into dfs files to distinguish files that can belong to another snapshot
=> feat: add snapshot-id field into dfs files

tests/dragonfly/replication_test.py
REPLTAKEVER fails when we are replication from 4 proactor threads to 2. Increasing timeout should fix this test.
Closes #5360
=> fix(pytest): Increase REPLTAKOVER time in test_take_over_seeder

src/server/command_registry.cc, src/server/command_registry.h, src/server/dragonfly_test.cc, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/server_family_test.py
Command latency is recorded in its histogram when command is invoked. 
When `info latencystats` is run, the latency for a fixed set of percentiles (50,99,99.9 by default) is returned per command. 
Currently the percentiles are fixed, but in a later PR these should be made configurable as command line option as well as `config set`.
FIXES #5092
=> server_family: Expose command latency stats as part of info

src/core/dash.h, src/facade/CMakeLists.txt, src/redis/CMakeLists.txt, src/server/common.cc, src/server/common.h, src/server/dfly_main.cc, src/server/memory_cmd.cc, src/server/server_family.cc, tests/dragonfly/memory_test.py, tests/dragonfly/replication_test.py
1. Use mimalloc 2.2.4 in Dragonfly project and stop relying on mimalloc in helio.
2. Fix a minor inefficiency in CanGrow, where we unnecessary called CanGrow twice.
Experimental runs on long-running production workloads show improvements with using mimalloc 2.2.4. Now it releases RSS more aggresively. The snapshot below demonstrates the improvement.
Before July 1, the datastore was running v1.29 and it is possible to see the huge difference between Used and RSS metrics. Since July 1, the datastore was running a version with mimalloc2 and it is possible to see how RSS memory follows `Used`. The peak on July 2, 18:00 is especially interesting as it shows a sudden spike in `Used` that caused RSS to grow significantly and then going back once `Used` went down. Before the switch the datastore …
=> chore: switch to mimalloc2

src/core/search/range_tree.cc, src/core/search/range_tree.h
This PR just does small changes in code (fixes comments in prev PRs).
1.  changes std::pair<double, double> to double for RangeTree keys
2. changes SkipUnvalidEntries to SkipInvalidEntries
3. Remove std::pair<iterator, iterator> from heap
=> chore(range_tree): Simplify RangeTree code

src/server/command_registry.cc, src/server/command_registry.h, tests/dragonfly/server_family_test.py
When command `config resetstat` is called, reset (clear out) all histograms for commands.
=> server_family: Support resetting latency histogram

src/core/compact_object.cc, src/core/compact_object.h, src/core/compact_object_test.cc, src/server/debugcmd.cc, src/server/main_service.cc
Before that, #4880 added huffman support for keys. This PR allows passing a separate table for string values. The table is not used by anything, so no functional changes are expected.
=> chore: allow initializing a separate huffman table for string values

src/core/search/indices.cc, src/core/search/indices.h, src/core/search/range_tree.cc, src/core/search/range_tree.h, src/core/search/range_tree_test.cc, src/core/search/search.cc, src/core/search/search_test.cc
TODO: PR description
Before:
| Benchmark                                                   | Time (ns) | CPU (ns) | Iterations |
|-------------------------------------------------------------|-----------|----------|------------|
| BM_SearchSeveralNumericAndTagIndexes/num_docs:10000         |   345431  |  345381  |     2021    |
| BM_SearchSeveralNumericAndTagIndexes/num_docs:100000        |  3132211  | 3132008  |      224    |
| BM_SearchSeveralNumericAndTagIndexes/num_docs:1000000       | 45877866  |45861242  |       15    |
After:
| Benchmark                                                   | Time (ns) | CPU (ns) | Iterations |
|-------------------------------------------------------------|-----------|----------|------------|
| BM_SearchSeveralNumericAndTagIndexes/num_docs:10000 …
=> feat(search_family): Introduce SingleBlockRangeResult and TwoBlocksRangeResult

src/facade/dragonfly_connection.cc, src/server/main_service.cc
Problem: During replication, we saw that the master disconnects from the replica. We don't have enough logs to understand the reason.
Fix: Added logs to 3 possible places where disconnecting can be triggered from.
=> chore: add more logs during replication

src/server/journal/streamer.cc, src/server/journal/streamer.h
The problem: when slot migration runs, it takes up majority of scheduling time and throttles io connections greatly. As a result, the write traffic throughput goes down almost to 0.
The solution: it's an intermediate solution that adds a tunable sleep to the migrations fiber.
=> fix: add a sleep to relax slot migration process

src/server/dflycmd.cc, src/server/rdb_load.cc, src/server/rdb_load.h, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/server_family.cc, src/server/server_family.h, src/server/snapshot.h
This PR adds aux-strings to the header of dfs files.
aux-strings do not break compatibility and potentially provide
better memory management and consistency checks during the snapshot load.
All in all this PR should not change functionality or compatibility
with older Dragonfly versons.
=> feat: add more auxillary strings to the snapshot

src/server/list_family.cc
This commit adds the `CO::NO_AUTOJOURNAL` command option for the `BLMPOP` command to disable default journaling. Also, the commit ensures that the `journal_rewrite` parameter is set to `true` when calling `OpPop`.
Resolves issue mentioned in #5370
=> fix: adjust BLMPOP command options and implementation for proper journaling

src/server/db_slice.cc, src/server/dragonfly_test.cc
Fixes issue where entries with zero-allocation values (like small integers) were not being evicted in cache mode, potentially causing memory bloat.
The previous implementation incorrectly skipped evicting entries where `HasAllocated()` returns false, but keys themselves consume memory and should be eligible for eviction.
Changes:
- Remove `!evict_it->second.HasAllocated()` check from eviction logic in `DbSlice::FreeMemWithEvictionStepAtomic`
- Add test `ZeroAllocationEviction` to verify entries with small values but long keys can be evicted
Fixes: [#5496](https://github.com/dragonflydb/dragonfly/issues/5496)
=> fix: allow eviction of zero-allocation entries in cache mode

src/server/debugcmd.cc, src/server/debugcmd.h
Currently, this command shows the histogram of segment sizes (occupancy) in the table.
=> feat: add debug segments command

src/server/dflycmd.cc, src/server/main_service.cc
Dragonfly closes idle connections after some time. It should skip replica connections that may find themselves idle but apperently not all replica connections were marked as such.
This pr marks replica flow connections as "replica_conn".
=> fix: prevent idle disconnects for replica flow connections

src/core/dfly_core_test.cc, src/server/debugcmd.cc
This is done because apparently zstd implementation can write out of bounds and cause crashes if counts are too high.
So we limit the counting per shard if we cross 1<<19 freq, and once we merge all the shards, we also scale down counts to be below 1<<23.
=> fix: reduce cardinality of the huffman histogram

src/server/rdb_save.cc, src/server/rdb_save.h, src/server/snapshot.cc, tests/dragonfly/replication_test.py
Serializing entries of a bucket during snapshot might contain large strings which potentially cross the serialization threshold imposed by `FlushIfNeeded()`. If the next element in the bucket is a big value (let's say a hash table), we will first serialize its first element of the container and then Flush which can lead to memory pressure. To avoid that, we call `FlushIfNeeded()` after we serialize each string.
Resolves #5394
=> chore: flush after serializing big string

tests/dragonfly/replication_test.py
I am skipping this because it fails all the time. It's impossible to raise PR's and merge.
=> chore: skip test_replication_onmove_flow

tools/replay/main.go, tools/replay/workers.go
Example:
```
./traffic-replay -ignore-parse-errors -time-limit 60 run /home/builder/traffic/traffic*
```
=> chore: -time-limit option was added to record traffic tool

src/facade/conn_context.h, src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/server/acl/acl_family.cc, src/server/main_service.cc, src/server/server_family.cc, src/server/server_state.cc
The issue is that `SendAsync` might preempt if the monitor connection needs to shut down because the pipeline buffer is over the limit. The fix is to move the ShutdownSelfBlocking to allow the async fiber and set the con_clossing to true.
* shutdown the connection within AsyncFiber instead of SendAsync
* rename ShutdownSelf to ShutdownSelfBlocking
=> chore: fix monitor preemption in atomic section

src/core/search/indices.cc, src/core/search/indices.h, src/core/search/range_tree.h, src/core/search/search.cc, src/core/search/search.h, src/core/search/search_test.cc, src/server/search/doc_index.cc, src/server/search/search_family.cc, src/server/search/search_family_test.cc, tests/dragonfly/search_test.py
Introduce the BLOCKSIZE option for numeric fields in the FT.CREATE command.
This option allows fine-grained control over the block size used by the range tree for each numeric index independently.
**How to use it?**
To control the latency of your range queries, you can use the `BLOCKSIZE` option. If you know the average number of documents matched by your range queries, setting the block size close to that average can significantly speed them up.
Setting the block size higher or lower does not necessarily mean your queries will be faster or slower — it depends on the actual results of your range queries.
**Tip:**
To estimate how many documents your query matches, you can use the `FT.PROFILE` command. After collecting some statistics, you can then tune the BLOCKSIZE accordingly for optimal …
=> feat(search_family): Add BLOCKSIZE option for FT.CREATE

src/server/json_family.cc, src/server/json_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5396
Implements proper RESP3 formatting for JSON commands:
- JSON.TYPE
- JSON.NUMINCRBY
- JSON.NUMMULTBY
Fixes JSON commands to follow RESP3 protocol.
=> feat: add RESP3 support for JSON.TYPE and JSON numeric operations

src/server/acl/acl_family.cc, src/server/acl/acl_family.h
The issue is that we called `TlsSocket::Shutdown` while traversing the connections. Since Shutdown is preemptive, it violates the atomicity guarantees of the operation.
Helps with #5524
=> fix(acl): preemptive TlsSocket::Shutdown in atomic section

tools/replay/main.go, tools/replay/workers.go
Add `compare-host` option to `traffic-replay` to compare results from different dragonfly versions
=> feat(traffic_replay): Add compare option

.gitignore, src/server/cluster/cluster_family.cc, src/server/cluster/incoming_slot_migration.h, src/server/db_slice.cc, tests/dragonfly/cluster_test.py
Enable migrations for shard flows on destination instance.
Benchmarking: 1M small keys 
||before|after|
|-|---|---|
|time|10s|8s|
|cpu (dest)| 100/400% | 60%/400%|
Note that increasing destination throughput increases source node cpu usage
=> feat(cluster): migrate thread on same shard config

src/core/dfly_core_test.cc, src/core/glob_matcher.cc, src/core/glob_matcher.h, tests/dragonfly/set_test.py
`GlobMatcher` constructor is extremely slow sometimes as it requires to compile the regex produced from the glob expression. A simple example is the small glob tested in the benchmark: `a*a*a*.pt` which takes roughly `70ms` to compile, `diminishing any of the performance gains produced by the fast matching`. There are ways to mitigate this but for now we should fall back to the plain and simple `stringmatchlen` which does penaltize the hot path (I will also time bound the SSCAN loop in a separate PR just like SCAN).
Results from running the benchmark locally on `release` build:
`./dfly_core_test --benchmark_filter=BM_MatchGlobSlow`
With `reflex` 
```
-----------------------------------------------------------
Benchmark                 Time             CPU   Iterations …
```
=> chore: use stringmatchlen in GlobMatcher

src/facade/dragonfly_connection.cc
`GetSocketInfo` is slow and when used frequently within a `LOG()` statement it can impose a significant amount of latency. From perf, it showed that 40% of cpu time was spent in that function, and specifically in `ReadTcpInfo`.
This PR reduces the time we call `LOG()` and removes the call to `GetSocketInfo` for the flow that it always returns "socket not found" (because the socket no longer exists in /proc/net/tcp and parsing it takes a big cpu slice).
=> chore: excessive logging in dragonfly connection

src/server/command_registry.cc
If histogram init fails, we should crash instead of using a null pointer as a histogram. 
init can fail for non-memory related reasons such as validations on the distance between lowest and highest values.
=> server: Check result of `hdr_init`

src/server/generic_family.cc, src/server/journal/cmd_serializer.cc, src/server/rdb_save.cc, src/server/rdb_save.h
Problem: During the cluster migration process, we waste CPU resources on CRC calculation
Fix: ignore CRC during the  migration process
=> feat: remove crc calculation for migration

tests/dragonfly/replication_test.py
Setting `point_in_time_replication` to `False` can result in failing test when master and replica have different values.
=> chore: Don't use point_in_time_replication = False in test_replication_all

src/external_libs.cmake, tools/packaging/Dockerfile.alpine-dev, tools/packaging/Dockerfile.ubuntu-dev
The top level `cmake` directory was removed in a recent PR, it is cleaned up from the dockerfile here so the https://github.com/dragonflydb/dragonfly/actions/workflows/docker-dev-release.yml action can run. 
Dockerfiles in that action still try to copy cmake directory and fail.
The patches directory is added because the build failed while trying to patch mimalloc2.
=> docker: Remove cmake dir from dockerfile which no longer exists, add patches dir

.github/workflows/ci.yml, src/redis/zmalloc.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/geo_family.cc, src/server/journal/cmd_serializer.cc, src/server/journal/streamer.cc, src/server/journal/streamer.h, src/server/table.h
This heuristic should replace the previous flags like --migration_buckets_sleep_usec and --migration_buckets_serialization_threshold which are still present as safeguards.
=> feat: introduce a CPU budget parameter to control slot migration pacing

src/core/search/base.h, src/core/search/block_list.cc, src/core/search/block_list.h, src/core/search/compressed_sorted_set.cc, src/core/search/compressed_sorted_set.h, src/core/search/index_result.h, src/core/search/range_tree.h, src/core/search/search_test.cc
Add block-level jumps to the BlockList, as well as power-of-two-length jumps based for base vector iterators.
This optimization speeds up merging for all index types, not just numeric indexes.
Before:
| Benchmark                                                  | Time (ns)  | CPU (ns)   | Iterations |
|------------------------------------------------------------|------------|------------|------------|
| BM_SearchNumericAndTagIndexes/num_docs:10000               | 12752      | 12751      | 5392       |
| BM_SearchNumericAndTagIndexes/num_docs:100000              | 1407975    | 1407833    | 497        |
| BM_SearchNumericAndTagIndexes/num_docs:1000000             | 11055515   | 11054017   | 64         |
| BM_SearchSeveralNumericAndTagIndexes/num_docs:10000        | 154778     | 154766     | …
=> feat(search_family): Speed up merging of index results

src/core/interpreter.cc, src/core/interpreter.h, src/core/interpreter_test.cc
problem: incorrect calculation of memory allocation/deallocation in the lua script, because of script is executing in different threads but statistic is thread_local
fix: every script calculates the used memory and statistic updates only in the corresponding thread where the script was get/returned
=> feat: fix lua memory deallocation and lua_mem_gc_threshold=0 disable lua force GC calls

src/server/server_family.cc
It was observed during an incident that server stopped accepting new connections due to high used memory, but the logs did not have messages to confirm this.
Logs are added, every 1000 entries to prevent excess logging fluctuating around the memory limit, although the caller `EngineShard::StartPeriodicShardHandlerFiber` also runs periodically.
=> server: Log warning if server stops accepting connections

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/facade.cc, src/facade/facade_types.h, src/server/config_registry.cc, src/server/config_registry.h, src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, src/server/server_family.cc, src/server/server_state.cc, src/server/server_state.h, tools/local/monitoring/grafana/provisioning/dashboards/dragonfly.json
Partially covers https://github.com/dragonflydb/dragonfly/issues/5630
1. Remove `pipeline_low_bound_stats` and instead introduce `squash_stats_latency_lower_limit` flag
that filters out latency stats based on the lower limit threshold.
2. Consolidate all the squashing metrics inside multi_command_squasher code.
3. Add `pipeline_queue_wait_duration_seconds`, `pipeline_dispatch_skip_flush_total`, `net_read_yields_total` metrics.
4. Reduce reliance on `ProactorBase::GetMonotonicTimeNs` as it's inaccurate - switch to CycleClock where possible.
5. Finally fix a bug where mismatch config type prevented us from using CONFIG SET and change the settings online.
=> chore: more pipeline latency coverage

src/server/geo_family.cc, src/server/geo_family_test.cc
The issue is that we called `std::partial_sort` on a range that's invalid: `begin + count > cont.size()` which triggers `ub`.
* fix ub
* add test
=> fix: ub in GEORADIUSBYMEMBER

src/server/set_family_test.cc, src/server/test_utils.cc, src/server/test_utils.h
It's cumbersome to call `Run()` every time with each command argument separately
=> chore: string_view overload for BaseFamilyTest::Run

src/core/string_map.cc, src/server/hset_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5623
The problem occurred during the conversion from listpack to StringMap when HEXPIRE was called. In `StringMap::ObjectClone()`, sds values were implicitly converted to `string_view` using the `const char*` constructor, which uses `strlen()` and stops at the first null character.
Changes:
- Use explicit `string_view(ptr, len)` constructor with `sdslen()` in `ObjectClone()`
- Add test case to verify null character preservation after HEXPIRE
=> fix: preserve null characters in hash values after HEXPIRE

src/core/compact_object.cc, src/core/page_usage_stats.cc, src/core/page_usage_stats.h, src/core/page_usage_stats_test.cc
Objects which are skipped during defragmentation fall in two categories:
* not required (eg INT_TAG)
* not supported but will require support (eg qlist)
The counts for both are tracked and reported, to make it easier to understand where defragmentation did not have an effect.
=> core: Track objects skipped during defragmentation

src/server/main_service.cc, src/server/server_family.cc, tests/dragonfly/cluster_test.py
`REPLTAKEOVER` in cluster mode does not shut down master. Now a node that is in `TAKEN_OVER_STATE` (i,e, repltakeover) is allowed to become a replica of another node via the `REPLICAOF` command. 
* allow REPLICAOF command in TAKEN_OVER server state and only in cluster mode
Resolves #5611
=> chore: allow replicaof in cluster mode when state is TAKEN_OVER

src/facade/dragonfly_connection.cc, src/server/main_service.cc, tools/local/monitoring/grafana/provisioning/dashboards/dragonfly.json
Fix pipeline_queue_wait_duration_seconds and pipeline_commands_duration_seconds with pipeline_dispatch_commands_total that before that did not take into account squash_stats_latency_lower_limit filter.
=> fix: accounting of metrics under squash_stats_latency_lower_limit filter

src/server/engine_shard_set_test.cc, src/server/set_family.cc, src/server/set_family_test.cc, src/server/test_utils.cc, src/server/test_utils.h, tests/dragonfly/set_test.py
We ignored the cardinality of the produced shard sets. So, for some inputs we would copy the largest set. If for example a set_a on shard 1 had 600m elements and the second set_b had 5, we would create a hash table of 600m elements instead of 5.
Resolves #5590
=> chore: sort per shard sorted sets for SINTER

src/server/json_family.cc, src/server/json_family_test.cc
If key exists and it has expiry after we use JSON.SET expiry object will not be removed. Now when creating JSON object with same name remove previous expiry object if it exists.
Fixes #5653
=> fix(json_family): Remove expiry of existing keys in JSON.SET

src/server/multi_command_squasher.cc, src/server/stream_family.cc
Fixes https://github.com/dragonflydb/dragonfly/issues/5690 #5695 #5694 #5689 #5688
The problem: we accessed the caller stack variables (max_exec_cycles) in MultiCommandSquasher::ExecuteSquashed.
The access was done after the call to `bc.Dec()`, which unblocks ExecuteSquashed.
As a result, the callback function that was still running could corrupt memory contents of some other variable
as ExecuteSquashed could exit by that time.
In addition, harden checks in stream_family.cc in StreamAppendItem.
Finally, we update helio which fixes https://github.com/dragonflydb/dragonfly/issues/5693
=> fix: stack corruption in MultiCommandSquasher

src/server/rdb_save.cc
Fixes regression crash: https://github.com/dragonflydb/dragonfly/actions/runs/17025808197/job/48261017365
Follow up: https://github.com/dragonflydb/dragonfly/pull/5655 
The Python test snapshot_test.py::test_parallel_snapshot_race_condition uncovered an additional case. It occurs only in the arm64/epoll environment.
I could reproduce it only on a large number of executions:
```
pytest -q tests/dragonfly/snapshot_test.py::test_parallel_snapshot_race_condition --df=force_epoll --df=proactor_threads=2 --df=num_shards=1 --repeat 20 -vv
```
Root cause: for single-snapshot flows (shard_snapshots_.size() == 1), the snapshot was destroyed from the caller thread, violating shard thread-affinity. In some paths, it could also lead to an indexing mismatch.
Fix: 
- Track the owning shard id on …
=> fix: RdbSaver: destroy SliceSnapshot on its shard thread to fix flaky crash on ARM64 with --force_epoll

src/server/geo_family.cc, src/server/geo_family_test.cc
The following bugs existed in geo commands:
1. reject with error if count 0
2. reject with* and store* options when used together
3. reduce result vector to count in SortIfNeeded even if the command has unsorted option
4. minor refactoring
* add tests
resolves #5692
=> fix: command parsing in geo family

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/flag_utils.h, src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, src/server/server_state.cc, src/server/server_state.h, src/server/tiered_storage.cc, src/server/tiered_storage.h
Before I add a few scheduler flags, I'd like to avoid creating a million setters
The idea is that by providing two functions, `UpdateFromFlags` and `GetMutableFlagValues`, we can let the registry know that it has to call the former whenever a flag from the latter changes. This way each class cleanly keeps its flags in it's own codebase and mutability can be enabled in a single line
=> chore(server): Semi-automatic flag updates

src/server/search/aggregator.h, src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/index_join.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
Join index_join with the FT.AGGREGATE command.
First PR is #5604
Most of the lines are from prev PR and also I added a lot of tests. Real number of lines is not so big
=> feat(search_family): Add LOAD_FROM to the FT.AGGREGATE command

src/server/search/doc_index.h, src/server/search/index_join.cc, src/server/search/index_join.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
Improve sorting and limiting in index joins.
Right now we apply SORTBY and LIMIT only after both join stages have finished—i.e., we (1) perform the join, and then (2) load all requested fields for every joined entry. Because there can be a lot of joined entries, we end up loading many fields we’ll later discard when sorting/limiting.
The fix is to apply SORTBY and LIMIT immediately after the first stage—right after we build the join result, but before we load per-entry fields. That way we only fetch fields for the top offset + total candidates (or whatever budget we choose), which speeds up the request — especially when most entries would be dropped by the final sort/limit anyway.
=> feat(search_family): Improve sorting and limiting in index joins

src/external_libs.cmake
Fixes: https://github.com/dragonflydb/dragonfly/actions/runs/17200686960/
Remove GIT_SHALLOW: shallow clones may miss the pinned commit SHA (when it’s not at the tip), causing checkout failures. A full clone reliably fetches that commit while preserving the exact pin; the only trade-off is a slightly larger download.
=> fix: macos and linux build

src/server/engine_shard_set.h, src/server/string_family.cc, src/server/string_family_test.cc
* server: Use nanoseconds to measure duration in throttle algorithm
Previously we used milliseconds to measure time units. However this causes issues when a sub-millisecond refill interval is required for the algorithm. To fix this we move here to nanosecond time units.
There are some issues which arise because of this, all of which are acceptable:
* We have to use the current time at the point of throttle function call as a representation of "now", instead of the start of transaction time.
* The retry after/reset after timestamps are still in ms during throttle calculation, so they lose some precision.
The former is acceptable, as although it will cause slightly more lenient throttling, the measure is at a sub-millisecond level. Similarly in case of the latter, it is hard to imagine a …
=> server: fix max emission limit in throttle command (cherry-pick to v1.33)

src/server/geo_family.cc, src/server/geo_family.h, src/server/geo_family_test.cc
Implements the `GEORADIUS_RO` command which is a read-only variant of the existing `GEORADIUS` command. Resolves #3882.
Command documentation can be found [here](https://redis.io/docs/latest/commands/georadius_ro/).
=> feat: Implement GEORADIUS_RO command

src/server/main_service.cc
Current documentation isn't giving all useful informations I think, cf:
```
dragonfly --help
[...]
--maxmemory (Limit on maximum-memory that is used by the database. 0 - means
the program will automatically determine its maximum memory usage.
default: 0); default: 0B;
```
=> as a user of DF that is configuring the datastore, how do I know what value to pass here ?
Easy fix here: let's just tell precisely the possible values in the description.
NB: I'm really not an expert in Dragonfly, so don't hesitate to review if the possible values are what should be recommended to use 🙏
=> docs: improve description of --maxmemory parameter (units/tiering/minPerThread)

src/core/task_queue.cc
TaskQueue is used to process callbacks from the requests. The hypothesis is that increasing its priority, we will reduce P99 latency of tasks that are being starved by other fibers.
=> chore: update task queue fiber priority to high

src/redis/rax.c, src/redis/rax.h, src/redis/t_stream.c, src/server/stream_family.cc, tests/dragonfly/cluster_test.py
Add check fails when we trim or delete list packs in stream code. Push check in low level functions of lp/stream code
=> chore: check fail for empty listpacks in streams

src/server/cluster/incoming_slot_migration.cc, src/server/main_service.cc
fixes: #5648
I've tested different options, and the current implementation allows me to see p99 < 400us on my PC during the whole migration process. migration speed decreased by 5-10%
=> feat: improve target node latency during migration

src/server/main_service.cc
Currently we allow 1024 uknown command with max length of 4096 characters to be stored in temporary vector. Create more strict rule that allows only 64 entries with max length of 20 chars.
Closes #5732
=> chore: Strict bounds when adding uknown command for INFO ALL stats

src/server/geo_family.cc, src/server/geo_family.h, src/server/geo_family_test.cc
This PR implements the read-only variant of the existing `GEORADIUSBYMEMBER_RO` command. The command documentation can be found [here](https://redis.io/docs/latest/commands/georadiusbymember_ro/).
Resolves #3881.
=> feat: Implement GEORADIUSBYMEMBER_RO command

src/server/dfly_bench.cc
Flag can be used to set fixed length of value  or used as range `min:max` where length of value will be randomly selected.
=> feat(dfly_bench): Generate value with random length

src/server/json_family.cc, src/server/json_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/5741
Fixes JSON RESP3 compatibility issue where JSON commands returned extra nested arrays instead of the expected format.
=> fix: JSON RESP3 compatibility - remove extra nested arrays for most commands

src/server/set_family.cc, src/server/zset_family.cc, src/server/zset_family.h, tests/dragonfly/replication_test.py
related to: #5413
problem: during full_sync phaze Z...STORE commands can create an incorrect result on the replica because some keys can be absent.
fix: Z...STORE operations transform into DEL ... and ZADD ... operations
=> fix: replication for Z...STORE commands

src/server/dragonfly_test.cc, src/server/main_service.cc
Previously when the lua legacy float flag was set, doubles would be sent as floats for RESP2 but for RESP3 this behavior was skipped. This changeset extends the behavior to RESP3 as well.
fixes https://github.com/dragonflydb/dragonfly/issues/5745
Note: the previous behavior was not a bug, but the flag needs to be extended to RESP3 now in response to real world requirements where third party libraries such as `redis_rate` use a RESP3 client but expect long values in response.
=> server: Enable lua legacy float response for RESP3

src/server/dflycmd.cc, src/server/journal/streamer.cc, src/server/journal/streamer.h
problem: we don't have enough logs to figure out the takeover failures.
fix: added more logs regarding JournalStreamer
=> chore: add more logs for takeover

patches/mimalloc-v2.2.4/3_track_full_size.patch, src/core/page_usage_stats.h, src/core/segment_allocator.cc, src/external_libs.cmake, src/redis/zmalloc.h, src/redis/zmalloc_mi.c, src/server/dragonfly_test.cc, src/server/engine_shard.cc
Before - we had relatively slow check for counting wasted fragmentation via zmalloc_get_allocator_wasted_blocks that took 10ms or more in production. The reason for that is that it iterate over all the memory pages on a single shard through the single call.
Now we implement an iterative version of it by iterating over a single page queue data-structure in the heap. Once we start the iterative process we will continue aggregating stats over all the page queues in the heap until we reach the end and then conclude if defragmentation is needed.
this should reduce the call time to EngineShard::DefragTaskState::CheckRequired by x70 (number of page queues in the heap).
=> chore: implement the iterative fragmentation check

src/server/conn_context.cc, src/server/conn_context.h, src/server/main_service.cc, src/server/multi_test.cc, src/server/server_family.cc, src/server/server_state.cc, src/server/server_state.h
A new label `conn_stored_commands` is added to the metric `memory_by_class_bytes`. This value tracks the total size of the `StoredCmd` objects held in `ConnectionState::ExecInfo` objects in the `body` vector.
The size is added as a field on the `ExecInfo` object and a separate set of methods is added to read and write the size on this object. 
The reason for doing this and not directly using `UsedMemory` method on `ExecInfo` is that `ExecInfo::UsedMemory` will iterate over the vector to find the size. In order to update the metric, when storing a new command we must add the delta introduced by the command. For this we must find the used memory before and after the new command is stored, and `UsedMemory` must iterate over the entire vector. As the vector size grows this can become …
=> server: metrics to track stored command sizes

src/facade/error.h, src/facade/facade.cc, src/facade/facade_types.h, src/server/cluster_support.cc, src/server/cluster_support.h, src/server/common.cc, src/server/common.h, src/server/config_registry.cc, src/server/config_registry.h
Since c++17 `inline` variables can be used for a _definition_ of a variable in a header file which is included in multiple source files. This avoids the need to use `extern` in the header and defining the variable in a source file.
The linker will merge the symbols from different translation units at link time.
https://en.cppreference.com/w/cpp/language/inline.html
=> facade/server: Use inline instead of extern to reduce loc

src/server/dfly_bench.cc
Sometimes when dfly_bench parses a response to extract host to connect to, it fails inside boost make_address. This error is thrown up the stack causing the program to fail without clear indication of what the error was. 
See example run https://github.com/dragonflydb/controlplane/actions/runs/17032489974/job/48277888480
Changed to use the `error_code` variant of `boost::asio::ip::make_address` to print the error with the address which failed to parse.
=> dfly_bench: Show error on failing to make address

src/facade/dragonfly_listener.cc, src/facade/dragonfly_listener.h, src/server/server_family.cc, tests/dragonfly/shutdown_test.py
Fixes: https://github.com/dragonflydb/dragonfly/issues/5444
- Parse SHUTDOWN options: SAVE, NOSAVE, SAFE, NOW, FORCE, ABORT
- SAVE and SAFE: unified behavior; snapshot happens during shutdown (no immediate save)
- FORCE: disables snapshot (save_on_shutdown=false) and enables fast shutdown
- NOW/FORCE: enable fast shutdown (skip graceful wait in Listener::PreShutdown)
- ABORT: returns error (not supported yet)
=> feat: SHUTDOWN: fast path for NOW/FORCE; unify SAVE/SAFE; support NOSAVE

src/core/page_usage_stats.cc, src/core/page_usage_stats.h, src/core/page_usage_stats_test.cc
Change bloom filter to hyperloglog as discussed in pr https://github.com/dragonflydb/dragonfly/pull/5560#issuecomment-3254082470
external usage of the page usage stats class does not change.
With HLL no storage is required for the page addresses which reduces memory usage, the code only needs to maintain a constant count of registers to estimate cardinality, which is what we need at the end of the defragment command.
Note: Dense hll is used here, sparse hll could be used and converted to dense (as a follow up). The count of page addresses per class can be less than the number of registers (16384), in this case sparse hll might take up lesser memory.
=> core: Replace sbf with hyperloglog

src/server/db_slice.cc, src/server/db_slice.h, src/server/debugcmd.cc, src/server/generic_family.cc, src/server/journal/cmd_serializer.cc, src/server/journal/cmd_serializer.h, src/server/journal/streamer.cc, src/server/journal/streamer.h, src/server/snapshot.cc, src/server/string_family.cc, src/server/tiered_storage.cc, tests/dragonfly/cluster_test.py
=> fix: stale pointer reference during slot migration and flush

src/server/rdb_load.cc, src/server/rdb_load.h
Motivation: Withhold partial values (big values that are still streamed) from the dashtable to prevent them from being involved in background processes, like tiered storage offloading for example. Allowing partial values to participate in those can break correctness
=> chore(rdb): Insert big values only after full construction

src/core/compact_object.cc, src/core/compact_object.h, src/core/compact_object_test.cc, src/server/debugcmd.cc, src/server/dragonfly_test.cc
1. Differrentiate huffman encoding for strings and values.
2. Fix "debug compression" to set huffman table for both domains.
=> chore: support huffman encoding for string values

src/server/server_family.cc
A metric was copy-pasted which resulted in a duplicate name.
Replaces the second name with `defrag_objects_moved`
fixes #5828
=> server: Fix metric name

src/server/db_slice.cc, src/server/db_slice.h, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/memory_test.py
Add SYNC option to FLUSHDB and FLUSHALL. SYNC doens't block other commands, it just waits for the flush to finish. The pytest asserts that immediately after FLUSHALL SYNC we have free RSS memory
Fixes https://github.com/dragonflydb/dragonfly/issues/5581
=> fix(server): Support FLUSH(ALL) SYNC

src/facade/command_id.h, src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/facade.cc, src/server/acl/validator.cc, src/server/channel_store.cc, src/server/channel_store.h, src/server/cluster/cluster_family_test.cc, src/server/command_registry.cc, src/server/command_registry.h, src/server/conn_context.cc, src/server/conn_context.h, src/server/db_slice.cc, src/server/main_service.cc, src/server/main_service.h, tests/dragonfly/cluster_test.py
* Refactor CommandId/CommanRegistry to unifromly determine the command "kind" and expose it via limited interface. Previously we used different approaches up to the authors liking
* Introduce `is_sharded` field to `PubMessage` to choose between "message" and "smessage" when replying
* Add simple "pubsub" test in cluster_family_test (not best place, but there was one before it 🤷🏻‍♂️ )
Fixes #5738
=> fix(server): Use correct messages for sharded pubsub

src/facade/error.h, src/facade/op_status.cc, src/facade/op_status.h, src/redis/util.c, src/redis/util.h, src/server/dfly_main.cc, src/server/hset_family.cc, src/server/hset_family_test.cc, src/server/string_family.cc, src/server/string_family_test.cc, tests/dragonfly/eval_test.py
problem: string2ld consumes 15KB of stack
fix: use absl::SimpleAtod() to convert string to double
before fix: stack usage was 31.2KB, after fix 16.4KB
=> fix: stack overflow in hincrbyfloat

.github/actions/repeat/action.yml, .github/workflows/repeat-tests.yml
Allows setting vmodule level for tests, eg:
```
gh workflow run "Repeat Tests" --ref abhijat/feat/vmodule-on-repeat-tests -f branch=abhijat/feat/vmodule-on-repeat-tests -f count=500 -f expression="-xv dragonfly -k test_client_kill" -f timeout=300m -f epoll=epoll -f vmodule_expression="server_family=2,dragonfly_connection=2,listener_interface=2"
```
note `-f vmodule_expression="server_family=2,dragonfly_connection=2,listener_interface=2"`
Also clean up to use `if` expression suggested in https://github.com/dragonflydb/dragonfly/pull/5805#discussion_r2349348492
=> ci: Allow overriding log level for modules when repeating tests

src/core/search/base.h, src/core/search/query_driver.cc, src/core/search/query_driver.h, src/core/search/search.cc, src/core/search/search.h, src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
Even it is deprecated FILTER can still be used as part of FT.SEARCH
command. Add support for it by reconstruction of AST tree.
Closes #5822
=> feat(search): FT.SEARCH FILTER option

tests/dragonfly/requirements.txt, tests/dragonfly/server_family_test.py
Adds a test which starts a prometheus container, the container scrapes dragonfly and runs for a few seconds.
The test confirms that there are no warning or error logs seen in the container.
FIXES https://github.com/dragonflydb/dragonfly/issues/5831
=> tests: Add test for prometheus metrics sanity check

src/server/replica.cc, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/replication_test.py
This PR implements the new ReplicaOf algorithm that does not use two phase locking.
**How ReplicaOf worked previously**:
1. stop the old replica -> dragonfly is processing read only commands normally
2. Set the flag to loading -> dragonfly stops processing read only commands because state is loading
3. create a new replica object 
4. release the mutex
5. allow the new replica object to do IO by connecting to the new master and exchange the necessary info to actually start the replication flow. -> This may fail yet we prematurely set the flag to loading and stopped the old replica
6. relock the mutex after the greet, clean up if the context got cancelled (by another replicaof command) or start the main replication fiber to properly start replication.
There are multiple issue with this:
1. …
=> chore: new ReplicaOf algorithm

src/core/search/lexer.lex, src/server/search/search_family_test.cc
fixes: #4999
Added the ability to search for any symbols in the tag
=> feat: add symbols search in tag

src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
Implements the `DD` (Delete Documents) option for `FT.DROPINDEX` command.
Fixes: https://github.com/dragonflydb/dragonfly/issues/5513
=> feat(search): Add DD option support for FT.DROPINDEX command
