dragonflydb/dragonfly

src/server/server_family.cc
Related to #46 (https://github.com/dragonflydb/dragonfly/commit/4d276c7ef0a1f04c3efddab7c10bca1e8ee820c2)
=> Fix info command to use git version

src/core/dash.h, src/core/dash_internal.h, src/core/expire_period.h, src/core/external_alloc.h, src/core/interpreter.h, src/core/small_string.h, src/server/db_slice.h, src/server/set_family.cc
=> Improve Comment Readability

src/facade/dragonfly_listener.cc, src/server/server_family.cc, src/server/server_family.h
This PR is the first step towards completing #61.
The server doesn't expose all metrics yet, so still WIP :)
=> Add basic Prometheus support and metrics

.github/workflows/ci.yml, src/server/engine_shard_set.cc, src/server/server_family.cc, src/server/server_family.h
1. Introduce `hz` flag to control the frequency of periodically running tasks.
2. Update helio dependency.
=> Fixes #66.

README.md, examples/grafana/dashboard.json, src/server/server_family.cc
The only missing command is `dragonfly_commands_total`, TBD.
=> Add Promehtues metrics for Grafana close #61

tools/docker/entrypoint.sh
This should solve the awkward command overrides in K8S scripts.
Fixes #57.
=> feat(docker): try increasing a memlock limit in the container

.pre-commit-config.yaml, .pre-commit-hooks.yaml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, contrib/scripts/conventional-commits
=> feat(community): Add Conventional Commits; Code of Conduct #107

docs/api_status.md, src/core/compact_object.cc, src/facade/error.h, src/facade/facade.cc, src/facade/op_status.h, src/facade/reply_builder.cc, src/redis/stream.h, src/redis/t_stream.c, src/server/debugcmd.cc, src/server/main_service.cc, src/server/server_family.cc, src/server/stream_family.cc, src/server/stream_family.h, src/server/stream_family_test.cc
=> implement partial streams API

CMakeLists.txt, src/core/dash.h, src/core/dash_internal.h, src/core/dash_test.cc, src/redis/sds.c, src/server/db_slice.cc, src/server/db_slice.h, src/server/generic_family.cc, src/server/main_service.cc, src/server/string_family.cc
=> chore(strings): Simplify Set flow

contrib/docker/README.md, contrib/docker/docker-compose.yml
Signed-off-by: Luca Goslar <47827429+lucagoslar@users.noreply.github.com>
fix(docker-compose): Add memlock conf to service
Signed-off-by: Luca Goslar <47827429+lucagoslar@users.noreply.github.com>
=> fix(docker-compose): Fetch actual Docker Compose file and add memlock conf to service

src/facade/dragonfly_connection.cc, src/server/generic_family.cc, tools/release.sh
Also, enhance release script to apply linker optimizations when building the binaries.
=> fix(server): Fix a crash when running "client list" command.

src/core/CMakeLists.txt, src/core/dash_bench.cc
=> chore(dash): add dashtable benchmark.

docs/api_status.md, src/server/main_service.cc
Also make subcommand matching for pubsub case insensitive.
=> chore(pubsub): update api status

src/server/rdb_load.cc, src/server/rdb_load.h
This commit fixes the behavior with streams loading and resolves #159.
=> chore(rdb): Move object creation during load operation to shard threads.

docs/quick-start/README.md
Add some notes, as mentionned in #181.
Unsigned commit but it's not touching the code so hopefully you can merge as-is.
=> doc(quick-start): add note for known issues

src/core/dash_bench.cc, src/server/server_family.cc
=> chore(server): improve error logging if info command fails.

src/server/dfly_main.cc
=> fix(server): exit gracefully when iouring not supported

src/server/dfly_main.cc
=> fix(server): setup sigill handler (#183)

src/server/dfly_main.cc
This closes #202.
In addition, update helio dependency.
=> fix(server): add gitsha to version output.

README.md
=> docs(README): minor fix

src/server/generic_family.cc, src/server/generic_family_test.cc
Signed-off-by: odedponcz <oded@poncz.com>
=> fix: RENAMENX according to spec #229

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md
Signed-off-by: odedponcz <oded@poncz.com>
=> docs: Improve wording in issue reporting

src/facade/dragonfly_listener.cc
Signed-off-by: Oded Poncz <oded@poncz.com>
=> fix:change statis assets url for http monitoring page

README.md, docs/memcached_benchmark.md
Signed-off-by: Oded Poncz <oded@poncz.com>
=> Move assets to static

src/redis/redis_aux.c, src/redis/redis_aux.h, src/server/rdb_load.cc, src/server/set_family.cc, src/server/set_family.h
=> chore(set): minor cleanups and refactorings.

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/server/main_service.cc, tests/dragonfly/conftest.py, tests/dragonfly/server_family_test.py
=> fix(server): Fix QUIT not shutting down connection

src/server/conn_context.cc, src/server/conn_context.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/dragonfly_test.cc, src/server/generic_family.h, src/server/hset_family.cc, src/server/json_family.cc, src/server/list_family.cc, src/server/main_service.cc, src/server/main_service.h, src/server/set_family.cc, src/server/string_family.cc, src/server/string_family.h, src/server/table.h, src/server/zset_family.cc
=> feat(server): Watch & Unwatch commands

docs/api_status.md
This is the API status of the master branch, right? (the website directly refers here and not to the latest release)
- WATCH/UNWATCH will be implemented as #277 will be merged soon
- I've looked up missing commands as by #91 to see what still needs to be implemented
- Some commands are already implemented but not listed
=> docs(api): Update api_status.md

src/facade/dragonfly_connection.cc, src/redis/CMakeLists.txt, src/server/CMakeLists.txt, src/server/common.h, src/server/list_family.cc, src/server/main_service.cc, src/server/malloc_stats.cc, src/server/server_family.cc
=> chore(server): Fix clang warnings and errors

src/core/dash_internal.h, src/core/dense_set.cc, src/core/dense_set.h, src/core/external_alloc.cc, src/core/external_alloc.h, src/core/interpreter.h
Small readability fixes in `src/core/` all in comments. No functional changes.
=> docs(src/core): readability improvements

src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/rdb_test.cc
Signed-off-by: Braydn <braydn.moore@uwaterloo.ca>
=> fix(server): Added RDB load / save for DenseSet

src/core/compact_object.cc, src/server/conn_context.cc, src/server/generic_family_test.cc, src/server/journal/journal_shard.cc, src/server/json_family.cc, src/server/list_family_test.cc, src/server/malloc_stats.cc, src/server/rdb_save.cc, src/server/replica.cc
Readability fixes across `src/server` that only occur in a single file.
BTW, put some respect on Dr. Lemire's name... Just read his work :100:
=> docs(server): readability cleanup

README.md
=> Added more useful flags to the flags section

src/server/string_family.cc, src/server/string_family_test.cc
feat(server): support for the options EXAT and PXAT for the set command.
* For values less than 0 in the command returning "invalid expire time"
* For values that expired before the current time, the function return OK but will not set the value (per Redis today).
* For values in the future it would translate to milliseconds and do offset from current time (so we are keeping the offset).
=> feat(server): adding support for EXAT PXAT option at set command

README.md
Signed-off-by: Oded Poncz <oded@poncz.com>
=> feat(docs): Update broken link to grafana dashboard

docs/differences.md, src/core/compact_object.cc, src/facade/reply_builder.cc, src/facade/reply_builder.h, src/server/CMakeLists.txt, src/server/container_utils.cc, src/server/container_utils.h, src/server/generic_family.cc, src/server/generic_family.h, src/server/generic_family_test.cc, src/server/list_family.cc, src/server/server_family.cc, src/server/set_family.cc, src/server/stream_family.cc, src/server/zset_family.cc
=> feat(server): SORT command prototype

src/server/json_family.cc, src/server/json_family.h, src/server/json_family_test.cc
=> feat(server): implement json.objkeys command (#104)

src/server/db_slice.cc
This fixes #322 though some memory is still kept by memory allocator.
=> feat(server): Enforce decomitting memory pages upon flushdb call

src/core/dense_set.cc, src/core/dense_set.h, src/core/string_set.cc, src/core/string_set.h
=> chore(DenseSet): Some code reorder without change in functionality.

src/core/dense_set.cc, src/core/dense_set.h, src/core/string_set.cc, src/core/string_set.h, src/core/string_set_test.cc
=> Add expiry semantics to the set.

src/server/hset_family.cc, src/server/hset_family.h
=> chore(hset): Get rid of helper functions in header file.

src/server/bitops_family_test.cc, src/server/debugcmd.cc, src/server/dragonfly_test.cc, src/server/generic_family_test.cc, src/server/list_family_test.cc, src/server/main_service.cc, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/rdb_test.cc, src/server/server_family.cc, src/server/string_family_test.cc
Refactor RdbSnapshot and consolidate iouring linux file handling in a single place.
=> chore(server): reduce iouring exposure across the codebase

src/server/json_family.cc, src/server/json_family.h, src/server/json_family_test.cc
=> feat(server): implement json.strappend & json.clear commands (#104)

docs/api_status.md, src/server/generic_family.cc, src/server/generic_family.h, src/server/generic_family_test.cc
This would add support for the persist command #345
=> feat(server): support for persist command #345

src/server/CMakeLists.txt, src/server/test_utils.cc
=> chore(test): Allow running tests with epoll proactor

CONTRIBUTORS.md, src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
Implements `ZMSCORE` (https://redis.io/commands/zmscore/), closes #357
=> feat(server): Implement ZMSCORE command #357

src/server/json_family.cc, src/server/json_family.h, src/server/json_family_test.cc
=> feat(server): implement json.arrpop command (#104)

src/server/json_family.cc, src/server/json_family.h, src/server/json_family_test.cc
=> feat(server): implement json.arrtrim command (#104)

src/server/list_family.cc, src/server/list_family.h, src/server/list_family_test.cc
Implements LPOS (https://redis.io/commands/lpos/)
Supports optional arguments
closes https://github.com/dragonflydb/dragonfly/issues/368
=> feat(server): Implement LPOS command #368

CONTRIBUTORS.md, src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
Implements ZPOPMIN and ZPOPMAX
Closes #358
Closes #359
=> feat(server): Implement ZPOPMIN and ZPOPMAX #358 #359

src/server/common.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/generic_family.cc, src/server/generic_family.h
This is preparation for https://github.com/dragonflydb/dragonfly/pull/387
=> chore(server): Refactor expire functionality and move it to DbSlice

src/server/json_family.cc, src/server/json_family.h, src/server/json_family_test.cc
=> feat(server): implement json.arrindex command (#104)

CONTRIBUTORS.md, src/server/list_family.cc, src/server/list_family.h, src/server/list_family_test.cc
Signed-off-by: chenyuxuan.allen <dev.allenchen@gmail.com>
feat(server): implement command "LMOVE" (#369)
changes:
* add support for LMOVE
* reconstruct MOVE-like command (RPOPLUSH)
hope this would help
=> feat(server): implement LMOVE #369

CONTRIBUTORS.md, src/server/db_slice.cc, src/server/string_family.cc, src/server/string_family.h, src/server/string_family_test.cc
Signed-off-by: matchyc <dawnlight.yc@protonmail.com>
issue: #385 
- Why we need this:
Add GETEX command
- What has been done:
Parsing args in `getex` command and using extended `OpGet` to finish it.
=> feat(server): Implement GETEX command #385

LICENSE.md, README.md, docs/api_status.md
=> docs(server): Update the API status, README and LICENSE date

.github/workflows/docker-release.yml
A small link fix for the discord notification
=> ci(workflow): fixing discord notification link

src/server/common.h, src/server/debugcmd.cc, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/snapshot_test.py
Migrating replication branch on main, part 1
Implementation taken from MVP #352 
* Add dedicated summary file to multi file snapshots
* Support loading multi file snapshots
* Introduce AggregateValue
* Refactor snapshot loading function to be a bit cleaner and easier to understand
* Add pytests for snapshots
=> feat(server): Multi rdb load

src/server/dflycmd.cc, src/server/dflycmd.h, src/server/server_family.cc
Migrating replication branch on main, part 2
Mixed implementation
* Split up DflyCmd::Run into parts
* Add utilities for managing SyncInfo
=> refactor(server): Refactor and tidy dflycmd

docs/api_status.md, src/server/generic_family.cc, src/server/generic_family.h, src/server/generic_family_test.cc
Signed-off-by: b0bleet b0bleet@placeq.com
=> feat(server) implement pexpire command

src/server/json_family.cc, src/server/json_family.h, src/server/json_family_test.cc
Signed-off-by: b0bleet@placeq.com
=> server: implemented json.arrappend command

src/server/json_family.cc, src/server/json_family.h, src/server/json_family_test.cc
=> feat(server): implement json.debug command (#104)

src/server/dragonfly_test.cc, src/server/list_family.cc, src/server/main_service.cc, src/server/transaction.cc, src/server/transaction.h
=> fix(server): issue with invalid command inside multi #468

src/server/common.cc, src/server/common.h, src/server/generic_family.cc, src/server/hset_family.cc, src/server/set_family.cc, src/server/set_family_test.cc
=> SSCAN command support count and match parameters

src/server/dfly_main.cc
=> fix(server): Fix bad maxmemory casting

src/server/server_family.cc
Fixes #475 
I've added auto snapshot destruction in case of errors for the new multi-file snapshot feature, but didn't do it for the rdb files.
=> fix(server): Fix snapshot saving bug

src/server/server_family.cc
=> fix(server): Fix path concatenation in save

src/server/json_family.cc, src/server/json_family.h, src/server/json_family_test.cc
=> feat(server): implement json.resp command (#104)

src/server/debugcmd.cc, src/server/server_family.cc, src/server/server_family.h
=> chore: Rename DoFlush to Drakaris.

src/server/server_family.cc, src/server/server_family.h
=> feat: Add last_save_duration_sec metric

src/server/server_family.cc
=> fix(server): Handle data directory errors

src/server/error.h, src/server/memory_cmd.cc, src/server/memory_cmd.h, src/server/rdb_save.cc
=> fix: Fix bugs around rdb save and improve memory accounting

src/server/db_slice.cc, src/server/dragonfly_test.cc
=> fix(server): Fix db_slice insertion bug with callbacks

src/server/engine_shard_set.h
Fix closure capture in RunBriefInParallel and RunBlockingInParallel
=> fix(server): Fix lambda capture in RunInParallel functions

src/server/json_family.cc, src/server/json_family.h, src/server/json_family_test.cc
This is the first step of JSON.SET command implementation. The next step is the implementation of the json_family working behind an JSON type and string type(how that is implemented now).
=> feat(server): implement json.set command (#104)

src/server/db_slice.cc, src/server/engine_shard_set.cc, src/server/tiered_storage.cc, src/server/tiered_storage.h
=> chore: tiered_storage - cleanups and refactorings.

src/server/dfly_main.cc
=> bug(server): exit not crash when port in use

.github/workflows/regression-tests.yml
=> fix: Use dev image for running regression tests

.github/workflows/regression-tests.yml
=> fix: Use dev image for running regression test

.github/workflows/regression-tests.yml
=> feat(regression test): add timeout cpu info and inc frequecy

src/server/generic_family.cc, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/snapshot.cc, src/server/snapshot.h
I refactored the snapshot to become better structured and more readable, added comments to all the main functions and a call-tree diagram to understand how it roughly works
=> refactor(server): Refactor snapshot

src/CMakeLists.txt
=> chore: Add lz4 to the source dependency

src/CMakeLists.txt, src/server/CMakeLists.txt, src/server/rdb_save.cc, src/server/rdb_save.h
=> feat(rdb save): add Lz4Compressor

.github/workflows/release.yml
=> fix(github): add libzstd-dev dep to aarch64 release pipeline

src/server/rdb_extensions.h, src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/rdb_save.h
=> feat(rdb save): Create compressor interface

.github/workflows/ci.yml
=> feat(ci test): add build and test on release mode

src/core/generate_bin_sizes.py, src/server/string_family.cc, src/server/tiered_storage.cc, src/server/tiered_storage.h
=> Support offloading of blobs longer than 2KB

tools/defrag_mem_test.py, tools/requirements.txt
Adding a python application that can test whether a memory was defrag and monitor whether this was detected.
To install - (best after you're setup a virtual environment) - run pip install -r requirements.txt
To run - you can run it without any parameters: in which case it would use a fix key name, number of entries is ~4,000,000 and the value size is set to 64. Note that you can control on these as well as the dragonfly host name and port number (see more details at the top of the file).
This will set up 4 time number of keys, the start deleting keys. While doing so it would monitor the stats to check whether we found and run defrag operation. If so it would print it out, otherwise it would print memory starts.
The application would stop …
=> feat(server): active memory defrag test application

src/core/compact_object.cc, src/core/compact_object_test.cc, src/core/detail/bitpacking.cc, src/core/detail/bitpacking.h
=> feat: implement ascii_unpack using SIMD instructions

src/server/rdb_load.cc, src/server/rdb_load.h
=> bug(rdb load): Rdb loader tasks stop running on failure #567

src/core/detail/bitpacking.cc
=> fix: choose an appropriate SIMD implementation for aarch64

src/server/engine_shard_set.cc
Set mem_defrag_threshold so that defrag will be trigerred when memory grows.
=> fix: handle corner case when comitted memory is negative

src/core/CMakeLists.txt, src/core/compact_object.cc, src/core/compact_object_test.cc, src/core/dense_set.cc, src/core/dense_set.h, src/core/sds_utils.cc, src/core/sds_utils.h, src/core/string_map.cc, src/core/string_map.h, src/core/string_map_test.cc, src/core/string_set.cc, src/core/string_set.h, src/core/string_set_test.cc, src/server/hset_family.cc, src/server/hset_family.h, src/server/hset_family_test.cc, src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/set_family.cc
=> use dense_set for hashmap family

src/server/db_slice.cc, src/server/db_slice.h, src/server/dragonfly_test.cc, src/server/server_family.cc
Signed-off-by: ashotland <ashotland@gmail.com>
=> feat(server): track hits and misses stats.

src/server/db_slice.cc, src/server/db_slice.h, src/server/dragonfly_test.cc, src/server/string_family.cc
=> fix(server):set of existing object with expiry

src/core/compact_object.cc, src/core/compact_object.h, src/server/CMakeLists.txt, src/server/bitops_family.cc, src/server/common.cc, src/server/common.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/debugcmd.cc, src/server/dragonfly_test.cc, src/server/engine_shard_set.cc, src/server/generic_family_test.cc, src/server/rdb_test.cc, src/server/server_family.cc, src/server/string_family.cc, src/server/test_utils.cc, src/server/test_utils.h, src/server/tiered_storage.cc, src/server/tiered_storage_test.cc
1. Support tiered deletion.
2. Add notion of tiered entity in "DEBUG OBJECT" output.
=> chore: Add tiered_storage_test.

tools/cache_logs_player.py
=> fix(tools): cache logs player handle append as redis append

tools/cache_logs_player.py
Signed-off-by: ashotland <ashotland@gmail.com>
=> feat(tools):cache log player batching all the way optimisation

src/server/dfly_main.cc
fix issue #603
This will print a one time message is case of an error, when trying to access the remote version.
The error message is in format "Remote version - ..." with the cause of the error.
For example when the network is not working it report on my Linux machine "Bad Address" (which is the error returned network).
<!--
**Commits Must Be Signed and Your PR title must conform to the conventional commit spec**
* See: https://github.com/dragonflydb/dragonfly/blob/main/CONTRIBUTING.md
* Please follow the section on `pre-commit hooks`, a linter will validate before you push
Example PR Title: <type>(<scope>)!: <description>
* `type` = bug, chore, feat, fix, docs, build, style, refactor, perf, test
* `!` = OPTIONAL: signals a breaking change
* …
=> fix(server): only print version if successfully connect.

src/server/dragonfly_test.cc, src/server/main_service.cc
=> feat(server family): reject flushall and flushdb on multi command

src/server/replica.cc, src/server/replica.h
=> feat(replica): enable multi cmd sync on flag

src/server/replica.cc
=> bug(replica): multi command on single shard exec all commands

src/core/compact_object.cc, src/server/dragonfly_test.cc
=> fix(core): Fix compact object bug

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h
=> chore(facade): speed up request allocation in pipeline mode

src/server/engine_shard_set.cc, src/server/engine_shard_set.h, src/server/server_family.cc
=> fix(server): Convert Heartbeat from a periodic task to a fiber

src/server/bitops_family.cc, src/server/blocking_controller.cc, src/server/blocking_controller_test.cc, src/server/engine_shard_set.cc, src/server/generic_family.cc, src/server/hset_family.cc, src/server/list_family.cc, src/server/main_service.cc, src/server/server_family.cc, src/server/set_family.cc, src/server/string_family.cc, src/server/transaction.cc, src/server/transaction.h, src/server/zset_family.cc
Me and Adi are now actively adding changes to the Transaction class, so I decided to clean it up a little:
- The header was really chaotic, I ordered the parts logically, so you can get an overview now
- I added some missing comments and updated deprecated ones
- ~~I replaced all the manual index accesses `SidToId` with a `PerShardStorage` that has an operator[](ShardId)~~
- I improved some wicked parts like directly accessing LockCnt's inner array without any explanations
=> Refactor transaction

src/server/generic_family.cc
=> (generic family): journal support move command

src/server/generic_family.cc, src/server/list_family.cc, src/server/transaction.cc, src/server/transaction.h
=> feat(list family): impl rename journal commands

src/server/conn_context.h, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/replica.cc, src/server/server_family.cc
See #706 for more context
Signed-off-by: ashotland <ashotland@gmail.com>
=> feat(server): report slaves ip and listening port in INFO REPLICATION

src/core/interpreter.cc, src/core/interpreter_test.cc, src/server/zset_family.cc, src/server/zset_family_test.cc
Fixes #713 
Fix issue with:
* ZRANGE LIMIT doesnt work with negative count
* `unpack` in lua is not defined
=> fix(server): Fix Lua & Zset issue

README.md
Signed-off-by: fannyfan414 <32100589+fannyfan414@users.noreply.github.com>
=> docs(readme): Add ulimit to docker-compose example

src/server/conn_context.cc, src/server/conn_context.h, src/server/dragonfly_test.cc, src/server/main_service.cc, src/server/transaction.cc
Needed for sentinel support (#706)
=> feat(server): Allow admin commands in multi

src/server/dfly_main.cc
=> Stop ping dev version

.github/workflows/ci.yml
=> chore(ci):Reduce --gtest_repeat to 10

src/server/common.cc, src/server/common.h, src/server/db_slice.cc, src/server/engine_shard_set.cc, src/server/engine_shard_set.h, src/server/journal/serializer.cc, src/server/journal/types.h, src/server/rdb_load.cc, src/server/replica.cc, src/server/replica.h, src/server/snapshot.cc, tests/dragonfly/replication_test.py, tests/dragonfly/utility.py
This adds:
- automatic expiry on master side
- expiry out of order execution on replica
=> feat(server): Auto expiry + small replica refactor

.github/workflows/regression-tests.yml
=> Add -x to pytest invocation

.github/workflows/release.yml
=> feat(action): build debian package for arm64 arch (#719)

tools/local/monitoring/docker-compose.yml
=> Add renderer to grafana

tests/dragonfly/sentinel_test.py
=> fix(regression-tests):Skip sentinel regression tests

.github/workflows/regression-tests.yml
=> Notify on cancelled too

docs/api_status.md, src/server/list_family.cc, src/server/list_family_test.cc
Also update api_status with ZUNION and BRPOPLPUSH
=> feat(list): Add BLMove command

src/server/dragonfly_test.cc, src/server/main_service.cc, src/server/server_family.cc, src/server/server_family.h, src/server/server_state.h, src/server/string_family_test.cc, src/server/transaction.cc
=> chore(server): track ooo transactions via metrics.

src/server/main_service.cc, src/server/main_service.h, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/generic_test.py
=> feat(server): Enable overriding --requirepass form env var

.github/workflows/regression-tests.yml
=> test(regression-tests): stop regression-tests schedual run

.github/workflows/regression-tests.yml, src/server/replica.cc, src/server/transaction.cc
1. change default flag value
2. add regression tests for both value
3. fix compilation warning
=> fix(replica) : replica will not sync execution multi shard commands as default

tests/dragonfly/replication_test.py
We never check we successfully connect to different masters
=> feat(tests): Add rotating master test

docs/dashtable.md
The existing link from `twitter.github.io` does not seem to render for some reason.
This PR replaces the `expiration.svg` image with a working URL.
=> docs(dashtable): Fix image URL for expiration 

src/server/json_family.cc, src/server/json_family_test.cc
=> fix(server): JSON.RESP path arg should be optional (#852)

src/server/common.cc, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/error.h, src/server/rdb_load.cc, src/server/replica.cc
=> fix(server): Fix replication logs

CONTRIBUTING.md, README.md, docs/api_status.md, src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/server/main_service.cc, src/server/replica.cc, src/server/replica.h, src/server/server_family.cc, src/server/server_family.h, src/server/server_state.h, tests/README.md, tests/dragonfly/cluster_test.py, tests/dragonfly/conftest.py, tests/dragonfly/connection_test.py, tests/integration/.run_ioredis_valid_test.sh, tests/integration/run_ioredis_on_docker.sh
Signed-off-by: Leonardo Mello <lsvmello@gmail.com>
Resolves: https://github.com/dragonflydb/dragonfly/issues/332
I have some doubts so I'll mark this as a draft, can you please review the _TODO_ comments?
=> feat: support cluster mode emulation

src/facade/dragonfly_connection.cc, tests/dragonfly/connection_test.py
=> fix: resize buffer correctly when checking for http header line

tests/dragonfly/sentinel_test.py, tests/pytest.ini
=> fix: logging in sentinel_test

contrib/charts/dragonfly/ci/affinity-values.golden.yaml, contrib/charts/dragonfly/ci/command_extraargs-values.golden.yaml, contrib/charts/dragonfly/ci/extracontainer-string-values.golden.yaml, contrib/charts/dragonfly/ci/extracontainer-tpl-values.golden.yaml, contrib/charts/dragonfly/ci/extravolumes-values.golden.yaml, contrib/charts/dragonfly/ci/initcontainer-string-values.golden.yaml, contrib/charts/dragonfly/ci/initcontainer-tpl-values.golden.yaml, contrib/charts/dragonfly/ci/passwordsecret-values.golden.yaml, contrib/charts/dragonfly/ci/persistent-values.golden.yaml, contrib/charts/dragonfly/ci/resources-values.golden.yaml, contrib/charts/dragonfly/ci/securitycontext-values.golden.yaml, contrib/charts/dragonfly/ci/tls-values.golden.yaml, contrib/charts/dragonfly/ci/tolerations-values.golden.yaml
As Version is encoded into the rendered Helm manifests, They need to be
updated with each release so that these files are in sync with the latest release
version.
=> chore(helm): update golden files to latest version

tests/dragonfly/redis_replicaiton_test.py
Most of them skipped / commented-out to serve as repro without failing on CI.
=> fix(tests):Some test cases for redis replication

src/server/dfly_main.cc
=> Skip version check if $DFLY_DEV_ENV is set

docs/differences.md, src/server/common.h, src/server/generic_family_test.cc, src/server/string_family.cc, src/server/string_family_test.cc
=> feat: increase expiry period to 8 years.

src/server/dragonfly_test.cc, src/server/server_family.cc
=> feat(server): hello and info sidekiq compatibility

src/server/rdb_load.cc, src/server/rdb_save.h, src/server/rdb_test.cc, src/server/replica.cc
1. replica load expired keys
2. fix memory leak
3. remove some todo comments
=> fix(rdb_load): replica load expired keys

tests/integration/pascaldekloe.Dockerfile
Caught quite a few Dragonfly bugs with the unit tests from this Go client. Probably worth a spot in CI against regression.
=> Integration test docker image with Go client

.gitignore, src/facade/reply_builder_test.cc, src/server/db_slice.cc, src/server/dflycmd.cc, src/server/dragonfly_test.cc, src/server/memory_cmd.cc, src/server/memory_cmd.h, src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/replica.h, src/server/server_family.cc
While at it, fix some compile warnings, 2 of them are actual bugs (missing virtual d'tor).
=> fix: Get DragonDB to compile with clang.

src/core/detail/bitpacking.cc, src/core/detail/bitpacking.h
Reduce reliance on modern vectorized architectures pending proper configuration flags. Should fix the daily build pipeline.
Fixes #732.
=> feat: Support sse2 builds.

src/core/interpreter.cc, src/core/interpreter.h, src/core/interpreter_test.cc, src/server/common.cc, src/server/common.h, src/server/main_service.cc, src/server/multi_test.cc, src/server/rdb_load.cc, src/server/script_mgr.cc, src/server/script_mgr.h
=> feat(server): Specify script flags with shebang

tests/dragonfly/utility.py
=> fix(tests): Revive commented out actions

tests/dragonfly/utility.py
=> fix(tests):Comment out ZPOPMIN Action Again

docs/rdbsave.md
=> docs(rdb): fix typo

tests/dragonfly/list_family_test.py
=> fix: list_family_test works with async client

src/server/hset_family.cc, src/server/hset_family_test.cc
=> fix(server): Fix hset buffer bug

README.md, README.zh-CN.md
I translate the README doc to a Chinese version
hope it can help more people using Dragonfly project
=> docs: add a chinese language readme

src/server/replica.cc, src/server/replica.h, tests/dragonfly/replication_test.py
=> bug(replica): support auth master

README.md
Hi DragonFly! 
We're Ritza, a boutique technical writing agency that specialises in creating documentation, guides and blog posts for very technical audiences. We've worked with companies like Sourcegraph and Replit to create content that software developers love.
Part of our mission is improving the quality of all technical materials, so here are some improvements to your README.
Please let me know if we can help you with any other content!
=> docs(readme): Fix up grammar and consistency

src/facade/dragonfly_connection.h
=> fix: compatibity with older linux distributions

src/core/fibers.h, src/core/uring.h, src/server/conn_context.h, src/server/io_mgr.cc, src/server/journal/journal_slice.cc, src/server/replica.cc, src/server/tiered_storage.h, src/server/transaction.h
=> fix: another pass on fixing namespace imports to support fb2

src/facade/dragonfly_connection.cc
=> fix(server): Use connection pool only for regular messages

src/server/replica.cc, src/server/replica.h, src/server/server_family.cc
More logging to help debug #1032
=> feat(server): Better logging for replication

src/server/replica.cc
Remove SocketSource because now FiberSocketBase implements the Source interface.
=> chore: update helio dependency

src/core/interpreter.cc
Lua is___type__ functions allow type coercion (casting double to string), so they should be replaced by a simple type switch
=> fix(interpreter): Remove converting type checks

src/server/CMakeLists.txt, src/server/command_registry.cc, src/server/command_registry.h, src/server/conn_context.cc, src/server/conn_context.h, src/server/list_family_test.cc, src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, src/server/multi_test.cc, src/server/transaction.cc, src/server/transaction.h
Implements basic command squashing for MULTI-EXEC and enables it by default
=> feat(server): Squashed exec

src/facade/dragonfly_listener.cc
fixes partially #1056 (the crash part).
=> fix: do not crash when running on WSL1

src/server/bitops_family.cc, src/server/command_registry.cc, src/server/common.h, src/server/debugcmd.cc, src/server/dflycmd.cc, src/server/generic_family.cc, src/server/hset_family.cc, src/server/journal/serializer.cc, src/server/journal/serializer.h, src/server/journal/types.h, src/server/journal_test.cc, src/server/json_family.cc, src/server/json_family_test.cc, src/server/list_family.cc, src/server/main_service.cc, src/server/memory_cmd.cc, src/server/multi_command_squasher.cc, src/server/server_family.cc, src/server/set_family.cc, src/server/stream_family.cc, src/server/string_family.cc, src/server/test_utils.cc, src/server/transaction.cc, src/server/transaction.h, src/server/zset_family.cc
=> Remove cmd name from args

src/server/main_service.cc, src/server/main_service.h
I need the validation part separately to validate commands in async lua calls
=> chore: Split DispatchCommand into validation and main part

src/server/string_family.cc
Previously we called GetString() every time SET was used, which is unneeded in the vast majority of cases.
#841
=> Only copy previous value's string when needed.

src/server/string_family.cc
I believe this is a better API as it's harder to mistakenly use.
#841
=> Revert to use CachePrevValueIfNeeded(), but let it call GetString() if needed.

src/server/dfly_main.cc, src/server/generic_family.h, src/server/server_family.cc
=> feat(server): Support CONFIG GET [databases|maxmemory]

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/server/conn_context.cc, src/server/main_service.cc, src/server/server_family.cc, src/server/test_utils.cc, src/server/test_utils.h
This PR fixes #1039 and:
* refactors connection - first commits have no functional changes
* limits max size of dispatch queue size - last commit
Please look at them on a per-commit basis, because I also did some refactoring.
=> Refactor connection

src/server/server_family.cc
Fixes #1084 by adding an error message that clarifies where the error came from.
Checked by trying to dump in a read-only directory.
```
127.0.0.1:6379> save
(error) ERR Permission denied
----->
127.0.0.1:6379> save
(error) ERR Permission denied: Couldn't open file for writing (is direct I/O supported by the file system?)
```
=> fix(server): Better error reporting when opening snapshot files

docs/transaction.md
Added a short description of command squashing to the docs
=> docs: describe command squashing

src/server/dfly_main.cc
Specifically, do not check-fail when reading cgroup file path.
=> chore: adding polishes for reading cgroup files

src/server/main_service.cc, tests/dragonfly/eval_test.py
* Not calling toupper before looking up command id
* Wrong error reply context
=> Fix async lua bugs

src/CMakeLists.txt, src/core/CMakeLists.txt, src/core/search/CMakeLists.txt, src/core/search/lexer.lex, src/core/search/parser.y, src/core/search/query_driver.cc, src/core/search/query_driver.h, src/core/search/scanner.h, src/core/search/search_parser_test.cc
Add initial test for the scanner.
This is mostly boilerplate code, no business logic, no ast and minimal parsing code.
The test builds and passes.
=> feat: Add skeleton code for parser/lexer generation

tests/dragonfly/sentinel_test.py
- Some more logging
- Use PortPicker
=> Sentinel test debug

src/facade/facade_types.h, src/server/CMakeLists.txt, src/server/common.cc, src/server/db_slice.cc, src/server/db_slice.h, src/server/hset_family.cc, src/server/journal/journal_slice.cc, src/server/journal/types.cc, src/server/journal/types.h, src/server/main_service.cc, src/server/rdb_save.cc, src/server/set_family.cc, src/server/string_family.cc
No actual changes, just useful logging from the last days.
=> chore: Update comments and logs after debugging

src/core/search/CMakeLists.txt, src/core/search/lexer.lex, src/core/search/parser.y, src/core/search/query_driver.cc, src/core/search/query_driver.h, src/core/search/scanner.h, src/core/search/search_parser_test.cc
=> chore: support more token types in the lexer

src/server/dfly_main.cc
Closes #979 and #983.
When the flag `--port 0` is passed, we disable the following listeners:
- `main_listener` (default TCP listener, usually port 6379)
- `admin_listener` (optional listener, disabled nonetheless as it uses TCP)
And instead require a UNIX socket passed, to which we talk instead.
---
About #983: if we run Dragonfly as a service with `PrivateNetwork=true`, then it crashes instead with the error:
```
Could not open port 6379, error: Address family not supported by protocol
```
which makes sense, as the service blocks all *network* connections.
=> don't listen for TCP connections when `--port 0` is passed

src/core/search/CMakeLists.txt, src/core/search/lexer.lex, src/core/search/parser.y, src/core/search/search_parser_test.cc
=> feat: Extend parsing to field  impressions

.github/workflows/reusable-container-workflow.yaml, Makefile
A proposed fix for #1136.
@Pothulapati, what's the best way to test that this works?
=> chore: Tweak debug symbols generation for releases

src/server/replica.cc, src/server/replica.h, src/server/server_family.cc, tests/dragonfly/replication_test.py
@Pothulapati said in #1132 that we sometimes return the wrong value for the replication state.
I think I understood where it can go wrong. I changed the calculation to be more rebust and added a basic test.
close #1132
=> fix(server): Wrong replication state

src/server/script_mgr.cc, src/server/script_mgr.h
Fixes bug from regression tests
=> fix: fix script body access

src/server/dflycmd.cc
=> fix: fix passing scripts

.github/workflows/regression-tests.yml
temporary remove till fix the timeout fails in arm machine
=> chore(regression tests) : remove replication tests from arm host runner

tests/dragonfly/requirements.txt
=> fix: fix duplicated dependency

tests/dragonfly/server_family_test.py
One more small pytest fix 😓 should pass now
=> fix: fix test connection name

.github/workflows/release.yml
=> chore: Add bison to release build dependencies

src/server/cluster/cluster_config.cc
=> fix: Lock before accessing slots_

src/server/cluster/cluster_config.cc, src/server/cluster/cluster_config.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/table.cc, src/server/table.h
I added DFLY CLUSTER GETSLOTINFO 
now it returns only key count
will expand the returned data in later PRs
=> feat(cluser): support GETSLOTINFO

src/server/server_family.cc
=> fix: use strings to keep the result of GetBucketPath()

src/server/string_family.cc
=> bug(server): fix cash SET mykey 123 [PX/EX] with no px arg

src/facade/command_id.h, src/facade/facade.cc, src/server/command_registry.cc, src/server/command_registry.h, src/server/main_service.cc, src/server/main_service.h
Also, move command registry command logic to main_service where it should reside.
=> chore: factor out commandid from the server lib

src/server/CMakeLists.txt, src/server/cluster/cluster_family.cc, src/server/cluster/cluster_family.h, src/server/cluster_family_test.cc, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/server_family.cc
=> refactor(cluster): Move management commands from `DFLY CLUSTER` prefix to `DFLYCLUSTER`.

src/server/stream_family.cc
I mixed up array initialization and zero initialization :)
=> fix: actually zero initialize the struct

src/server/stream_family.cc, src/server/stream_family_test.cc, src/server/transaction.cc
=> fix: support XREAD ... STREAMS ... keys derivation

src/server/journal/executor.cc, src/server/journal/executor.h, src/server/replica.cc, src/server/replica.h
No idea what's the perf impact, but it's not going to hurt
=> perf: Use InlinedVector in TransactionData for the common case of single commands

src/facade/resp_expr.h, src/server/cluster/cluster_config.cc, src/server/cluster/cluster_config.h, src/server/cluster/cluster_family.cc, src/server/cluster_family_test.cc
Implementation supports 3 cases:
1. Emulated mode (as was previously implemented)
2. Non-configured cluster mode
3. Configured cluster mode
=> feat(cluster): Implement `CLUSTER INFO`.

src/server/cluster/cluster_config.cc, src/server/cluster_config_test.cc
=> feat(cluster): Do not allow node IDs to appear more than once.

src/server/dfly_main.cc
=> fix: move version check earlier in the flow

src/facade/dragonfly_connection.h, src/server/cluster/cluster_family.cc, src/server/cluster_family_test.cc, src/server/conn_context.h, src/server/test_utils.cc, src/server/test_utils.h
=> feat(cluster): dflycluster commands only under admin port

src/server/cluster_family_test.cc, src/server/generic_family.cc
=> feat(cluster): select not allowed in cluster mode

src/server/cluster/cluster_family.cc, src/server/cluster_family_test.cc
=> refactor(cluster): Unify cluster-disabled error message.

tests/dragonfly/cluster_test.py
=> bug(cluster): Fix failing cluster test.

src/core/search/ast_expr.cc, src/facade/resp_expr.h, src/server/search/doc_index.cc, src/server/search_family_test.cc
To reduce diff on my main PR:
* Add new tests
* Add custom matcher for checking document ids
* Small bug fixes
=> chore: improve search tests + fixes

src/server/cluster/cluster_config.cc, src/server/cluster_config_test.cc, src/server/cluster_family_test.cc
=> feat(cluster): first config set drop all entries not owned by node

tools/docker/Dockerfile.ubuntu-dev
=> Add bison to build process, and libxml2 to runtime

src/facade/reply_builder.cc, src/facade/reply_builder.h, src/facade/reply_builder_test.cc, src/server/hset_family.cc, src/server/list_family.cc, src/server/main_service.cc
=> fix: Batch array length before sending its contents

docs/build-from-source.md
=> Add latest dependencies.

src/redis/listpack.c, src/server/debugcmd.cc, src/server/rdb_load.cc, src/server/rdb_test.cc, src/server/stream_family.cc
We can not pass null pointers to listpack.
Fixes #1305 and probably fixes #1290
=> fix: fix crash when inserting to listpack an empty value.

src/server/cluster/cluster_family.cc, src/server/server_family.cc, src/server/server_family.h
=> fix(cluster): Eliminate race in `CLUSTER` commands.

tests/dragonfly/__init__.py, tests/dragonfly/cluster_test.py, tests/dragonfly/conftest.py
When reviewing, please note that:
1. I don't speak Python
2. It's my first time modifying pytests
So basically - I don't know what I'm doing, so do not assume any competence :)
=> test(cluster): Add basic cluster mode pytests.

src/server/search/search_family.cc, tests/dragonfly/search_test.py
Fixes latest regression test error
=> fix: Skip optional WEIGHT param in ft.create

.github/workflows/regression-tests.yml
=> chore: Double regression tests timeout (10m->20m)

src/server/hset_family.cc
=> fix(server): Return null when `HRANDKEY` doesn't find a key.

src/facade/error.h, src/facade/facade.cc, src/server/cluster/cluster_family.cc, src/server/cluster_family_test.cc, src/server/debugcmd.cc, src/server/debugcmd.h, src/server/main_service.cc
1. add slots <start> <end> option to debug populate command
2. fix some error prints in cluster mode
=> feat(server): debug poplulate add slots option

tests/dragonfly/search_test.py
Accidentally duplicated a line
=> fix: fix search_test after incorrect rebase

src/server/transaction.cc, src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
Implements [ZDiff](https://redis.io/commands/zdiff/) command
=> feat(zset family): Implement ZDiff command issue #1311

src/server/error.h, src/server/rdb_load.cc, tests/dragonfly/replication_test.py
=> fix(replication): Restart replication upon receiving `FLUSHALL` during full sync

src/server/dflycmd.cc
=> fix(replication): Destroy rdb saver on the same thread it was created

.github/workflows/regression-tests.yml, src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, tests/dragonfly/connection_test.py
This test should trigger the runtime error. Fixes https://github.com/dragonflydb/dragonfly/issues/782#issuecomment-1581227708
from #782 issue
=> Fix reply builder access issue

src/core/search/indices.cc, src/core/search/indices.h, src/core/search/search.cc, src/server/search/search_family.cc
First part of #1343 
- Avoid copies when possible
- Sort sub results by size 
Didn't benchmark yet.
=> feat: Basic search optimizations

patches/lua-v5.4.4.patch, src/CMakeLists.txt, src/core/compact_object.cc, src/core/compact_object.h, src/core/compact_object_test.cc, src/core/dash.h, src/core/dash_test.cc, src/core/dense_set.cc, src/core/dense_set.h, src/core/mi_memory_resource.h, src/core/string_map.h, src/core/string_set.h, src/core/string_set_test.cc, src/facade/dragonfly_connection.cc, src/server/engine_shard_set.h, src/server/table.cc, src/server/table.h
1. Use experimental/memory_resource because clang on freebsd does not support yet std::memory_resource
2. Pull latest helio with all the compatibility fixes.
3. Replace linux only SOL_TCP constant with IPPROTO_TCP (same value).
4. Fix build files to work on FreeBsd system.
=> chore: fix some of FreeBsd compile issues.

src/server/stream_family.cc, src/server/stream_family_test.cc
Dragonfly doesn't support `xgroup createconsumer`. This PR aims to fix that.
Fixes #1368
=> feat(xgroup): add support for xgroup createconsumer

patches/lua-v5.4.4.patch
=> fix(lua): Fix build on arm

src/core/search/CMakeLists.txt, src/core/search/ast_expr.cc, src/core/search/ast_expr.h, src/core/search/base.h, src/core/search/indices.cc, src/core/search/indices.h, src/core/search/lexer.lex, src/core/search/parser.y, src/core/search/query_driver.h, src/core/search/search.cc, src/core/search/search.h, src/core/search/search_test.cc, src/core/search/vector.cc, src/core/search/vector.h, src/server/search/search_family.cc
Implement basic KNN. For now it can be used only within the core part.
Allowing this in queries requires adding support for reading vectors from hset fields/json, parsing query parameters, etc...
=> feat: Basic KNN (core only)

tests/dragonfly/replication_test.py
I think I managed to replicate the issue by just running something on all CPUs in the background, really degrading the sync perf. Then the heuristic 1 second wait didn't suffice and as a result the test failed.
I changed it so we no longer check the new sync id right after the FLUSHALL. Instead we do it after the whole full sync has finished which is more stable. As a bonus, no need to sleep any more :)
=> fix(test): Fix a race condition in test_flushall_in_full_sync

tests/dragonfly/replication_test.py
This failed when running the tests in release mode.
=> Put more keys, make it non-failure if the test fails because of bad params

src/facade/dragonfly_connection.cc, src/facade/facade.cc, src/facade/facade_types.h, src/facade/redis_parser.cc, src/facade/reply_builder.cc, src/facade/reply_builder.h, src/server/server_family.cc, src/server/transaction.cc, src/server/transaction.h, tests/dragonfly/conftest.py, tests/dragonfly/connection_test.py
Required to track errors easily with `--vmodule=reply_builder=1`
=> fix: remove bad check-fail in the transaction code

src/server/cluster/cluster_family.cc, src/server/cluster/cluster_family.h, src/server/cluster/cluster_family_test.cc
=> feat(cluster): Implement `CLUSTER KEYSLOT` command

src/server/dragonfly_test.cc, src/server/server_family.cc
=> fix: out of bounds typo

src/facade/dragonfly_connection.cc, src/server/conn_context.h, src/server/container_utils.cc, src/server/container_utils.h, src/server/dflycmd.cc, src/server/list_family.cc, src/server/main_service.cc, src/server/server_family.cc, src/server/zset_family.cc
=> chore: improve connection I/O errors reporting

src/facade/redis_parser.cc
=> feat(server): set allowed key size 256MB

src/core/search/base.h, src/core/search/indices.cc, src/core/search/indices.h, src/core/search/search.cc, src/core/search/search.h, src/core/search/search_test.cc, src/server/search/doc_accessors.cc, src/server/search/doc_accessors.h, src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family.cc, tests/dragonfly/search_test.py
This PR exposes the core KNN parts to the search_family and now allows to use KNN with external clients
=> feat: Implement KNN interface

src/server/blocking_controller.cc, src/server/engine_shard_set.cc, src/server/engine_shard_set.h, src/server/list_family_test.cc, src/server/transaction.cc
=> fix: call NotifyPending only from tx queue invocations

src/server/server_family.cc
=> feat(server): add flag to set FiberQueueThreadPool thread size

src/server/dfly_main.cc
=> feat(server): add unixsocketperm support

src/server/conn_context.h, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/replica.h, src/server/server_family.cc, src/server/server_family.h, tests/dragonfly/__init__.py, tests/dragonfly/replication_test.py, tests/dragonfly/requirements.txt
=> Expose replication lag metrics

src/server/dfly_main.cc
On dragonfly startup print:
1  Which file we are logging to and where
2. How to get more help with the flags (--help, --helpfull)
3. Website and doc links
This PR addresses the request on #1380
=> feat(log): On startup print info to stdout 

src/server/dflycmd.cc
=> fix: Don't calculate replication lags when replica is not in stable sync

src/server/cluster/cluster_family_test.cc, src/server/db_slice.cc
=> bug(cluster): fix crush on flush slots with shutdown

.github/workflows/regression-tests.yml, tests/dragonfly/connection_test.py
PR changes
1. dont send on cancel
2. send link to job
=> feat(github regression): add link to github job 

src/server/cluster/cluster_config.h, src/server/cluster/cluster_config_test.cc, src/server/snapshot.h
=> cleanups: Remove unused member, rename test, remove unused forward decl.

README.ja-JP.md, README.md, README.zh-CN.md
I created Japanese translated README.
=> Add Japanese README

src/server/conn_context.h, src/server/main_service.cc, src/server/multi_test.cc, src/server/script_mgr.cc, src/server/script_mgr.h, tests/dragonfly/eval_test.py
Quick fix to make global eval work under multi #1417 
Adding a proper solution to our technical debt because this is a very dirty fix 🙄
=> feat: global eval in exec

src/server/dfly_main.cc, src/server/main_service.cc, src/server/main_service.h, src/server/server_family.cc, src/server/server_family.h, src/server/test_utils.cc, tests/dragonfly/server_family_test.py
- Add a test for CLIENT LIST which is the visible result of this.
=> fix(server): Initialize ServerFamily with all listeners.

src/facade/dragonfly_listener.cc, src/facade/dragonfly_listener.h, src/facade/op_status.cc, src/facade/op_status.h, src/server/common.cc, src/server/common.h, src/server/db_slice.cc, src/server/db_slice.h, src/server/dfly_main.cc, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/engine_shard_set.h, src/server/journal/journal_slice.cc, src/server/main_service.cc, src/server/main_service.h, src/server/replica.cc, src/server/replica.h, src/server/server_family.cc, src/server/server_family.h, src/server/test_utils.cc, src/server/transaction.cc, tests/dragonfly/__init__.py, tests/dragonfly/replication_test.py, tests/dragonfly/server_family_test.py, tests/dragonfly/utility.py
Support a safe transfer of ownership from a master to a replica.
Closes #1446
=> feat: Support atomic replica takeover

.snyk, tools/docker/Dockerfile.alpine-dev
Also, upgrade the alpine docker image according to Snyk suggestions.
=> chore: tune snyk coverage to ignore test files

README.ja-JP.md, README.ko-KR.md, README.md, README.zh-CN.md
Firstly, thank you for creating such a wonderful solution.
On this occasion, as there is no Korean 🇰🇷 translation for README.md yet, I took the opportunity to translate it.
I kindly ask for your review.
Thank you.
=> docs : add korean translated README

src/server/main_service.cc
Pull test conditions out of the function and simplify its interface.
=> chore: simplify SendMonitor function

src/server/script_mgr.cc
=> feat: do not process lua script if sha exists in cache

src/redis/CMakeLists.txt, src/redis/geo.c, src/redis/geo.h, src/redis/geohash.c, src/redis/geohash.h, src/redis/geohash_helper.c, src/redis/geohash_helper.h, src/redis/pqsort.c, src/redis/pqsort.h
Taken from redis source repo, tag: 7.0.8.
=> chore: import geo related files to Dragonfly repo

src/redis/geohash.c, src/server/zset_family.cc, src/server/zset_family.h
1. Remove shard-local functions from zset_family.h and move them into anonymous namespace in cc file.
2. Fix a warning in geohash.c
=> chore: refactor zset_family

src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
Only most basic functionality is covered, the options support and variadic functionality for GEOADD is missing.
=> feat: implement two geo commands GEOADD/GEOHASH

tools/docker/Dockerfile.alpine-dev
=> fix: weekly alpine build

.pre-commit-config.yaml, pyproject.toml, tests/dragonfly/__init__.py, tests/dragonfly/cluster_test.py, tests/dragonfly/conftest.py, tests/dragonfly/connection_test.py, tests/dragonfly/eval_test.py, tests/dragonfly/generic_test.py, tests/dragonfly/json_test.py, tests/dragonfly/list_family_test.py, tests/dragonfly/pymemcached_test.py, tests/dragonfly/redis_replication_test.py, tests/dragonfly/replication_test.py, tests/dragonfly/search_test.py, tests/dragonfly/sentinel_test.py, tests/dragonfly/server_family_test.py, tests/dragonfly/shutdown_test.py, tests/dragonfly/snapshot_test.py, tests/dragonfly/utility.py, tests/integration/async.py, tests/integration/generate_sets.py
1. Add black formatter to precommit
2. Run it on all pytests
=> feat: Add black formatter to the project

.github/workflows/reusable-container-workflow.yaml
=> chore: update ci action versions

src/server/server_family.cc, src/server/server_family.h
This enable filtering instances by role in dashbaords.
=> feat(server):export role as Prometheus metric

src/server/server_family.cc, src/server/server_family.h
=> fix(server, metrics):gauge metric value can't be text 

src/server/dragonfly_test.cc, src/server/server_family.cc
=> chore: rename dfly_ metrics to dragonfly_

src/server/rdb_load.cc, src/server/rdb_test.cc
Fix #1570. Tests to follow shortly.
=> fix(rdb): Fix loading of small integers and remove code duplication

tests/dragonfly/replication_test.py
=> test(replication): add admin port replication tests

.github/workflows/daily-builds.yml
=> feat(github-actions): add bullmq tests in daily builds

src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
resolves dragonflydb/dragonfly#1546
=> feat: add support for GeoPos command

src/server/zset_family.cc, src/server/zset_family_test.cc
=> feat: complete GEOADD functionalities (options + multiple parameters)

src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
=> feat: support for GEODIST added

src/core/interpreter.cc
`mimalloc_glue` is a patched copy of `l_alloc`, Lua's default alloc function: https://github.com/lua/lua/blob/ea39042e13645f63713425c05cc9ee4cfdcf0a40/lauxlib.c#L1017-L1025
=> Use mimalloc with Lua.

src/server/main_service.cc, src/server/multi_test.cc
The problem was with the logic inside Exec(...) that unconditinally labeled multi transactions as global even if they did not contain any EVAL calls.
=> fix: Fix faulty logic that forces multi transactions to run as global

tests/dragonfly/connection_test.py, tests/dragonfly/replication_test.py
This fixes the failures observed in regression tests. No actual code changes made.
=> tests: Add a password to TLS configurations

src/server/multi_test.cc
Fixes #1563 
I don't understand how it worked before, but it works now 🤷🏻‍♂️
=> fix: fix multi test

src/server/transaction.cc
Simplifies ScheduleInShard. No functional changes
=> fix: simplify ScheduleInShard

src/server/main_service.cc
=> chore: disable multi-squashing

src/facade/dragonfly_connection.cc
=> fix(server): Do not crash on parse error

src/core/bptree_set.h, src/core/bptree_set_test.cc, src/core/detail/bptree_internal.h
It's a partial implementation for only the insertion API. Deletion api will follow up in a different PR
=> feat: Add GetRank to bptree API

src/core/compact_object.cc, src/core/compact_object_test.cc, src/server/debugcmd.cc, src/server/debugcmd.h, src/server/table.h
Partially addresses https://github.com/dragonflydb/dragonfly/issues/1618.
Does not add field/value histograms yet.
=> Add "DEBUG OBJHIST"

src/server/cluster/cluster_family_test.cc
We saw some unrelated tests failing there.
=> fix(server): Increase default timeout

src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/search/search_family.h, src/server/search/search_family_test.cc, tests/dragonfly/search_test.py
=> feat: FtList, FtDropIndex and FtInfo

.github/workflows/ci.yml, src/server/dragonfly_test.cc, src/server/test_utils.cc, src/server/tiered_storage_test.cc
=> test(server): Run all unit tests with `--force_epoll`

src/server/main_service.cc, src/server/transaction.cc, src/server/transaction.h
This will save hops by short-circuiting execution of commands.
=> opt(server): Execute lua on target shard, if it's 1

src/server/db_slice.cc, src/server/search/doc_index.cc, src/server/search/search_family_test.cc
This PR adds missing expiry updates for search documents
=> feat: Update search index on expiry

src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h, tests/dragonfly/conftest.py, tests/dragonfly/connection_test.py, tests/dragonfly/snapshot_test.py
=> fix: Fix squashing, pytest arg formatting

src/facade/dragonfly_connection.cc
Fixes flushing bug found by regtests
=> fix: fix batching during dispatch mode changes

src/core/bptree_set.h, src/core/sorted_map.cc, src/core/sorted_map_test.cc, src/server/zset_family_test.cc
=> feat: implement GetRange/GetLexRange for bptree.

src/server/replica.cc
When we re-connect to a redis master with partial sync, don't say 'Starting full sync'
=> replication: fix misleading log message about full sync

src/core/compact_object.cc, src/core/compact_object_test.cc, src/core/string_map.cc, src/core/string_map.h, src/core/string_map_test.cc
This PR adds defragmentation for hash values
=> feat: Defragmentation for hash values 

src/server/memory_cmd.cc
=> chore: add clear metric for the fragmentation waste

tests/dragonfly/search_test.py
Must be some kind of broken merge🤷🏻
=> fix: fix search test

.github/workflows/ci.yml
=> chore: integrate sccache

.github/workflows/ci.yml
=> chore: cover zset over bptree implementation in the CI.

src/server/server_family.cc
Now if rdb load fails we the server will exit
=> fix(server): service exit on rdb load fail

src/facade/dragonfly_connection.cc, src/server/main_service.cc
=> fix: Add db id to client list attributes

src/server/server_family.cc
now used_memory_rss is computed correctly.
=> fix: account for huge pages when displaying RSS usage

src/redis/object.c
=> fix: Add missing encodings to strEncoding

src/server/server_family.cc
=> fix: add maxmemory_policy item to info memory section

.github/workflows/daily-builds.yml, docs/build-from-source.md, patches/lua-v5.4.4.patch, src/CMakeLists.txt, src/core/CMakeLists.txt, src/core/dash_test.cc, src/core/search/indices.cc, src/core/search/parser.y, src/facade/dragonfly_connection.cc, src/facade/dragonfly_listener.cc, src/redis/debug.c, src/redis/zmalloc.h, src/server/CMakeLists.txt, src/server/detail/save_stages_controller.cc, src/server/dfly_main.cc, src/server/generic_family.cc, src/server/main_service.cc, src/server/memory_cmd.cc, src/server/rdb_load.cc, src/server/rdb_save.cc, src/server/search/doc_index.h, src/server/server_family.cc
It compiles most of the code though some linking problems still exist.
=> chore: add macos daily build

.github/workflows/release.yml, docs/build-from-source.md, src/CMakeLists.txt, src/core/search/CMakeLists.txt, src/core/search/indices.cc, src/server/search/search_family_test.cc, tools/packaging/Dockerfile.alpine-dev, tools/packaging/Dockerfile.ubuntu-dev
=> Remove ICU library

src/redis/stream.h, src/server/stream_family.cc, src/server/stream_family.h, src/server/stream_family_test.cc
Add support for `xclaim` command.
Fixes #1162
=> feat(stream): add support for xclaim command

src/facade/dragonfly_connection.cc
=> chore: partially revert adjust batching behavior to reduce network

src/facade/dragonfly_connection.cc
Reverts dragonflydb/dragonfly#1821
=> Revert "chore: partially revert adjust batching behavior to reduce network"

.github/workflows/ci.yml
Reverts dragonflydb/dragonfly#1815, this prevents contributions from outside of the repo (see #1832)
=> Revert "feat(CI): Configure sccache to work with GCS"

src/core/search/parser.y, src/core/search/search_test.cc
=> fix(search-parser): fix AND, OR, NOT parsing issue

src/server/CMakeLists.txt, src/server/acl/test/wrong.acl, tests/dragonfly/acl_family_test.py
* Create a temporary acl file to test within acl_family_test
* Use tempfile to generate temporary files 
* Delete old files from src/server/acl/test
* Fixes the release build
=> fix(AclFamily): move acl test files to pytest

.devcontainer/fedora/devcontainer.json, .github/actions/regression-tests/action.yml, .github/workflows/release.yml, Makefile, tests/README.md, tools/packaging/Dockerfile.alpine-dev, tools/packaging/Dockerfile.alpine-prod.wip, tools/packaging/Dockerfile.ubuntu-dev, tools/packaging/Dockerfile.ubuntu-prod, tools/packaging/rpm/build_rpm.sh, tools/packaging/rpm/dragonfly.conf, tools/packaging/rpm/dragonfly.service, tools/packaging/rpm/dragonfly.spec
Also, link dragonfly with stdlib++ and libgcc statically.
=> Add build_rpm script and rpm spec

src/server/server_family.cc, tests/dragonfly/server_family_test.py
=> Support 'databases' alias for CONFIG GET

.github/workflows/daily-builds.yml, src/CMakeLists.txt, src/core/CMakeLists.txt, src/core/search/CMakeLists.txt
=> chore: enable search lib on Apple

src/server/detail/snapshot_storage.cc
With this the macos workflow passes: https://github.com/andydunstall/dragonfly/actions/runs/6187852066
=> feat(snapshot): fix build on macos

.github/workflows/daily-builds.yml, src/server/server_family.cc
Build everything on macos.
Run all the tests.
=> Run unit tests in macos build

src/server/json_family.cc, tests/dragonfly/json_test.py
Fixes https://github.com/dragonflydb/dragonfly/issues/1863
=> fix: fix json.arrappend not allowing passing JSON objects

.github/workflows/release.yml
=> chore: build rpm package for the release

tools/packaging/Dockerfile.ubuntu-dev, tools/packaging/Dockerfile.ubuntu-prod
Fixed [weekly builds](https://github.com/dragonflydb/dragonfly/actions/workflows/docker-weekly.yml) and also reduced our prod docker size.
Build that succeeded: https://github.com/dragonflydb/dragonfly/actions/runs/6217698601
=> fix: weekly build

src/server/acl/acl_family.cc, src/server/acl/acl_family.h, src/server/acl/acl_family_test.cc
* add acl users command
* add unit tests
@dranikpg I did not forget you with the proactor pool change. I will add it on the PR's that polish our implementation
resolves: #1886
=> feat(AclFamily): add acl users command

src/server/acl/acl_family.cc, src/server/acl/acl_family.h, src/server/acl/acl_family_test.cc
* add acl getuser command
* add unit tests
@dranikpg same as part 13
resolves: #1888
=> feat(AclFamily): add acl getuser command

src/server/test_utils.cc, src/server/test_utils.h
=> chore: Introduce basic deadlock detector for tests

src/core/search/ast_expr.h, src/core/search/search.cc, src/core/search/search.h, src/core/search/search_test.cc, src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
Don't crash on errors in search.
=> fix: Better error handling in search algorithm

src/facade/reply_builder.cc
=> fix: avoid calling 'sink_->Write()' with an empty buffer

src/server/transaction.h
=> doc(server): Copy important note from transactions doc to the code

src/server/search/doc_index.cc, tests/dragonfly/search_test.py
The details of the vector field were missing from the snapshot
=> fix: Correctly persist vector indices

src/server/transaction.cc
=> opt(server): Call `reserve()` with correct argument

src/server/main_service.cc, src/server/main_service.h, src/server/multi_test.cc, src/server/transaction.cc, src/server/transaction.h
=> opt(lua): Avoid separate hops for lock & unlock on single shard execution

src/server/test_utils.cc
=> fix: Actually print fibers from all the threads

tests/dragonfly/connection_test.py, tests/dragonfly/requirements.txt
Current version doesn't even work with the search tests
=> chore(regtest): Update redis dependency

tests/dragonfly/replication_test.py
=> fix(regtests): filter client setinfo from rewrite log

src/core/search/ast_expr.cc, src/core/search/ast_expr.h, src/core/search/lexer.lex, src/core/search/parser.y, src/core/search/search.cc, src/core/search/search.h, src/server/search/doc_index.cc, src/server/search/doc_index.h, src/server/search/search_family.cc, src/server/transaction.cc, tests/dragonfly/search_test.py
=> feat(search): return scores

src/server/server_family.cc
Looks like `search/search_family.cc` isn't included on mac - which means `RebuildAllSearchIndices` segfaults as `service->FindCmd("FT.CREATE")` returns `null` in https://github.com/dragonflydb/dragonfly/blob/main/src/server/server_family.cc#L253 when loading snapshots
(Once macos is in a more stable state should probably enable in regression tests or something)
=> fix: macos segfault loading snapshot

src/server/detail/save_stages_controller.cc, src/server/detail/save_stages_controller.h, src/server/dflycmd.cc, src/server/dflycmd.h, src/server/error.h, src/server/journal/journal_slice.cc, src/server/protocol_client.h, src/server/rdb_load.cc, src/server/rdb_load.h, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/replica.cc, src/server/replica.h, src/server/server_family.cc, src/server/snapshot.cc, src/server/snapshot.h, src/server/version.h, tests/dragonfly/__init__.py, tests/dragonfly/proxy.py, tests/dragonfly/replication_test.py, tests/dragonfly/utility.py
This enables partial sync on replication reconnects.
=> feat(replication): First iteration on partial sync.

src/server/error.h, tests/dragonfly/proxy.py, tests/dragonfly/replication_test.py
Apparently GitHub runners don't like IPv6?
=> fix(regtests): Bind to 127.0.0.1 and not localhost

src/server/dfly_main.cc, src/server/engine_shard_set.cc, src/server/replica.cc
=> fix: small typos on flags

src/server/acl/acl_family.cc, src/server/acl/acl_family_test.cc, src/server/acl/user_registry.cc, src/server/acl/user_registry.h, tests/dragonfly/acl_family_test.py
* do not allow to delete default user
* upon loading an acl file, if default does not exist create them
* add test
=> fix(AclFamily): do not allow to delete default user

tests/dragonfly/cluster_test.py, tests/dragonfly/instance.py, tests/dragonfly/replication_test.py
as caught on https://github.com/dragonflydb/dragonfly/actions/runs/6326295832/job/17206983510
=> fix(regtests): Limit infinite loop in replication_test

src/facade/conn_context.h, src/server/acl/acl_log.cc, src/server/cluster/cluster_family.cc, src/server/conn_context.cc, src/server/dflycmd.cc, src/server/main_service.cc, src/server/server_family.cc
=> chore: rename owner to conn

src/server/db_slice.cc, src/server/dflycmd.cc, src/server/engine_shard_set.cc, src/server/rdb_load.cc, src/server/server_family.cc
=> chore: adjust verbosity level 1 not be over-verbose in prod

src/server/dfly_main.cc
Replace raw `new/delete` with RAII for admin and main listener
=> chore(dfly_main): refactor to use RAII

src/server/conn_context.h, src/server/main_service.cc
=> fix: fix eval in multi interpreter borrow

src/core/interpreter.cc, src/server/stream_family.cc, src/server/stream_family.h, src/server/stream_family_test.cc
fixes: https://github.com/dragonflydb/dragonfly/issues/1899
Examples:
```
127.0.0.1:7000> xadd foo 1-* k1 v1                                                                                                                                                            
"1-0"                                                                                                                                                                                         
127.0.0.1:7000> xadd foo 1-* k2 v2                                                                                                                                                            
"1-1" …
```
=> feat(streams): support XAUTOCLAIM command

src/server/CMakeLists.txt, src/server/dfly_main.cc
=> fix: make --help flag work for development builds

src/server/main_service.cc, src/server/test_utils.cc, tests/dragonfly/instance.py
=> opt(server): If unspecified, use num_shards == proactor_threads

tests/dragonfly/instance.py
* add vmodule (dragonfly_connection, accept_server, listener_interface) level 1 logging for df instances
* print generated logs when an instance fails to stop
=> chore(regTests): add basic module logging and print when tests fail

.github/workflows/regression-tests.yml
Replace the job timeout with build timeout + run timeout
=> chore(regTests): separate build and reg tests timeouts

src/server/engine_shard_set.cc, src/server/engine_shard_set.h
=> fix(server): Start periodic fiber only once init completes

src/core/search/ast_expr.cc, src/core/search/ast_expr.h, src/core/search/base.h, src/core/search/indices.cc, src/core/search/indices.h, src/core/search/lexer.lex, src/core/search/parser.y, src/core/search/scanner.h, src/core/search/search_parser_test.cc, src/core/search/search_test.cc, src/core/search/sort_indices.cc, src/core/search/sort_indices.h
Changes all integers to doubles
=> fix(search): Use double numeric values

src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/multi_command_squasher.h
* exclude eval from pipeline squashing
* add some debug prints to multi-command-squasher
=> fix(server): Exclude eval from pipeline squashing

src/server/main_service.cc
Fixes #2032, needed for redis-om library
=> feat(server): Support COMMAND INFO

src/server/command_registry.cc, src/server/server_family.cc, src/server/server_state.h, src/server/slowlog.cc, src/server/slowlog.h
=> chore: add a debug check in slowlog

src/server/set_family.cc, src/server/set_family_test.cc
=> feat: implement SINTERCARD

src/server/acl/acl_family.cc, tests/dragonfly/acl_family_test.py
=> feat(acl): add config set for aclfile

src/core/dense_set.cc, src/core/dense_set.h, src/core/string_map.cc, src/core/string_map.h, src/core/string_map_test.cc, src/server/generic_family.cc, src/server/generic_family_test.cc, src/server/hset_family.cc, src/server/hset_family.h, src/server/search/doc_accessors.cc, src/server/set_family.cc
Fix some corner case bug with set family as well.
=> feat: implement fieldttl for the hash family

src/core/search/lexer.lex, src/core/search/parser.y, tests/dragonfly/requirements.txt, tests/dragonfly/search_test.py
Add redis-om tests to ensure it keeps being supported
=> chore(search): add redis-om test

src/server/replica.cc, src/server/replica.h, tests/dragonfly/replication_test.py
=> fix: localize timeout in test_cancel_replication_immediately test

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, tests/dragonfly/connection_test.py
=> fix: skip setting tcp_nodelay for unix domain sockets

.github/workflows/ci.yml, src/facade/facade.cc, src/server/acl/acl_family.cc, src/server/common.h, src/server/main_service.cc
=> wrap dragonfly_test with gdb inside a CI

src/core/search/ast_expr.cc, src/core/search/ast_expr.h, src/core/search/parser.y, src/core/search/search_test.cc, tests/dragonfly/search_test.py
Last small change to broaden support for redis-om
=> chore(search): Add exclusive range option

src/server/memory_cmd.cc
This command forces the memory manager to decommit memory pages back to the OS. In addition, fixed some positional bugs in "memory malloc-stats"
=> feat: add 'memory decommit' command

src/facade/dragonfly_connection.cc, src/server/rdb_save.cc, tests/dragonfly/server_family_test.py
=> fix: inject our own parser for slowlog get

src/server/detail/snapshot_storage.cc, src/server/detail/snapshot_storage.h, src/server/server_family.cc
=> feat(aws): add https support

src/core/dfly_core_test.cc, src/core/intent_lock.h, src/core/tx_queue.h, src/server/test_utils.cc
=> chore: add more debug info if a deadlock is caught in unit tests

src/server/db_slice.cc, src/server/db_slice.h, src/server/generic_family.cc, src/server/generic_family.h, src/server/generic_family_test.cc
Add NX, XX, LT, GT options to EXPIRE, EXPIREAT, PEXPIRE and PEXPIREAT.
https://github.com/dragonflydb/dragonfly/issues/842
=> feat: Implement options for EXPIRE command

src/server/search/doc_index.cc, tests/dragonfly/search_test.py
Fix bug with field flags not being persisted in snapshots
=> fix(search): Persist field flags

src/server/main_service.cc, src/server/multi_test.cc
=> fix(server): Fix crash when connection uses multiple lua scripts

src/server/db_slice.cc, src/server/replica.cc, src/server/server_family.cc, tests/dragonfly/replication_test.py
* Makes FLUSHALL sync
~~* Removes preceding FLUSHALL to Replicaof~~
* Refactors ReplicaOf
* Fixes bug in Replica with reply
=> fix(replica): fix replica reconnect handing

src/core/dense_set.cc, src/core/dense_set.h, src/core/string_map.cc, src/core/string_map.h, src/core/string_set_test.cc, src/server/dfly_main.cc, src/server/hset_family.cc, src/server/rdb_load.cc, src/server/rdb_save.cc
=> fix: Correctly grow dense_set in the Reserve call

src/server/server_family.cc
This is regarding the issue #1904, @royjacobson can you please take your time to see if it's solve the issue or need to make any changes to resolve the issue or in correct track.
=> Add number of threads to INFO

src/facade/dragonfly_listener.cc
https://github.com/dragonflydb/dragonfly/issues/2090
=> fix(facade): Avoid check on getsockopt  SO_INCOMING_NAPI_ID

src/server/acl/acl_family.cc, src/server/acl/acl_log.cc, src/server/acl/acl_log.h, tests/dragonfly/acl_family_test.py
=> feat(acl): add config set for acllog_max_len

tests/dragonfly/requirements.txt, tests/pytest.ini
=> chore: improve pytest ux

src/server/multi_test.cc, src/server/transaction.cc
=> fix(transaction): Reset reverse index in multi-tx

src/server/detail/save_stages_controller.cc, src/server/detail/snapshot_storage.cc, src/server/server_family.cc, tests/dragonfly/replication_test.py
Specifically, the confusion is often around the cron expression.
=> chore: help users to fix a mistake of setting quotes in the flagfile

src/facade/dragonfly_connection.cc, src/server/multi_command_squasher.cc
* Raise pipeline squashing limit to 10
* Add a comment to multi_command_squasher
=> chore: raise pipeline squashing limit

src/server/config_registry.cc, src/server/dfly_main.cc, src/server/server_family.cc
* fix small data race with maxclients
* make config::set an atomic operation
=> fix: small races on config registry and maxclients

README.md
=> doc(README): Explain how to use env var flags

src/server/hset_family.cc, src/server/hset_family_test.cc
=> fix(server): Do not return empty array after expiration

src/core/search/lexer.lex, src/core/search/search_parser_test.cc, src/server/search/doc_accessors.cc, src/server/search/doc_accessors.h, src/server/search/search_family.cc, src/server/search/search_family_test.cc
* The RETURN clause supports generic json expressions, so don't crash when they're invalid 😅 
* Fix a very stupid bug with serialization
=> chore(search): Safe json validation, serialize fix

src/server/main_service.cc
It's not the prettiest, but it's functional.
=> feat(server): Add `/clusterz` page with info on cluster

src/server/dragonfly_test.cc
@theyueli please make sure that with your new eviction changes, it makes sense for a recently inserted key to be removed.
=> fix(unittest): Fix regression to sticky-eviction unittest

.github/workflows/ci.yml, src/facade/facade_test.cc, src/facade/facade_test.h, src/server/zset_family_test.cc
=> chore: Enable unit-tests in CI

src/server/search/doc_index.cc, src/server/search/search_family.cc, src/server/search/search_family_test.cc, src/server/server_family.cc, tests/dragonfly/search_test.py
* Add index definition info to FT.INFO
* Add field flags into to FT.INFO
=> chore(search): Extend FT.INFO

src/server/detail/save_stages_controller.cc, src/server/detail/snapshot_storage.cc, src/server/detail/snapshot_storage.h, src/server/server_family.cc
=> feat:add new macros {Y}, {m} and {d} to dbfilename flag

README.zh-CN.md
=> docs(readme): Fix README.zh-CN benchmark link

README.md
=> doc: How to bind to all IPv4 IP addresses

src/facade/cmd_arg_parser.cc, src/server/set_family.cc, src/server/set_family_test.cc, src/server/zset_family.cc, src/server/zset_family.h, src/server/zset_family_test.cc
=> feat: add SRANDMEMBER and ZRANDMEMBER

src/server/cluster/cluster_family_test.cc
=> fix(tests): Fix flaky cluster test

src/server/dflycmd.cc, src/server/dflycmd.h, src/server/main_service.cc, tests/dragonfly/replication_test.py
=> chore: lower takeover test load, add comments

src/facade/dragonfly_connection.cc
Moves refactoring out of #2156 
* Fix message size computation
* Drain dispatch queue on disconnect
=> chore: dragonfly_connection fixes

CONTRIBUTORS.md, contrib/charts/dragonfly/README.md
* Fixed the link to the Helm packages that was returning a 404.
* Added the example command in a a shell code block
=> Incorrect link to helm chart packages

src/server/detail/save_stages_controller.cc, src/server/detail/save_stages_controller.h, src/server/dflycmd.cc, src/server/main_service.h, src/server/rdb_load.cc, src/server/rdb_load.h, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/replica.cc, src/server/search/search_family.cc, src/server/server_family.cc, src/server/server_family.h, src/server/transaction.cc, src/server/transaction.h, tests/dragonfly/replication_test.py
Adds support for replicating search index definitions
=> fix(search): Fix replication

tests/dragonfly/replication_test.py
we have a bug in client pause with squashing commands flow
skipping this test till we fix the bug
=> regression: skip client pause test utill we fix the bug

src/server/server_family.cc
* add missing field used_memory_peak
=> chore(server_family): add missing field used_memory_peak_human in command info

src/server/json_family.cc, src/server/json_family_test.cc
=> fix(json): fix json dot path

src/server/server_family.cc, src/server/server_family.h
Langchain needs this for some reason... 😕  
Also fixes #2135
=> chore: Module list

src/facade/dragonfly_connection.cc, src/facade/memcache_parser_test.cc, tests/dragonfly/pymemcached_test.py
Addresses #2120
* fix length checks for store commands
* add test
=> fix(memcached): add length check for key values

src/core/search/search.cc, src/server/search/search_family_test.cc
Found when running https://github.com/RedisVentures/redis-product-search
=> fix(search): Fix score alias for knn wrapped in sort

src/facade/dragonfly_listener.cc, src/server/conn_context.cc, src/server/dflycmd.cc, src/server/engine_shard_set.cc, src/server/journal/journal.cc, src/server/main_service.cc, src/server/server_state.cc, src/server/snapshot.cc, src/server/test_utils.cc
The fix itself in helio. Here we just pull it and align the code.
=> fix: regression test failures

src/core/dash_internal.h
=> fix: wrong assert check in dash segment

src/server/rdb_save.cc, src/server/snapshot.cc
=> fix(server): Fix crash when using MEMORY STATS commands

src/server/list_family.cc
=> fix(server): Call PostUpdate from `LPUSH` even for new keys

src/CMakeLists.txt, src/core/json_test.cc
=> chore: add a test demonstrating on how to pass a dash within json path

src/facade/acl_commands_def.h, src/server/acl/user.cc, src/server/acl/user.h, src/server/acl/user_registry.cc, src/server/acl/user_registry.h, src/server/acl/user_registry_test.cc
PR1:
* add storage for acl keys
part of #2229
(tests are added in later PR's because it's easier to test once we have acl get and acl list with keys -- see later PR's)
=> feat(acl): add storage for acl keys

src/server/tiered_storage.cc
=> chore: update helio

src/facade/dragonfly_connection.cc, tests/dragonfly/connection_test.py
Fixes a bug found in #2255 
Adds a test
=> fix(server): Fix client pause and add test

src/server/server_family.cc
This will allow easier aggregation and usage with Prometheus & Grafana
=> feat(server): Better reporting of per-type memory in `/metrics`

CONTRIBUTORS.md, src/facade/reply_builder.cc, src/facade/reply_builder.h, src/facade/reply_builder_test.cc, src/server/main_service.cc, src/server/main_service.h, tests/dragonfly/connection_test.py
Related Issue: https://github.com/dragonflydb/dragonfly/issues/847
Implement NUMSUB subcommand
=> feat(server): Implement NUMSUB subcommand

src/core/heap_size.h, src/facade/conn_context.h, src/server/conn_context.cc, src/server/conn_context.h, src/server/main_service.cc, src/server/memory_cmd.cc
While at it, fix initialization of replication info, to correctly account for replication connections.
=> fix(memory): Add missing fields in connection memory

src/facade/conn_context.h, src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, src/facade/dragonfly_listener.cc, src/facade/dragonfly_listener.h, src/facade/facade.cc, src/facade/op_status.h, src/server/blocking_controller_test.cc, src/server/cluster/cluster_config.cc, src/server/cluster/cluster_config.h, src/server/cluster/cluster_family.cc, src/server/conn_context.cc, src/server/conn_context.h, src/server/container_utils.cc, src/server/container_utils.h, src/server/dflycmd.cc, src/server/list_family.cc, src/server/main_service.cc, src/server/server_family.cc, src/server/server_family.h, src/server/stream_family.cc, src/server/transaction.cc, src/server/transaction.h, src/server/zset_family.cc, tests/dragonfly/cluster_test.py
=> feat(cluster): Cancel blocking commands on cluster update

src/server/server_family.cc
=> feat(server): Add dispatch queue bytes to /metrics

src/server/replica.cc, src/server/replica.h, src/server/server_family.cc
=> feat(replica): add master id on replica output for info replication

src/server/blocking_controller.cc, src/server/db_slice.cc, src/server/db_slice.h, src/server/generic_family.cc, src/server/generic_family_test.cc, src/server/json_family.cc, src/server/set_family.cc, src/server/string_family.cc, src/server/table.h, src/server/zset_family.cc
=> refactor(DbSlice): Replace `FindExt()` with `FindMutable()` and `FindReadOnly`

src/core/dense_set.cc, src/core/dense_set.h
=> feat(server): Better accounting of DenseSet memory

src/server/stream_family.cc, src/server/stream_family_test.cc
partly fixes #2294
bug: id ">" means that the consumer wants to receive only messages that were never delivered to any other consumer
fix: added temporary test results, the correct ones are commented out until we fix the blocking mechanism. Fix the requested range for blocking operations
=> fix(stream): make fix for XREADBLOCK function

src/server/blocking_controller_test.cc, src/server/engine_shard_set.cc, src/server/engine_shard_set.h, src/server/main_service.cc, src/server/main_service.h, src/server/multi_test.cc, src/server/server_family.cc, src/server/server_state.cc, src/server/server_state.h, src/server/string_family_test.cc, src/server/test_utils.cc, src/server/test_utils.h, src/server/transaction.cc, tests/dragonfly/eval_test.py
=> feat: introduce transaction statistics in the info output

src/server/CMakeLists.txt, src/server/command_registry.cc, src/server/command_registry.h, src/server/main_service.cc, src/server/server_family.cc, src/server/slowlog.cc, src/server/slowlog.h
Goal: to improve readability of the code.
=> chore: refactor slowlog code, no functionality changes

src/server/debugcmd.cc, src/server/debugcmd.h, src/server/main_service.cc, src/server/multi_command_squasher.cc, src/server/server_family.cc, src/server/server_state.cc, src/server/server_state.h
This information is exposed via "DEBUG EXEC" command.
=> feat: track differrent patterns of multi/exec transactions

src/server/CMakeLists.txt, src/server/search/aggregator.cc, src/server/search/aggregator.h, src/server/search/aggregator_test.cc
First step for aggregator for FT.AGGREGATE #2190. 
PS: Using FT.AGGREGATE will also allow sorting without sortable fields
=> feat(search): Aggregator, step 1

src/facade/reply_builder.cc, src/facade/reply_builder.h, src/server/server_family.cc, src/server/server_family.h
=> feat(server): Add reply count & latency metrics

src/server/transaction.cc
=> fix: Invalid key lock strings with squashing

src/server/server_family.cc
=> fix(server): Fix reply seconds & better metrics names

src/core/simple_lru_counter.cc, src/core/simple_lru_counter_test.cc
=> fix(SimpleLruCounter): Correctly set bumped node's next

src/server/db_slice.cc, src/server/db_slice.h, src/server/engine_shard_set.cc, src/server/multi_test.cc, src/server/transaction.cc, src/server/transaction.h
=> chore: transaction simplification

src/facade/CMakeLists.txt, src/facade/conn_context.cc, src/facade/conn_context.h, src/facade/dragonfly_connection.cc, src/facade/facade.cc, src/facade/facade_types.h, src/facade/reply_builder.cc, src/facade/reply_builder.h, src/facade/reply_builder_test.cc, src/server/server_family.cc, src/server/server_family.h
Also, get rid of awkward reply builder statistics and use thread local stats for that
=> chore: add "send" state to client list

src/server/generic_family.cc, src/server/rdb_save.cc, src/server/rdb_save.h, src/server/rdb_test.cc
=> refactor(rdb): Expose default compression mode without direct flag

src/server/generic_family.cc, src/server/rdb_save.cc, src/server/rdb_save.h
=> refactor(serializer): Move DUMP logic into RdbSerializer

src/facade/dragonfly_connection.cc, src/facade/dragonfly_listener.cc, src/server/transaction.cc
=> feat: introduce user timeout

src/facade/dragonfly_listener.cc
=> chore: add comment for c_rehash in ca_cert_dir flag description

src/core/sorted_map_test.cc
=> chore: add memory usage test for skiplist encoding

src/server/main_service.cc, tests/dragonfly/snapshot_test.py
=> fix(server): crash on rename save command on background save

src/server/cluster/cluster_family.cc, src/server/cluster/cluster_family.h, src/server/cluster/cluster_shard_migration.cc, src/server/cluster/cluster_slot_migration.cc
Just small refactoring to remove extra step for cluster migration procedure
=> refactor(cluster): remove SYNC cmd and do data transferring during FLOW

src/server/dfly_main.cc
=> fix: ignore unexpected contents for /sys/fs/cgroup/cpu.max

src/server/server_family.cc, src/server/server_family.h
1. Move helper functions to cc anonymous scope
2. Remove dead code.
=> chore: server_family cleanups

src/server/server_family.cc
Adding it both to the info log and the INFO response in the server section, similarly to how it's reported by redis.
=> feat: add os string

src/server/cluster/cluster_family_test.cc, src/server/debugcmd.cc, src/server/detail/save_stages_controller.cc, src/server/detail/save_stages_controller.h, src/server/generic_family_test.cc, src/server/rdb_test.cc, src/server/server_family.cc, src/server/server_family.h
implement #2386
added fields:
1) last_failed_save
2) last_error
3) last_failed_save_duration_sec
4) saving
5) current_save_duration_sec
=> feat(info): add new persistence section fields

src/server/journal/streamer.cc, src/server/journal/streamer.h
=> feat(cluster): Add params to slot migration full sync cut

src/server/debugcmd.cc, src/server/debugcmd.h
=> feat: allow checking the compressability of the data

src/server/memory_cmd.cc
=> fix: do not return an error in memory-usage command

src/facade/dragonfly_connection.cc, src/facade/dragonfly_connection.h, tests/dragonfly/connection_test.py
Fix bug with missing flush after stopping dispatch fiber for migration
=> Fix flush when migrating connection

src/core/dash_internal.h, src/core/dash_test.cc
=> feat: introduce segment merge operation

src/server/transaction.cc, src/server/transaction.h
Guards access to local_result_ in case of oom error where multiple shards might write into it at once -> ub
=> fix(tx): guard parallel writes to local result

src/server/rdb_load.cc, src/server/transaction.cc, src/server/transaction.h
=> fix(rdb): Remove transaction from pre/post load search index rebuild

src/server/db_slice.cc, src/server/db_slice.h, src/server/server_family.cc, src/server/server_family.h
=> fix: non reset fields in command config resetstat

src/server/dragonfly_test.cc, src/server/server_family.cc
=> fix(info): Reply with correct `redis_mode` in `INFO

tools/release.sh
=> fix: release.sh

src/server/db_slice.h, src/server/engine_shard_set.cc, src/server/engine_shard_set.h, src/server/transaction.cc, src/server/transaction.h
Also allow OOO execution for all tx types
=> chore(transaction): Clean up scheduling code

src/core/bptree_set_test.cc
=> chore: add both df tree impelementations to memory usage test

src/server/engine_shard_set.cc, src/server/engine_shard_set.h, src/server/server_family.cc
=> fix(server): dont allow snapshoting in tiering mode

src/core/bptree_set_test.cc
=> chore: improve benchmark for bpptree and zsl tree

src/server/journal/streamer.cc
=> fix(RestoreStreamer): Fix a few glitches

tests/dragonfly/cluster_test.py, tests/dragonfly/utility.py
=> test(cluster): Enable seeder to work against a Dragonfly cluster

README.md
=> Update README.md to include dragonfly cloud link

src/server/journal/journal_slice.cc, src/server/top_keys.cc, src/server/transaction.cc, src/server/transaction.h
1. Stop writing to the replication ring_buffer
2. Stop allocating in TopKeys 
3. Tighter CHECKs around tx execution.
=> fix: fixes for v1.14.0

src/core/interpreter.cc, tests/dragonfly/eval_test.py
fixes #2441 
* add no-op redis.log command
=> feat(lua): add no-op redis.log command

tests/dragonfly/redis_replication_test.py
1. Reduced number of slaves in the test from 4 to 2. Not sure why we test with many DF slaves and how it helps with testing DF.
2. Improved pytest code and added more logs so we won't spend time on this test again in the future.
=> Fix redis->DF replication tests

tests/dragonfly/replication_test.py
=> test: Disable flaky test `test_policy_based_eviction_propagation`
