dragonflydb/dragonfly

- .github/workflows/docker-release.yml
Deploying components based purely on latest-tag is bad practice and might lead to problems down the line. Being able to use an immutable tag will make working with the container image more predictable.
Currently looking into writing a helm chart, and helm defaults to use the appVersion defined in the Chart.yaml as the image tag. Really don't want to hardcode the tag as latest :)
> Update docker-release workflow to tag image with release version

- .github/workflows/ci.yml
- .github/workflows/docker-release.yml
- .github/workflows/release.yml
This PR updates the GitHub Actions to latest major tags.
> CI: Use v3 of Actions "upload-artifacts", "checkout" and "cache"

- README.md
`cmake` and `c++` compilers are required to build from source.
Otherwise, you'll enter errors like
```
$ ./helio/blaze.sh -release
Using launcher
+ cmake -L -B build-opt -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=
./helio/blaze.sh: line 51: cmake: command not found
```
or
```
$ ./helio/blaze.sh -release
Using launcher
+ cmake -L -B build-opt -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -GNinja -DCMAKE_CXX_COMPILER_LAUNCHER=
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at …
```
> Update build steps for Ubuntu

- doc/dashtable.md
Hello, this is just a small typo fix.
In the [`dashtable.svg`](https://github.com/dragonflydb/dragonfly/blob/main/doc/dashtable.svg) diagram, the number segment is denoted by `N` while `K` is used for buckets (like bucket1, bucket2, ..., bucketK).
> docs: Fix a variable name for bucket in Dashtable section

- CONTRIBUTORS.md
- src/server/channel_slice.cc
- src/server/channel_slice.h
- src/server/conn_context.cc
- src/server/dragonfly_test.cc
- src/server/main_service.cc
- src/server/test_utils.cc
- src/server/test_utils.h
There were various readability issues around variants of `Subscriber` in functions, variables, docs.
This splits resolving those into logical commits.
```bash
grep -ri subsrib | wc -l
27
grep -ri subsrib | wc -l
0
```
Let me know if anything looks off to you. I separated them to make it easier to revert if something isn't correct.
Best,
Ryan
> Fix Various Naming Conventions around `Subscriber`

- contrib/charts/dragonfly/Chart.yaml
- contrib/charts/dragonfly/README.md
- contrib/charts/dragonfly/templates/deployment.yaml
- contrib/charts/dragonfly/templates/metrics-service.yaml
- contrib/charts/dragonfly/templates/prometheusrule.yaml
- contrib/charts/dragonfly/templates/servicemonitor.yaml
- contrib/charts/dragonfly/templates/statefulset.yaml
- contrib/charts/dragonfly/templates/tls-secret.yaml
- contrib/charts/dragonfly/values.yaml
This will
- bump the chart appVersion to v0.1.1 and remove the hardcoded reference to the latest tag from values.yaml
- add a parameter to override the container's init command
- For something like (inspired by https://github.com/dragonflydb/dragonfly/issues/57#issuecomment-1145073128)
- ```
command:
cmd:
- '/bin/sh'
- '-c'
- 'ulimit -l unlimited && dragonfly'
securityContext:
privileged: true```
- implement parameters to enable the applications tls function
- this was possible to be done before, but required fiddling with extraArgs, extraVolumes and extraVolumeMounts
- add CRs for ServiceMonitor and PrometheusRule objects, so the app can be monitored and alerting can be configured
Please feel free to squash and merge the PR on your end :)
> Helm chart updates (v0.1.1, init command override, TLS configuration, CRs for ServiceMonitor and PrometheusRule objects)

- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/dragonfly_test.cc
- src/server/main_service.cc
Both `UNSUBSCRIBE` and `PUNSUBSCRIBE` have a command arity of -1 in the official redis implementation where no arguments implies that all channels (for `UNSUBSCRIBE`) or patterns (for `PUNSUBSCRIBE`) should be removed from the connections subscriptions.
- Extracted logic for unsubscribing "all" from `OnClose` into `UnsubscribeAll` and `PUnsubscribeAll`.
- Extracted common code for building `{subscribe, unsubscribe, psubscribe, punsubsribe}` responses into `SendSubscriptionChangedResponse` method.
1. CLI:
```bash
> echo UNSUBSCRIBE | redis-cli
1) "unsubscribe"
2) (nil)
3) (integer) 0
> echo PUNSUBSCRIBE | redis-cli
1) "punsubscribe"
2) (nil)
3) (integer) 0
```
2. Python 
```python
import redis
client = redis.Redis()
pubsub = client.pubsub()
pubsub.subscribe(f"channel{i}" for i in range(5)) …
```
> Support Pubsub (P)UNSUBSCRIBE commands without arguments

- src/server/conn_context.cc
- src/server/conn_context.h
This issue was noted while testing the changes for #111. The reference redis implementation returns the total number of subscriptions for `{SUBSCRIBE, UNSUBSCRIBE, PSUBSCRIBE, PUNSUBSCRIBE}` commands ([reference](https://github.com/redis/redis/blob/805191c791e1f84618c1f69dacec27ac3fecd1e4/src/pubsub.c#L167)).
> Use sum instead of individual counts for channels/patterns

- src/facade/facade_types.h
- src/server/dragonfly_test.cc
- src/server/server_family.cc
- src/server/stream_family_test.cc
Only accept `protover=2` as a valid argument as that is the only thing that is supported at the moment. For all other arguments degrade to 'unknown command'
The previous implementation creates issues for clients expecting the presence of the HELLO command to also signal
the presence of RESP3 (as technically the command appeared in redis at the same time as support for RESP3).
It also did not raise any errors when unsupported (or invalid) arguments were passed to the command (such as `AUTH`, `SETNAME`)
#126 
- `SETNAME` support
- `AUTH` support
> Reduce scope of HELLO implementation

- .github/PULL_REQUEST_TEMPLATE.md
This will reduce redundancy around asking new committers to signoff and follow conventional commits.
> docs(PR Template): Add PR Template Enforcing Conventional Commits #107

- src/server/zset_family.cc
- src/server/zset_family_test.cc
1. fixed  zrevrange support WITHSCORES
2. add zrevrange test case
Fixes https://github.com/dragonflydb/dragonfly/issues/106
```
127.0.0.1:6379> zadd test 8 "a" 7 "b" 2 "c" 3 "d" 6 "e"
(integer) 5
127.0.0.1:6379> zrevrange test 0 100 WITHSCORES
1) "a"
2) "8"
3) "b"
4) "7"
5) "e"
6) "6"
7) "d"
8) "3"
9) "c"
10) "2"
```
```
[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from ZSetFamilyTest
[ RUN      ] ZSetFamilyTest.Add
[       OK ] ZSetFamilyTest.Add (20 ms)
[ RUN      ] ZSetFamilyTest.ZRem
[       OK ] ZSetFamilyTest.ZRem (14 ms)
[ RUN      ] ZSetFamilyTest.ZRangeRank
[       OK ] ZSetFamilyTest.ZRangeRank (16 ms)
[ RUN      ] ZSetFamilyTest.ZRemRangeRank
[       OK ] ZSetFamilyTest.ZRemRangeRank (24 ms)
[ RUN      ] …
```
> fix(zset): fixed zrevrange support WITHSCORES and add zrevrange test case (#106)

- src/facade/redis_parser.cc
- src/facade/redis_parser.h
- src/facade/redis_parser_test.cc
Relevant only for client-side parsing. Thus it did not affect production code.
> fix(parser): Fix wrong parsing of nested arrays.

- src/server/server_family.cc
Add support for INFO CPU based on the redis documentation found at https://redis.io/commands/info/
Fixes #18 
```
127.0.0.1:25455> info cpu
used_cpu_sys:23.13618
used_cpu_user:31.507270
used_cpu_sys_children:0.0
used_cpu_user_children:0.0
used_cpu_sys_main_thread:0.6184
used_cpu_user_main_thread:0.2086
```
> feat(server): Add support for CPU to Info family of commands (fixes #18)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
You probably still need to go into repo settings -> General and check `Template repository` (and check  `Require contributors to sign off on web-based commits` also) to get these to activate. 
After you do that, when you open a new issue, it should give them Bug/Feature as the only issue options.
They are also presented with Discord, Discussions(Where to put benchmark-ish things), and your Twitter :)
Let me know if there are any issues.
> chore(issues): Add issue templates with links to Discord/Discussions

- src/core/tx_queue.h
- src/facade/conn_context.h
- src/facade/dragonfly_connection.cc
- src/server/CMakeLists.txt
- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/engine_shard_set.cc
- src/server/main_service.cc
- src/server/stream_family.cc
- src/server/transaction.cc
- src/server/transaction.h
- tests/async.py
In rare cases a scheduled transaction is not scheduled correctly and we need
to remove it from the tx-queue in order to re-schedule. When we pull it from tx-queue
and it has been located at the head, we must poll-execute the next txs in the queue.
1. Fix the bug.
2. Improve verbosity loggings to make it easier to follow up on tx flow in release mode.
3. Introduce /txz handler that shows currently pending transactions in the queue.
4. Fix a typo in xdel() function.
5. Add a py-script that reproduces the bug.
> fix(transaction): Fix rare deadlock case - fixes #150.

- src/server/command_registry.cc
- src/server/command_registry.h
- src/server/dragonfly_test.cc
- src/server/main_service.cc
- src/server/transaction.cc
- src/server/zset_family.cc
1. Correctly parse keys for EVAL command.
2. Support PUBLISH within lua.
3. Remove spurious failure in debug-mode with the increased verbosity level.
Fixes #59 (another bug).
> fix(lua): Fix few lua-related bugs

- src/facade/dragonfly_connection.cc
- src/facade/facade.cc
- src/facade/facade_types.h
- src/facade/redis_parser.cc
- src/server/server_family.cc
Add indication of parser errors to info stats.
> fix(parser): Raise parser limit for array length from 8K to 64K

- .github/workflows/docker-release.yml
This should fix #144. Once a new container image is built and successfully pushed, the file `contrib/charts/dragonfly/Chart.yaml` will be updated based on `env.TAG_NAME`. This will only be done for non-prerelease images.
> feat(actions): bump helm-chart version when new container image is published

- contrib/docker/README.md
- contrib/docker/docker-compose.yml
> docs(docker-compose): Explain `NAT` overhead in docker-compose 

- src/facade/dragonfly_connection.cc
- src/facade/reply_builder.cc
- src/facade/reply_builder.h
- src/redis/CMakeLists.txt
- src/server/hset_family.cc
1. Make it use vectorized send instead of concatenating everything into a single string.
2. vectorized SendStringArr could fail sending large arrays for lengths higher than 512 (returned EMSGSIZE).
We improved the implementation so it would send those arrays in chunks of 256 items.
> chore(server): Improve the implementation of SendStringArr.

- src/server/error.h
- src/server/rdb_load.cc
- src/server/rdb_load.h
- src/server/rdb_test.cc
- src/server/set_family.cc
- src/server/set_family.h
Related to #159. Before this change, rdb loading thread has been creating all the redis objects as well.
Now we separate rdb file parsing and objects creation. File parsing phase produces a load trace of one or more binary blobs.
Those blobs are then passed to the threads that are responsible to manage the objects.
The second phase is object creation based on the trace that was passed. Finally those binary blobs are destroyed.
As a result, each thread creates objects using the memory allocator it owns and memory stats become consistent.
> chore(rdb): move object creation during loading to shard threads.

- .github/workflows/docker-release.yml
Docker release pipeline can not push to protected main branch using
the service token. This switches to PAT secret.
> fix(action): switch git push to dedicated action

- tests/pytest/test_dragonfly.py
Signed-off-by: Shmulik Klein <shmulik.klein@gmail.com>
> [WIP] test: add dragonfly_db fixture to python tests #199

- src/redis/object.c
- src/server/db_slice.cc
- src/server/db_slice.h
- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
- src/server/string_family.cc
- src/server/table.cc
- src/server/table.h
- src/server/test_utils.cc
1. Erase expiry data from the expire table in case of evictions.
2. Add test that covers the bug.
> fix(server): Fix #207

- src/server/CMakeLists.txt
- src/server/common.h
- src/server/debugcmd.cc
- src/server/dflycmd.cc
- src/server/dflycmd.h
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
- src/server/generic_family.cc
- src/server/hset_family.cc
- src/server/journal/journal.cc
- src/server/journal/journal.h
- src/server/journal/journal_shard.cc
- src/server/journal/journal_shard.h
- src/server/list_family.cc
- src/server/main_service.cc
- src/server/replica.cc
- src/server/server_family.cc
- src/server/server_family.h
- src/server/server_state.h
- src/server/set_family.cc
- src/server/stream_family.cc
- src/server/string_family.cc
- src/server/string_family.h
- src/server/transaction.cc
- src/server/transaction.h
- src/server/zset_family.cc
1. No entries data is written into a journal yet.
2. Introduced a state machine to start and stop journal using a new auxillary command "dfly".
3. string_family currently calls an universal command Journal::RecordEntry that should
save the current key/value of that entry. Please note that we won't use it for all the operations
because for some it's more efficient to record the action itself than the final value.
4. no locking information is recorded yet so atomicity of multi-key operations is not preserved for now.
> feat(journal): Introduce basic journal support.

- src/server/dfly_main.cc
> feat(server): add pidfile parameter.

- src/server/json_family.cc
- src/server/json_family.h
- src/server/json_family_test.cc
> feat(server): implement JSON.STRLEN & JSON.TYPE commands

- src/server/json_family.cc
- src/server/json_family.h
- src/server/json_family_test.cc
> feat(server): implement JSON.TOGGLE & JSON.ARRLEN & JSON.OBJLEN commands

- CONTRIBUTORS.md
- src/server/CMakeLists.txt
- src/server/server_family.cc
- src/server/server_family.h
- src/server/snapshot_test.cc
- tests/README.md
- tests/dragonfly/__init__.py
- tests/dragonfly/blpop_test.py
- tests/dragonfly/conftest.py
- tests/dragonfly/key_limit_test.py
- tests/dragonfly/requirements.txt
- tests/dragonfly/snapshot_test.py
- tests/pytest/conftest.py
- tests/pytest/requirements.txt
- tests/pytest/snapshot_test.py
- tests/pytest/test_dragonfly.py
* feat(test): Added the ability to specify dragonfly cli parameters on a test basis (#199)
Signed-off-by: Braydn <braydn.moore@uwaterloo.ca>
> feat(server): Implemented periodic snapshotting (#161)

- src/core/dash.h
- src/core/dash_internal.h
- src/core/dash_test.cc
- src/facade/facade_test.h
- src/server/db_slice.cc
- src/server/db_slice.h
- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/generic_family.cc
- src/server/rdb_load.cc
- src/server/server_family.cc
- src/server/snapshot.cc
- src/server/table.h
- src/server/tiered_storage.cc
Before this change Dragonfly evicted items only when it was low on memory and had to grow its main dictionary.
It is not enough because in many cases Dragonfly can grow in memory even when the main dictionary does not grow.
For example, when its dictionary is less than 90% utilized but the newly added objects require lots of memory.
In addition, the dashtable could add additional segments when others had enough available slots to fill the rest of the free memory.
This change adds another layer of defense that allows evicting items even when dictionary segments are not full.
The eviction is still local with respect to a segment. On my tests it seems that it's much harder to cross maxmemory limit than before.
In addition we improved our heuristic that allowed the dashtable to grow. Now it …
> feat(server): tighten memory checks when inseting a new object.

- docs/api_status.md
- src/server/CMakeLists.txt
- src/server/bitops_family.cc
- src/server/bitops_family.h
- src/server/bitops_family_test.cc
- src/server/main_service.cc
- src/server/string_family.h
feat(server): add support for bit commands - currently only getbit and setbit work correctly #213
* The command gitbit work correctly: return 1 if bit on, 0 otherwise including for missing keys and offset out of bound.
* The command setbit work correctly: return the old value for the bit at offset and set new key and value if missing.
* Other commands just return 0 for now
Signed-off-by: Boaz Sade <boaz1sade@gmail.com>
> feat(server): adding support for bitops #213

- docs/api_status.md
- src/server/generic_family.cc
- src/server/generic_family.h
- src/server/generic_family_test.cc
- src/server/list_family_test.cc
- src/server/test_utils.cc
- src/server/test_utils.h
- src/server/transaction.cc
> feat(server): Implement MOVE command

- docs/api_status.md
- src/server/bitops_family.cc
- src/server/bitops_family.h
- src/server/bitops_family_test.cc
Support for the bitcount command:
- update api_status.md update license
* If key doesn't exists - return 0.
* If range illegal (start less than end or start larger than value length) return 0.
* if only key name is given return the number of bit set to 1 for all the key value.
* If only range is given, count number of bits set to 1 for the bytes in the range.
* if range is given and last argument is BIT count in bits range and not bytes range.
> feat(server): bitcount commands support and unit tests  #213

- CMakeLists.txt
- cmake/Packing.cmake
- src/CMakeLists.txt
feat(packaging): create deb packaging #249
This allows creation of .deb package file after creating the dragonfly binary with ```ninja dragonfly```, using ```cpack -G DEB``` from ```./build-opts```
Dragonfly is installed to ```/usr/bin/dragonfly```
> feat(packaging): create deb packaging #249

- src/server/CMakeLists.txt
- src/server/bitops_family.cc
- src/server/blocking_controller.cc
- src/server/common.h
- src/server/db_slice.cc
- src/server/db_slice.h
- src/server/debugcmd.cc
- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
- src/server/generic_family.cc
- src/server/generic_family.h
- src/server/generic_family_test.cc
- src/server/hset_family.cc
- src/server/json_family.cc
- src/server/list_family.cc
- src/server/list_family_test.cc
- src/server/rdb_load.cc
- src/server/set_family.cc
- src/server/stream_family.cc
- src/server/string_family.cc
- src/server/string_family.h
- src/server/string_family_test.cc
- src/server/test_utils.cc
- src/server/test_utils.h
- src/server/transaction.cc
- src/server/transaction.h
- src/server/zset_family.cc
Partially implements #6.
Before, each shard lazily updated its clock used for the expiry evaluation.
Now, the clock value is set during the transaction scheduling phase and is assigned
to each transaction. From now on DbSlice methods use this value when checking whether
the entry is expired via passed DbContext argument.
Also, implemented transactionally consistent TIME command and
verify that time is the same during the transaction. See
https://ably.com/blog/redis-keys-do-not-expire-atomically for motivation.
Still have not implemented any lamport style updates for background processes
(not sure if it's the right way to proceed).
> feat(server): Introduce transaction clock

- src/server/CMakeLists.txt
Fixes #325. Apparently, before the fix AVX instructions were produced right at the start, thus the server crashed before it had a chance to install sigill handler.
> fix(server): dfly_main.cc now compiled with march=core2.

- docs/api_status.md
- src/server/bitops_family.cc
- src/server/bitops_family_test.cc
Support for bitop command
* For details about the command see [redis doc for the command](https://redis.io/commands/bitop/)
* This command set a dest key after running bit operation from other keys
* Note that the bytes class in the tes filet is not suitable for general use.
> feat(server): support for bitop command -  unit tests added #213

- src/server/common.cc
- src/server/zset_family_test.cc
Fixes #326 
The zrange commands accepts limits to filter out the number of eleents. These can be -INF/+INF, but these INF should handled as case insensitive to match how redis process these commands. see #326
> feat(server): zrange family command support INF as case insensitive #326

- src/core/dense_set.cc
- src/core/dense_set.h
- src/core/string_set.cc
- src/core/string_set.h
- src/core/string_set_test.cc
- src/server/set_family.cc
> chore(denseset): Simplify DenseSet, remove empty links.

- src/core/dense_set.cc
- src/core/string_set_test.cc
- src/server/set_family.cc
- src/server/set_family.h
Add `SADDEX <key> <seconds> member member ....`
Provides expiry semantics for set members with seconds resolution.
Some important things to note:
1. The expiry is passive only, so if nobody touches that set then its members are being kept.
2. SCARD provides an upper bound estimation of set size for sets holding the expiring members.
The reason for this is because SCARD returns a cached size and does not go over all members
to check whether they expired. For regular sets it's exact, of course.
Fixes #335
> feat(setfamily): Add SADDEX command

- src/server/CMakeLists.txt
- src/server/dfly_main.cc
This would ensure that when running "./dragonfly --help" it would report correctly the help message.
Note that 
* unlike --helpful that is not filtering any flags in the output, the help is more restricted to what is reported.
* This can break in case the complied locations for the files at which is searches for flags to report in the help are either at full path or relative path. This would try to ensure that it would work in either case.
> fix(server): better support for the --help option

- src/server/memory_cmd.cc
- src/server/memory_cmd.h
Now it will print deduplicated lines, shortening the table dramatically. Also it's now easier to import it into excel.
> chore(server): Improve malloc-stats output

- .github/workflows/docker-release.yml
fixes https://github.com/dragonflydb/dragonfly/issues/309
Looks like this:
To set up - first create a Discord webhook (make sure to put a nice avatar and name):
Then, add a new repo secret in GitHub:
> build(ci): add discord message on docker release

- docs/api_status.md
- src/server/generic_family.cc
- src/server/generic_family.h
- src/server/generic_family_test.cc
- src/server/rdb_save.cc
- src/server/rdb_save.h
Support for dump command.
* This was checked to be inline with the results produced by redis.
* Note that this would work only for version 9 of RDB, It seems that in the next version (10) the format is different (redis branch > 7).
* This support for list, hash, set, sorted set, stream and other types that we know how to generate RDB files for. 
* To make issue #343 cannot be closed until we are supporting restore as well.
> fix(server): support for dump command, API update #343

- src/server/db_slice.cc
- src/server/memory_cmd.cc
Also, add timing stats to malloc-stats command.
> fix(server): remove double decrement of obj_memory_usage.

- src/core/compact_object.cc
- src/core/compact_object.h
- src/core/compact_object_test.cc
- src/server/container_utils.h
- src/server/hset_family.cc
- src/server/hset_family_test.cc
- src/server/rdb_save.cc
- src/server/set_family.cc
The bug was that when the hset had listpack encoding, it returned only keys instead of returning keys and values.
In addition, in preparation to having our own denset encoding for hset, I cleaned up the code and introduced our own encoding constants for hset encoding.
> fix(hset): fix hset match bug

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
The sending of messages that require async handling such as pub/sub and pipelines is now using different implementation that is based on explicit typing. 
currently it would have support for 2 explicit types:
* pipeline - this mode delegates command through the connection.
* Pub/sub messages - publishing command through the connection to a given subscriber
This change is required so that we would later be able to support more types and easily change this to make it simpler.
We would use this change to support issue #344
> feat(server): sending and dispatching of messages using different internals

- docs/dense_set.md
- src/server/memory_cmd.cc
Also update dense_set.md with a reproducable test on how to see memory differences of DenseSet vs RedisDict.
> feat(server): Allow sampling arena stats from a specified thread

- docs/api_status.md
- src/facade/conn_context.h
- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/facade.cc
- src/server/CMakeLists.txt
- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/main_service.cc
- src/server/main_service.h
- src/server/server_state.cc
- src/server/server_state.h
Adding support for the monitor command.
The monitor command is a tool to debug other connections, by sending the command args to the connection which is set to mode 'monitor''.
For more details about the monitor command - [see redis monitor command doc here](https://redis.io/commands/monitor/).
Please note that:
- You can only send "QUIT" and "RESET" command while the connection is in monitor mode.
- For this implementation it is assumed that there will be limited number of connections that are in monitor mode - i.e. we are monitoring many connections into very few connections.
- The implementation ensure to work asynchronously and to verify that the connection is alive until the last message is sent it "borrow" the connection until the message is sent over to the socket.
- A later PR …
> Monitor command

- src/server/main_service.cc
This would address two issues:
- For some reason the documentation for the monitor command do say that we need to return OK after registering the connection for monitor
- The database index and square brackets around the connection string were missing.
> feat(server): monitor command should return OK on creation (#344)

- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/snapshot.cc
- src/server/snapshot.h
Migrating replication branch on main, part 3
Mixed implementation
* Split slice snapshot flow into start and optional stop
* Split rdb saver into start and optional stop
* Tidy code a bit
This two-phase snapshotting is needed by the stable state mvp
> refactor(server): Separate start & stop in rdb save

- src/server/main_service.cc
Signed-off-by: Super-long <0x4f4f4f4f@gmail.com>
This is a problem to be solved, but not necessarily the final version. I encountered the following problem when compiling dragonfly：
In the man documentation I found this description：
You can check the glibc version by running ldd --version, and on my machine I have the following output：
This is an issue that needs to be fixed in order to compile dragonfly more robustly.
Currently gettid appears in helio/util/uring/proactor_test.cc and src/server/main_service.cc, and in proactor_test.cc because of third_party/gperf/src/stacktrace_ instrument-inl.h(#include <gperftools/profiler.h>) defines #define gettid() syscall(__NR_gettid), so it compiles without error on my machine.
It looks like there are several fixes like this
1. Create a public file …
> fix: dragonfly compilation failure due to glibc version less than 2.30

- tests/README.md
- tests/dragonfly/conftest.py
- tests/dragonfly/connection_test.py
- tests/dragonfly/requirements.txt
feat(server): tests for pipeline and pubsub added
Add tests for:
- monitor command
- pipeline mode
- pub/sub
Please note that you would need to update the test env as the requirements have changed (pip install -r tests/dragonfly/requirement.txt)!
> feat(server): monitor command - cover by tests

- src/facade/facade.cc
Signed-off-by: Leonardo Mello [lsvmello@gmail.com](mailto:lsvmello@gmail.com)
This fixes https://github.com/dragonflydb/dragonfly/issues/390.
Created a new branch to join the commits as requested in https://github.com/dragonflydb/dragonfly/pull/438. I'm not confortable with `git rebase` yet, sorry.
Just as a recap: this sets the command name to lowercase on WrongNumArgsError and InvalidExpireTime functions.
> fix: "wrong number of arguments" must be in lower case

- src/server/zset_family.cc
- src/server/zset_family.h
- src/server/zset_family_test.cc
Closes #422
Since the new ZRange regroups all the other (now deprecated) ZRange functions, I did some refactoring to avoid duplicating code from these functions. This made it possible to have support for ZRevRangeByLex for free, since the visitor function already supported it.
Also spotted and corrected an error in ZRangeByLex when parsing the offset parameter.
There are some unrelated formatting changes that were added by clang-format.
> feat(server): Support for LIMIT and REV in ZRANGE #422

- src/server/engine_shard_set.cc
- src/server/list_family_test.cc
- src/server/transaction.cc
The bug was that if two push operations where queued together in the tx queue, and the first push awakes pending blpop, then the PollExecution function would continue with the second push before switching to blpop, which contradicts the spec.
> fix(list): Fixes blpop failure.

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- CONTRIBUTING.md
Signed-off-by: Leonardo Mello <lsvmello@gmail.com>
Closes https://github.com/dragonflydb/dragonfly/issues/200
- Added `clang-format` in `.pre-commit-config.yaml`
- Updated `CONTRIBUTING.md` with  `pre-commit` and `clang-format` installation script 
I ran `pre-commit run --all-files` but it change more than 100 files, so I didn't commit that change.
The `pre-commit` runs only on staged files, so the fixes can be done incrementally.
> ci: added clang pre-commit hook

- tests/README.md
- tests/integration/.dockerignore
- tests/integration/.patch_ioredis.sh
- tests/integration/.run_ioredis_valid_test.sh
- tests/integration/ioredis.Dockerfile
- tests/integration/run_ioredis_on_docker.sh
This commit do not include any changes in functionalities, but enable successfully running ioredis tests
1. Add scripts that allow running ioredis using docker image
2. some twinks to the docker file
3. update to the readme.
Please note that since ioredis has coverage for features that we are not supporting yet, using the script to run it on the container is the safest way to currently execute these tests right now. Also as we add more features, these scripts need to be updated accordingly.
> feat(tests): ioredis being able to successfully run tests, make it ready to be part of CI

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/server/dragonfly_test.cc
- src/server/main_service.cc
- src/server/test_utils.cc
- src/server/test_utils.h
- tests/dragonfly/connection_test.py
This remove the need to have "borrow tokens" to messages that are sending over pub channel.
It replaces it with a "simple share_ptr that would be cleaned once we are done with all the instances that are holding it.
Also added a system test that opens up few connections and subscribe to it and sending multiple messages to all subscribes.
This is done in hope that it would catch any memory issue that may happen in case there is an issue with this impl.
> feat(server): simplify handling of the pub message handling

- src/server/replica.cc
- src/server/replica.h
- src/server/server_family.cc
Migrating replication branch on main, part 5
The replica became an manageable 1k LOC mess 🤯 Time to fix technical debt 🔧 🔨 
Mixed implementation:
- Cleaned up and re-ordered header
- Added more comments everywhere
- Added helper functions for common scenarios
- Did some planning ahead for replication branch features (more code re-use!!)
> refactor(server): Refactor replica

- src/server/dragonfly_test.cc
- src/server/main_service.cc
- tests/dragonfly/server_family_test.py
- tests/integration/.patch_ioredis.sh
- tests/integration/.run_ioredis_valid_test.sh
- tests/integration/ioredis.Dockerfile
This commit is meant to bypass issue #457 
This is not a fix but a workaround. There is a new issue #467 that is meat for fixing the root cause.
This one is only temporary solution of the issue. What it does is making sure that if we have "eval" inside "Multi" it would return an error to the user. The reason that this do not let users running scripts inside Multi is that this would cause transaction schedule function to be called recursively. This in turn will break the precondition for the function that is not to allow calling it from within the same schedule context. 
This PR just block this from happening by failing the multi in case the user sends eval in the list of commands.
This also update the list of the commands that we are …
> fix(server): reject eval inside transaction multi blocks #457

- src/core/dense_set.cc
- src/core/dense_set.h
- src/server/set_family_test.cc
> bug(dense set): fix scan function to return only home bucket data

- README.md
- src/server/common.cc
- src/server/dfly_main.cc
- src/server/main_service.cc
Signed-off-by: Leonardo Mello <lsvmello@gmail.com>
Closes: https://github.com/dragonflydb/dragonfly/issues/302
I also tried to improve the minimum memory necessary message with the actual value so the user doesn't have to calculate based on the pool size (as a user I didn't know how to get that value 🫠).
As always, if you find any improvements just say so and I'll be glad to do it.
> fix: maxmemory flag support human-readable format

- src/server/string_family.cc
- src/server/string_family.h
- src/server/string_family_test.cc
This PR solves two problems.
1. implements KEEPTTL.
2. fixed the problem that StringFamily is not recognized when there is a conflict between options.
Two changes.
1. change SetParams.how/keep_expire to SetParams.flags.
2. Added conflict recognition between different options in StringFamily::Set.
Added two new tests.
1. KEEPTTL function test.
2. Conflict detection between different options in SetCommand.
The PR for the KEEPTTL option implementation in Redis is here: https://github.com/redis/redis/pull/6679/files
The part of Setcommand in redis that detects conflicts is at: https://github.com/redis/redis/blob/unstable/src/t_string.c#L201
PS：There is an incompatibility between the current implementation and redis.
1. set key value EX 100 EX 200 in df fails
2. redis executes set key value EX …
> feat(server): add support for KEEPTTL options with SET command #389

- src/core/dense_set.cc
This is a simple fix for removing a warning during compilation.
> fix: DCHECK_NOTNULL gets WARNING when return value is not used.

- tests/dragonfly/replication_test.py
The test is marked as skipped so that it would not run. 
We would be able to monitor that it is skipped, and when this is working, we can enable it again
Note that if you like to run this test you need to remove (locally) "pytest.mark.skip" for this test.
This would allow for tests to pass successfully for now.
> fix(test): skip pytest test_simple_full_sync_mutli_crash due to crash

- src/server/generic_family.cc
- src/server/hset_family.cc
- src/server/set_family.cc
- src/server/zset_family.cc
- tests/dragonfly/server_family_test.py
fixes issue #503 
The scan commands - scan, hscan, zscan, sscan all should return bulk string and not a "regular string" for the cursor value.
This issue was found as a result of running a java client ([redisson source code](https://github.com/redisson/redisson), that expecting to have the correct data type for this case.
> fix(server): all scan commands needs to return cursor as bulk string #503

- src/server/bitops_family.cc
- src/server/generic_family.cc
- src/server/rdb_load.cc
- src/server/replica.cc
- src/server/server_family.cc
> fix: clang warnings.

- src/server/common.cc
- src/server/common.h
- src/server/debugcmd.cc
- src/server/dflycmd.cc
- src/server/rdb_load.cc
- src/server/rdb_load.h
- src/server/server_family.cc
- src/server/server_family.h
- tests/dragonfly/replication_test.py
Un-invent re-invented wheels 😄 
Now that I introduced some more abstractions in my last PRs, we can use them in other places as well
> fix(server): Increase common abstraction usage

- src/server/rdb_save.cc
- src/server/replica.cc
- src/server/server_family.cc
- tests/README.md
- tests/dragonfly/__init__.py
- tests/dragonfly/conftest.py
- tests/dragonfly/replication_test.py
Fixes bug in replica.cc
Add option to run instances inside gdb
> fix(server): Fix replication bug, add gdb opt to pytest

- docs/build-from-source.md
- src/redis/redis_aux.c
- src/redis/redis_aux.h
- src/server/CMakeLists.txt
- src/server/generic_family.cc
- src/server/rdb_extensions.h
- src/server/rdb_load.cc
- src/server/rdb_load.h
- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/snapshot.cc
- src/server/snapshot.h
> feat(rdb save): add blob compression on snapshot

- src/server/generic_family.cc
- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/snapshot.cc
> feat(rdb save): serializer flush to sink only on flush call

- .github/workflows/ci.yml
- .github/workflows/regression-tests.yml
- src/core/compact_object_test.cc
- src/redis/zmalloc.h
- src/redis/zmalloc_mi.c
- src/server/CMakeLists.txt
- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
This PR is a merge-able version for the high level flow of active deframation.
This contain:
1. mi malloc support for a function that identify that underutilised pages based on memory addresses.
2. Tests from dragonfly side for this.
3. New defrag task in engine shard to run based on current memory usage and trigger the defrag action.
This do not contain:
1. Actual "low level" implementation for the defrag operation that would later add to compact object.
2. Unit test that would verify that the task really executed the defrag operation.
> feat(server): active memory fragmentation - high level flow

- src/core/compact_object.cc
- src/core/compact_object.h
- src/core/compact_object_test.cc
- src/server/dfly_main.cc
- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
- src/server/test_utils.cc
- src/server/test_utils.h
fixes #448 
feat(server): active memory defrag task #448
This PR is a complementary PR for the high level implementation of the defrag task - [PR 509](https://github.com/dragonflydb/dragonfly/pull/509).
In this PR we are covering the low level part that do the actual defragmation operation.
This can close issue #448.
Please note that we are disabling small string in this PR!.
Also note that we are changing mi_malloc memory decommit policy to wait for 0 ms from the default value.
Right now the flag that control the actual execution of the shard scan - "mem_defrag_threshold" is set to 1, this means that the task will do actual work only if we are at memory limits. To make it more reasonable we should change this to 0.05 or run with …
> feat(server): memory defrag support - unit tests added to verify #448

- src/core/compact_object.cc
- src/core/small_string.cc
- src/core/small_string.h
> feat: add defrag support for small strings

- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
- src/server/server_family.cc
Add metrics for the memory defragmentation.
This see this run the command "info stats"
Two new entries:
defrag_attempt_total - the total number of times that the stasks (for all shards) checked memory for possible defragmentation
defrag_realloc_total - the total number of pointers (from all shards) that were moved dues defragmentation
> feat(server): adding matrices for memory defrag

- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
- src/server/server_family.cc
Another defrag counter - this one count the number of times that we are attempting the defrag operation.
The flag "defrag_attempt_total" will count the number of times that we access the memory to try and check if this memory location is underutilised. 
The new flag "defrag_task_invocation_total" will count the number of time that we call the function that do the memory scan (i,e we detect possible memory underutilised).
> feat(server): defrag memory counter for total memory access

- contrib/charts/dragonfly/templates/deployment.yaml
- contrib/charts/dragonfly/templates/statefulset.yaml
- contrib/charts/dragonfly/values.yaml
- tools/docker/Dockerfile.alpine-prod
- tools/docker/Dockerfile.ubuntu-prod
- tools/docker/healthcheck.sh
This change will add a proper healthcheck to the container. Similar to `redis-cli ping`, just without `redis-cli`.
At the same time, we'll start utilising the new healthcheck in the helm chart. Sample container available at `ghcr.io/tamcore/dragonfly:v0.12.0` :)
> feat: add healtcheck for container

- src/core/CMakeLists.txt
- src/core/compact_object.cc
- src/core/compact_object.h
- src/core/compact_object_test.cc
- src/core/json_object.cc
- src/core/json_object.h
- src/server/common.cc
Adding support for JSON type.
This makes that JSON one of the types that we are saving in its native format and can accessing keys based on this type.
This is the first step for the completion of the JSON.SET command in the sense that we are not yet using this type for any of the JSON family commands.
Once this PR is completed we can go ahead and start using this type for the JSON commands.
Note that:
1. We should switch to mimalloc based allocator, but this is not working right now due to issue with the JSON code we're using (open issue for this and waiting for it to resolved).
2. You should use the function JsonFromString to correctly create a JSON object that can be saved to the store.
3. Later it would be possible to access and change the …
> feat(server): json set type support

- src/facade/dragonfly_connection.cc
- src/server/debugcmd.cc
- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/generic_family_test.cc
- src/server/io_mgr.cc
- src/server/list_family_test.cc
- src/server/main_service.cc
- src/server/rdb_test.cc
- src/server/replica.cc
- src/server/server_family.cc
- src/server/server_family.h
- src/server/snapshot.cc
- src/server/string_family_test.cc
- src/server/test_utils.cc
Switch to using fibers_ext::Fiber.
> chore: Update helio dependency

- README.md
+ removed duplicated explanation
Signed-off-by: Tomato6966
> added example of start script

- src/server/generic_family.cc
- src/server/json_family.cc
- src/server/json_family_test.cc
- tests/dragonfly/json_test.py
- tools/json_benchmark.py
Fixes issue #238 
This PR add the use of the new JSON type for the JSON commands. 
This would ensure that when the command JSON.SET is processed, it would set the type to be OBJ_JSON as well as when the need to update a value, or get the value is called with any of the JSON commands, it would search with OBJ_JSON.
This would also reduce the need to call to the paring from string into JSON.
Note that we are still using the standard allocator because jsoncons still did not fix the issue related to using custom allocator.
> feat(server): JSON family using JSON type

- src/server/generic_family.cc
- src/server/rdb_load.cc
- src/server/rdb_load.h
Specifically, pass OpaqueObj to parsing routines so that they could fill it instead of creating it. In addition, this change improves the interface between generic_family and RdbLoad code: it removes reliance on the internal Item class.
> chore: Refactor RdbLoad

- src/core/mpsc_intrusive_queue.h
- src/server/rdb_load.cc
- src/server/rdb_load.h
> chore: Adding a mpsc intrusive queue based on Vyukov's design

- .github/workflows/ci.yml
- src/core/CMakeLists.txt
- src/core/compact_object.cc
- src/core/compact_object.h
- src/core/compact_object_test.cc
- src/core/detail/bitpacking.cc
- src/core/detail/bitpacking.h
- src/server/generic_family_test.cc
My benchmark shows 3.5 improvement when packing a large string.
> feat: introduce simd algorithm for bitpacking

- src/core/compact_object.cc
- src/core/compact_object_test.cc
- src/core/detail/bitpacking.cc
- src/core/detail/bitpacking.h
> chore: Improve the implementation of simd based packing

- contrib/charts/dragonfly/values.yaml
Zero clue why it worked before. Had installed it multiple times.. Fixes #588
```
$ helm install --create-namespace --namespace dragonfly dragonfly .
NAME: dragonfly
LAST DEPLOYED: Wed Dec 21 20:22:35 2022
NAMESPACE: dragonfly
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
export POD_NAME=$(kubectl get pods --namespace dragonfly -l "app.kubernetes.io/name=dragonfly,app.kubernetes.io/instance=dragonfly" -o jsonpath="{.items[0].metadata.name}")
export CONTAINER_PORT=$(kubectl get pod --namespace dragonfly $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
echo "You can use redis-cli to connect against localhost:6379"
kubectl --namespace dragonfly port-forward $POD_NAME 6379:$CONTAINER_PORT
```
But is definitely at …
> fix(chart): probe indentation

- src/core/compact_object.h
- src/core/generate_bin_sizes.py
- src/server/common.cc
- src/server/common.h
- src/server/db_slice.cc
- src/server/server_family.cc
- src/server/string_family.cc
- src/server/table.cc
- src/server/table.h
- src/server/tiered_storage.cc
- src/server/tiered_storage.h
1. Allow offloading blobs larger than 2KB.
2. Totally redesign the offloading algorithm for blobs smaller than 2KB.
3. Fix bugs around IO request cancelations.
> feat(server): Redesign and simplify tiered storage module.

- src/server/CMakeLists.txt
- src/server/dfly_main.cc
Fixes issue #558 
A task that monitors the version from a remote endpoint.
This would print a message in case we have mismatch between the local version and the remote version.
In case we are running in dev build, this task will not run.
> feat(server): adding version monitoring task

- src/server/dragonfly_test.cc
fix issue #571 
There was an issue with the defrag unit test that when run by its own it would not start the task that collect the use memory stats from all shards. This would result in the task for defrag not running because the use memory == 0.
On top of it, there was an issue that since this started with empty memory the defrag task was not ran by other tests, and so the counter for running the defrag test was not activated.
Note that since we're going to rewrite the logic for defrag, this is going to change soon again, but for now, it required that this test will work correctly.
To ensure that the test is ran with less memory the flag that control the memory threshold is set as well.
The test also set enough memory so that we would not …
> fix(server): defrag unit test fix

- tools/defrag_mem_test.py
This contain no real code changes:
1. Upgrade version for helio with updated version for mimalloc from v2.0.5 to v2.0.7
2. Change the default for the defrag test util to make it easier to reproduce the use case.
> chore(server): upgrade mimalloc for v2.0.7

- .github/workflows/docker-release.yml
- .github/workflows/docker-weekly.yml
- .github/workflows/reusable-container-workflow.yaml
- Makefile
- tools/docker/Dockerfile.alpine-dev
- tools/docker/Dockerfile.alpine-prod.wip
- tools/docker/Dockerfile.ubuntu-dev
- tools/docker/Dockerfile.ubuntu-prod
- tools/release.sh
Closes #308. Exerpt from commit message:
- make use of docker buildx caching when possible (helpful with local docker builds)
- introduce a reusable container workflow which is triggered by docker-release and docker-weekly workflows
- added an alpine-dev Dockerfile
- split release.sh contents into different Makefile targets
- make use of job matrix to build alpine + ubuntu in parallel
- make alpine build optional by checking for Dockerfile presence
- as the pre-built release binaries don't work with alpine, because of glibc <-> musl incompatibilities
Tagged images will look like
- From pre-existing docker-release workflow (which will not output an alpine image, as Dockerfile.alpine-prod has been renamed)
- For release v0.12.2
- <img width="375" alt="docker-release yaml v0 12 2 …
> feat: build and publish weekly alpha/development container image

- tools/cache_logs_player.py
- tools/requirements.txt
> feat(tools):Cache logs player

- docs/quick-start/README.md
I had issues when running the command on my m2 macbook air. [It turns out][1] that apparently docker desktop on macOS doesn't really support the host option.
Additionally, it looks like I had to explicitly pass the port mapping options for the ports to be actually mapped.
There might be a better and more efficient solution, but this is what I came up with and it finally worked.
[1]:https://github.com/docker/for-mac/issues/1031
> docs(quickstart): Clarify docker command for macOS

- .ct.yaml
- .github/workflows/ci.yml
- Manually setting `--set=image.repository=ghcr.io/${{ github.repository }}` for this CI job, so the image is pulled from Github instead
- If the workflow is manually triggered (`github.event_name == 'workflow_dispatch'`), it will not check for changes made to the chart and simply force a run
- Fail with invalid YAML
- https://github.com/tamcore/dragonfly/actions/runs/3801483178/jobs/6465998892
- Fail with broken PodSpec
- https://github.com/tamcore/dragonfly/actions/runs/3801584857/jobs/6466201901
- Pass, as PR doesn't change chart
- https://github.com/tamcore/dragonfly/actions/runs/3801652981/jobs/6466348221
- Pass, as PR changes chart but does not break it
- https://github.com/tamcore/dragonfly/actions/runs/3801698388/jobs/6466447398
> feat(ci test): add testing for helm chart

- src/core/compact_object_test.cc
- src/redis/zmalloc.h
- src/redis/zmalloc_mi.c
- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
This would switch to per shard memory stats to trigger the defrag scan.
The main change is that now, if a given shard is not underutilised, it would not be affected by the overall memory usage and so only shard that can perform the defrag would scan the to find locations that are underutilised.
This was tested with the utility we have to ensure that we did not have any degradation, and to ensure that it is starting and stopping as expected and term of finding and "fixing" the defragmentation.
> feat(server): using memory defrag with per shard mem info

- src/server/dfly_main.cc
- tools/docker/Dockerfile.ubuntu-prod
1. Align checked version with the format provided by the endpoint
2. Improve error reporting as well as install ca certificates in the docker file.
> fix(server): version check bugs

- src/server/server_family.cc
Signed-off-by: ashotland <ashotland@gmail.com>
Fixes #637  
Added:
- version
- hits/misses
- rss memory
> feat(server): Add metrics

- contrib/charts/dragonfly/README.md
- contrib/charts/dragonfly/templates/_pod.tpl
- contrib/charts/dragonfly/templates/certificate.yaml
- contrib/charts/dragonfly/values.yaml
With this it'll be possible, to just trigger certificate creation through cert-manager. Granted, deploying the `Certificate` object was already pretty easy through the `extraObjects` object, but this makes it even easier :)
Comes in handy, when the user already operates a his own CA and has a `(Cluster)Issuer` ready for it.
> feat(chart): add feature to generate/request TLS certificate through cert-manager

- tools/docker/Dockerfile.alpine-dev
- tools/docker/Dockerfile.alpine-prod.wip
- tools/docker/healthcheck.sh
While implementing the healthcheck I forgot to cover TLS, causing the healthcheck throw a bunch of handshake errors in the application log. This change takes care of that.
Now it tries to rely on OpenSSL to establish the connection.
> feat(container): make healthcheck tls compatible

- tools/cache_testing.py
- tools/requirements.txt
Signed-off-by: Ubuntu <ubuntu@ip-172-31-12-15.us-west-2.compute.internal>
Adds a cache testing tool that produces values according to a Zipfian distribution to test cache, as per issue #253.
> feat(tools): Add Zipfian cache testing tool

- src/core/interpreter.cc
- src/server/dragonfly_test.cc
This happens when the last argument is a number because SNPrintF makes sure to write \0 even though we did not account of that when passing capacity. Since we allocate more than we use, the only thing we need to do is to pass larger capacity.
> fix(lua): fix a bug that truncates the last lua argument.

- src/server/rdb_save.cc
- src/server/snapshot.cc
- src/server/snapshot.h
Fixed stats accounting. Now loop_serialized + side_saved should correspond to number of saved items in a shard.
> chore(server): snapshot stats fix

- src/server/journal/executor.cc
- src/server/replica.cc
- src/server/replica.h
@dranikpg 
I have some problem with the cancellation in this which I will continue investigate.
> feat(replica): support multi shard commands new flow

- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/snapshot.cc
- src/server/snapshot.h
The bug was here:
```
VLOG(2) << "FlushDefaultBuffer " << bytes.size() << " bytes";
PushBytesToChannel(current_db_, bytes);
default_serializer_->Clear();
```
We might block on the channel when pushing. If the snapshot continues serializing, it will write to the default serializer. And once the channel unblocked, the clear will remove everything - not only the part it has written, but also the new one. 
The solution would be to make Clear consume only a fixed part - but instead I decided to revert some changes I made previously as well because of the changes in async streamer.
I initially abstracted flushing in snapshot to pushing just bytes taken from the rdb serializer. But since in the async streamer we're gonna make the streamer base to act as a sink as well, we can just use …
> fix(server): Fix bug in flushing in snapshot

- src/server/db_slice.cc
- src/server/journal/executor.cc
- src/server/journal/executor.h
Looks like last bug left for new pytest to pass🥳 
If you try accessing a new database in stable state, it will fail because it doesn't exist on replica. Once the executor sees a new db for the first time, it creates it.
This looks like a very raw solution, probably we should have some execution flag inside the tx framework that will check for this on replica? But I hope this is enough for now
> fix(server): Fix db initialization in stable state

- src/server/journal/executor.cc
- src/server/journal/executor.h
- src/server/replica.cc
One more issue: Replica is not flushing its DB before retrying full sync.
Is this placement correct? Now the replica flushes after REPLICAOF and before each full sync.
> fix(server): Flush dbs before full sync

- tools/release.sh
This commit include:
- update helio version that include a fix in the code to ensure that we will not have link issue (not using getaddrinfo_a)
- the build script that we are using as part of the releases will ensure that the code is able to link outside of the build machine (ubuntu 20.04)
> fix(build): verify build image for releases

- src/server/main_service.cc
When cancelling the replica while it was about to execute `FlushAll()`, the instance would crash.
As far as I understand, when stopping the instance, all transactions are stopped when destroying the connection that spawned them. But for the journal executor we don't have one.
It would crash because the varz parts are finalized before the replica is, so I just swapped them. It seems to be working now. Not sure if this order breaks anything?
> fix(server): Fix shutdown order

- src/redis/rdb.h
- src/server/error.h
- src/server/generic_family.cc
- src/server/rdb_extensions.h
- src/server/rdb_load.cc
- src/server/rdb_load.h
- src/server/rdb_save.cc
- src/server/rdb_save.h
- tests/dragonfly/utility.py
Fixes #587 
- Support json inside rdb saver and loader
- Add json values & commands to pytest data generator
> feat(server): Json rdb support

- src/server/blocking_controller.cc
- src/server/blocking_controller.h
- src/server/blocking_controller_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
- src/server/list_family.cc
- src/server/list_family_test.cc
- src/server/transaction.cc
- src/server/transaction.h
The bug is when an expired transaction stays in the watched queue.
Now we remove the transaction from the watched queues in a consistent manner based on the keys it was assigned to watch.
> fix(server): Fix a bug with brpoplpush

- src/server/dflycmd.cc
- tests/dragonfly/replication_test.py
Previously replication didn't work with a single threaded master
> fix(server): Fix replication on a single thread

- tests/dragonfly/replication_test.py
- tests/dragonfly/utility.py
> test(replication_test) : add replica flushall test

- src/server/rdb_test.cc
> test(rdb): Add json dump & restore test

- src/server/CMakeLists.txt
- src/server/dflycmd.cc
- src/server/io_utils.cc
- src/server/io_utils.h
- src/server/journal/serializer.cc
- src/server/journal/serializer.h
- src/server/journal_test.cc
- src/server/rdb_save.cc
- src/server/rdb_save.h
This PR introduces:
- BufferedStreamerBase for managing wakeups/blocks to allow creating double-buffered streamers easily
- JournalStreamer that uses BufferedStreamerBase
Why BufferedStreamerBase separately? In the future, We might want to replace the snapshot channel with it in case of single producer - single consumer to remove allocations, synchronization, fragmentation, etc...
> feat(server): Buffered streamer + use on stable state

- src/server/test_utils.cc
- src/server/test_utils.h
- src/server/tiered_storage_test.cc
> fix(test): reduce flakiness of tiered_storage_test

- src/facade/dragonfly_connection.cc
> fix(server): Fix connection bug

- src/server/common.cc
- src/server/set_family.cc
- src/server/transaction.cc
- src/server/transaction.h
> feat(set family): rewrite set store commands to journal

- .github/workflows/release.yml
- tools/packaging/generate_changelog.sh
This complement PR [689](https://github.com/dragonflydb/dragonfly/commit/57e3ec9a81f72d649997f54646d786592aec5166).
And should complete issue #249 
It would generate along with the normal binaries, an installation package for Debian, that can be used for installation on Debian based distributions. 
There is a change in the package generation as well:
In order to ensure that we can generate the change log file, we are trying to fetch them if they do not exists. 
The reason that this is required is to make sure that we are creating unique deb package with different version number for each of these builds.
> feat(actions): add support for debian packaging

- src/server/bitops_family.cc
- src/server/common.cc
- src/server/common.h
- src/server/generic_family.cc
- src/server/set_family.cc
- src/server/transaction.cc
- src/server/transaction.h
> (generic family): journal support rename command

- tools/packaging/debian/control
There was an issue with the dependency on systemctl. This would cause serious issue when systemd is installed. Remove it then verify that the resulting package install successfully on Ubuntu 20/22 and Debian 11
> feat(build): debian package building fix dependency bug

- src/server/db_slice.cc
- src/server/string_family.cc
This fix issue #705 
GETEX command with PERSIST will result in integer overflow since in this case, the expiration time cannot be calculated.
The fix is, in case we have persist enable, don't try to calculate the persist time, just set as persist value.
> fix(server): fix getex command with persist can get time overflow

- README.md
- src/facade/dragonfly_connection.cc
- src/server/dfly_main.cc
Fix issue #668 
This will:
* change the flag http_admin_console --> primary_port_http_enabled.
* Add flag admin_port that when set, enable connecting with HTTP/RESP to this port.
* Add flag admin_bind that when set (together with admin_port),  enable connection with HTTP/RESP on this address/port.
* By default these two new flags are disabled.
* Note that if the connection is from admin port while admin port is enabled, it will allow HTTP connection to this port/address only. Trying to connect to the console from the "normal" port will not for HTTP connection
> feat(server): admin port and interface

- src/server/dfly_main.cc
- src/server/server_family.cc
- src/server/transaction.cc
- src/server/zset_family.cc
- src/server/zset_family_test.cc
> fix(server): zunion now supports variadic arguments

- src/server/dragonfly_test.cc
- src/server/transaction.cc
> fix(server): Fix multi tx cleanup

- .github/workflows/release.yml
- tools/packaging/generate_debian_package.sh
This would add support for building the debian package for ARM64 based arch.
* The git action file will run the script that generate a package for ARM as well as for x86.
* The build script is now accepting new arg of the arch type.
* The build of the ARM package can only be run inside environment that is itself ARM64.
> feat(action): build debian package for arm64 arch

- src/server/string_family.cc
- src/server/string_family.h
- src/server/string_family_test.cc
> feat(string family): implement `cl.throttle`

- src/server/string_family.cc
on my machine it gave me:
```
inlined from ‘void dfly::SetCmd::RecordJournal(const dfly::SetCmd::SetParams&, std::string_view, std::string_view)’ at /home/roman/projects/dragonfly/src/server/string_family.cc:494:14: /home/roman/projects/dragonfly/build-opt/_deps/abseil_cpp-src/absl/container/inlined_vector.h:627:29: warning: ‘cmds’ may be used uninitialized [-Wmaybe-uninitialized]
```
> fix: a small warning fix.

- .github/workflows/ci.yml
- src/server/dragonfly_test.cc
- src/server/main_service.cc
- src/server/transaction.cc
The scenario is described in a unit test that reproduces the issue with high chance. Also added dragonfly_test in repeat=100 mode to CI.
> fix(lua): Fix a deadlock happenning when calling a lua script

- tests/dragonfly/sentinel_test.py
> fix(sentinel_test):Remove return type which breaks regression tests

- src/server/list_family.cc
- src/server/transaction.cc
- tests/dragonfly/replication_test.py
> feat(list family): support blocking command for replication

- src/server/dragonfly_test.cc
- src/server/main_service.cc
> fix(server): Reset interpreter stack on errors

- tests/dragonfly/replication_test.py
This test fails from time to time. It looks like we have some kind of conflict between the heartbeat fiber and other stuff on replication. Lets disable it for now to reduce the likelihood of tests failing until its resolved
> Exclude single threaded test now that expiry is tested

- tests/dragonfly/sentinel_test.py
Successful CI run:
https://github.com/dragonflydb/dragonfly/actions/runs/4095713187/jobs/7062824086
> fix(regression-tests): sentinel_test.py: Ditch docker whcih is complex on CI in favour of local redis binary

- src/core/interpreter.cc
- src/server/dflycmd.cc
- src/server/main_service.cc
- src/server/script_mgr.cc
- src/server/script_mgr.h
- src/server/server_family.cc
- src/server/server_state.h
Also provide new subcommands "script list" and "script latency" Fixes #754
> feat(server): add latency statistics for lua script calls

- src/facade/dragonfly_connection.cc
- src/facade/facade.cc
- src/facade/facade_types.h
- src/server/main_service.cc
- src/server/server_family.cc
In addition:
1. improve logging of received commands
2. provide stable ordering of error stats and commandstats
> feat(server): add total_connections_received statistics

- src/core/interpreter.cc
- src/core/interpreter.h
- src/server/common.cc
- src/server/main_service.cc
- src/server/rdb_load.cc
- src/server/script_mgr.cc
- src/server/server_state.h
> feat(server): Pool lua interpreters

- src/core/segment_allocator.cc
- src/core/segment_allocator.h
- src/server/memory_cmd.cc
- src/server/memory_cmd.h
1. Remove dangerous check-fail in SegmentAllocator.
2. Allow printing heap stats for both backing and data heaps.
> feat(server): Extend malloc-stats command functionality.

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/facade.cc
- src/facade/facade_types.h
- src/server/CMakeLists.txt
- src/server/common.cc
- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/main_service.cc
- src/server/server_family.cc
- src/server/server_state.cc
- src/server/server_state.h
1. now pipeline_cache_capacity tracks how many bytes are allocated via free_req_pool_ cache. it's been shown now via "pipeline_cache_bytes" stat in "info memory" command.
2. a small refactoring of server_state code into server_code.cc
> feat(server): track pipeline requests cache capacity

- src/facade/CMakeLists.txt
- src/facade/reply_builder.cc
- src/facade/reply_builder.h
- src/facade/reply_builder_test.cc
Fixes issue #180 
This do unit test converge for reply_builder RESP.
* Verify that the resulting output bytes are in correct format based on the protocol spec.
* Verify that the messages can be successfully parsed by the REDIS parser.
> test(server): adding unit tests for reply builder

- src/server/main_service.cc
- tests/dragonfly/connection_test.py
fixes issue #756 
* Move the report of the command so that we will see it even if there are issues with the command execution.
* Add test to reproduce the issue as part of the integration tests.
> fix(server): monitor lua at script execution

- src/server/debugcmd.cc
- src/server/replica.cc
- src/server/replica.h
- src/server/server_family.cc
- src/server/server_family.h
- tests/dragonfly/replication_test.py
1. Add DEBUG REPLICA OFFSET command which will return the sync id and array offsets for each flow
2. fix bug in Replica::TransactionReader::NextTxData
> feat(replica): add debug command - replica offset

- src/server/transaction.cc
- src/server/transaction.h
InitByArgs is 200+ LOC and I need to extend it to support different multi-transaction modes, so I decided to refactor it a little, else it'll become an unmanageable mess 
I've split it into multiple commits, each of them encompasses one or two changes
> Refactor initialization phase of transaction

- src/server/engine_shard_set.cc
- src/server/journal/streamer.h
- tests/dragonfly/replication_test.py
1. Fix replica offset
2. Remove old tx offset
> fix(server): Fix bugs

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/server/main_service.cc
> feat(facade): Limit request cache using runtime flag

- src/server/debugcmd.cc
- src/server/server_family.cc
Introduce a new flag `df_snapshot_format` that controls the default behavior. The flag itself is defaulted to save snapshots in a new Dragonfly specific format.
BREAKING CHANGE: before that Dragonfly saved snapshots in rdb format by default. Now the flag controls which format is chosen when issuing SAVE/BGSAVE commands. In addition, "SAVE DF", "SAVE RDB" can be used to save using dragonfly/redis formats accordingly.
> feat(server): save dragonfly snapshot in a new format by default

- tests/dragonfly/snapshot_test.py
> fix(pytest): fix periodic test

- src/server/conn_context.cc
- src/server/conn_context.h
This is useful when DF is used to store large blobs and MULTI is used.
> chore(server): reduce number of allocations with multi-exec commands

- .github/workflows/regression-tests.yml
Run every 3 hours
Add -s to pytest invocation
> chore(regressions-tests): Update regression-tests.yml

- src/core/dense_set.cc
- src/core/dense_set.h
- src/core/string_map.cc
- src/core/string_map_test.cc
- src/core/string_set.cc
Now string_map respects the optional ttl argument that accepts ttl time in seconds. Upon traversing and accessing expirerd elements they will be transparently removed and deleted from the map.
> feat(core): Add Ttl semantics to string_map

- .github/workflows/ci.yml
- src/server/common.h
- src/server/db_slice.cc
- src/server/main_service.cc
- src/server/multi_test.cc
- src/server/transaction.cc
- src/server/transaction.h
This commit adds the notion of multi transaction modes that allow controlling the execution and
locking behaviour of multi transactions.
In general, there are four modes:
- GLOBAL: all commands run within a global transaction. There is no need for recording locks. Lua scripts can theoretically run with undeclared keys.
- LOCK_AHEAD: the transaction locks all keys ahead likewise to a regular transaction and schedules itself.
- LOCK_INCREMENTAL: the transaction determines what shards it has keys in and schedules itself on those shards, but locks only when accessing a new key. This allows other transactions to run ooo alonside with a big multi-transaction that accesses a contended key only at its very end.
- NON_ATOMIC: all commands run separately, no atomicity is provided, likewise to a …
> Basic multi modes for MULTI/EXEC

- src/server/zset_family.cc
- src/server/zset_family_test.cc
The commands should allow count to be optional and default to `1` as per the official redis command documentation ([ZPOPMIN](https://redis.io/commands/zpopmin/), [ZPOPMAX](https://redis.io/commands/zpopmax/)).
Will fix: #801
> fix(zset): Make count optional for ZPOP{MIN,MAX}

- src/server/debugcmd.cc
- src/server/debugcmd.h
Specifically, provide a total length over all shards of pending txs. Also, provide number of "free" transactions pending in the queue - those that could progress immediately but do not because they are not first in the queue.
> feat(server): add debug information about running transactions

- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/main_service.cc
- src/server/main_service.h
- src/server/multi_test.cc
- src/server/transaction.cc
- src/server/transaction.h
- add multi modes to eval
- add non atomic modes
- allow undeclared kets with global & non atomic modes
> EVAL multi modes + non atomic modes

- src/server/db_slice.cc
- src/server/db_slice.h
- src/server/snapshot.cc
When traversing over buckets for snapshoting we deside to serialize bucket if its version is lower than snapshot version,
after we serialize the bucket we update the snapshot version.
When we have 2 snapshots S1 and S2 running at the same time with versions v1 , v2 where v1 < v2 and
S2 reaches bucket B before S1, then S1 will skip serializing the bucket .
My fix:
In BucketSaveCb called from the snapshot main loop, we first trigger calls of OnDbChange for all snapshots with version less than the current flow version. This way we make sure that the snapshot with higher version will not overide the bucket version before the snapshot with lower version will serialize it
Fixes #823
> bug(snapshot): Fix unwriten entries in multiple snapshotting Fixes   #823

- docs/build-from-source.md
> docs: Add how to build dragonfly on Fedora

- src/core/CMakeLists.txt
- src/core/simple_lru_counter.cc
- src/core/simple_lru_counter.h
- src/core/simple_lru_counter_test.cc
Part of the heavy keeper algo, required for #257.
Also see #446 for the initial (abandoned) PR.
> feat(server): add lru data structure

- src/server/common.h
- src/server/hset_family.cc
- src/server/hset_family.h
- src/server/hset_family_test.cc
- src/server/set_family.cc
The format as follows: `HSETEX key seconds field value [field value ...]` This allows adding hset members with expiration time in seconds.
Both `SADDEX` and HSETEX` do not support currently RDB serialization and replication.
This will be added in subsequent PRs.
Fixes #687
> feat(server): Add HSETEX command

- src/server/main_service.cc
- src/server/multi_test.cc
It crashed on the assert in PostItem, its redundant as all users of SendSimpleStrArr call PostItem themselves afterwards
> fix(server): Fix lua reply builder

- src/server/transaction.cc
Currently we re-use transactions in the non-atomic multi mode and the callback in ExecuteAsync looks like the following:
```python
mask = GetMask(shard)
seq_after = Add(seqlock, 0, release)
if seq_after == seq_old and mask & ARMED: Poll()
```
However it might happen that the transaction is already being re-used when the callback is run, so we should avoid accessing the mask and just quietly drop the callback.
I suggest accessing the mask only when checking the seqlock, which means that the wait barrier didn't finish and all state remained untouched.
```python
seq_after = Load(seqlock, acquire)
if seq_after == seq_old and GetMask(shard) & ARMED: Poll()
```
I must admit I don't understand your "trick". 
> we use fetch_add with release trick to make sure that local_mask is loaded before we …
> fix(server): Reorder ExecuteAsync callback seqlock check

- src/server/json_family.cc
- src/server/json_family_test.cc
The `JSON.ARRTRIM` command is now aligned with `ElastiCache` flavor.
Fixes #844
> fix(server): fix JSON.ARRTRIM implementation (#844)

- src/server/journal/serializer.cc
- src/server/journal/serializer.h
- src/server/rdb_load.cc
- src/server/rdb_load.h
- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/snapshot.cc
- src/server/snapshot.h
1. Serializer encode db index of entries
2. Do not encode db index inside consume channel
3. Allow push serialized data to channel from main snapshot loop and from journal callback (push may preempt)
> bug(snapshot) : Do not preempt inside OnDbChange issue #829

- contrib/charts/dragonfly/ci/affinity-values.golden.yaml
- contrib/charts/dragonfly/ci/command_extraargs-values.golden.yaml
- contrib/charts/dragonfly/ci/extracontainer-string-values.golden.yaml
- contrib/charts/dragonfly/ci/extracontainer-tpl-values.golden.yaml
- contrib/charts/dragonfly/ci/extravolumes-values.golden.yaml
- contrib/charts/dragonfly/ci/initcontainer-string-values.golden.yaml
- contrib/charts/dragonfly/ci/initcontainer-tpl-values.golden.yaml
- contrib/charts/dragonfly/ci/passwordsecret-values.golden.yaml
- contrib/charts/dragonfly/ci/persistent-values.golden.yaml
- contrib/charts/dragonfly/ci/resources-values.golden.yaml
- contrib/charts/dragonfly/ci/securitycontext-values.golden.yaml
- contrib/charts/dragonfly/ci/tls-values.golden.yaml
- contrib/charts/dragonfly/ci/tolerations-values.golden.yaml
- contrib/charts/dragonfly/templates/certificate.yaml
- contrib/charts/dragonfly/templates/deployment.yaml
- contrib/charts/dragonfly/templates/metrics-service.yaml
- contrib/charts/dragonfly/templates/service.yaml
- contrib/charts/dragonfly/templates/serviceaccount.yaml
- contrib/charts/dragonfly/templates/statefulset.yaml
- contrib/charts/dragonfly/templates/tls-secret.yaml
Fixes https://github.com/dragonflydb/dragonfly/issues/874
This updates all the namespace fields in the Helm chart to use the `Release.Namespace` template variable. This is the recommended way to do it in Helm 3, and allows the chart to be installed in a namespace as set by the user, without having to modify the chart or use `--namespace` in `kubectl`.
This seems to be the [recommended approach in Helm](https://github.com/helm/helm/issues/5465).
> fix(charts): Use `Release.Namespace` everywhere

- contrib/charts/dragonfly/golden_test.go
While we have docs in `Contributing.md`, It seems better to
have that command emitted in the error message.  It is much 
more straightforward this way.
> test(helm): Add command to update golden files

- src/server/zset_family.cc
- src/server/zset_family.h
- src/server/zset_family_test.cc
I worked on it because it was missing for the redis compare library.
Fixes #838
> feat(zset_family): support zscan match and count optional params issue

- tests/dragonfly/redis_replicaiton_test.py
- tests/dragonfly/utility.py
> Add basic replicaiton from redis test

- src/server/replica.cc
If we call the function inside DCHECK it is not called when we build dragonfly opt
> bug(replica): call add entry outside DCHECK

- src/server/list_family.cc
because ArgSlice (absl::span) is not the owner memory when constructing with initializer list we must make sure that the span is passed directly to function.
i.e
arg = ArgSlice {"1"}
foo(arg) // arg is dangling pointer
we should use 
foo(ArgSlice {"1"})
> bug(list_family): fix BPopPusher command replication

- src/server/json_family.cc
- src/server/json_family_test.cc
> fix(server): fix JSON.MGET implementation (#849)

- .github/workflows/regression-tests.yml
Replication tests currently time out, its most likely because of the enormous amount of debug output
> fix(tests): Disable logging in replication tests

- .github/workflows/regression-tests.yml
- tests/dragonfly/__init__.py
- tests/dragonfly/replication_test.py
Add small delay before re-starting master
> fix(pytest): Add master restart delay

- src/server/transaction.h
> // store operations below can not be ordered above the fence
is not the same as the meaning of release (i.e. its the opposite)
> no reads or writes in the current thread can be reordered after this store
we need acquire, but actually also release to commit the results of the function that calls WaitForShardCallbacks
> fix(server): Change WaitForCallbacks mem order

- src/server/rdb_load.cc
- src/server/rdb_save.cc
- src/server/snapshot.cc
> fix: send a single RDB_OPCODE_FULLSYNC_END from a snapshot

- .github/workflows/ci.yml
- .github/workflows/docker-release.yml
- contrib/charts/dragonfly/.helmignore
- go.work
Golden files need to be updated as version is updated in the `Chart.yaml` file. This commit adds the step to update the golden files in the release pipeline.
To make that possible, The following additional changes are also required:
- `Go.Work`: This adds support [multi-module workspaces](https://go.dev/doc/tutorial/workspaces) as we will have the tests along with the operator in sub-folders. This is required to run go cmds from the root directory. (like running tests in this case).
- `.helmignore`: This updates the Helm chart to ignore the `/ci` folder during helm packaging as those are not required for users of the chart.
> chore(helm): Make release pipeline to update golden files

- src/server/bitops_family.cc
- src/server/bitops_family_test.cc
> feat(server): Implement BITPOS.

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/reply_builder.h
- src/server/conn_context.cc
- src/server/dragonfly_test.cc
- src/server/main_service.cc
- src/server/test_utils.cc
- src/server/test_utils.h
- tests/README.md
- tests/dragonfly/connection_test.py
> fix: Fix a corruption when connection writes interleaving messages

- .github/workflows/docker-release.yml
Adds a call in the release workflow to re-trigger Vercel Docs website deployment to re-build it to get the latest version number shown in the docs.
> feat(workflow): Add Vercel Docs Hook to release workflow

- src/server/main_service.cc
- src/server/multi_test.cc
- src/server/script_mgr.cc
- src/server/script_mgr.h
1. What format should pragmas use? Now I just parse the first line that goes
```
-- pragma: *pragmas*
```
2. I currently count settings from our base default, not from the configured ones. This means that script pragmas totally override everything, i.e. doing `-- pragma: ` will reset to default state, even when the default script config flag had some pragmas included
> feat(server): Pragmas from scripts

- src/server/blocking_controller_test.cc
- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
- src/server/main_service.cc
- src/server/server_state.cc
- src/server/server_state.h
This should reduce the access cost to thread_local objects.
> chore: change thread_local to  __thread when possible.

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/reply_builder.cc
- tests/README.md
- tests/dragonfly/connection_test.py
Previously we set batch mode when dispatch queue is not empty but dispatch queue could contain other async messages related to pubsub or monitor. Now we enable batching only if there are more pipeline commands in the queue. 
Fixes #935.
> fix: correctly set batching mode during pubsub

- .github/workflows/daily-builds.yml
Fixes #732 
This commit adds a scheduled job that runs 8 AM Israel time every day, with common build configuration flags so that we can be sure that building from source for known configurations is possible.
> feat(ci): Add daily builds BFS verification

- src/server/replica.cc
- tests/dragonfly/redis_replicaiton_test.py
We must flush all inside replication full sync because if we get disconnected from master we will go to full sync again
> fix(replication): redis replication flush all before full sync

- .github/workflows/daily-builds.yml
This commits fixes the flag to use the right format
for `x86-64`
> fix(ci): Use correct `x86-64` with builds

- src/server/blocking_controller.cc
- src/server/blocking_controller.h
- src/server/blocking_controller_test.cc
- src/server/engine_shard_set.cc
- src/server/list_family.cc
- src/server/list_family_test.cc
- src/server/transaction.cc
Part 2 of the fixes:
1. Added a list_family test that has not passed before that commit
2. Made sure that multiple waked brpop transaction would not
snatch items from one another.
3. Fixed watched-queues clean-up logic inside blocking_controller that caused deadlocks.
> improve consistency around brpop flow

- src/server/transaction.cc
- src/server/transaction.h
The deadlock happenned during the brpop flow where we access shard_data.local_data from both coordinator and shard threads. Originally, shard_data.local_data was not designed for concurrent access so I used ARMED bit to deduplicate callback runs for each shard. The problem is that with BRPOP it could happen, the ExecuteAsync would do "=| ARMED" and in parallel NotifySuspended would apply " |= AWAKED" in the shard thread, and both R/M/W operations would corrupt each other.
Therefore, I separated now completely shard-local local_data mask and is_armed boolean. Moreover, since now we use atomics for is_armed, I increased PerShardData size to 64 bytes to avoid false cache sharding betweenn PerShardData objects.
Fixes #945
> fix: Fix deadlock in the transaction code.

- src/server/CMakeLists.txt
- src/server/db_slice.cc
- src/server/main_service.cc
- src/server/table.cc
- src/server/table.h
- src/server/top_keys.cc
- src/server/top_keys.h
- src/server/top_keys_test.cc
TopKeys uses a custom implementation of HeavyKeeper to track top (hot) keys usage for debugging purposes.
This commit also integrates TopKeys (default off) into DbTable and counts usage of (present) key lookups.
Fixes #257
> feat(server): Introduce and use TopKeys class.

- src/server/transaction.cc
- src/server/transaction.h
Fix:
- shard_data re-use for non-atomic multi
- indexing
> fix(server): Fix transaction index + shard_data multi re-use

- src/core/interpreter.cc
- src/server/main_service.cc
string* err is now only used for errors, otherwise return value should be clear
> fix(server): fix Interpreter::AddFunction

- tools/docker/healthcheck.sh
Fixes #942 
Alpine images don't have bash installed by default, so we need to use
`/bin/sh` instead. This follows the **same existing convention that
we follow in the `entrypoint.sh` script**.
Both ubuntu and alpine images have been tested (i.e healthchecks to
pass) to work with this change.
Build the new image
```bash
docker build -f ./tools/docker/Dockerfile.alpine-dev . -t ghcr.io/pothulapati/df
```
Run and Verify
```bash
docker run --network=host --ulimit memlock=-1 ghcr.io/pothulapati/df  &
docker ps
```
> fix(docker): Use the right shebang in `healthcheck.sh`

- tests/dragonfly/replication_test.py
Test script replication with simple test
Fixes #885
> tests(replication): Test script replication

- src/redis/sds.h
- src/redis/t_zset.c
- src/server/zset_family.cc
- src/server/zset_family_test.cc
- tests/dragonfly/utility.py
Crash was due to an attempt to access nullptr[-1], which is a bad idea :)
Fixes #949
> bug(server): Fix crash in ZPOPMIN

- tests/dragonfly/json_test.py
> fix: Adapt json_test to async_client

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/dragonfly_listener.cc
- src/facade/dragonfly_listener.h
- src/server/conn_context.cc
- src/server/main_service.cc
- src/server/server_family.cc
1. fix potential crash bug when traversing connections with client list
2. fetch cpu/napi id information when handling a new connection.
3. add thread id (tid) and irqmatch fields to client list command.
4. Implement a heuristic under flag that puts a connection on the
CPU id that handles the IRQ queue that handles its socket.
However, if a too wide gap introduced between number of connections on
IRQ threads and other threads we fallback to other threads.
In my tests I saw 15-20% CPU reduction when this heuristic is enabled.
> fix: improve connection affinity heuristic

- src/facade/reply_builder.cc
- src/facade/reply_builder.h
- src/facade/reply_builder_test.cc
- src/server/debugcmd.cc
- src/server/generic_family.cc
- src/server/hset_family.cc
- src/server/main_service.cc
- src/server/memory_cmd.cc
- src/server/script_mgr.cc
- src/server/server_family.cc
- src/server/set_family.cc
- src/server/stream_family.cc
Refactor ReplyBuilder:
- Functions like SendStringArrayAsMap are only used once or twice, but there are lots of virtual overrides for them and at the end they converge to one generic function, so its better to expose the type enum instead of the overloads
- Explicitly set overrides
- Tidy some code
> refactor(facade): Refactor reply builder

- src/server/channel_store.cc
- src/server/channel_store.h
- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/dragonfly_test.cc
- src/server/main_service.cc
- src/server/main_service.h
- src/server/server_family.cc
- src/server/server_family.h
- src/server/server_state.h
Implements RCU (read-copy-update) for updating the centralized channel store.
Contrary to old mechanism of sharding subscriber info across shards, a centralized store allows avoiding a hop for fetching subscribers. In general, it only slightly improves the latency, but in case of heavy traffic on one channel it allows "spreading" the load, as the single shard no longer is a bottleneck, thus increasing throughput by multiple times.
```
Benchmarks:
1. Dry run without subscribers
OLD
===================================================================================================
Type          Ops/sec    Avg. Latency     p50 Latency     p99 Latency   p99.9 Latency       KB/sec  
---------------------------------------------------------------------------------------------------
Publishs …
```
> feat(server): Pubsub updates with RCU

- .github/workflows/reusable-container-workflow.yaml
Fixes #999 
This PR updates the container release workflow to delete the
unstripped packages so that we prevent the stripped packages from
being overwritten.
This should reduce the size of the container images significantly.
> fix(ci): Use stripped binaries for docker images

- src/server/server_family.cc
- src/server/server_family.h
For cluster mode.
Simply return OK.
Fixes #1003
> bug(server): emulate readonly command

- src/facade/facade_test.h
- src/server/transaction.cc
- src/server/transaction.h
1. Adds memory barriers around `run_count_` so that the coordinator thread won't read stale data.
2. (unrelated to the fix): Replaces transaction callback with `FunctionRef` that does not allocate like `std::function`.
Fixes #997.
> fix: add missing barrier to fix reads in the coordinator fiber

- src/server/zset_family.cc
- src/server/zset_family_test.cc
This is aligned with Redis' behavior.
Fixes #833
> ZPOPMAX and ZPOPMIN now reply with scores.

- .pre-commit-config.yaml
- contrib/charts/dragonfly/Chart.yaml
- contrib/charts/dragonfly/ci/passwordsecret-values.golden.yaml
- contrib/charts/dragonfly/ci/persistence-and-existing-secret.golden.yaml
- contrib/charts/dragonfly/ci/persistence-and-existing-secret.yaml
- contrib/charts/dragonfly/templates/_pod.tpl
When installing the helm chart with persistence to true and using an existingSecret (or with only tls enabled), the following parsing error is triggered:
Error: YAML parse error on dragonfly/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 61: did not find expected key.
This simple PR fixes this.
> bug(helm): Fix parsing error with statefulset

- src/core/fibers.h
- src/core/uring.h
- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_listener.cc
- src/facade/dragonfly_listener.h
- src/server/common.cc
- src/server/conn_context.cc
- src/server/db_slice.cc
- src/server/db_slice.h
- src/server/debugcmd.cc
- src/server/dflycmd.cc
- src/server/dflycmd.h
- src/server/engine_shard_set.cc
- src/server/io_mgr.cc
- src/server/io_mgr.h
- src/server/io_utils.h
- src/server/journal/journal_slice.cc
- src/server/journal/journal_slice.h
- src/server/journal/streamer.cc
- src/server/journal/streamer.h
- src/server/replica.cc
- src/server/server_family.cc
- src/server/server_family.h
- src/server/snapshot.cc
- src/server/snapshot.h
- src/server/tiered_storage.cc
- src/server/tiered_storage.h
Remove Boost.Fibers mentions and remove fibers_ext mentions. Done in preparation to switch to helio-native fb2 implementation.
> chore: remove fiber related names from the codebase

- src/facade/CMakeLists.txt
- src/facade/reply_builder.cc
- src/facade/reply_builder.h
- src/facade/reply_builder_test.cc
- src/facade/reply_capture.cc
- src/facade/reply_capture.h
- src/server/main_service.cc
- src/server/string_family.cc
Implement CapturingReplyBuilder to allow capturing responses and replaying them.
Captured responses will be used for executing multiple squashed commands in parallel. The stored responses can then be reordeded and replayed from a single thread.
> feat(facade): Capturing reply builder

- src/server/server_family.cc
Fix #859.
Sample output after the change:
```
127.0.0.1:6379> role
1) "master"
2) 1) 1) "127.0.0.1"
2) "6380"
3) "stable sync"
```
> fix(server): Return the replica's port on ROLE command

- tests/README.md
- tests/dragonfly/conftest.py
- Allows setting the global random seed with a flag
- Adds output for pytests that print the global random seed before creating the seeder
- Makes it possible to repoduce command sequences
> feat(tests): rand seed flag and output

- CMakeLists.txt
- src/core/CMakeLists.txt
* allow to pass a custom OpenSSL folder from build command as -DOPENSSL_ROOT_DIR=/path/to/openssl/folder
* make sure crypto and ssl library using the same installation source
> (build)allow to compile with a custom OpenSSL installation

- src/facade/dragonfly_listener.cc
- src/server/main_service.cc
- src/server/multi_test.cc
Specifically, introduce `conn_io_threads` and `conn_io_thread_start` flags that choose which threads can handle I/O. In addition, introduce `num_shards` flag that may override how many database shards exist in a dragonfly process.
> feat: increase the flexibility of how to assign DF threads

- .github/workflows/ci.yml
- CMakeLists.txt
- src/CMakeLists.txt
- src/core/CMakeLists.txt
- src/facade/CMakeLists.txt
- src/facade/ok_main.cc
- src/server/CMakeLists.txt
- src/server/blocking_controller_test.cc
- src/server/dfly_main.cc
- src/server/io_mgr.cc
- src/server/io_utils.h
- src/server/server_family.cc
- src/server/test_utils.cc
It's a bit more efficient than Boost.Fibers due to better integrations of Fibers with Proactor loop.
> chore: change Dragonfly to use fb2 helio library.

- src/server/multi_command_squasher.h
#1049 was not rebased on top of #1025 and it broke a type alias
> fix: use fibers.h alias for SimpleChannel

- src/server/replica.cc
- src/server/replica.h
Fix #1032 
The problem turned out to be that we call `Replica->Stop()` while holding the global replication mutex. The `Stop()` call was blocked because the previous replication fiber was trying to reconnect and it was stuck in the `ConnectAndAuth()` stage of the `MainReplicationFb` mainloop.
This kind of fixes the issue by setting timeouts for our replication sockets: 20 seconds for the initial connection and 1 second for any subsequent re-connection attempt. These timeouts can be configured with flags. So now the previous replica will stop faster and won't block the command for 2 minutes.
> fix(server): Set lower timeouts for Replica::ConnectAndAuth()

- .github/workflows/regression-tests.yml
There are weird errors coming from regression tests.
I would like to remove temporary the self-hosted runner to reduce the noise until we find the root cause.
> chore: disable self-hosted runner

- src/server/engine_shard_set.cc
- src/server/list_family_test.cc
- src/server/main_service.cc
- src/server/multi_command_squasher.cc
Make blpop test pass with squashing. The problem was that the txid was not properly reported back to the testing code.
Also, fixed redundant codepath for defragmentation.
> feat: enable multi-tx squashing.

- src/server/main_service.cc
- src/server/multi_command_squasher.cc
- src/server/transaction.cc
- tests/dragonfly/replication_test.py
We previously didn't update ConnectionContext::cid for multi transactions at all (even for non squashed, it just wasn't null there). 
Also, squashed stub transactions didn't update their timer
> fix: Update cntx->cid on multi-tx'es

- src/core/interpreter.cc
- src/core/interpreter.h
- src/core/interpreter_test.cc
- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/main_service.cc
- src/server/main_service.h
- src/server/multi_command_squasher.cc
- src/server/transaction.cc
Implements a very basic version of `redis.acall`, an alternative to `redis.call` that doesn't execute commands immediately, but instead aggregates them and executes them squashed. Increases performance by up to 50% in many cases.
> Lua script async calls

- tests/dragonfly/__init__.py
The regression tests failed because we tried to start 3 instances with the same port. Fix by making PortPicker never return the same port twice.
> fix(tests): Don't return the same port from PortPicker.get_available_port twice

- src/server/rdb_load.cc
- src/server/rdb_load.h
1. Pull newest helio that fixes 32-bit overflow in IoBuf.
2. Allow responsiveness when loading huge sets and maps.
3. Break array of blobs into segments of limited size so that  we won't allocate billion-byte arrays when handling large (h)sets.
It reduces pressure on the allocator when loading millions of items.
Fixes #1076.
> fix: bugs in rdb code

- docs/transaction.md
- src/server/main_service.cc
- src/server/multi_command_squasher.cc
- src/server/transaction.cc
- src/server/transaction.h
Removes incremental locking, all its usages and mentions. Incremental locking is incompatible with out-of-order execution of multi hop transactions, which is a more important optimization.
> fix: Remove incremental locking

- src/server/db_slice.cc
- src/server/db_slice.h
- src/server/server_family.cc
Add statistics about how many times DF rejection to proceed with insertion of an entry due to possible OOM situation.
> feat: add oom insertion rejections

- tools/packaging/debian/dragonfly.conf
- tools/packaging/debian/dragonfly.service
1. Tune some security directives.
2. Fix the flags file that mistakenly configured dragonfly to store its dump files into /run (tmpfs).
> fix: systemd configuration

- src/server/replica.cc
Second part of fix for #931 
We do DNS resolving for replication commands, and it has to support IPv6.
We try to choose an IPv4 address if possible and then fallback to IPv6 if not.
To check that we manage to replicate a IPv6 address, you can setup a redis docker image
```bash
docker network create --ipv6 --subnet 2001:db8:abcd::/64 test_ipv6
docker run --network test_ipv6 --name my_redis -d redis
docker inspect my_redis | grep GlobalIPv6Address
```
and connect a dragonfly instance to it locally.
> feat(server): Support IPv6 addresses for replication

- tests/dragonfly/snapshot_test.py
From #1028 
Manual instance spawning does not disable the default instance, so they both conflict if run one after another
> fix: fix default instance port blocking in pytest

- src/server/command_registry.h
- src/server/generic_family.cc
- src/server/rdb_save.cc
- src/server/replica.cc
- src/server/replica.h
- src/server/server_family.cc
- src/server/snapshot.cc
- src/server/snapshot.h
- tests/dragonfly/replication_test.py
Fix #1017
There's still a stage that's not interruptible: When forming the initial connection to the master.
Also fixed 2 crashes (one of them in a DCHECK) in the replication cancelling flow.
I did some stress testing locally, so I'm relatively sure it works. Still a bit unsure about how to test this...
> fix(server): Allow interrupting REPLICAOF commands during full sync

- tests/dragonfly/__init__.py
- tests/dragonfly/snapshot_test.py
For example, this will be needed to disable auto save on shutdown with --dbfilename=""
Before:
```
df_factory.create(param="")  # -> ./dragonfly --param
df_factory.create(param=None)  # -> ./dragonfly --param "None"
```
After:
```
df_factory.create(param="")  # -> ./dragonfly --param ""
df_factory.create(param=None)  # -> ./dragonfly --param
```
> chore: Allow passing empty strings as flag arguments in DflyInstance

- contrib/charts/dragonfly/templates/prometheusrule.yaml
Fixes https://github.com/dragonflydb/dragonfly/issues/1015
This commit fixes a rendering error where when the rules are
empty, the helm chart fails to render. By using the correct
indentation, the chart will render correctly.
> fix(helm): Allow prometheus rules fields to be empty

- src/server/server_family.cc
- tests/dragonfly/snapshot_test.py
Allowing `..` inside dbfilename can allow almost arbitrary overwrite of files outside of `--dir`. Under specific assumptions, this might be a security issue. Fix by filtering not allowing such components.
> fix(server): Don't allow directory escapes in dbfilename

- src/server/db_slice.cc
- src/server/snapshot.cc
- src/server/snapshot.h
Fix the problem described by @romange in #1036.
Some synchronizations were removed after Adi and I went over the code. I left `CHECK`s around to be a bit more safe.
> fix(server): Prevent preemption inside SerializeBucket

- tests/dragonfly/__init__.py
- tests/dragonfly/replication_test.py
After #1086, some replication tests were broken sometimes. This disables snapshots everywhere in the tests unless explicitly provided (`snapshot_test.py` for example). Accidental snapshots make testing more complicated so it is better to avoid them at all.
> fix(tests): Disable 'dbfilename' unless explicitly given in the test

- src/server/dfly_main.cc
Dragonfly now respects CGroup limits (memory, CPUs) and uses those instead of the host's limits.
Closes #986.
> fix: container limits

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/server/conn_context.cc
- src/server/dragonfly_test.cc
- src/server/main_service.cc
- src/server/test_utils.cc
- src/server/test_utils.h
Important memory optimizations for pubsub:
* We previously had a `class Connection::Request` which contained a `variant<PipelineMessage, PubMessage, MonitorMessage>`. The issue - `PipelineMessage` stores lots of stuff inline and its size is 200+ bytes - so the size of `Request` is by itself 200+ bytes.
* `PubMessage` contained two `shared_ptr<string>` for channel and name, and one optional `string` for the pattern and also some other fields for another mode - stack size ~64 bytes. 
* `PubMessage` heap overhead: two strings and two shared_ptr control blocks (24+24+24?+24?) = 96 bytes.
**So in the end a simple `publish foo bar` costs us 300+ bytes** and multiple allocations 💀 Redis writes directly to client buffers and it takes up around ~10 bytes there. A x30 difference. This means, that …
> Dispatch queue memory optimizations

- src/core/interpreter.cc
- src/core/interpreter.h
- src/facade/reply_builder.h
- src/facade/reply_capture.cc
- src/facade/reply_capture.h
- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/main_service.cc
- src/server/main_service.h
- src/server/multi_command_squasher.cc
- src/server/multi_command_squasher.h
- tests/dragonfly/eval_test.py
Last part of basic squashing. I've created issues for upcoming problems to tackle them later.
This PR collects errors from `acall` and `apcall` and aborts in the first case. 
Besides it:
* add a memory limit for acall buffers
* reverts from channels to basic vectors as we don't stream yet either way
* disables non-error reply capturing for async lua -> increases performance
> Collect errors from async lua calls

- src/server/journal/executor.cc
- src/server/journal/executor.h
A regular reply builder with a null sink still serializes all replies. The capturing reply builder with a `NONE` filter is a no-op for all send methods.
> fix: replace journal executor reply builder

- src/server/command_registry.cc
- src/server/command_registry.h
- src/server/db_slice.cc
- src/server/script_mgr.cc
- src/server/server_family.cc
- src/server/transaction.cc
- src/server/transaction.h
- tests/dragonfly/replication_test.py
Fixes #1040 
The solution is this PR for replicating scripts:
Script is non key command and is not part of the transaction framework which is how we replicate commands.
Therefor I created a new command mask, if this mask is set I use the transaction framework using shard 0 to replicate the command
> bug(server): replicate scripts in stable state

- tests/dragonfly/sentinel_test.py
As can be seen in the log of a failure 10 secs can be just shy and eventually the value is present both in replica and master:
[2023-04-24 15:22:15.836 INFO] key was set on promoted replica, awaiting get on promoted replica.
[2023-04-24 15:22:25.905 INFO] SYNC1 [0, 0] [0, 0] (first log in timeout exception expect clause)
[2023-04-24 15:22:25.957 INFO] replica val: b'value'
[2023-04-24 15:22:25.957 INFO] master val: b'value'
(full log https://github.com/dragonflydb/dragonfly/actions/runs/4787901920/jobs/8513772429)
> test(sentinel_test.py): increase timeout in failover test

- src/server/generic_family.cc
- src/server/hset_family.cc
- src/server/hset_family_test.cc
- src/server/string_family.cc
The call was left during big refactoring when we removed command name from the arguments slice passed to commands.
Fixes #1140
> fix: remove redundant ToLower call from the HSET function

- src/CMakeLists.txt
- src/core/search/CMakeLists.txt
- src/core/search/ast_expr.h
- src/core/search/lexer.lex
- src/core/search/parser.y
- src/core/search/query_driver.h
- src/core/search/scanner.h
- src/core/search/search_parser_test.cc
Also, add basic test with Parser.
> feat: Add unicode support and replace flex with reflex.

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/server/main_service.cc
Fixes #1039 
This PR:
* Adds "almost correct" backpressure to publish messages (without decreasing dispatch performance)
* Enables batching for pubsub
> Dispatch queue backpressure and batching

- src/server/dragonfly_test.cc
- src/server/main_service.cc
- src/server/server_family.cc
Hi @romange,
I just tried to implement AUTH and SETNAME in the HELLO command to resolve the issue https://github.com/dragonflydb/dragonfly/issues/1151 by copying logic from here https://github.com/redis/redis/blob/d659c734569be4ed32a270bac2527ccf35418c43/src/networking.c#L3529-L3579
#Fixes #1151
> feat(server): allow AUTH and SETNAME options in the HELLO command

- src/facade/dragonfly_connection.cc
- src/server/command_registry.h
- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/main_service.cc
- src/server/multi_command_squasher.cc
- src/server/multi_test.cc
Together with `default_lua_config` solves #781.
> feat: ignore MULTI/EXEC if the transaction consists of EVAL commands

- src/server/command_registry.cc
- src/server/command_registry.h
- src/server/main_service.cc
- src/server/main_service.h
- src/server/server_family.cc
- src/server/stream_family.cc
- src/server/stream_family_test.cc
- src/server/transaction.cc
- src/server/transaction.h
- src/server/zset_family.cc
Along the way, performs small cleanups in command handling code.
Fixes #854.
> fix: 'xgroup help' should show help message

- src/core/compact_object.cc
Randomly stumbled upon this function, saw that it has a typo :)
> fix(server): Fix typo in CompactObj::operator==

- src/core/small_string.h
- src/core/string_map.h
- src/core/string_set.h
- src/facade/memcache_parser.h
- src/facade/op_status.h
- src/server/main_service.cc
* Re-add includes that were removed
* Fix 2 std::moves that didn't work as expected (found by better move analysis!)
> chore: Fix errors/warnings in GCC13

- src/server/replica.cc
This bug was found inside `test_cancel_replication_immediately` of the regression tests
https://github.com/dragonflydb/dragonfly/actions/runs/4828930130/jobs/8603358782
The stacktrace suggests that we try to shut down a socket that is already closed or not initalized. What is more, 
>  [Error generic:125 while calling check_connection_error(ec, kConnErr)](replica.cc:181] Error generic:125 while calling check_connection_error(ec, kConnErr))
indicates that it must be that `Replica::Start` is cancelled after the socket is initialized (the pointer is valid), but before it's connected (fd = -1)
I first looked only at the iouring socket's code and saw that fd is not changed even on errors, which made me think of many different causes for this bug. But as pytests are running with epoll, it …
> fix: fix replica closing socket

- src/core/interpreter.cc
- src/core/interpreter.h
- src/core/interpreter_test.cc
- src/server/dflycmd.cc
- src/server/multi_test.cc
- src/server/script_mgr.cc
- src/server/script_mgr.h
- src/server/server_family.cc
Regex for detecting possible async calls for scripts
> Detect possible async calls in scripts

- src/server/replica.cc
Fix regression tests (again).
The socket is closed on destruction, no need to close it ahead. If we close it ahead, asserts in the regular socket flow fail (we don't check there every time if its valid or not)
> fix: remove preliminary socket close in replica

- src/server/generic_family.cc
- src/server/generic_family_test.cc
> PERSIST returns 0 when key has no expiry

- src/CMakeLists.txt
- src/core/search/CMakeLists.txt
- src/core/search/ast_expr.cc
- src/core/search/ast_expr.h
- src/core/search/lexer.lex
- src/core/search/parser.y
- src/core/search/query_driver.cc
- src/core/search/query_driver.h
- src/core/search/search_parser_test.cc
Simplest possible AST for: term, not, and, or
> feat: simple AST for search

- src/server/dragonfly_test.cc
- src/server/multi_test.cc
- src/server/test_utils.cc
- src/server/test_utils.h
> Enable unlock for all tests.

- src/core/search/CMakeLists.txt
- src/core/search/ast_expr.cc
- src/core/search/ast_expr.h
- src/core/search/base.cc
- src/core/search/base.h
- src/core/search/parser.y
- src/core/search/search_parser_test.cc
> Support fields in search mvp

- src/facade/redis_parser.cc
- src/facade/redis_parser_test.cc
Fixes a bug parsing nested arrays in client mode.
When `parse_stack_.emplace_back(len, cached_expr_)` is called **before** creating the new array, the root array would be added to `parse_stack_` twice and the leaf array would never be added. That means when a stack was popped, `cached_expr_` would end up pointing to the wrong array.
Such as the array `[[['foo'],['bar']],['car']]` (`"*2\r\n*2\r\n*1\r\n$3\r\nfoo\r\n*1\r\n$3\r\nbar\r\n*1\r\n$3\r\ncar\r\n"`) would have been parsed as `[[['foo']],['bar'],['car']]`, since after `foo` was parsed such that the nested array was at capacity, popping the stack would end up pointing `cached_expr_` to the root array instead of the first nested array.
> fix: fix parsing nested arrays

- src/core/CMakeLists.txt
- src/core/search/CMakeLists.txt
- src/core/search/search.cc
- src/core/search/search.h
- src/server/CMakeLists.txt
- src/server/container_utils.cc
- src/server/container_utils.h
- src/server/hset_family.cc
- src/server/main_service.cc
- src/server/search_family.cc
- src/server/search_family.h
- src/server/search_family_test.cc
Implements brute force search
Basic redis search interface:
- FT.CREATE with a single index
- FT.SEARCH
> Basic search

- CONTRIBUTORS.md
- README.md
- README.zh-CN.md
- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/server/main_service.cc
Signed-off-by: Paweł Kapliński [pawkapl89@gmail.com](mailto:pawkapl89@gmail.com)
Fixing issue #1181
Changes:
- adding admin_nopass flag
- when admin_nopass flag is turned on, clients have open access to the admin network interface and console at admin port pointed by admin_port flag. 
- when admin_nopass flag is turned off, admin network interface requires AUTH just like a regular network interface.
> feat(admin): Implement admin_nopass flag

- src/server/CMakeLists.txt
- src/server/server_family.cc
- src/server/server_family.h
1. Load flow reorganized - most of the logic is now in InferLoadFile function. S3 read is not yet supported.
2. Write path is implemented. Specifically, you can use undocumented (by design) option to save like: `SAVE rdb s3://bucket/path/file`.
3. When using `--dir=s3://bucket/path/` it also saves into s3 on shutdown.
> feat: Implement rdb snapshot write directly into s3.

- tests/dragonfly/cluster_test.py
- tests/dragonfly/conftest.py
- tests/dragonfly/connection_test.py
- tests/dragonfly/eval_test.py
- tests/dragonfly/generic_test.py
- tests/dragonfly/json_test.py
- tests/dragonfly/list_family_test.py
- tests/dragonfly/redis_replicaiton_test.py
- tests/dragonfly/replication_test.py
- tests/dragonfly/requirements.txt
- tests/dragonfly/sentinel_test.py
- tests/dragonfly/snapshot_test.py
- tests/dragonfly/utility.py
aioredis is deprecated and recommends to transition to redis-py. New modules like redis search are supported only there 
Fixes #1190 
There is also some kind of new issue with cluster client disconnects on redis-py 5.4 😵 For some reason it's still counted as alive even when the connection pool is closed, so I had to disable connection checks with cluster clients
> fix: use redis.asyncio instead of aioredis

- src/server/main_service.cc
- src/server/server_family.cc
> chore: Add vlog printings every time we switch global state

- .vscode/launch.json
- src/server/zset_family.cc
- src/server/zset_family.h
- src/server/zset_family_test.cc
> feat: implement ZINTERCARD

- tests/dragonfly/redis_replicaiton_test.py
Move timeout decrement to the end so we don't assert if we succeed in the last second (looks like this was the case in the recent regression test faliure on CI)
Clarify the commnet of await_synced
> fix(tests):Small fix to redis replication test

- src/server/main_service.cc
DF build currently gives this warning:
```
../src/server/main_service.cc: In member function ‘bool dfly::Service::CheckKeysOwnership(const dfly::CommandId*, facade::CmdArgList, dfly::ConnectionContext*)’:
../src/server/main_service.cc:625:49: warning: ‘keys_slot’ may be used uninitialized in this function [-Wmaybe-uninitialized]
625 |   if (!server_family_.cluster_config()->IsMySlot(keys_slot)) {
```
I first wanted to ignore it, but it seems that slot_id can actually be non initialized. Because even if cid->first_key_pos() > 0, the command itself can have 0 keys if it uses variadic keys. For example: EVAL {script} 0.
(Yes, it seems like we don't have any tests for this part yet)
> fix: handle no key commands in slot check

- src/server/cluster/cluster_config.cc
- src/server/cluster/cluster_config.h
- src/server/cluster_config_test.cc
- src/server/server_family.cc
> feat(server): SetConfig() for ClusterConfig.

- src/core/search/base.h
- src/core/search/search_parser_test.cc
- src/server/search_family.cc
- src/server/search_family.h
- src/server/search_family_test.cc
- tests/dragonfly/search_test.py
Adds:
- Support for json values in search
- Basic python test for search
> feat: search json support + client tests

- .pre-commit-config.yaml
- src/redis/stream.h
- src/redis/t_stream.c
- src/server/stream_family.cc
- src/server/stream_family_test.cc
Fixes #1163 
XADD command currently doesn't support minid, nomkstream and limit options. This PR aims to support these options.
Additionally, I modified the pre-commit configuration file to correctly exclude multiple files (i.e. src/redis and ci/ directories).
> Support MINID, NOMKSTREAM and LIMIT options for XADD command

- src/server/rdb_load.cc
Moves the temporary variable outside the loop so we can reuse the buffer.
> opt: Slightly less allocations in OpaqueObjLoader::CreateHMap

- src/server/db_slice.cc
- src/server/db_slice.h
I created FlushSlots function in db_slice. It should be called from DFLY CLUSTER CONFIG command when slots are deleted from node.
> feat(cluster): impl slot data delete

- src/server/CMakeLists.txt
- src/server/cluster/cluster_config.cc
- src/server/cluster/cluster_config.h
- src/server/cluster_config_test.cc
- src/server/dflycmd.cc
- src/server/dflycmd.h
- src/server/dflycmd_test.cc
> feat(server): Implement `DFLY CLUSTER CONFIG` command.

- tools/docker/Dockerfile.ubuntu-prod
Fixes https://github.com/dragonflydb/dragonfly/issues/1238
> fix(docker): Install libxml2 as part of ubuntu Dockerfile

- src/server/stream_family.cc
- src/server/stream_family.h
- src/server/stream_family_test.cc
Implements milestone 1 from https://github.com/dragonflydb/dragonfly/issues/1164.
As described in https://github.com/dragonflydb/dragonfly/issues/1164, this has a few limitations:
* BLOCK is not supported
* COUNT is a required parameter (due to how transactions parse arguments)
* Only supports commands with 2 streams (again due to limitations in how transactions parse arguments)
> feat(stream) Add support for XREAD

- src/server/dflycmd.cc
- src/server/dflycmd.h
- src/server/engine_shard_set.h
- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/server_family.cc
We would create a connection per thread, not per shard thread. The PR changes it to replicate only over shard.
I'm pretty sure we don't send anything over that connection, and now that I switch to absolute offsets instead of per-replication offsets it was awkward to handle offsets without having an actual shard.
> fix(replication): Don't open a replication flow in non-shard threads

- src/server/stream_family.cc
Following the [comment](https://github.com/dragonflydb/dragonfly/pull/1201#issuecomment-1552640507), a warning is popping up while building the `stream_family.cc` file.
```
[19/37] Building CXX object src/server/CMakeFiles/dragonfly_lib.dir/stream_family.cc.o
/home/roy/work/dragonfly/src/server/stream_family.cc: In function ‘facade::OpResult<streamID> dfly::{anonymous}::OpAdd(const dfly::OpArgs&, std::string_view, const dfly::{anonymous}::AddOpts&, facade::CmdArgList)’:
/home/roy/work/dragonfly/src/server/stream_family.cc:543:5: warning: missing initializer for member ‘streamAddTrimArgs::id’ [-Wmissing-field-initializers]
543 |     };
|     ^
/home/roy/work/dragonfly/src/server/stream_family.cc:543:5: warning: missing initializer for member ‘streamAddTrimArgs::id_given’ …
```
> fix(stream): avoid using designated initializer

- src/server/multi_test.cc
Failed in #1234. 
If the second fiber runs before the first, then the values read are nils. The checks below expect them to be at least present.
> fix: fix multi test

- src/server/common.h
- src/server/debugcmd.cc
- src/server/journal/journal.cc
- src/server/journal/journal.h
- src/server/journal/journal_slice.cc
- src/server/journal/journal_slice.h
- src/server/server_state.cc
- src/server/server_state.h
- src/server/transaction.cc
#908 added a path to schedule transactions immediately if the operator fiber was on the same thread as the shard of the relevant keys.
This caused a replication bug: When the replica would receive a command from the journal it could schedule it immediately, before the matching RDB record was loaded. Since the RDB reader is not using the regular transaction mechanisms, it's tricky to use the regular locking mechanism to fix the issue. Instead of locking, I fixed it by completely disabling inline scheduling when the DB is in a 'LOADING' state.
Close #1036
> feature(server): Bring back inline scheduling

- src/server/cluster/cluster_config.cc
- src/server/cluster/cluster_config.h
- src/server/cluster/cluster_family.cc
- src/server/cluster_config_test.cc
- src/server/db_slice.h
On config update we check what are the deleted slots and delete the db data of deleted slots
testing:
I checked the config command deletes slots data manually
I want to add a unit test for it , but now I understand that I need a command for the node id to implement the test, so I will create it in a new PR once you merge your cluster family PR changes.
> feat(cluster): cluster config delete now owned slots data

- .github/workflows/ci.yml
- CMakeLists.txt
> chore: Try to turn on Werror in the CI

- src/core/fibers.h
- src/core/uring.h
- src/facade/dragonfly_listener.h
- src/server/io_mgr.cc
- src/server/server_family.cc
1. Refactor snapshot saving logic, specifically, build the full path once for both versions.
2. Pull the newest version of helio, where many s3 bugs are fixed.
3. Include some cleanups because helio now does not contain Boost.Fibers implementation anymore.
> fix: S3 writes are now working with new format as well

- src/server/stream_family.cc
- src/server/stream_family_test.cc
https://github.com/dragonflydb/dragonfly/pull/1235 restricted the XREAD arguments to always include COUNT and 2 streams due to limitations parsing the keys - though thats now been fixed by https://github.com/dragonflydb/dragonfly/pull/1250 so those restrictions can be removed
> fix: remove xread required arguments

- src/server/cluster_family_test.cc
- src/server/main_service.cc
This only applies to cluster mode.
Fixes #1266
> Reply with `MOVED` error for non-owned slots.

- src/facade/conn_context.h
- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/facade.cc
- src/server/conn_context.cc
- src/server/conn_context.h
- src/server/dragonfly_test.cc
- src/server/main_service.cc
- src/server/test_utils.cc
- src/server/test_utils.h
- tests/dragonfly/connection_test.py
Fixes #1245 
Make subscribe reply immediately. Solves two issues:
1. During pipeline (where requests are part of dispatch q) the subscribe response is pushed back to the dispatch queue, so the client can receive its reply potentially very long after it executed. Most clients (probably?) expect a direct reply
2. Currently the responses are pushed back after all the channel store callbacks have been registered. This means that if a subscribe has many channels with possible suspension points (like `SUBSCRIBE ch1 ... ch10`), then until it gets to subscribe to the tenth, other channels could have received lots of messages.  What is more, its theoretically possible that a client receives a message before the confirmation itself.
> fix: fix dispatch ordering

- src/server/blocking_controller.cc
- src/server/blocking_controller_test.cc
- src/server/container_utils.cc
- src/server/list_family.cc
- src/server/stream_family.cc
- src/server/stream_family_test.cc
- src/server/transaction.cc
Adds support for XREAD BLOCK
1. Looks up the ID of the last entry in each stream, which is used to:
a. Resolve the `$` ID
b. Check if there are any entries that can be resolved without blocking
2. If there are no entries that can be resolved, either:
a. If BLOCK is used, blocks for the requested timeout
b. Otherwise returns an empty array
3. If the command blocked, once awoken it resolves just the woken stream
4. Otherwise it does a normal XREAD as before
Note resolving a blocked command and a non-blocked command are different, since AFAIK only the shard that had the awoken key blocks waiting for the awoken transaction to proceed, so need to ensure only the awoken key is resolved. If we used OpRead it could end up resolving from a different stream to the one that was awoken (if another …
> feat(streams): Add support for XREAD BLOCK

- src/server/cluster/cluster_family.cc
- src/server/cluster_family_test.cc
Works in all 3 modes: emulated, cluster and unconfigured-cluster.
Fixes #1278
> feat(cluster): Implement `CLUSTER SLOTS`.

- src/server/dfly_main.cc
Read the maximum memory on LXC containers too, such as GKE with Containerd. Fixes #1292.
> bug(memory): read LXC memory.limit_in_bytes too

- src/server/cluster/cluster_family.cc
- src/server/cluster/cluster_family.h
- src/server/cluster_family_test.cc
Implementation handles the following cases:
1. Real, configured cluster
2. Real, unconfigured cluster (error message)
3. Emulated cluster
4. Cluster mode unset (error message)
The only regression from previous (emulated mode) is that we no longer specify 'disconnected'. This is because, in cluster mode, we can't tell that anyway, so we might as well do that in emulated mode as well.
Fixes #1278
> feat(cluster): Implement CLUSTER NODES command.

- tests/dragonfly/conftest.py
Gets rid of the `[2023-05-28 14:34:27.304 DEBUG] Using selector: EpollSelector` spam.
> chore: Silence unwanted asyncio clutter

- tests/dragonfly/search_test.py
Use different indices for different types now that we have a strict mapping
> fix: fix search test

- src/server/conn_context.h
- src/server/replica.cc
- src/server/replica.h
- src/server/server_family.cc
- src/server/version.h
Implement support for #1216: We now send the server version to the client in the `replconf capa dragonfly` response, and the client sends back its version with `replconf client-version ver`.
I'd like to rebase #1259 on top of this in order to conditionally disable the ACKs.
> feat(server): Add versioning to dragonfly replication

- .github/workflows/ci.yml
- src/core/search/parser.y
- src/facade/reply_builder.cc
- src/facade/reply_builder.h
- src/server/stream_family.cc
I accidentally disabled `-Werror` when adding the Clang flow
> fix: werror in ci and warning that slipped by

- src/server/multi_test.cc
- src/server/script_mgr.cc
- src/server/string_family.cc
- src/server/string_family.h
- src/server/string_family_test.cc
- tests/dragonfly/eval_test.py
Keep consistent and use 'flags' everywhere. Need to settle for normal names now because those will be mentioned in docs.
* SCRIPT CONFIG should be SCRIPT FLAGS
* defualt_lua_config should be default_lua_flags
Another change: Add STICK option to SET
> fix: script flags naming + add stick option

- src/server/dflycmd.cc
- src/server/dflycmd.h
- src/server/replica.cc
- src/server/server_family.cc
- tests/dragonfly/replication_test.py
Add a 'lag=LAG' field to `INFO REPLICATION`.
The lag is defined to be the maximal difference over all the shards between master's LSN and acknowledged LSNs from replica. A flag to control PING interval was added to improve testing stability.
> feat: Report replication lag in INFO REPLICATION

- src/core/search/CMakeLists.txt
- src/core/search/base.h
- src/core/search/indices.cc
- src/core/search/indices.h
Implements two basic search indices without any optimizations.
* TextIndex
* NumericIndex
I've just cut them out of my larger PR #1294 .
So far at this step they're dead simple, so I don't see any reason to test them. The tests in the main PR verify correctness good enough
> feat: simple search indices (unused)

- src/server/server_family.cc
- src/server/server_family.h
Close #1309.
Example output:
```
I20230529 15:37:32.397684 291516 server_family.cc:635] Loading /home/roy/work/dragonfly/build-dbg/dump-2023-05-29T15:37:31-summary.dfs
I20230529 15:37:32.400419 291520 listener_interface.cc:96] sock[53] AcceptServer - listening on port 6379
I20230529 15:37:32.402602 291519 server_family.cc:678] Load finished, num keys read: 2000
```
> fix: Clarify logging for snapshots loading.

- src/server/stream_family.cc
- src/server/stream_family.h
- src/server/stream_family_test.cc
Adds support for XTRIM (https://github.com/dragonflydb/dragonfly/issues/1332)
* Renames `TrimStrategy` enum given the `AddOptsTrim` prefix seems redundant given its always prefixed by `TrimStrategy`?
* Adds `OpTrim` which is the same as trimming in `OpAdd` (theres a TODO about handling replication copied over from `OpAdd` which seems out of scope for this)
* Refactors `XADD` and `XTRIM` argument parsing into `ParseAddOrTrimArgsOrReply` (which matches how Redis parses the commands given their arguments are very similar)
> feat(streams): Add support for XTRIM

- src/server/replica.cc
- src/server/replica.h
Callers don't have to manipulate the buffer themselves now, better error handling.
> Chore: Clean up interface of Replica::ReadRespReply

- src/server/main_service.cc
- tests/dragonfly/cluster_test.py
This allows masters to send data of non-owned keys to their replicas, which is useful when:
1. Config is temporarily different between master and replica
2. Preparing for taking ownership over currently not-owned slots (in the
upcoming migration feature)
Fixed #1319
> feat(cluster): Allow actions on non-owned keys on replication port.

- src/core/search/ast_expr.cc
- src/core/search/ast_expr.h
- src/core/search/indices.cc
- src/core/search/indices.h
- src/core/search/lexer.lex
- src/core/search/parser.y
- src/core/search/search.cc
- src/core/search/search.h
- src/core/search/search_parser_test.cc
- src/core/search/search_test.cc
- src/server/search/search_family.cc
- src/server/search_family_test.cc
- tests/dragonfly/search_test.py
This PR adds support for [RediSearch Tags](https://redis.io/docs/stack/search/reference/tags/) in the whole pipeline from parser to ft.create schema.
> feat: Support tags in search

- src/server/cluster/cluster_family.cc
- src/server/cluster_family_test.cc
> fix(cluster): Fix crash when getting `DFLYCLUSTER GETSLOTINFO` with no other args.

- src/server/list_family.cc
We sometimes experience crashes with BLPOP that are so far impossible to reproduce. I'll try to reproduce it tomorrow once again, but unfortunately I need to add this tracing, so that we'll have more info for subsequent crashes. Now when people report them, we have no more than the key.
I want to detect what sequence of actions led to loosing the key between the wakeup request and actual pop. I didn't wire it into db_slice, but I print if the key had expiry just in case.
I hope allocating a string won't affect performance. It'll be removed once the issue is solved.
> chore: Add blpop crash diagnostics

- src/server/list_family.cc
- src/server/list_family_test.cc
Fixes the `LINSERT` pivot - before the pivot was being capitalised rather than the direction
Fixes https://github.com/dragonflydb/dragonfly/issues/1364
> fix: fix linsert pivot

- tools/docker/Dockerfile.alpine-dev
- tools/docker/Dockerfile.alpine-prod.wip
Currently, The docker run command on an alpine image fails due to the
lack of this dependency
> fix(alpine): Add libxml2 into the build pipeline

- src/server/dfly_main.cc
Following some community interaction, this PR adds detection for cgroup v1 as well, where previously there was only v2 support.
> CGroup v1 detection

- src/server/debugcmd.cc
- src/server/rdb_test.cc
1. found a bug in the keys, they jumped with no reason in the regular debug populate function. I fixed it and added a check in unit test.
2. Added print for the set to see if it fails in the CI
I still did not found the reason why it fails on ARM. When running on aws arm machine with same number of cores the bug does not reproduce. I will try to see if it fails here in the CI
> bug(debug populate): fix debug populate keys

- src/server/cluster/cluster_config.cc
- src/server/cluster/cluster_config.h
- src/server/cluster/cluster_config_test.cc
- src/server/cluster/cluster_family.cc
- src/server/cluster/cluster_family.h
- src/server/cluster/cluster_family_test.cc
- src/server/main_service.cc
As part of this change, now `SetConfig()` does not return the deleted slots, but instead we calculate it ourselves once (instead of it being done in each thread separately).
While at it, add a small test function to remove `sleep()`s and wait in a less fragile way.
Fixes #1357
feat(cluster): Use thread-local cluster config
To support this, I refactored some of the code:
* We no longer have `IsConfigured()` and `SetConfig()`, now configuration validation is done via instantiation
* As a result, we check if `tl_cluster_config` is `nullptr` or not to determine whether the cluster has been configured
* Pushing new configuration is done via copy-c'tor                                                                                                         
While at it, add a small test function …
> feat(cluster): Use thread-local cluster config

- src/facade/reply_builder.cc
- src/facade/reply_builder.h
This removes the "25" limit for batched messages.
Turns out the aggregation in #1287 was not aggressive enough, because it's quite possible to reach the specified max capacity of  io vectors. For example, each "QUEUED" is actually "+", "QUEUED", "\r\n" so we can reach the limit with about 8 batched commands and then we prematurely flush.
Closes #1285
> fix(server): Do more aggressive batching.

- src/server/rdb_test.cc
- src/server/stream_family.cc
`xinfo groups` command sends all the information as string (irrespective of their true type e.g. integer). This PR fixes that.
> fix(xinfo): send integer info in correct type

- src/server/search/doc_index.cc
- src/server/search/doc_index.h
- src/server/search/search_family.cc
- src/server/search/search_family_test.cc
This PR adds support for the LIMIT option for search. Because scoring is not implemented, it just cuts off the part in the order it was retrieved.
The default limit is 10
> feat: search limit

- src/server/stream_family.cc
Non-aggregated xread replys contributed to the high latency in https://github.com/dragonflydb/dragonfly/issues/782
> fix: aggregate xread and xrange replys

- src/facade/reply_builder.cc
- src/facade/reply_builder.h
- src/server/main_service.cc
Lua scripts not aggregating seemed to be the main cause of the high latency running `should obliterate a queue with high number of jobs in different statuses` in https://github.com/dragonflydb/dragonfly/issues/782 - so adding aggregation to `EVAL`/`EVALSHA`
Though adding that increased the latency of `EXEC/MULTI` transactions containing Lua scripts, as `MULTI` does its own aggregating, but each script also aggregating causes extra sync writes (from each script calling `StopAggregate`)
Maybe theres a nicer way to do this...? It reduces the `should obliterate a queue with high number of jobs in different statuses` latency from ~15s to ~1.5s
> fix: aggregate eval replys

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/dragonfly_listener.cc
- src/server/server_family.cc
- tests/dragonfly/shutdown_test.py
- Adds a new 'IsCurrentlyDispatching' method to `facade::Connection`.
- Adds a time limited (10ms) wait for all connections to stop dispatching on shutdown.
- Move `EnterLameDuck` earlier so we stop accepting new commands earlier in the shutdown flow.
- Adds a new python test for the new safety feature.
Closes #1313.
> fix: A more gracefull shutdown

- src/server/conn_context.h
- src/server/main_service.cc
- tests/dragonfly/replication_test.py
Fixes #1391
It looks that long ago we planned to distinguish scripts read-only status ahead, so all of them were marked as write. Found this comment:
>   // TODO: to determine whether the script is RO by scanning all "redis.p?call" calls
// and checking whether all invocations consist of RO commands.
// we can do it once during script insertion into script mgr.
For now I've removed any categorization into read-only or not. Write commands will fail as usual.
> fix: Allow readonly commands in replica script

- src/core/search/base.h
- src/core/search/indices.cc
- src/core/search/indices.h
- src/core/search/search.cc
- src/core/search/search.h
- src/server/db_slice.cc
- src/server/db_slice.h
- src/server/hset_family.cc
- src/server/json_family.cc
- src/server/search/doc_accessors.cc
- src/server/search/doc_accessors.h
- src/server/search/doc_index.cc
- src/server/search/doc_index.h
- src/server/search/search_family.cc
- src/server/search/search_family_test.cc
Can only be tested after #1294 
This PR:
* Before the document is changed, calls RemvoeDoc on each shard document index that tracks the document
* After the document is changed, calls AddDoc on the same shard doc indices
* Some small naming changes for less ambiguity
Basically, to update a document, it is fully removed and then fully added. In the future we should only update the indices which are affected by the changed fields (if its possible, definitely for hset, more difficult with json)
> feat: track update and delete for search

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
My recent PR accesses Connection->cc_ on shutdown, but sometimes it's a null pointer.
Make it optional.
> Fix crash on shutdown from #1388

- src/server/list_family_test.cc
- src/server/transaction.cc
NotifyPending was being called when a blocked transaction expires, which meant other blocked transactions could be woken up even though another transaction could be in progress. NotifyPending has no affect on the blocked transaction.
Fixes https://github.com/dragonflydb/dragonfly/issues/1387.
(Ran `list_family_test --gtest_repeat=100` as requested which passed)
> fix: remove NotifyPending from UnwatchShardCb

- .github/workflows/ci.yml
- contrib/charts/dragonfly/ci/resources-values.golden.yaml
- contrib/charts/dragonfly/ci/resources-values.yaml
- contrib/charts/dragonfly/ci/taints-tolerations-values.golden.yaml
- contrib/charts/dragonfly/ci/taints-tolerations-values.yaml
- contrib/charts/dragonfly/templates/_pod.tpl
Hello,
This pull request addresses a significant issue found in the Helm template for Dragonfly deployment related to the mishandling of 'tolerations' and 'affinity'.
**Problem**:
The problem was that the Helm template incorrectly concatenated values within 'tolerations' and 'affinity', which led to erroneous YAML outputs. Specifically, the rendered YAML for the tolerations would incorrectly join the last toleration and 'affinity', as evidenced by the resulting YAML.
**Change**:
The change primarily involves updating the Helm chart's handling of 'tolerations', 'nodeSelector', and 'affinity' values. The adjustment lies in the removal of the dash (-) in the 'with' statement for each of the three values. The changes are as follows:
```yaml
{{- with .Values.tolerations -}}
{{- with …
```
> bug(helm) Fix tolerations and affinity mishandling in Helm template

- src/facade/dragonfly_connection.cc
- src/facade/redis_parser.cc
Fix for https://github.com/dragonflydb/dragonfly/issues/1327.
To avoid the client `write` failing on a protocol error, meaning they never read the protocol error response, this closes only the servers send side of the connection (to send a FIN to the client but not an RST if the client keeps writing) then drains the client socket. So on the client `write` will still succeed, then they will receive the error protocol response.
So in https://github.com/dragonflydb/dragonfly/issues/1327, the client now receives `panic: Protocol error: invalid multibulk length` rather than `panic: write tcp 127.0.0.1:42780->127.0.0.1:6379: write: connection reset by peer`.
> fix: drain the connection socket on a protocol error

- src/server/engine_shard_set.cc
- src/server/transaction.cc
- src/server/transaction.h
- tests/dragonfly/generic_test.py
Fixes the long hunted blpop bug
> fix: Don't remove non-concluding tx from queue on ooo runs

- patches/lua-v5.4.4.patch
- src/core/dash_internal.h
- src/core/detail/bitpacking.cc
- src/core/sse_port.h
> feat: add s390x architecture support

- .github/workflows/docker-weekly.yml
This commit updates the weekly docker build to use `dragonfly-weekly`
image tag so that we get better separation. We also now push these
images with the github sha commit tags. We also update `latest` as
these get pushed.
> feat(CI): Update weekly build image name to be `dragonfly-weekly`

- .github/workflows/reusable-container-workflow.yaml
Currently, During docker release we don't actually build the alpine release but the new docker run test ends up trying to run it and fails. This adds the same toggle that we use for build to prevent the test step.
> fix(docker-release): Run Docker test only if image is built

- tools/cluster_mgr.py
Now this management script can:
* Create a cluster (before this PR)
* Print an existing cluster configuration
* Shutdown an existing cluster
* Move slots between cluster nodes
To support connecting to a cluster (for all new functions), I had to change the way admin ports are defined. Instead of having the user (optionally) specify the first port, they are hard-coded to be the regular port + 10,000. This is done because we can't detect the admin port based for an existing cluster (like via `CLUSTER SHARDS`).
> test(cluster): Extend cluster_mgr.py

- tests/dragonfly/requirements.txt
Add numpy to regtests dependencies
> fix: add numpy to regtests (needed for knn)

- src/server/db_slice.cc
- src/server/db_slice.h
- src/server/generic_family_test.cc
- src/server/main_service.cc
- src/server/main_service.h
- src/server/server_family.cc
- tests/dragonfly/snapshot_test.py
This PR adds `loading` and `rdb_changes_since_last_save` fields to `INFO PERSISTENCE` command. 
This PR addresses the issue #1408
> feat(server): Add missing fields to INFO PERSISTENCE command (#1408)

- README.md
- README.zh-CN.md
- src/server/dfly_main.cc
- src/server/main_service.cc
- tests/dragonfly/pymemcached_test.py
The product is called Memcache**D**. Noticed this when writing docs
> fix: rename memcache to memcacheD

- tests/dragonfly/conftest.py
This PR is a temporary solution for clients that are not properly removed from the connection pool triggering an active client assertion during dragonfly instance shutdown
> fix: failing assertion on snapshot regression tests when dbfly instance shuts down

- src/server/json_family.cc
- src/server/json_family_test.cc
Fixes #1456 
There is a special optimization for root level set that doesn't parse the path. It already checks both "." and "$". This is why it failed only for get commands
> fix: support json v1 dot path

- tools/packaging/debian/rules
This PR adds relevant Build Options to retain debug symbols.
After this:
Also, With this the deb package size grew from 3 MB to 9 MB,
> feat(debian): retain debug symbols in deb package

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/server/dflycmd.cc
- src/server/dflycmd.h
- src/server/server_family.cc
> fix: avoid using main_listener when migrating connections

- CONTRIBUTING.md
Update `contributing.md` to contain information about our code guidelines
> docs: update contributing.md with style guidelines

- tests/dragonfly/replication_test.py
The seeding phase ended too fast in release mode, so we couldn't verify the lag info is working.
> fix: Increase the duration of the seeding in test_replication_info.

- src/server/cluster/cluster_family.cc
- src/server/cluster/cluster_family.h
- src/server/cluster/cluster_family_test.cc
- src/server/replica.cc
- tests/dragonfly/cluster_test.py
This fixes potential data diffs between master and replica upon slot moving
Fixes #1320
> feat(cluster): Send flush slots cmd from masters to replicas.

- tests/dragonfly/snapshot_test.py
The test case for checking is_loading == 1 is inherently racy because the client can connect at any time before or after the dragonfly instance loads the snapshot.
> fix(regression): remove test case for info persistence

- tests/dragonfly/server_family_test.py
Disable this test because we experimentally allow eval in exec (and this test now works), yet there are very few safety checks and its kind of a hotfix. There is another tests already that asserts this behaviour in eval_test.py, so lets skip this one for now
> fix: disable prohibited eval in multi test

- src/server/dfly_main.cc
> fix: avoid crashing dragonfly on parsing error of cgroups config

- src/server/engine_shard_set.cc
- src/server/list_family.cc
- src/server/transaction.cc
- src/server/transaction.h
In addition, add more states to tx local_mask to allow easier debugging. Finally, add check-fail to verify tx invariants in order to prevent reaching errorneous states that are nearly impossible to analyze.
> chore: refresh helio

- src/server/dfly_main.cc
This PR fixes a small issue with slashes when printing log directories at startup. 
Specifically, the following demonstrates the issue:
```
./dragonfly --log_dir=/tmp/something 
output:
/tmp/somethingdragonfly.* 
```
> fix: add missing slash on startup for certain log_dir paths

- src/server/transaction.cc
- src/server/zset_family.cc
- src/server/zset_family_test.cc
Fixes #1442
Behaviour after this fix : 
```shell
127.0.0.1:6379> zunion 0 key
(error) ERR syntax error
127.0.0.1:6379> zunionstore out 0  aggregate
(error) ERR syntax error
```
> fix: zunion and zunionstore zero numkeys bug

- tests/dragonfly/cluster_test.py
The issue was that, sometimes, the ID generated for one of the nodes contained the slot ID that was used in the test (either 5259 or 5260). This caused the test to replace the "slot" part of the id, which in turn caused the node to think that it no longer owns any slot.
> Fix regression test failures.

- src/server/stream_family.cc
- src/server/stream_family.h
- src/server/stream_family_test.cc
- src/server/transaction.cc
XREADGROUP lets consumers read entries from streams. This PR implements the `XREADGROUP` command.
Fixes #1433
> feat(stream): add support for xreadgroup command

- src/CMakeLists.txt
- src/core/json_test.cc
- src/server/cluster/cluster_config.cc
- src/server/json_family.cc
The next version of jsoncons includes a few bug fixes and performance enhancements
Moreover, it contains the fix that allows the jsoncons to use mimalloc allocator instead of the standard allocator.
> chore: update jsoncons dependency

- src/server/dflycmd.cc
- src/server/dflycmd.h
- src/server/journal/journal.cc
- src/server/journal/journal.h
- src/server/journal/journal_slice.cc
- src/server/journal/journal_slice.h
1. We have not worked on it for many months
2. It's not on the short term roadmap
3. It complicates the code around the replication.
> chore: disable persistent journaling feature

- src/core/compact_object.cc
- src/server/zset_family.cc
- src/server/zset_family.h
Next step before pulling out "zset*" functionality into our own class.
No functional changes are done.
> chore: eliminate futher robj references in zset_family code

- src/server/CMakeLists.txt
- src/server/main_service.h
- src/server/protocol_client.cc
- src/server/protocol_client.h
- src/server/replica.cc
- src/server/replica.h
Commit #1: Split I/O logic away
Commit #2: Split shard replication into a new class.
> Refactor replication code

- .github/workflows/ci.yml
- src/server/main_service.cc
- src/server/multi_test.cc
* The bug - if all commands inside multi trasaction are eval commands and global scripts mode is on, we did ignored the trasaction and run each eval separately.
* The fix - run all evals under multi inside the global lock
> bug(server): multi exec eval

- tests/dragonfly/replication_test.py
The test fails sometimes when starting master after killing it. The reason for this is that OS did not release port untill we started master again.
The fix - adding sleep after kill
After we will have randomly selected ports on pytest we can remove this sleep.
> Fix(regression test): test_tls_replication

- src/server/server_family.cc
Command metrics are now compatible with redis metrics.
Adding lables to command stats.
This change also fixes the failing test replication_test.py::test_replication_info
> Fix(server): command duration metrics

- src/server/dfly_main.cc
Replace std::vector with absl::InlinedVector, to save an allocation on the not so hot path @chakaz :eyes:
> chore(VersionMonitor): replace std::vector with absl::InlinedVector

- src/server/dfly_main.cc
1.  Add RAII for cleaning up `ssl_ctx` within version monitor
2. Refactor some small parts of  `Run()` to make it more readable
> refactor(VersionMonitor): improve readability and add proper RAII to ssl_ctx

- src/server/protocol_client.cc
- src/server/protocol_client.h
- src/server/server_family.cc
- tests/dragonfly/__init__.py
- tests/dragonfly/tls_conf_test.py
This changes our authentication policy when using TLS:
1. If TLS is enabled, some authentication must be used.
2. Password authentication is allowed for client authentication.
> sec: Adjust flag validation for TLS.

- tests/dragonfly/replication_test.py
The bug: the test checks the replication using role command on replica The replica updates the status to full sync when starting the full sync flow, but actually the master did not start snapshoting yet. The fix: check the status using role command on master, because master updates the status only after snapshoting started.
> Fix(regression test): fix test_flushall_in_full_sync

- src/server/transaction.cc
- src/server/transaction.h
With this change, an attempt to execute a hop will short circuit (i.e. run the callback inline instead of a async hop) if it can (i.e. it should run in a single shard which happens to be the current shard).
This change has to potential to reduce latency of execution commands, and can be further utilized in the future for multi/eval if we'll run all commands on the target shard (if it's just one).
> opt(server): Short-circuit ExecuteAsync().

- src/core/CMakeLists.txt
- src/core/bptree_set.h
- src/core/bptree_set_test.cc
- src/core/detail/bptree_internal.h
- src/server/transaction.cc
The motivation to have our own b-tree to repalce zskiplist is shown by #1567 Based on the results we should greatly reduce the memory overhead per item when using a modern b-tree.
Currently the functionality supports Insert method only to reduce the review complexity. The design decisions behind the data structure are described in src/core/detail/btree_internal.h
> feat: very minimal code that adds b-tree to the codebase

- src/server/cluster/cluster_config.cc
- src/server/cluster/cluster_config.h
- src/server/cluster/cluster_family.cc
- src/server/cluster/cluster_family.h
- src/server/db_slice.cc
- src/server/engine_shard_set.h
- src/server/generic_family.cc
- src/server/main_service.cc
- src/server/server_family.cc
- src/server/server_family.h
- src/server/table.cc
This PR would have been 1 line change instead of 11 files, but it required some plumbing and refactoring:
* Now ClusterConfig is aware of emulated cluster mode
* As a result, this API was moved from ClusterFamily
* And so was the flag & its parsing
* ClusterFamily doesn't need is_emulated_cluster_ member
* ServerFamily no longer needs ClusterFamily* member (because the API is static)
* I also changed `ClusterConfig::IsClusterEnabled()` to `ClusterConfig::IsEnabled()` to be shorter
> feat(server): Use hashtags for sharding in emulated cluster mode.

- src/server/multi_test.cc
- src/server/transaction.cc
- src/server/transaction.h
The bug: when multi transaction run OOO we removed it from trasaction queue, causing non atomic execution.
The fix: When we run multi transaction unless it is the head in txq we remove it inside unlock multi from txq.
> bug(server): multi atomicity fix

- src/server/bitops_family.cc
- src/server/container_utils.cc
- src/server/generic_family.cc
- src/server/hll_family.cc
- src/server/list_family.cc
- src/server/set_family.cc
- src/server/stream_family.cc
- src/server/transaction.cc
- src/server/transaction.h
There is no utility function to close a transaction, so all usages had to define an empty callback and call Execute manually. No functional changes
> fix: add Transaction::Conclude

- src/core/bptree_set.h
- src/core/bptree_set_test.cc
- src/core/detail/bptree_internal.h
Implemented  BPTree::Delete method.
> Add delete functionality to the b+tree

- src/server/container_utils.cc
- src/server/container_utils.h
I refactored RunCbOnFirstNonEmptyBlocking a little to be more readable and easier to understand
1. I've explicitly split the callback invocation into expiry/non expiry path (I remember Roman once asked for this). The code flow is linear now and easier to grasp
2. Added some high level comments for logic
3. Some small changes
Shouldn't include any functional changes
> fix: refactor RunCbOnFirstNonEmptyBlocking

- src/server/multi_command_squasher.cc
- src/server/multi_command_squasher.h
- src/server/transaction.cc
- src/server/transaction.h
This PR changes the locking mechanism of non atomic squashing
Squashed sequences consists of batches that are executed in parallel on multiple shards.
Previously, all keys of a batch were collected and locked ahead of executing the full batch on multiple shards (akin to running a transaction with those collected keys)
Now, no keys are collected in advance. Instead the commands are just sent to their respective shards where they're executed on separate transactions. We could create a new transaction for every run, but I just create a single non-atomic multi transaction for every shard.
This new locking mechanism will be used for parallelizing pipelines.
> feat: Remove batch locks from non-atomic squashing

- src/server/server_family.cc
- tests/dragonfly/snapshot_test.py
Introducing a new flag --snapshot_cron, enabling users to use cronjob expressions to time snapshot saves.
Cronjob expressions are parsed using a third party library croncpp. 
This PR continues PR #1599, updating cron expressions to crontab style, up to minutes resolution instead of seconds.
> feat: support for cron expressions based snapshot (update).

- src/server/transaction.cc
- src/server/transaction.h
We perform a redundant hop for blocking transactions that didn't expire. It should be removed because it doesn't do anything useful
Fixes #1405
> fix: remove empty hop for non-expiring transactions

- src/core/bptree_set.h
- src/core/bptree_set_test.cc
- src/core/detail/bptree_internal.h
Also add a benchmark test that shows 2-3 times better performance for Find vs redis zslGetRank when number of items grows.
For Insert/Delete I expect the differrence be even bigger.
```
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
BM_FindRandomBPTree/1024         56000 ns        55996 ns        75079
BM_FindRandomBPTree/65536      9406738 ns      9406552 ns          450
BM_FindRandomBPTree/1048576  390559398 ns    390539398 ns           11
BM_FindRandomZSL/1024            87991 ns        87989 ns        49196
BM_FindRandomZSL/65536        17917190 ns     17916618 ns          196
BM_FindRandomZSL/1048576    1343231616 ns   1343130709 ns            3
```
> feat: Fix rank for delete operations

- src/server/server_family.cc
Snapshot caused endless save loop on exit due to fiber not finishing. The fix is to add a `break` to the `while` loop after `schedule_done_` has notified.
Solves #1636.
> hotfix: snapshot endless loop on exit.

- src/server/engine_shard_set.h
- src/server/multi_command_squasher.cc
This will avoid running on all threads every time
Didn't benchmark yet how much it helps squashed pipelines in the MVP, but I'm sure it won't make them slower 
On a small number of shards an evenly distributed pipeline runs on all shards on every single batch, but exceptions are possible
> fix: Add selective non-atomic squash dispatch

- src/facade/facade_types.h
- src/facade/reply_builder.cc
- src/facade/reply_builder.h
- src/facade/reply_capture.cc
- src/facade/reply_capture.h
- src/server/command_registry.cc
- src/server/command_registry.h
- src/server/main_service.cc
- src/server/main_service.h
Its an anti-pattern to use a mutable ConnectionContext pointer for both connection state queries and error replies. As a result we have a lot of excessive mutability and we pass it everywhere around. This might have not been an issue so far, but it becomes hard to manage with squashed command execution.
Its needed for squashed pipeline execution. Pipeline commands can make state changes (context & global), so command verification needs to happen immediately before execution. With squashed execution, this verification will take place from multiple threads -> possible trouble if not carefully done
> feat: Use const ConnectionContext in VerifyCommand

- src/core/search/compressed_sorted_set.cc
- src/core/search/compressed_sorted_set.h
- src/core/search/compressed_sorted_set_test.cc
- src/core/search/indices.cc
- src/core/search/indices.h
- src/core/search/search.cc
1. Use the newly created compressed sorted set type
2. Add back insertion optimization to compressed sorted set instead of separate back inserter
> feat: Use compressed sorted set for search

- src/core/CMakeLists.txt
- src/core/score_map.cc
- src/core/score_map.h
- src/core/score_map_test.cc
This map should serve as a replacement for dict that currently is used internally by the SortedMap. Specifically, it maps sds strings to scores to provide a reverse mapping. It should be more efficient in memory and CPU - requires a single allocation to store both the key and the value, in contrast to dict that needs two allocations.
In addition, it also reduces the object size needed for the zset score set: zsl stores both the sds pointer and its double, i.e. requires 16 bytes not including the metadata. By passing to bptree_set the internal ScoreMap objects that are allocated by ScoreMap::AddOrUpdate we can just store 8-byte pointers, not including the bptree metadata.
> feat: add ScoreMap that maps sds strings to doubles

- src/core/bptree_set.h
- src/core/bptree_set_test.cc
- src/core/detail/bptree_internal.h
Add iterate by rank functions.
For that we introduce BPTreePath::Next() and BPTreePath::Prev() functions that allow iterating over immutable tree.
> chore: Iterate over bptree_set.

- src/core/bptree_set.h
- src/core/bptree_set_test.cc
- src/core/detail/bptree_internal.h
Follows #1654 .
Also, fix Deletion bug inside DigRight function.
DeleteRangeByRank is implemented naively but it should be still
faster than zsl given that zsl needs to deallocate metadata per each item deleted.
> feat: Add LowerBound and DeleteRangeByRank

- src/core/bptree_set.h
- src/core/bptree_set_test.cc
- src/core/detail/bptree_internal.h
Implemented `DeleteRange(KeyT first, KeyT last, std::function<void(KeyT)> cb,
bool inclusive_first, bool inclusive_last)`
method. We need inclusive parameters because with doubles it harder to reduce
the query to a standard open-closed range.
> feat: Add DeleteByScore method

- src/server/command_registry.cc
- src/server/command_registry.h
- src/server/main_service.cc
- src/server/main_service.h
- src/server/multi_command_squasher.cc
- src/server/multi_command_squasher.h
- src/server/multi_test.cc
This PR:
1. Cleans up command verification a little bit and adds more comments about the differences
2. Makes more check functions accept only `tail arguments` - argument lists without the command name upfront, makes it easier to call them with stored commands
3. Enables verification for squashing. This makes it possible to verify commands while squashing instead of doing it ahead. This will allow a parallelized pipeline to be executed without verifying each command separately and breaking squashing chains
> feat: Refactor command verification before execution

- src/core/bptree_set_test.cc
- src/core/compact_object.h
- src/core/sorted_map.cc
- src/core/sorted_map.h
- src/core/sorted_map_test.cc
- src/server/zset_family_test.cc
1. intoduce variant of Redis and Dragonfly implementation and wrap each operation with a dedicated dispatcher operator. The dragonfly implementation path is a noop and not implemented.
2. Introduce a very basic sorted_map_test around Add and move the unrelated old test from sorted_map_test to bptree_set_test.
> chore: Refactor SortedMap

- src/server/dfly_main.cc
Fix the improper log to update on an older version.
I  hardcode tested this locally with with the following:
1. remote = 1.8.0 curr = 1.7.0
2. remote = 1.8.0 curr = 1.8.0
3. remote = 1.8.0 curr = 1.8.1
> fix(VersionMonitor): request to update on older version

- .github/workflows/ci.yml
- src/server/cluster/cluster_family_test.cc
- src/server/multi_test.cc
- src/server/test_utils.cc
- src/server/test_utils.h
1. Add test utility class that will add suspension to transaction execution.
2. Add test for locked keys in transaction
> test(server): test transaction locked keys

- src/server/main_service.cc
- src/server/main_service.h
Also, fix unreliable time measurement for http latency metric.
> chore: refactor a common code into a function

- .github/workflows/daily-builds.yml
Daily builds are currently failing because of bullmq tests. This PR comments out the bullmq test steps.
> fix(daily-builds): temporarily comment out bullmq tests

- src/server/main_service.cc
> opt(server): Run Lua on remote thread only if it's a different thread

- src/server/command_registry.cc
- src/server/command_registry.h
- src/server/main_service.cc
- src/server/main_service.h
- src/server/server_family.cc
- src/server/server_family.h
- src/server/server_state.h
cmdstats_map were on the hotpath and are needed only to update the command stats. Instead, I introduced the stats withing the CommandId itself that we lookup anyways. Also, it removes fragile dependency on naked command name char* pointers.
> chore: get rid of cmdstats_map

- src/core/sorted_map.cc
No functional changes are made.
> chore: move RdImpl functions together

- contrib/charts/dragonfly/ci/tls-values.golden.yaml
- contrib/charts/dragonfly/ci/tls-values.yaml
One of the install test seems to fail, This PR tries to
fix that by also including password with tls test
> fix(ci): use auth mechanism with tls helm values

- src/server/CMakeLists.txt
- src/server/acl/user.cc
- src/server/acl/user.h
- src/server/acl/user_registry.cc
- src/server/acl/user_registry.h
- src/server/acl/user_registry_test.cc
This PR implements the basic functionality required to build the ACL commands. 
1. This is a prototype, additional functionality will be added on separate PR's
2. I decided against fine grain locking for Users since 99.9% of the time we will only acquiring ReadLocks.  The impact on the performance of this on the hot path should be negligible.
3. I added a very simple Unit test which I am planning on expanding on separate PR's. Since, some things might change, I don't want to strand myself changing the unit tests over and over again
> chore: implemente User and UserRegistry classes

- src/server/acl/user.cc
- src/server/acl/user.h
The hash function was trimming the hash state to 32 bits, so it could be trivially brute forced after 4 billion attempts. XXH3 is also not a cryptographic hash which means it's generally not safe to use in this context.
SHA256 is safe and is also what Redis are using, it looks as if they're also allowing to set the password hash directly. So let's use this instead.
> security: Fix the password hashing in UserRegistry.

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/ok_main.cc
- src/facade/reply_builder.cc
- src/facade/reply_builder.h
- src/facade/service_interface.h
- src/server/main_service.cc
- src/server/main_service.h
- tests/dragonfly/connection_test.py
1. Adds DispatchManyCommands to Service interface that possibly can squash command execution. It uses a non-atomic transaction underneath to execute commands on top of it
2. Makes the context detect cases when the dispatch queue is filled with just commands that can be executed with DispatchManyCommands in one go
I've also run a few benchmarks to test the new feature. Before, pipelining from a single connection had really bad performance. 
1M LPUSH commands on 1k keys, evenly distributed, threshold 100, 32 sized batches, 
executed with `redis-cli --pipe < cmds`
```
Regular (8t): 12.2s
Regular (4t): 9s
Redis: 1.1s
Squashing (4t): 1.1s
Squashing (8t): 0.9s
```
For 8 threads is more than a tenfold improvement!
> feat: Pipeline squashing

- src/core/search/base.h
- src/core/search/search.cc
- src/core/search/search.h
- src/core/search/search_test.cc
- src/server/search/doc_accessors.cc
- src/server/search/doc_accessors.h
- src/server/search/doc_index.cc
- src/server/search/search_family.cc
- src/server/search/search_family_test.cc
- tests/dragonfly/search_test.py
This PR makes it possible to reference nested json fields in search documents and use short name alises (see tests)
> feat: json paths in search

- src/core/bptree_set.h
- src/core/bptree_set_test.cc
- src/core/detail/bptree_internal.h
- src/core/score_map.h
- src/core/sorted_map.cc
- src/core/sorted_map.h
- src/core/sorted_map_test.cc
Specifically add comparison operator that supports lex mode, score mode and infinity abstractions for both modes.
Also, introduce LEQ/GEQ range queries for bptree_set.
> feat: introduce partial DfImpl implementation for sorted_map

- src/facade/command_id.h
- src/facade/facade.cc
- src/server/acl/acl_commands_def.h
- src/server/acl/user.cc
- src/server/acl/user.h
- src/server/acl/user_registry.cc
- src/server/acl/user_registry.h
- src/server/acl/user_registry_test.cc
- src/server/bitops_family.cc
- src/server/blocking_controller_test.cc
- src/server/cluster/cluster_family.cc
- src/server/command_registry.cc
- src/server/command_registry.h
- src/server/generic_family.cc
- src/server/hll_family.cc
- src/server/hset_family.cc
- src/server/json_family.cc
- src/server/list_family.cc
- src/server/main_service.cc
- src/server/search/search_family.cc
- src/server/server_family.cc
- src/server/set_family.cc
- src/server/stream_family.cc
- src/server/string_family.cc
- src/server/test_utils.cc
- src/server/zset_family.cc
1. Add acl categories to each command
2. Extend `facade::CommandId` to include acl category
3. Add dragonfly extensions to acl categories for modules like search, json etc (since modules in redis do not have acl categories by default but in dragonfly these are not implemented as modules)
> chore: add acl categories to all commands

- src/server/server_family.cc
The current `DoSave()` became a 200+ loc monster that is not only difficult to extend but also to read. I noticed this when I wanted to extend it for search serialization. 
Should not include any functional changes
> chore: clean up save

- tools/defrag_db.py
> tools: Hash defrag script

- tests/dragonfly/replication_test.py
- tests/dragonfly/sentinel_test.py
- tests/dragonfly/snapshot_test.py
- tests/pytest.ini
Marked every test running over 10s as 'slow'.
All the tests together - 10:13, only the fast tests - 2:40.
> chore: Mark slow pytests as 'slow' so they can be excluded.

- src/server/dfly_main.cc
Closes #1683.
---
Background: In k8s, the memory/CPU cgroups which are reported by `/proc/self/cgroup` do not exist, i.e., the path `/sys/fs/cgroup/<resource>/<k8s cgroup>` doesn't exist. This causes Dragonfly to not read container limits at all, hence missing potential limits set by the user.
Fix: Begin by first reading `/sys/fs/cgroup/<resource>/<limit>`, which, in words, means "read the resource limits of the system". Later the path `/sys/fs/cgroup/<resource>/<specific group>` is read, updating the limit if needed.
> fix: Correctly read container limits when running under k8s

- src/server/acl/acl_family.cc
- src/server/acl/acl_family.h
- src/server/main_service.cc
- tests/dragonfly/acl_family_test.py
1. Fixed broken `ACL` command (previously df crashed)
2. Fixed broken `ACL LIST STR` (previously passed, now prints an argument error)
3. Added tests
> fix(AclFamily): commands parsing and error handling

- src/core/overloaded.h
- src/server/acl/acl_commands_def.h
- src/server/acl/acl_family.cc
- src/server/acl/acl_family.h
- tests/dragonfly/acl_family_test.py
* Add `ACL SETUSER` command
* Add tests
> feat(AclFamily): add acl setuser command

- src/facade/CMakeLists.txt
- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/resp_expr.cc
- src/facade/resp_expr.h
- src/server/dflycmd.cc
- src/server/rdb_load.cc
- src/server/rdb_load.h
- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/replica.cc
- src/server/search/doc_index.cc
- src/server/search/doc_index.h
- src/server/search/search_family.cc
- src/server/server_family.cc
- tests/dragonfly/search_test.py
This PR adds persistence for search indices
Their definitions are stored in plain string form in AUX fields
> feat: search index persistence

- src/server/acl/acl_commands_def.h
- src/server/acl/acl_family.cc
The loop had several problems - it's using `step` to access the strings, but the bitfields is not contiguous (there's a jump between `SCRIPTING` and `FT_SEARCH`), and it has two off-by-ones (`KEYSPACE` and `JSON` are never checked for).
> fix(ACL): Fix the iteration over categories loop in AclToString

- src/server/search/doc_index.cc
- src/server/search/doc_index.h
- src/server/server_family.cc
Now indices are built separately after they've been read.
1. Instead of splitting the Init/Rebuild steps, they could've been collected as strings and build fully after loading. But it would've made the dfs loading / search code more complex. Now they're created & validated & stored, but not populated with documents. 
2. Either way we'll need some kind of post-load controller. Alternatively we store the index definitions in all shards and all loading steps are fully independent
3. Index construction will be async at some point either way, so it will be enough just to notify the "async index creator" after loading that it can run
For now I hope this fix suffices 👀
> fix: fix index loading

- src/server/protocol_client.cc
If an empty buffer is passed to the socket Recv function - it returns error 103. Even if we returned success, this would lead to the endless loop since the parser requires more data to parse the load.
Fixes #1680
> fix: the bug where iobuf should be enlarged during the replication

- src/server/db_slice.cc
- src/server/db_slice.h
- src/server/main_service.cc
- src/server/multi_test.cc
- src/server/string_family_test.cc
- src/server/test_utils.cc
- src/server/test_utils.h
1. remove validation to allow multi eval only in global script mode
2. send error if there is a mode conflict when running eval inside multi
3. change uniqe_keys_ to string set
> feat(server): support multi eval in lock ahead mode

- .github/workflows/ci.yml
Also, add sccache debug log in hope to understand
why we get 0 hits sometimes.
> fix: extend CI running time

- src/core/compact_object.cc
- src/core/compact_object.h
- src/core/compact_object_test.cc
- src/core/string_map.cc
- src/core/string_map.h
Fixes a bug from the hash defrag PR: Successful re-allocations are not reported back. 
Should we count a hash re-allocation as one (currently doing so) or also count every internal re-allocation (each StringMap key, etc.)  ?
> fix: fix defrag stats

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_listener.cc
- src/facade/dragonfly_listener.h
- src/server/config_registry.cc
- src/server/config_registry.h
- src/server/dfly_main.cc
- src/server/server_family.cc
- tests/dragonfly/config_test.py
Close #1496.
Also, make `CONFIG GET` use config_registry so it's easier to add flags.
> feat(server): Support limiting the number of open connections.

- src/server/dragonfly_test.cc
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
> fix: Run defrag on dbs > 0 as well

- src/server/rdb_load.cc
While loading rdb snapshot, if oom is reached a bad alloc exception is thrown. Now we catch it and write warning to log.
fixes #1708
> fix(server): rdb loader catch bad alloc

- src/facade/error.h
- src/facade/facade.cc
- src/server/config_registry.cc
- src/server/config_registry.h
- src/server/main_service.cc
- src/server/server_family.cc
- src/server/server_family.cc.orig
- tests/dragonfly/management_test.py
The command returns all the matched arguments and their current values. In addition, this PR adds mutability semantics to each config - whether it can be changed at runtime.
Fixes #1700
> feat: implement CONFIG GET command

- src/core/search/search.cc
- src/core/search/search.h
- src/core/search/search_test.cc
- src/server/search/doc_accessors.cc
- src/server/search/doc_accessors.h
- src/server/search/doc_index.cc
- src/server/search/doc_index.h
- src/server/search/search_family.cc
- src/server/search/search_family_test.cc
This PR adds the `RETURN` and `NOCONTENT` options to FT.Search queries. Most queries don't all the fields to be returned and only ask for specific ones (or even ids only). Sometimes a more complex path needs to be looked up and returned with a shorter name (alias/named return).
> feat(search): named return values

- src/server/command_registry.h
the bug: when command is renamed we show the rename command in command stats
the fix: print the origin command name in command stats
fixes #1756
> bug(server): command stats show origin command name

- src/server/journal/serializer.cc
- src/server/replica.cc
Gracefully handle two small `CHECK`s that can trigger sometimes on malformed replication data.
> fix(replication): Handle errors instead of crashing.

- CMakeLists.txt
- Makefile
Change the Makefile to configure the compile to produce code
compatible with core2 architecture for x86_64 systems.
Plus specify precise CPU extensions that we use in the code.
Partly addresses https://github.com/dragonflydb/dragonfly/issues/1519
Before the change we relied on default helio logic that configured
the build to run on sandybridge for x86_64.
This PR overrides x86_64 settings to much older core2 processor.
Also, we remove an unneeded cmake include.
> fix: make Dragonfly compatible with older systems

- .github/workflows/bullmq-tests.yml
- .github/workflows/daily-builds.yml
Also add fedora linux to daily build matrix.
> chore: split daily build and bullmq tests

- src/server/CMakeLists.txt
- src/server/detail/save_stages_controller.cc
- src/server/detail/save_stages_controller.h
- src/server/server_family.cc
- tests/dragonfly/__init__.py
1. No logic was changed during refactoring.
2. Flipped the flag to run regression tests for now own with zset_tree=on
> chore: move rdb save related logic into auxillary file

- tools/docker/Dockerfile.alpine-dev
- tools/docker/Dockerfile.alpine-prod.wip
- tools/docker/Dockerfile.ubuntu-dev
- tools/docker/Dockerfile.ubuntu-prod
- Beautified the Dockerfile a little bit
- Running the container as the `dfly` user resolves write permission issues on volumes provisioned on the Container-as-a-service provider, [fly.io](https://fly.io). If the container runs as root (which is the default if no user is specified), I'm unable to write files to an external `/data` volume. Additionally - it's also considered as best practice to execute a container with a user account that has lower privileges than root
---
I think it can solve this discussion: https://github.com/dragonflydb/dragonfly/discussions/1527
> fix: run container as `dfly` user

- src/server/acl/acl_family.cc
- src/server/acl/acl_family.h
- src/server/acl/user_registry.cc
- src/server/acl/user_registry.h
- src/server/acl/validator.cc
- src/server/acl/validator.h
- src/server/conn_context.h
- src/server/dfly_main.cc
- src/server/main_service.cc
- src/server/main_service.h
- src/server/server_family.cc
Currently df acquires a `ReadLock` over the `UserRegistry` to validate ACL categories, therefore any changes to the `UserRegistry` are immediately available when promt. This is not very performant for the hot path since the atomic increments on the lock force the cores to synchronize (caches + penalty of accessing memory that is outside of the core for NUMA).
This behavior is replaced by deep copying the acl categories in the `ConnectionContext`. When there is an update to that user's ACL categories, it is streamlined via the proactor to the already opened connections.
Therefore this PR:
* removes locking the registry when Validating users
* deep copies the acl categories in the connection context
* streamline updates to the acl categories via the proactor pool
> chore: remove locks from acl validation in the hot path

- src/facade/dragonfly_connection.cc
- src/facade/memcache_parser.cc
- src/facade/redis_parser.cc
- src/facade/redis_parser.h
- src/facade/reply_builder_test.cc
- src/server/protocol_client.cc
- src/server/test_utils.cc
Introduced `max_multi_bulk_len` as a max limit when parsing RESP arrays
as well as `max_client_iobuf_len` as a max limit on the iobuf used to
read from a socket.
> feat: introduce configurable flags for I/O limits

- .github/workflows/bullmq-tests.yml
- .github/workflows/daily-builds.yml
Also, use GITHUB_WORKSPACE due to https://github.com/actions/runner/issues/2058
> fix: use cd instead of working-directory which does not work

- src/server/search/doc_accessors.cc
- tests/dragonfly/search_test.py
This is actually RedisSearch's default behaviour
> fix(search): return whole json documents

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/server/acl/acl_family.cc
- src/server/acl/user_registry.cc
- src/server/acl/user_registry.h
- tests/dragonfly/acl_family_test.py
There was a bug on updates of the acl categories when squashing was used. Basically, the parent context could be accessed in parallel by the "stub" contexts causing a dreaded data race on the update. 
This is fixed by adding a new `AclUpdateMessage` at the front of the dispatch queue of the connection.
> fix(AclFamily): stream acl updates via dispatch queue in connection

- src/server/acl/acl_family.cc
- src/server/acl/acl_family.h
- src/server/main_service.cc
- tests/dragonfly/acl_family_test.py
> feat(AclFamily): add acl whoami command

- src/server/db_slice.cc
- src/server/main_service.cc
- src/server/rdb_load.cc
No memory limit on loading from file or replicating.
When loading a snapshot created by the same server configuration (memory and
number of shards) we will create a different dash table segment directory tree, because the
tree shape is related to the order of entries insertion. Therefore when loading data from
snapshot or from replication the conservative memory checks might fail as the new tree might
have more segments. Because we dont want to fail loading a snapshot from the same server
configuration we disable this checks on loading and replication.
fixes #1708
> fix(server): Dont apply memory limit when loading/replicating

- src/server/acl/acl_family.cc
- src/server/acl/user.cc
- src/server/acl/user.h
- src/server/acl/user_registry.cc
- src/server/acl/user_registry_test.cc
- tests/dragonfly/acl_family_test.py
We had back previously for interleaved updates to categories via `ACL SETUSER` command.
An example is:
`ACL SETUSER kostas -@SET +@SET` which would not result to `kostas` having the `SET` category enabled (because internally we would first update the `+` and then the `-` which would mess with the ordering. 
This PR fixes this. 
Later on next week I will add uniqueness to SETUSER, that is, the user won't be able to write redundant code like `-@SET +@SET`.
> fix(AclFamily): setuser signed interleaved categories updates

- tests/dragonfly/acl_family_test.py
I disable the flaky ACL tests for now because we now run the regression tests are part of the release build. This will interfere with our release schedule so I am pushing a temporary fix for now.
> chore(AclFamily): disable flaky tests

- src/core/search/search.cc
- src/core/search/search.h
- src/server/search/doc_index.cc
- src/server/search/doc_index.h
- src/server/search/search_family.cc
- src/server/search/search_family.h
- src/server/search/search_family_test.cc
Adds FT.PROFILE commands that runs the search query with profiling to see a detailed execution plan with timings. Does not comply with RS's FtProfile.
Example output for a simple query. First, it prints general results, then the detailed execution plan for each shard
> feat(search): FT.PROFILE

- src/core/dense_set.h
- src/core/external_alloc.cc
- src/core/json_object.h
- src/facade/ok_main.cc
- src/redis/object.h
- src/server/CMakeLists.txt
- src/server/dfly_main.cc
- src/server/journal/journal_slice.h
- src/server/list_family.cc
- src/server/main_service.cc
- src/server/server_family.cc
- src/server/string_family.cc
- src/server/tiered_storage.h
1. Do not use IOUring on non-linux systems.
2. Improve compatibility of the code for non-linux systems.
3. pull helio
> chore: dragonfly compiles on FreeBSD

- src/CMakeLists.txt
- src/facade/reply_builder_test.cc
Add double to string coversion tests.
Patch the library to avoid using locale - because freebsd c++ lib does not have this symbol.
changing this function: https://github.com/google/double-conversion/blob/master/double-conversion/string-to-double.cc#L55
> chore: Update double-conversion library

- src/core/search/base.h
- src/core/search/lexer.lex
- src/core/search/parser.y
- src/core/search/query_driver.cc
- src/core/search/query_driver.h
- src/core/search/scanner.h
- src/core/search/search.cc
- src/core/search/search.h
- src/core/search/search_parser_test.cc
- src/core/search/search_test.cc
- src/core/search/vector.cc
- src/core/search/vector.h
- src/server/search/doc_accessors.cc
- src/server/search/doc_accessors.h
- src/server/search/doc_index.cc
- src/server/search/doc_index.h
- src/server/search/search_family.cc
- tests/dragonfly/search_test.py
This PR makes it possible to use query parameters in search queries
For example `'$name => [KNN $k @pos $vec]' PARAMS name joe k 10 vec \x00\x00`
> feat(search): Query parameters

- src/server/main_service.cc
- tests/dragonfly/http_conf_test.py
CC @Pothulapati @ashotland for awareness.
> Enable authentication for the HTTP interface.

- src/facade/dragonfly_connection.cc
- src/facade/reply_builder.cc
- src/facade/reply_builder.h
1. Add a Yield() call before executing the last command in the async queue when needed.
2. Allow the receive buffer to grow when needed.
3. Improve debugging logs for batching behavior.
The whole 'triggering the bug' process looks like this:
1. We process a larger packet with multiple short commands inside a MULTI segment.
2. We read the commands into a relatively small buffer (size 256)
3. The `ParseRedis` loop reads commands from the first part of the packet and pushes them into the dispatch queue.
4. The dispatch fiber processes all the commands in the dispatch queue quickly and without preemption because it's inside a MULTI block and all commands return immediately. After emptying the queue it calls SetBatchMode(false) which causes a flush of the response buffer after the next command …
> fix(server): Adjust batching behavior to reduce network latency on MULTI blocks

- src/core/string_map.cc
- src/core/string_map.h
- src/server/hset_family.cc
- src/server/hset_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/858
It might possibly fix: https://github.com/dragonflydb/dragonfly/issues/1707
The algorithms that support both encodings (string map and listpack) have been implemented and tested. To use string map requires a larger hset (my tests used 500+ entries)
The random selection algorithms implemented for string map class are the reimplementation of the same algorithms used by Redis' listpack. (therefore same time complexities)
Without this patch:
```
127.0.0.1:6379> HSET coin heads obverse tails reverse edge null
(integer) 3
127.0.0.1:6379> HRANDFIELD coin 3 WITHVALUES
(error) ERR wrong number of arguments for 'hrandfield' command
127.0.0.1:6379> HRANDFIELD coin -1
(error) ERR wrong number of arguments for 'hrandfield' command …
```
> feat (hset): Support arguments (count, withvalues) in HRANDFIELD

- src/server/main_service.cc
- src/server/multi_test.cc
the bug: when returning error on a command in multi tx we do not cleanup the multi cntx
the fix: cleanup the cntx when error is returned
> bug(server): multi cleanup on error

- src/server/stream_family.cc
- src/server/stream_family.h
- src/server/stream_family_test.cc
This PR adds support for `xpending` command. I also created a `StreamCreateNack` function to use test-hookable `GetCurrentTimeMs()` instead of `mstime()`. It gives better control to test stream commands.
Fixes #1161
> feat(stream): add support for xpending command

- src/CMakeLists.txt
- src/core/search/CMakeLists.txt
- src/core/search/indices.cc
- src/core/search/indices.h
- src/core/search/search.cc
- src/core/search/search.h
- src/core/search/search_parser_test.cc
- src/core/search/search_test.cc
- src/server/search/search_family.cc
- tests/dragonfly/search_test.py
> feat(search): HNSW

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
A user reported crash in Connection::GetClientInfo function. When connection just start running, its phase_ variable was not initialized, so a possible "CLIENT LIST" command from another connection could trigger invalid data access when printing phase_. To be on the safe side I also verify that other pointers in the function are set (could also be that we have a similar issue during connection shutdown).
> fix: possible segfault bug

- src/server/server_family.cc
Fixes https://github.com/dragonflydb/controlplane/issues/226
When running on EC2, `AWS::Init()` makes a network call in `AWS::GetConnectionDataFromMetadata` which uses `ProactorBase::me`, so it must run in a proactor
Also pulls in latest helio changes (which includes other S3 fixes)
Tested on EC2
> fix(aws): initialise aws in a proactor

- src/facade/dragonfly_connection.cc
Builds on #1824 
Fixes the dispatch interruption bug
Instead of moving the `async_dispatch` guard I decided to clean the queue later, so that sync dispatch is still not possible. I think its "clearer", but let me know if its confusing
> fix: Reply within async_dispatch block in squashed pipeline

- src/server/detail/save_stages_controller.cc
- src/server/detail/save_stages_controller.h
- src/server/server_family.cc
- src/server/server_family.h
As part of cloud snapshots, looking at starting to remove `aws_` and `IsCloudPath` which are quite hard to maintain and will get harder when adding GCP snapshots as well
This starts to move storage specific logic into `SnapshotStorage` which can then be implemented for either local snapshots with `FileSnapshotStore` or AWS S3 with `AwsS3SnapshotStorage` (can then add `GcpStoreSnapshotStorage` later)
Only added `OpenFile` so far figuring its worth checking this approach is ok before doing too much - if its alright will move `InferLoadFile` and parts of `ServerFamily::Load` too so we can add support for loading snapshots from S3
My C++ is a bit rusty so please correct anything that doesn't look right or isn't idiomatic :)
I'm not sure what the standard practice is for tagging reviewers so …
> feat(snapshot): add snapshot storage

- tests/dragonfly/acl_family_test.py
The issue was that we appended the aclfile name onto the dragonfly binary (path + binary name). This ofc would break
> fix(regression-tests): correct path for acl files

- .github/workflows/ci.yml
This allows sharing of compiled artifacts across PRs, and so speeds up the CI.
> feat(CI): Configure sccache to work with GCS

- src/server/CMakeLists.txt
- src/server/detail/save_stages_controller.cc
- src/server/detail/save_stages_controller.h
- src/server/detail/snapshot_storage.cc
- src/server/detail/snapshot_storage.h
- src/server/server_family.cc
Moves storage specific logic for loading snapshots into `SnapshotStorage` and moves to a new file
* Replaces `InferLoadFile` with `SnapshotStorage::LoadPath`
* Replaces load path logic in `ServerFamily::Load` with `SnapshotStorage::LoadPaths`
* At some point can probably combine though just moving for now rather than doing any refactoring
* Opens snapshot file with `FileSnapshotStorage::OpenReadFile`
Now should be able to add support for loading snapshots from S3 by implementing `AwsS3SnapshotStorage` methods (will do that in another PR)
> feat(snapshot): move load path to snapshot storage

- src/facade/dragonfly_connection.cc
I am not sure about the root cause of this flow but we can definitely avoid a check-fail here.
> Fix a potential crash in OnBreakCb

- src/facade/CMakeLists.txt
- src/facade/dragonfly_listener.cc
- src/facade/tls_error.cc
- src/facade/tls_error.h
- src/server/protocol_client.cc
> fix(tls): User friendly logging of OpenSSL errors

- src/server/detail/snapshot_storage.cc
- src/server/detail/snapshot_storage.h
- src/server/server_family.cc
- src/server/server_family.h
Fixes https://github.com/dragonflydb/controlplane/issues/227.
Adds support for loading snapshots from S3. The Helio S3 client still needs some work to make it more reliable, though this at least gets loading snapshots working.
`AwsS3SnapshotStorage::OpenReadFile` is the same as `AwsS3SnapshotStorage::OpenWriteFile`, so the main changes here are adding `LoadFile` and `LoadFiles` implementations for S3
To match the correct snapshot, unlike `FileSnapshotStorage::LoadFile` we can't use globs, so this instead uses a regex for the timestamp and shard number.
(Note looked at combining `LoadFile` and `LoadFiles` to avoid repeated calls to S3, but since the `DEBUG` command allows explicitly specifying the load path its easier to keep separate. Could cache but doesn't seem worth it for 1 extra …
> feat(snapshot): add support for snapshot recovery from S3

- tests/dragonfly/generic_test.py
Unset `DFLY` env variables which are interfering with other tests
(It would be nice to be able to set those in Dragonfly without having to update the test process env but this seems ok for now)
> feat(tests): unset test DFLY env variables

- src/server/detail/save_stages_controller.cc
- src/server/server_family.cc
- tests/dragonfly/replication_test.py
The issue was that `snapshot_storage_` initialization was skipped when `replicaof` flag was used to start dragonfly.
1. Fixes #1857
2. Add test such that it doesn't happen again
> fix(ServerFamily): proper initialization of FileSnapshotStorage when replicaof flag is used

- src/server/acl/acl_family_test.cc
- src/server/acl/user.cc
Address #1862 
Basically, our implementation would only verify the default user with the password `nopass`. This restriction is lifted and now we conform with the redis impl of `AUTH` that authenticates with any password.
Moreover, I should check in a separate PR:
```
Otherwise if the "default" user is not flagged with "nopass"
```
> fix(Auth): authenticate with any password for default user

- tests/dragonfly/__init__.py
- tests/dragonfly/config_test.py
- tests/dragonfly/generic_test.py
- tests/dragonfly/http_conf_test.py
- tests/dragonfly/server_family_test.py
- tests/dragonfly/snapshot_test.py
- tests/dragonfly/tls_conf_test.py
Also removes some annoying boilerplate.
> chore: Add a context manager to DflyInstance so we don't forget to close them.

- src/server/CMakeLists.txt
- src/server/journal/executor.cc
- src/server/journal/executor.h
- src/server/journal/journal.cc
- src/server/journal/journal.h
- src/server/journal/journal_slice.cc
- src/server/journal/journal_slice.h
- src/server/journal/serializer.cc
- src/server/journal/streamer.cc
- src/server/journal/streamer.h
- src/server/journal/types.h
- src/server/rdb_load.cc
- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/snapshot.cc
- src/server/snapshot.h
This is infrastructure changes needed for partial sync, but no actual replication protocol changes are implemented here.
The journal ring buffer is enabled, some functionality is introduced, and the existing replication infrastructure is migrated to use the ring buffer instead of serializing in-place.
> feat(replication): Use a ring buffer with messages to serve replication.

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/server/CMakeLists.txt
- src/server/acl/acl_family.cc
- src/server/acl/acl_family.h
- src/server/acl/acl_log.cc
- src/server/acl/acl_log.h
- src/server/acl/helpers.cc
- src/server/acl/helpers.h
- src/server/acl/validator.cc
- src/server/main_service.cc
- src/server/server_family.cc
- src/server/server_state.h
- src/server/test_utils.cc
- tests/dragonfly/acl_family_test.py
* add acl log command
* add very basic testing because of broken redis pyclient
Resolves #1808
> feat(AclFamily): add acl log

- src/server/command_registry.cc
- src/server/command_registry.h
- src/server/script_mgr.cc
- src/server/search/search_family.cc
- src/server/server_family.cc
- src/server/transaction.cc
- src/server/transaction.h
Goal: Currently _all_ search commands are global transactions, readonly commands obviously should not be. Yet I want them to keep transactional to make it impossible for those read commands to interleave with write commands. This will guarantee that all read commands access the same search state on all shards.
We already have `NO_KEY_JOURNAL` to make no-key commands be logged in the journal. I changed to `NO_KEY_TRANSACTIONAL` to have a more generic name. (No key journal was used only by SCRIPT).
Additionally, I introduced `EnableShards()` to make it possible to run a no-key-transactional command on all shards
> feat: Span-all no-key transactional commands

- src/facade/cmd_arg_parser_test.cc
> fix: Disable Int<> calls in cmd_arg_parser_test for MacOS

- src/server/acl/acl_family.cc
- src/server/acl/acl_family.h
- src/server/acl/acl_family_test.cc
- src/server/acl/validator.cc
- src/server/acl/validator.h
* add acl dryrun command
* add unit tests
I decided to omit the optional `ARGS` because it does not make sense in the context of ACL, simply put, `ACL DRYRUN` asserts that a given command is allowed to be executed by the user. Therefore, if the command itself is illformed, is something beyond the scope of `ACL DRYRUN` (plus it would be really hard for us to check given our implementation).
resolves: #1895
> feat(AclFamily): add acl dryrun command

- src/core/compact_object.cc
- src/redis/listpack.h
- src/redis/object.c
- src/redis/object.h
- src/redis/redis_aux.c
- src/redis/redis_aux.h
- src/redis/t_hash.c
- src/redis/t_zset.c
- src/server/db_slice.cc
- src/server/dfly_main.cc
- src/server/hset_family.cc
- src/server/hset_family.h
- src/server/hset_family_test.cc
- src/server/memory_cmd.cc
- src/server/memory_cmd.h
- src/server/rdb_load.cc
- src/server/rdb_test.cc
- src/server/zset_family.cc
1. Cherry-pick changes from Redis 7 that encode integer scores more efficiently
2. Introduces optimization that first checks if the new element should be the last for listpack sorted sets.
3. Consolidates listpack related constants and tightens usage for listpack.
When running `redis-zbench-go -mode load -r 100000 -p 6379 -c 40 -key-elements-min=30 -key-elements-max=100` against v.10 and this PR, we improve the throughput by 4x on my machine.
> fix: improve performance of listpack sorted sets

- src/core/detail/bptree_internal.h
- src/core/uring.h
- src/server/detail/snapshot_storage.cc
- src/server/detail/snapshot_storage.h
- src/server/zset_family.cc
Check whether the key is the biggest one before doing the binary search. Also avoid using listpacks if possible during ZADD calls.
Before: 3K qps with `redis-zbench-go -mode load -r 100000 -p 6379 -c 40 -key-elements-min=130 -key-elements-max=200`
Now: 25K qps.
> chore: optimize BPTreeNode::BSearch

- src/server/dflycmd.cc
- src/server/zset_family.cc
- src/server/zset_family_test.cc
the bug: when calling zadd with non uniq members the server would result in updating the zset with the higher score instead of the last score given
f.e
zadd myzset 2 a 1 a
will result in member a score 2 while the expected 1 the fix: if the members in zadd command are not unique than we do not sort the members. As a result in this case when we dont sort we will not have perfomace optimization on listpack.
> bug(server): zadd wrong insert when non unique members

- src/facade/dragonfly_connection.cc
As discussed by @romange and me, after we've repeatedly received related bug reports: #1907 #1285
> fix(server): Flip tcp_nodelay to on by default

- src/server/server_family.cc
- src/server/server_family.h
- src/server/server_state.h
- src/server/transaction.cc
fixes #1797 
the bug: global command is not able to schedule into txq when high load pipelined commands. Only after the load finish the global transaction gets scheduled into the txq. The reason for this is when we start a global transaction we set the shard lock and all the transactions start to enter the txq. They compete with the global tx on the order they are inserted into the queue to preserve transaction atomicity. Because the global tx needs to be inserted to all shard queues its chance to schedule with order with all the other transactions is low. 
the solution: lock the global transaction inside the schedule in shard, locking closer to scheduling decreases the number of transactions in the queue and the competition on ordering correctly has higher chance now.
> bug(server): global command stalls on server load with pipeline mode

- src/core/dense_set.cc
- src/core/dense_set.h
- src/core/score_map.cc
- src/core/score_map.h
- src/core/sorted_map.cc
- src/core/string_map.cc
- src/core/string_set.cc
- src/core/string_set.h
A regular DenseSet insertion first checks for uniqueness and then inserts a new element. Sometimes we know that the new element is new and we can insert it without checking for uniqueness first.
Also, pass hashcode into internal functions so we could save some hash calls.
> chore: remove redundant Find calls when inserting into DenseSet

- src/CMakeLists.txt
- src/server/CMakeLists.txt
- src/server/common.cc
- src/server/dragonfly_test.cc
- src/server/string_family.cc
Integrate a wonderful library fast_float by Daniel Lemire. It achieves x2 improvement on x86_64:
```
BM_ParseFastFloat         663 ns          663 ns      1049085
BM_ParseDoubleAbsl       1358 ns         1358 ns       523853
```
on c6g:
```
BM_ParseFastFloat        2207 ns         2207 ns       317968
BM_ParseDoubleAbsl       5028 ns         5028 ns       139341
```
> chore: implement ParseDouble using fast_float

- src/server/stream_family.cc
- src/server/stream_family_test.cc
fixes https://github.com/dragonflydb/dragonfly/issues/1860
Therefore, now:
```
127.0.0.1:6379> flushdb
OK
127.0.0.1:6379> "XREADGROUP" "GROUP" group consumer COUNT 10 BLOCK 5000 STREAMS stream >
(error) NOGROUP No such key 'stream' or consumer group 'group' in XREADGROUP with GROUP option
```
(used to block for 5 seconds..)
and
```
127.0.0.1:6379> flushdb
OK
127.0.0.1:6379> "XGROUP" "CREATE" stream group "0" MKSTREAM
OK
127.0.0.1:6379> keys *
1) "stream"
127.0.0.1:6379> "XREADGROUP" "GROUP" group consumer COUNT 10 BLOCK 5000 STREAMS stream >
(nil)
(5.02s)
```
(used to return immediately without blocking)
> bug(streams): fixing xreadgroup's behavior to be compatible with Redis

- .pre-commit-config.yaml
- patches/jsoncons-v0.171.0.patch
- src/CMakeLists.txt
- src/server/json_family.cc
- src/server/json_family_test.cc
Fixes: https://github.com/dragonflydb/dragonfly/issues/848
> feat(json): support JSON.GET pretty print options

- src/facade/reply_builder.cc
- src/server/common.cc
- src/server/zset_family.cc
- src/server/zset_family_test.cc
when we have 1 or 2 members.
I assume that using ZADD with a single member is probably the most common usecase
> chore: Avoid allocating unique_members arrays 

- src/server/db_slice.cc
- src/server/dragonfly_test.cc
The issue was that the `Heartbeat` would run every `1ms` and this is problematic because the `for-loop` would take less than `1ms` to finish. Therefore, the memory pool would not adjust and items would not be evicted from the store. By doubling the amount of elements created in the for-loop, we give enough time for the first heartbeat to run and adjust the memory available (which will cause the evictions to happen). 
This passes locally but if we see flakes on the CI we can slightly increase the elements we create in the forloop again.
> fix(dragonfly_test): failing bug207 on build opt

- patches/lua-v5.4.4.patch
Fixes `makefile:84: *** ERROR: unknown architecture arm64.  Stop.` on ARM64 MacOS
Copied the changed line from the above `ifneq (, $(filter $(uname_m),x86_64 amd64))`
> feat(build): fix lua on mac arm64

- src/core/dense_set.cc
- src/core/dense_set.h
- src/core/sorted_map.cc
- src/core/sorted_map.h
- src/facade/reply_builder.cc
- src/server/hset_family.cc
- src/server/zset_family.cc
1. ExpireIfNeeded was unjuistifiedly high in the profile topk table. Lets make the initial condition within an inline to reduce its impact.
2. Reserve space for hmap/zset if multiple items are added.
3. Fix DenseSet::Reserve that was broken and never actually worked
> chore: performance improvements around zset

- src/server/json_family.cc
- src/server/json_family_test.cc
> fix: set the key index within the json.debug command

- src/core/sorted_map.cc
- src/redis/redis_aux.c
Also, bring back the default max listpack entries count for zset to 128. The reason for this - I've added some optimizations that improved listpack performance and also because I would like to write an article about it and I need to compare Dragonfly to Redis7 that has this setting set to 128 by default.
> chore: flip default sorted set implementation to bptree

- src/core/search/search.cc
- src/core/search/search.h
- src/server/search/doc_index.cc
- src/server/search/doc_index.h
Don't return more search results than requested from core search algorithm. This is because for some queries (like the select ALL query) the result set is borrowed, which leads to a very expensive copy
Also trace the number of filtered items pre-aggregation (will only be used later)
Helper for both #1941 #1924
> feat(search): Early limit cutoff

- src/redis/stream.h
- src/server/stream_family.cc
- src/server/stream_family.h
- src/server/stream_family_test.cc
fixes https://github.com/dragonflydb/dragonfly/issues/1869
> feat(streams): support XACK command

- src/server/protocol_client.cc
Small logging change, but the current message sounds like an error.
> chore: Change the DNS log message to something that makes sense externally

- src/redis/stream.h
- src/redis/t_stream.c
- src/server/stream_family.cc
fixes https://github.com/dragonflydb/dragonfly/issues/1945
> bug(streams): entries_read is not updated on xreadgroup command

- src/redis/stream.h
- src/redis/t_stream.c
- src/server/rdb_test.cc
- src/server/stream_family.cc
- src/server/stream_family_test.cc
entries_read and lag have been added to the output of `XINFO GROUPS` since Redis 7.0. Also fixed a bug that incorrectly sets the initial value of `entries_read` when a consumer group is created.
fixes https://github.com/dragonflydb/dragonfly/issues/1948
So now it prints:
```
127.0.0.1:6379> "XGROUP" "CREATE" stream group "0" MKSTREAM
OK
127.0.0.1:6379> XINFO GROUPS stream
1)  1) "name"
2) "group"
3) "consumers"
4) (integer) 0
5) "pending"
6) (integer) 0
7) "last-delivered-id"
8) "0-0"
9) "entries-read"
10) (nil)
11) "lag"
12) (integer) 0
```
> feat(streams): support entries_read and lag for XINFO GROUPS

- src/core/interpreter.cc
saves 1-2% due to SetGlobalArrayInternal calls with lots of arguments/keys.
> chore: preallocate lua arrays

- tests/dragonfly/replication_test.py
The issue was very interesting. First, that it always failed on `build-opt`. Second, the long story short is that DF would replicate everything really fast, that would make the assertion at the end of the test fail (because there would be no stale LSN, it would be the last item). Let me explain:
I noticed that df on the first call of `Flow()` LSN would hold the value of `0`, which makes sense since the replication did not even start before the pytest dropped the connection via the `proxy.drop()`. BUT, on the next iteration of the for loop in pytest, DF would have an LSN number equal to the amount of items created by the seeder which simply meant that by the time the proxy drops the connection a second time, the replica has already established a connection with DF AND finished the …
> fix(regTests): adjust network disconnect small buffer to pass on

- src/core/search/CMakeLists.txt
- src/core/search/ast_expr.h
- src/core/search/base.cc
- src/core/search/base.h
- src/core/search/search.cc
- src/core/search/search.h
- src/core/search/search_test.cc
- src/core/search/sort_indices.cc
- src/core/search/sort_indices.h
- src/server/search/doc_index.cc
- src/server/search/doc_index.h
- src/server/search/search_family.cc
- src/server/search/search_family_test.cc
Adds SORTBY clause to sort search results
> feat(search): Basic sorting

- .github/actions/regression-tests/action.yml
- tests/dragonfly/conftest.py
- tests/dragonfly/instance.py
- tests/dragonfly/utility.py
> fix(regtests): Colored per-instance log

- .github/actions/regression-tests/action.yml
- .github/workflows/ci.yml
- .github/workflows/regression-tests.yml
- .github/workflows/release.yml
- tests/dragonfly/instance.py
- tests/dragonfly/utility.py
1. stop passing the flag use_zset_tree as it is true on default
2. fix ci test to run replication tests
3. change replication tests seeder to sometimes add more than 128 values to zset to test the pbtree impl
> chore(regression): test bptree on regression pytests

- tests/dragonfly/replication_test.py
The issue was similar with test `network_disconnect_small_buffers` but this time the debug build could be slow enough for the replication to not finish. As a consequence, by the time the test reached the assertion, the log did not contain the expected output.
> fix(RegTests): fix replication test_network_disconnect_active_stream

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/dragonfly_listener.cc
- src/facade/dragonfly_listener.h
- src/facade/service_interface.h
- src/server/cluster/cluster_family.cc
- src/server/cluster/cluster_family_test.cc
- src/server/dfly_main.cc
- src/server/main_service.cc
- src/server/main_service.h
- src/server/server_family.cc
- src/server/test_utils.cc
- src/server/test_utils.h
- tests/dragonfly/http_conf_test.py
* Http now `auths` with username `default` instead of `user`
* skip auth for `/metrics` page
* add/improved tests
* fix a bug with admin port requiring auth on http even if nopass was set
* update helio ref
* update listener class to now contain its respective Role
* fix http init to only include admin and main listener
> chore(Http): change authed username to default and skip auth on metrics

- tests/dragonfly/redis_replication_test.py
- tests/dragonfly/utility.py
#1963 Increased the load a little and it was enough to make the test time out. It takes >2 min alone so I decided to lower the load a little
> fix(regtests): Reduce load on redis replication test

- src/server/debugcmd.cc
- src/server/debugcmd.h
stats per shard:
* memory
* key count
* expire count
* key reads (misses + hits)
[... please suggest more useful .... ]
additionally at the end max/min values for each stat are printed
> chore: DEBUG SHARDS

- CONTRIBUTING.md
Fixed typos and grammar in ```./CONTRIBUTING.md```
> Docs: fix typos and grammar

- tests/dragonfly/replication_test.py
If this test fails again we would need a different approach.
> fix(regTests): adjust small network buff test

- tests/dragonfly/replication_test.py
The main issue of this test was the subsequent calls to `replicate()`:
```
async def replicate(index):
await asyncio.sleep(10.0 * random.random())
```
DF internally calls `replica_->Start()` each time it receives a `REPLICAOF` command. Within `Start`, if the context gets canceled replica would sent a "replication cancelled" error which this test explicitly checks for. Because of the random delays, for certain executions of this test, `Start()` would finish before it ever got canceled, and therefore it would never send `replication canceled` error. 
1. I removed the multiple master nodes since we are only interested in the cancellation mechanism of the replica. This cleaned up the test a little bit to be more expressive.
2. I removed the waiting time such that the replicate() loop sends …
> fix(regTests): test_cancel_replication_immediately races

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
- src/facade/facade.cc
- src/facade/facade_types.h
- src/server/dflycmd.cc
- src/server/dflycmd.h
- src/server/io_utils.cc
- src/server/io_utils.h
- src/server/journal/streamer.h
- src/server/main_service.cc
- src/server/multi_test.cc
- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/rdb_test.cc
- src/server/server_family.cc
- src/server/server_family.h
- src/server/server_state.cc
- src/server/server_state.h
- src/server/snapshot.cc
- src/server/snapshot.h
- src/server/string_family_test.cc
- src/server/tiered_storage_test.cc
1.  Clean up metrics collection (no functional changes)
- Group together tx stats in Metrics struct
- Remove ADD_HEADER
- Small polishment
2. Add dispatch queue stats
- entries
- bytes
- peak_bytes
3. Add replication buffer stats
- total streamer buffer capacities
- full sync buffers & channel bytes
4. Add a per-thread limit to the dispatch queue size
> fix(server): Add additional metrics

- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
I had a very silly bug in my last PR, the pytests catched it😭  In EnusreAsyncMemoryBudget I was calculating the budget not for the intended dispatch thread, but the current one by accessing the thread_local queue limits struct
Instead, we need to access the owning thread's queue memory stats
> fix: fix queue backpressure access

- src/server/acl/acl_family.cc
- src/server/acl/user_registry.cc
- src/server/main_service.cc
- tests/dragonfly/acl_family_test.py
* requirepass also updates ACL default user password
* update config set requirepass to include the new behaviour
* add tests
* fix non existent default user when loading empty files
> update(requirepass): behave as redis requirepass

- src/server/dfly_main.cc
- tools/packaging/debian/control
- tools/packaging/debian/dragonfly.conf
- tools/packaging/debian/dragonfly.logrotate
The new logrotate settings assume that dragonfly closes a log file once it grows to large. It never rotates file that is currently open for writing.
Specifically logrotate:
1. rotate only log files
2. skip those that are currently open by a process.
3. compresses using zstd which is more cpu efficient than gzip
4. does not truncate/create old files as 0-sized blobs - just renames them
Fixes #1935
> fix: logrotate for dragonfly logs

- src/server/detail/snapshot_storage.cc
A few improvements to AWS error handling and logging:
**Allow directory with no path**
We should support `--dir=s3://mybucket` even though it doesn't have a path.
**Logging and Error Handling**
Improves the error handling and logging of the S3 client since some errors are hard to understand currently
**Helio**
Depends on https://github.com/romange/helio/pull/154
> feat(aws): s3 snapshot error handling

- tools/balls_bins.py
> chore: add balls and bins simulator

- src/CMakeLists.txt
- src/core/interpreter.cc
- src/core/interpreter.h
- src/core/interpreter_test.cc
- src/facade/dragonfly_connection.cc
- src/server/conn_context.cc
- src/server/main_service.cc
Also, few additional changes that do not affect functionality.
1. make sure passed arguments to DispatchCommand are `\0` delimited during pipelining.
2. extend lua malloc hook to call precise functions - to help with cpu profiling.
3. reuse arguments buffer (save allocations) when calling Dragonfly command from lua scripts.
> fix: buffer overrun when passing long command name from lua

- .github/workflows/ci.yml
- .github/workflows/docker-release.yml
Closes #2009 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=changed::true"
```
**TO-BE**
```yaml
echo "changed=true" >> $GITHUB_OUTPUT
```
> chore: Replace deprecated command with environment file

- src/server/main_service.cc
- src/server/multi_command_squasher.cc
- src/server/transaction.cc
- src/server/transaction.h
When initializing squashed stub transactions, don't recompute the shard id (because its always the same - the current one)
> fix(server): Don't recompute shard for squashed stub tx

- src/core/dense_set.cc
- src/core/dense_set.h
- src/core/string_set.h
- src/core/string_set_test.cc
We introduce `iterator Find(member)` function
as well as iterator members to actually get the expiry time.
> feat: allow extracting the expiry time from string_set

- src/server/CMakeLists.txt
- src/server/engine_shard_set.cc
- src/server/engine_shard_set.h
- src/server/engine_shard_set_test.cc
This will allow some use cases with few busy keys to distribute load more evenly between threads.
Idea by @dranikpg.
To calculate how many entries are needed in the table I used the following quick-n-dirty code, to reach <1% collision with 100 keys:
```cpp
bool Distribute(int balls = 100, int bins = 100) {
vector<int> v(bins);
for (int i = 0; i < balls; ++i) {
v[rand() % v.size()]++;
}
for (int v : v) {
if (v >= 2) {
return true;
}
}
return false;
}
int main(int argc, char** argv) {
int has_2_balls = 0;
constexpr int kRounds = 1'000'000;
for (int i = 0; i < kRounds; ++i) {
has_2_balls += Distribute(100, 500'000);
}
cout << has_2_balls << " rounds had 2+ balls in a single bin out of " << kRounds << endl;
}
```
> opt(server): Allow round-robin keys between shards based on prefix

- src/facade/dragonfly_connection.cc
- src/server/main_service.cc
AS per request:
* Set pipeline squashing by default to 20
* Enable multi-exec squashing
Some side notes:
1. Pipeline squashing reorders commands which might be unexpected to users
2. We still have performance trouble with squashed reads, see bottom of #1907
> chore: Enable squashing by default

- src/facade/op_status.cc
- src/facade/op_status.h
- src/server/transaction.cc
- src/server/zset_family_test.cc
Fixes the assertion failure as reported by #1994.
> fix: reject zset variadic commands with 0 keys

- src/server/main_service.cc
- src/server/transaction.cc
Calling `Shard()` on a normalized key does not detect the round-robin prefix, as we decided to only apply that on hash-tags.
~It looks like that `DCHECK()` fails when working with BullMQ.
I imagine it's the fact that we schedule the remote Lua work with ScheduleSingleHop, but I haven't thought too much about it.~
> fix(server): Fix shardlocal eval with round-robin prefix

- src/core/dense_set.cc
- src/core/string_set.h
- src/server/generic_family.cc
- src/server/generic_family.h
- src/server/generic_family_test.cc
- src/server/set_family.cc
- src/server/set_family.h
Currently implemented only for saddex.
> feat: add fieldttl command that returns the ttl of the member

- tools/packaging/Dockerfile.ubuntu-prod
After this PR:
```
dragonfly on  tar/healthcheck_port [$!?] via C v11.3.0-gcc via △ v3.22.1 via 🐹 v1.20.2 via 🐍 v3.10.6 on ☁️  (us-east-1) on ☁️  tarun@dragonflydb.io 
❯ docker build --no-cache -f ./tools/packaging/Dockerfile.ubuntu-prod .
Sending build context to Docker daemon  105.8MB
Step 1/24 : FROM ghcr.io/romange/ubuntu-dev:20 as builder
---> 91563d76322e
Step 2/24 : ARG TARGETPLATFORM
---> Running in 84e6971077c6
Removing intermediate container 84e6971077c6
---> a6bf761f6a5f
Step 3/24 : WORKDIR /build
---> Running in 9381c3df44cb
Removing intermediate container 9381c3df44cb
---> 334fd565b419
Step 4/24 : COPY tools/docker/fetch_release.sh /tmp/
---> 09ed3b5fefb1
Step 5/24 : ARG SUEXEC_HASH=d6c40440609a23483f12eb6295b5191e94baf08298a856bab6e15b10c3b82891
---> Running in a03cb5ccab00 …
```
> fix(ubuntu-prod): Set suexec hash correctly

- src/core/search/indices.cc
- src/core/search/search_test.cc
Fixes a bug with hnsw crashing when overstepping the initial limit
> fix: Don't crash on reaching hnsw capacity

- .github/workflows/ci.yml
- src/facade/dragonfly_connection.cc
- src/facade/dragonfly_connection.h
> fix(sock): Use the updated cancellation cb interface.

- .github/actions/regression-tests/action.yml
- tests/dragonfly/acl_family_test.py
- tests/dragonfly/server_family_test.py
The issue was that we only exited when the exit code was 124 which did not cover all the cases.
> fix(regTests): properly handle other error codes on timeouts

- src/server/detail/save_stages_controller.cc
- src/server/detail/save_stages_controller.h
- src/server/rdb_save.cc
- src/server/rdb_save.h
- src/server/server_family.cc
- src/server/server_family.h
Add memory bytes used by running snapshot save.
When running save command it will create a snapshot save operation, To enable info command to fetch the memory used by this running process, I created a callback which return the bytes used by the current running save operation, there is only one save at a single time.
When staring a save, the save stages controller will update the callback to the running save instance, this way info command can invoke the callback and get this instance memory buffers size.
> feat(server): add memory stats for snapshot save

- .vscode/launch.json
- src/core/bptree_set.h
- src/core/bptree_set_test.cc
Reported by a user on Discord, we had a bug reverse iterating items in BPTree.
Thanks @romange for the actual fix :)
> fix(bptree): Reverse iteration

- docs/build-from-source.md
Based on this: https://github.com/dragonflydb/dragonfly/discussions/289#discussioncomment-7392440
> fix(docs): add missing libstdc++-static dependency info

- tests/dragonfly/requirements.txt
When `pip3 install -r dragonfly/requirements.txt`: 
```
ERROR: Cannot install redis-om==0.2.1 and redis==5.0.0 because these package versions have conflicting dependencies.
```
I downgraded `redis` to `4.6.0` because otherwise we can't really fix the error. 
I am still unsure how this passes on the CI because I created temporary branch that should fail if `pip install` fails but it fails locally :/
> fix(requirements): conflicting dependencies redis and redis-om

- src/server/main_service.cc
- src/server/multi_test.cc
- src/server/transaction.cc
We used to set `time_now_ms_` only in the non-squashed execution path.
Fixes #2034
> fix(server): Correctly set expiration from Lua scripts

- src/core/search/base.h
- src/core/search/indices.cc
- src/core/search/search_test.cc
- src/core/search/sort_indices.cc
- src/server/search/doc_accessors.cc
- src/server/search/doc_accessors.h
- src/server/search/search_family_test.cc
- tests/dragonfly/search_test.py
Fixes one of the issues discussed in #1995 with arrays not being indexed
> fix(search): Support indexing array paths

- src/facade/command_id.h
- src/server/acl/acl_family.cc
- src/server/acl/acl_family_test.cc
- src/server/command_registry.cc
- src/server/command_registry.h
- src/server/main_service.cc
* Fix renaming ACL commands
* Fix ACL subcommands to be treated as such. For example: ACL list would print all ACL subcommands. Now it only prints ACL
* Add tests
Addresses #2036
> fix(AclFamily): renaming commands and subcommands

- src/facade/reply_builder.cc
- src/facade/reply_builder.h
- src/facade/reply_capture.cc
- src/server/main_service.cc
- tests/dragonfly/instance.py
* set member variable to point to the reply builder
* remove redundant checks
* import missing signal in instance.py
> fix(ReplyGuard): set member variable on construction and remove unused

- tests/dragonfly/snapshot_test.py
`TestDflyAutoLoadSnapshot` was failing because client would send a `SET` command before `DF` got into the loading phase
> fix(regTests): can't execute command while loading on snapshots

- tests/dragonfly/replication_test.py
Regression test sometimes fails because for a short period of time after `wait_available_async()` returns, the result of `ROLE` could still be different from `stable_sync`
[Failure example](https://github.com/dragonflydb/dragonfly/actions/runs/6726461923/job/18282759612#step:6:1863)
We change our state from `LOADING` to `ACTIVE` [here](https://github.com/dragonflydb/dragonfly/blob/d08d7f13b450be2048d59d5e0af9f4554978b235/src/server/replica.cc#L426), but then we change the sync state 2 times:
1. `!R_SYNCING` [here](https://github.com/dragonflydb/dragonfly/blob/d08d7f13b450be2048d59d5e0af9f4554978b235/src/server/replica.cc#L427C28-L427C37)
2. And only later to `R_SYNC_OK` (meaning `stable_sync`) [here](https://github.com/dragonflydb/dragonfly/blob/d08d7f13b450be2048d59d5e0af9f4554978b235/src …
> fix(regTests): Wait between `ACTIVE` until `stable_sync

- src/server/command_registry.cc
We are allowed to migrate threads in commands, so we shouldn't cache the server state pointer before invocation
> fix: more server state read in command invocation

- src/server/config_registry.cc
- src/server/server_family.cc
- src/server/server_family.h
- tests/dragonfly/snapshot_test.py
> add ability to set snapshot_cron flag during runtime(#1762)

- .github/actions/regression-tests/action.yml
- tests/dragonfly/cluster_test.py
- tests/dragonfly/config_test.py
- tests/dragonfly/instance.py
- tests/dragonfly/replication_test.py
- tests/dragonfly/snapshot_test.py
Also force colors when running pytest in github actions.
> chore: use decode_responses when creating a redis client

- CONTRIBUTING.md
**Description:**
This PR addresses a minor typo in the "CONTRIBUTING.md" file. The typo was found in the "Conventional Commmits" section, where "commmits" was mistakenly spelled with an extra "m."
**Changes Made:**
- Corrected the typo by removing the extra "m," making it "commits."
**Why is this change necessary?**
The typo in the contributing documentation could potentially confuse new contributors or lead to misunderstandings. By fixing this typo, we ensure that the documentation is clear and accurate for everyone who wants to contribute to the project.
**How Has This Been Tested?**
This change has been locally tested to verify the accuracy and readability of the modified text.
**Related Issues:**
No related Issues
> docs(contributing): Fix typo in CONTRIBUTING.md

- tools/local/monitoring/grafana/provisioning/dashboards/dashboard.json
- tools/local/monitoring/prometheus/prometheus.yml
The dashboard used `dragonfly_up` metric to boostrap itself but this metric does not exist anymore. I replaced it with `dragonfly_version` In addition, the exported format changed slightly because I used the recent grafana version to export.
> fix: local grafana dasboard

- src/server/acl/acl_family.cc
- src/server/acl/helpers.cc
- src/server/acl/helpers.h
- tests/dragonfly/acl_family_test.py
Addresses #2094
* replace `>` with `#` for acl files
* replace `ACL SETUSER` with `USER` for acl files
* add case insensitive parsing for acl files
* update tests
> fix(acl): case insensitive parsing from files and serialization format

- src/server/db_slice.cc
This caused a UBSan warning to be printed in test `DflyEngineTest.Bug207`
```
/usr/include/c++/11/bits/stl_vector.h:1046:34: runtime error: reference binding to null pointer of type 'struct value_type'
```
> fix(test): Don't access null pointer

- src/server/server_family.cc
- src/server/server_family.h
- tools/local/monitoring/grafana/provisioning/dashboards/dashboard.json
- tools/local/monitoring/prometheus/prometheus.yml
Should allow track caches where Dragonfly is not responsive to I/O due to big CPU tasks.
> feat: expose fiber responsiveness metrics

- src/core/string_map.cc
- src/core/string_map.h
- src/core/string_map_test.cc
- src/server/hset_family.cc
- src/server/hset_family_test.cc
The issue is twofold:
1. If all elements are expired, dividing by `Size()` will crash. However, we cannot know this in advance, as `begin()` will actually invalidate all elements, but we're already inside `RandomPair()` which must return a result (it should not be called if *real* size is 0, after expiration)
2. We cannot use `operator +=` before we know how many *real* elements are in the array. Today we do `+= rand() / Size()`, and this in fact is problematic even if `Size()` is non-zero, but is greater than post-expiration size
Unfortunately, this solution will iterate over all elements in map for the multi-random retrieval function, to know how many non-expired elements (if any) are in the list. I don't think it's too bad, as we iterate there anyway (although not necessarily through …
> fix(server): Do not crash `HRANDFIELD` if some/all elements expired

- src/core/compact_object.cc
- src/core/dense_set.cc
- src/core/dense_set.h
- src/core/sorted_map.cc
- src/core/sorted_map.h
- src/core/string_map.cc
- src/core/string_map.h
- src/core/string_map_test.cc
- src/core/string_set_test.cc
- src/server/hset_family.cc
- src/server/rdb_save.cc
- src/server/set_family.cc
Then use the right version (hopefully) in the right places.
Specifically, this fixes a serialization bug, where we could send malformed responses when using `UpperBoundSize()` to write array length.
> fix(DenseSet): Rename `Size()` to `UpperBoundSize()` and add `SizeSlow()`

- src/server/cluster/cluster_family_test.cc
- src/server/generic_family_test.cc
- src/server/rdb_test.cc
- src/server/test_utils.cc
- src/server/test_utils.h
This is a pretty recent regression.
> fix(unittest): Init with `dbfilename=` before attempting to `save`

- src/facade/memcache_parser.cc
- src/facade/memcache_parser.h
- src/facade/memcache_parser_test.cc
- src/server/main_service.cc
- tests/dragonfly/pymemcached_test.py
addresses #2121
* remove limit of 8 keys per command
* refactor (small) of the parsing logic
* add test
> fix(memcached): parsing multi key get command

- src/server/command_registry.cc
- src/server/dragonfly_test.cc
In practive, commands larger than SSO would not work.
Fixes #2131
> fix(rename-command): Fix subtle UB when renaming commands

- src/server/zset_family.cc
- src/server/zset_family.h
- src/server/zset_family_test.cc
> Add GeoRadiusByMember support

- src/server/generic_family.cc
STICK just sets flags, so it should the same as expire, etc
> chore(acl): Fix STICK flags

- src/server/search/search_family_test.cc
> chore(search): Fix expiry test
